import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@/lib/supabase-server';
import {createAdminClient} from '@/lib/supabase-admin';
import {normalizeJourneyStage,RECRUITING_JOURNEY,toPipelineStorageStage} from '@/lib/recruiting-journey';

async function access(admin:any,viewerId:string,athleteId:string){if(viewerId===athleteId)return true;const {data:m}=await admin.from('organization_members').select('organization_id,role,organization_view_access').eq('user_id',viewerId).eq('status','active').maybeSingle();if(!m)return false;if(m.role==='owner'||m.role==='admin'||m.organization_view_access){const {data:am}=await admin.from('organization_members').select('user_id').eq('organization_id',m.organization_id).eq('user_id',athleteId).eq('role','athlete').eq('status','active').maybeSingle();return !!am}const {data:a}=await admin.from('athlete_advisor_assignments').select('athlete_user_id').eq('advisor_user_id',viewerId).eq('athlete_user_id',athleteId).eq('status','active').maybeSingle();return !!a}

export async function GET(req:NextRequest){const c=await createClient();const {data:{user}}=await c.auth.getUser();if(!user)return NextResponse.json({error:'Please sign in again.'},{status:401});const athlete=req.nextUrl.searchParams.get('athlete')||user.id,admin=createAdminClient();if(!await access(admin,user.id,athlete))return NextResponse.json({error:'Forbidden'},{status:403});const {data,error}=await admin.from('audit_log').select('id,entity_id,actor_user_id,metadata,created_at').eq('entity_type','recruiting_journey').order('created_at',{ascending:true}).limit(10000);if(error)return NextResponse.json({error:error.message},{status:500});const milestones=(data||[]).filter((x:any)=>x.metadata?.athlete_user_id===athlete).map((x:any)=>({id:x.id,athleteUserId:athlete,relationshipId:x.entity_id,collegeId:x.metadata?.college_id,stage:normalizeJourneyStage(x.metadata?.stage),previousStage:x.metadata?.previous_stage?normalizeJourneyStage(x.metadata.previous_stage):null,milestoneDate:x.metadata?.milestone_date||String(x.created_at).slice(0,10),note:x.metadata?.note||'',offerType:x.metadata?.offer_type||'',actorUserId:x.actor_user_id,createdAt:x.created_at}));return NextResponse.json({milestones})}

export async function POST(req:NextRequest){const c=await createClient();const {data:{user}}=await c.auth.getUser();if(!user)return NextResponse.json({error:'Please sign in again.'},{status:401});let body:any;try{body=await req.json()}catch{return NextResponse.json({error:'Invalid request.'},{status:400})}const relationshipId=String(body.relationshipId||''),stage=normalizeJourneyStage(body.stage),milestoneDate=String(body.milestoneDate||new Date().toISOString().slice(0,10));if(!relationshipId||!RECRUITING_JOURNEY.includes(stage))return NextResponse.json({error:'Invalid milestone'},{status:400});const admin=createAdminClient(),{data:r}=await admin.from('athlete_colleges').select('id,athlete_user_id,college_id,status').eq('id',relationshipId).maybeSingle();if(!r||r.athlete_user_id!==user.id)return NextResponse.json({error:'Only the athlete can change Recruiting Journey'},{status:403});const previousStage=normalizeJourneyStage(r.status);const storageStage=toPipelineStorageStage(stage);const {error}=await admin.from('athlete_colleges').update({status:storageStage}).eq('id',relationshipId);if(error)return NextResponse.json({error:error.message},{status:400});const {data:member}=await admin.from('organization_members').select('organization_id').eq('user_id',user.id).eq('status','active').maybeSingle();const {error:logError}=await admin.from('audit_log').insert({organization_id:member?.organization_id||null,actor_user_id:user.id,entity_type:'recruiting_journey',entity_id:relationshipId,action:'journey_stage_changed',metadata:{athlete_user_id:user.id,college_id:r.college_id,stage,previous_stage:previousStage,milestone_date:milestoneDate,note:String(body.note||''),offer_type:stage==='Offer'?String(body.offerType||''):''}});if(logError)return NextResponse.json({error:logError.message},{status:400});return NextResponse.json({ok:true,stage,milestoneDate})}
