'use client';

import Link from 'next/link';
import {useEffect,useState} from 'react';
import {createClient} from '@/lib/supabase-browser';

function destination(role:string,complete:boolean){if(!complete)return role==='athlete'?'/profile':role==='parent'?'/parent/profile':'/advisors/profile';return role==='athlete'?'/dashboard':role==='parent'?'/parent':'/advisors'}

export default function LegalAccept(){
 const c=createClient();
 const[checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[docs,setDocs]=useState<any>(null),[next,setNext]=useState('/dashboard');
 useEffect(()=>{(async()=>{const{data:{user},error:authError}=await c.auth.getUser();if(authError||!user){location.href='/login';return}const[{data:current,error:docError},{data:accepted,error:acceptError},{data:profile,error:profileError}]=await Promise.all([c.rpc('current_legal_documents'),c.rpc('has_current_legal_acceptance'),c.from('profiles').select('app_role,profile_completed_at').eq('id',user.id).maybeSingle()]);if(docError||!current?.length){setError('The current Terms of Service and Privacy Policy could not be loaded. Please try again.');setLoading(false);return}if(acceptError){setError('We could not verify your legal acceptance status. Please try again.');setLoading(false);return}const role=profile?.app_role||'athlete',dest=destination(role,!!profile?.profile_completed_at);setNext(dest);setDocs(current[0]);if(accepted){location.replace(dest);return}setLoading(false)})()},[]);
 async function accept(){if(!checked||busy)return;setBusy(true);setError('');const qs=new URLSearchParams(window.location.search),raw=qs.get('context'),context=['signup','existing_account','reauth','policy_update'].includes(String(raw))?String(raw):'existing_account';const{error:e}=await c.rpc('accept_current_legal_documents',{acceptance_context:context,acceptance_method:'clickwrap',client_user_agent:navigator.userAgent});if(e){setError('We could not record your acceptance. Please try again.');setBusy(false);return}location.replace(next)}
 if(loading)return <div className="min-h-screen grid place-items-center bg-slate-50 p-6"><div className="card p-8 max-w-md text-center"><div className="font-black">Loading legal terms...</div></div></div>;
 return <div className="min-h-screen grid place-items-center bg-slate-50 p-6"><div className="card p-6 sm:p-8 w-full max-w-lg bg-white"><div className="text-2xl tracking-tight text-center"><span className="font-black text-red-600">REBELS</span><span className="text-slate-900"> RECRUIT</span></div><div className="rr-eyebrow mt-8">BEFORE YOU CONTINUE</div><h1 className="text-2xl sm:text-3xl font-black mt-1">Review and accept our terms</h1><p className="text-slate-600 mt-3">Please review the current Terms of Service and Privacy Policy before continuing to Rebels Recruit.</p>{docs&&<div className="rounded-xl border bg-slate-50 p-4 mt-5 text-sm"><div className="font-bold">Current versions</div><div className="text-slate-600 mt-1">Terms: {docs.terms_version} · Privacy: {docs.privacy_version}</div></div>}<label className="flex items-start gap-3 rounded-xl border p-4 mt-5 cursor-pointer"><input type="checkbox" className="mt-1 h-4 w-4" checked={checked} onChange={e=>setChecked(e.target.checked)}/><span className="text-sm leading-6">I agree to the <Link href="/terms" target="_blank" className="font-bold text-red-700 hover:underline">Terms of Service</Link> and <Link href="/privacy" target="_blank" className="font-bold text-red-700 hover:underline">Privacy Policy</Link>.</span></label>{error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 mt-4 text-sm font-semibold text-red-700">{error}</div>}<button className="btn btn-red w-full mt-5 min-h-11" disabled={!checked||busy} onClick={accept}>{busy?'Saving acceptance...':'Accept & Continue'}</button><p className="text-xs text-slate-500 mt-4 text-center">Your acceptance is recorded with the versions and time so Rebels Recruit can maintain an audit history.</p></div></div>
}
