'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {Check,Compass,MapPin,RefreshCw,Sparkles} from 'lucide-react';
import AppShell from '@/components/AppShell';
import PageHeader from '@/components/PageHeader';
import {createClient} from '@/lib/supabase-browser';

type Fit={max_drive_minutes:number|null;distance_importance:string;max_annual_cost:number|null;cost_importance:string;athletic_aid_required:string;divisions:string[];school_sizes:string[];settings:string[];weather_preferences:string[];academic_interests:string[];campus_experience:string[];city_access_preferences:string[];competition_preferences:string[];religious_affiliation_preferences:string[];school_types:string[];top_priorities:string[];notes:string;updated_at?:string|null};
const empty:Fit={max_drive_minutes:null,distance_importance:'',max_annual_cost:null,cost_importance:'',athletic_aid_required:'',divisions:[],school_sizes:[],settings:[],weather_preferences:[],academic_interests:[],campus_experience:[],city_access_preferences:[],competition_preferences:[],religious_affiliation_preferences:[],school_types:[],top_priorities:[],notes:''};
const distanceOptions=[['120','Up to 2 hours'],['240','Up to 4 hours'],['360','Up to 6 hours'],['600','Up to 10 hours'],['99999','Anywhere']];
const groups=[
 {key:'divisions',title:'What softball levels are you open to?',subtitle:'Select every level you would seriously consider.',options:['NCAA DI','NCAA DII','NCAA DIII','NAIA','JUCO','No preference']},
 {key:'school_sizes',title:'What school sizes feel right?',subtitle:'It is okay to be open to more than one.',options:['Small','Medium','Large','No preference']},
 {key:'settings',title:'What kind of setting would you consider?',subtitle:'Select all environments that could work.',options:['Rural','College town','Suburban','Urban','No preference']},
 {key:'weather_preferences',title:'What weather are you comfortable with?',subtitle:'Select all that fit.',options:['Warm most of the year','Four seasons','Cooler climate','Snow is okay','No preference']},
 {key:'campus_experience',title:'What campus experience could work?',subtitle:'Select all that apply.',options:['Traditional residential campus','Commuter-friendly is okay','Either works','No preference']},
 {key:'city_access_preferences',title:'How important is access to a larger city?',subtitle:'Choose any descriptions that fit you.',options:['Want a city nearby','Fine being farther from a city','Either works','No preference']},
 {key:'competition_preferences',title:'What matters competitively?',subtitle:'You can value more than one thing.',options:['Best chance to play early','Highest level possible','Strong program culture','Championship contender','Development opportunity','No preference']},
 {key:'religious_affiliation_preferences',title:'How do you feel about religious affiliation?',subtitle:'Select what applies. “No preference” clears the other choices.',options:['Prefer religious affiliation','Open to religious affiliation','Don’t want religious affiliation','No preference']},
 {key:'school_types',title:'What school types would you consider?',subtitle:'Select all that apply.',options:['Public','Private','No preference']},
] as const;
const priorityOptions=['Academics','Cost','Distance from home','Playing opportunity','Softball level','School size','Campus setting','Weather','Campus life','Location / city access'];
function formatUpdated(v?:string|null){if(!v)return 'Not completed yet';return new Date(v).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}
export default function FitProfile(){
 const c=createClient();const [fit,setFit]=useState<Fit>(empty),[zip,setZip]=useState(''),[majors,setMajors]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState('');
 useEffect(()=>{(async()=>{const {data:{user}}=await c.auth.getUser();if(!user){setLoading(false);return}const [{data:a},{data:f}]=await Promise.all([c.from('athlete_profiles').select('home_zip,interested_majors').eq('user_id',user.id).maybeSingle(),c.from('college_fit_profiles').select('*').eq('user_id',user.id).maybeSingle()]);setZip(a?.home_zip||'');setMajors((a?.interested_majors||[]).join(', '));if(f)setFit({...empty,...f});setLoading(false)})()},[]);
 function toggle(key:keyof Fit,value:string){setFit(prev=>{const current=(prev[key] as string[])||[];if(value==='No preference')return {...prev,[key]:current.includes(value)?[]:['No preference']};const without=current.filter(x=>x!=='No preference');return {...prev,[key]:without.includes(value)?without.filter(x=>x!==value):[...without,value]}})}
 function togglePriority(value:string){setFit(prev=>{const current=prev.top_priorities;if(current.includes(value))return {...prev,top_priorities:current.filter(x=>x!==value)};if(current.length>=3)return prev;return {...prev,top_priorities:[...current,value]}})}
 async function save(){setSaving(true);setMsg('');const {data:{user}}=await c.auth.getUser();if(!user){setSaving(false);return}const interests=majors.split(',').map(x=>x.trim()).filter(Boolean);const now=new Date().toISOString();const [a,f]=await Promise.all([c.from('athlete_profiles').upsert({user_id:user.id,home_zip:zip.trim()||null,interested_majors:interests},{onConflict:'user_id'}),c.from('college_fit_profiles').upsert({...fit,user_id:user.id,academic_interests:interests,completed_at:now,updated_at:now},{onConflict:'user_id'})]);setSaving(false);if(a.error||f.error){setMsg(a.error?.message||f.error?.message||'Could not save your School Fit Profile.');return}setFit(v=>({...v,academic_interests:interests,updated_at:now}));setMsg('School Fit Profile saved.')}
 if(loading)return <AppShell><div className="max-w-5xl mx-auto p-8"><div className="card p-10 text-center muted">Loading your School Fit Profile...</div></div></AppShell>;
 return <AppShell><div className="max-w-5xl mx-auto px-5 md:px-8 py-7"><PageHeader title="School Fit Profile" subtitle="Tell Rebels Recruit what matters to you. Your answers can change anytime—and you can select multiple preferences whenever more than one option fits." action={<Link href="/discover" className="btn"><Compass size={17}/> Discover Schools</Link>}/>
 <div className="card p-5 mb-5 flex flex-col md:flex-row md:items-center gap-4"><div className="h-11 w-11 rounded-xl bg-slate-950 text-white flex items-center justify-center"><Sparkles size={20}/></div><div className="flex-1"><div className="font-black">Your preferences, not a permanent label</div><p className="muted text-sm mt-1">Retake or update this whenever your priorities change. Last updated: {formatUpdated(fit.updated_at)}</p></div></div>
 <div className="space-y-5">
  <Section title="Start with home" subtitle="We use ZIP code only for approximate recruiting travel time. We do not need your street address."><div className="grid md:grid-cols-2 gap-4"><label><span className="text-sm font-bold">Home ZIP Code</span><input className="input mt-1" inputMode="numeric" maxLength={10} placeholder="e.g. 66213" value={zip} onChange={e=>setZip(e.target.value.replace(/[^0-9-]/g,''))}/></label><label><span className="text-sm font-bold">How far from home would you consider?</span><select className="input mt-1" value={fit.max_drive_minutes??''} onChange={e=>setFit(v=>({...v,max_drive_minutes:e.target.value?Number(e.target.value):null}))}><option value="">Choose a range</option>{distanceOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label><span className="text-sm font-bold">How important is staying within that range?</span><select className="input mt-1" value={fit.distance_importance} onChange={e=>setFit(v=>({...v,distance_importance:e.target.value}))}><option value="">Choose</option><option>Must-have</option><option>Strong preference</option><option>Nice to have</option><option>Doesn’t matter</option></select></label></div></Section>
  <Section title="Cost & financial flexibility" subtitle="Use an all-in annual amount you would be comfortable considering before aid is finalized."><div className="grid md:grid-cols-3 gap-4"><label><span className="text-sm font-bold">Maximum annual all-in cost</span><input className="input mt-1" type="number" min="0" step="1000" placeholder="e.g. 30000" value={fit.max_annual_cost??''} onChange={e=>setFit(v=>({...v,max_annual_cost:e.target.value?Number(e.target.value):null}))}/></label><label><span className="text-sm font-bold">How much does cost matter?</span><select className="input mt-1" value={fit.cost_importance} onChange={e=>setFit(v=>({...v,cost_importance:e.target.value}))}><option value="">Choose</option><option>Must-have</option><option>Strong factor</option><option>Somewhat important</option><option>Not a major factor</option></select></label><label><span className="text-sm font-bold">Would you attend with no athletic scholarship?</span><select className="input mt-1" value={fit.athletic_aid_required} onChange={e=>setFit(v=>({...v,athletic_aid_required:e.target.value}))}><option value="">Choose</option><option>Yes</option><option>Maybe, depending on other aid</option><option>No</option><option>Not sure yet</option></select></label></div></Section>
  <Section title="Academics" subtitle="Add more than one possible major or academic interest, separated by commas."><label><span className="text-sm font-bold">Academic interests / possible majors</span><input className="input mt-1" placeholder="Biology, Exercise Science, Business..." value={majors} onChange={e=>setMajors(e.target.value)}/></label></Section>
  {groups.map(g=><Section key={g.key} title={g.title} subtitle={g.subtitle}><ChipGroup options={[...g.options]} selected={(fit[g.key as keyof Fit] as string[])||[]} onToggle={v=>toggle(g.key as keyof Fit,v)}/></Section>)}
  <Section title="What matters most?" subtitle={`Choose up to 3. ${fit.top_priorities.length}/3 selected.`}><ChipGroup options={priorityOptions} selected={fit.top_priorities} onToggle={togglePriority}/></Section>
  <Section title="Anything else we should know?" subtitle="Optional. Add context that a checkbox can’t capture."><textarea className="input min-h-28" placeholder="Example: I want a strong pre-health program, I care about dorm quality, or I would travel farther for the right academic fit." value={fit.notes} onChange={e=>setFit(v=>({...v,notes:e.target.value}))}/></Section>
 </div>
 <div className="sticky bottom-3 mt-6 card p-4 flex flex-col sm:flex-row sm:items-center gap-3 shadow-lg"><div className="flex-1 text-sm">{msg?<span className={msg.includes('saved')?'font-bold':'text-red-700'}>{msg}</span>:<span className="muted">Your answers stay editable at any time.</span>}</div><button className="btn btn-red" onClick={save} disabled={saving}>{saving?<RefreshCw size={17} className="animate-spin"/>:<Check size={17}/>} {saving?'Saving...':'Save School Fit Profile'}</button></div>
 </div></AppShell>
}
function Section({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="card p-5"><h2 className="font-black text-lg">{title}</h2><p className="muted text-sm mt-1 mb-4">{subtitle}</p>{children}</section>}
function ChipGroup({options,selected,onToggle}:{options:string[];selected:string[];onToggle:(v:string)=>void}){return <div className="flex flex-wrap gap-2">{options.map(o=><button key={o} type="button" onClick={()=>onToggle(o)} className={`rounded-xl border px-3.5 py-2.5 text-sm font-bold transition ${selected.includes(o)?'bg-slate-950 text-white border-slate-950':'bg-white hover:bg-slate-50'}`}>{selected.includes(o)&&<Check size={14} className="inline mr-1"/>}{o}</button>)}</div>}
