'use client';
import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {Check,Copy,ExternalLink,Film,Plus,Star,Trash2,X} from 'lucide-react';
import AppShell from '@/components/AppShell';
import {createClient} from '@/lib/supabase-browser';

const categories=['Highlight Reel','Skills Video','Game Film','Hitting','Fielding','Pitching','Catching','Other'];
type Video={id:string;athlete_user_id:string;title:string;description:string|null;category:string;provider:string;video_url:string;thumbnail_url:string|null;is_featured:boolean;created_at:string};
function providerFor(url:string){const s=url.toLowerCase();if(s.includes('youtu.be')||s.includes('youtube.com'))return'youtube';if(s.includes('hudl.com'))return'hudl';if(s.includes('vimeo.com'))return'vimeo';if(s.includes('sportsrecruits.com'))return'sportsrecruits';return'other'}
function youtubeId(url:string){try{const u=new URL(url);if(u.hostname.includes('youtu.be'))return u.pathname.split('/').filter(Boolean)[0]||'';if(u.hostname.includes('youtube.com')){if(u.pathname.startsWith('/shorts/'))return u.pathname.split('/')[2]||'';return u.searchParams.get('v')||''}}catch{}return''}
function providerLabel(p:string){return p==='youtube'?'YouTube':p==='hudl'?'Hudl':p==='vimeo'?'Vimeo':p==='sportsrecruits'?'SportsRecruits':p==='rebels_recruit'?'Rebels Recruit':'Video link'}
export default function VideoLibrary(){const sp=useSearchParams(),requestedAthlete=sp.get('athlete')||'',c=createClient();const [userId,setUserId]=useState(''),[athleteId,setAthleteId]=useState(''),[athleteName,setAthleteName]=useState(''),[videos,setVideos]=useState<Video[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[copied,setCopied]=useState('');const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[category,setCategory]=useState('Highlight Reel'),[url,setUrl]=useState(''),[featured,setFeatured]=useState(false);
 const readOnly=!!requestedAthlete&&requestedAthlete!==userId;
 async function load(target?:string){const {data:{user}}=await c.auth.getUser();if(!user){setLoading(false);return}setUserId(user.id);const athlete=target||requestedAthlete||user.id;setAthleteId(athlete);const [{data:rows},{data:p}]=await Promise.all([c.from('athlete_videos').select('*').eq('athlete_user_id',athlete).order('is_featured',{ascending:false}).order('created_at',{ascending:false}),c.from('profiles').select('full_name').eq('id',athlete).maybeSingle()]);setVideos((rows||[]) as Video[]);setAthleteName(p?.full_name||'');setLoading(false)}
 useEffect(()=>{load()},[requestedAthlete]);
 const grouped=useMemo(()=>categories.map(cat=>({cat,items:videos.filter(v=>v.category===cat)})).filter(g=>g.items.length),[videos]);
 function reset(){setTitle('');setDescription('');setCategory('Highlight Reel');setUrl('');setFeatured(false);setMsg('')}
 async function add(e:React.FormEvent){e.preventDefault();if(readOnly)return;let parsed:URL;try{parsed=new URL(url.trim())}catch{setMsg('Enter a valid video link, including https://');return}if(!['http:','https:'].includes(parsed.protocol)){setMsg('Enter a valid http or https video link.');return}setBusy(true);setMsg('');const provider=providerFor(url),yt=youtubeId(url),thumbnail=yt?`https://i.ytimg.com/vi/${yt}/hqdefault.jpg`:null;if(featured)await c.from('athlete_videos').update({is_featured:false}).eq('athlete_user_id',athleteId);const {error}=await c.from('athlete_videos').insert({athlete_user_id:athleteId,title:title.trim(),description:description.trim()||null,category,provider,video_url:url.trim(),thumbnail_url:thumbnail,is_featured:featured});if(error){setMsg(error.message);setBusy(false);return}setBusy(false);setOpen(false);reset();await load(athleteId)}
 async function remove(id:string){if(readOnly||!confirm('Remove this video from your library?'))return;await c.from('athlete_videos').delete().eq('id',id).eq('athlete_user_id',athleteId);await load(athleteId)}
 async function makeFeatured(v:Video){if(readOnly)return;await c.from('athlete_videos').update({is_featured:false}).eq('athlete_user_id',athleteId);await c.from('athlete_videos').update({is_featured:true}).eq('id',v.id).eq('athlete_user_id',athleteId);await load(athleteId)}
 async function copy(v:Video){try{await navigator.clipboard.writeText(v.video_url);setCopied(v.id);setTimeout(()=>setCopied(''),1600)}catch{}}
 return <AppShell><div className="max-w-6xl mx-auto px-5 md:px-8 py-7"><div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4"><div><div className="text-xs uppercase tracking-[.16em] font-black text-red-600">Recruiting toolkit</div><h1 className="text-3xl font-black mt-1">{readOnly&&athleteName?`${athleteName}'s Videos`:'My Videos'}</h1><p className="muted mt-2 max-w-2xl">Keep your recruiting videos in one place, then share the same links through email, text or social. Rebels Recruit stores the link—not the video file.</p></div>{!readOnly&&<button className="btn btn-red shrink-0" onClick={()=>{reset();setOpen(true)}}><Plus size={17}/> Add Video</button>}</div>
 <div className="mt-5 rounded-2xl border bg-slate-50 px-4 py-3 text-sm text-slate-700"><b>Free-first setup:</b> YouTube Unlisted works well because YouTube handles the upload and playback while Rebels Recruit keeps the recruiting library organized. Hudl, Vimeo, SportsRecruits and other video links are supported too.</div>
 {loading?<div className="card p-10 mt-6 text-center muted">Loading videos...</div>:videos.length===0?<div className="card p-10 mt-6 text-center"><Film size={36} className="mx-auto text-slate-400"/><h2 className="font-black text-xl mt-4">No videos yet</h2><p className="muted mt-2">Add a highlight reel, skills video, game film or position-specific clip.</p>{!readOnly&&<button className="btn btn-red mt-5" onClick={()=>setOpen(true)}><Plus size={16}/> Add your first video</button>}</div>:<div className="space-y-9 mt-7">{grouped.map(g=><section key={g.cat}><h2 className="font-black text-xl">{g.cat}</h2><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4 mt-3">{g.items.map(v=>{const yt=youtubeId(v.video_url);return <article key={v.id} className="card overflow-hidden flex flex-col"><div className="aspect-video bg-slate-950 relative">{yt?<iframe src={`https://www.youtube-nocookie.com/embed/${yt}`} title={v.title} className="absolute inset-0 h-full w-full" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/>:v.thumbnail_url?<img src={v.thumbnail_url} alt="" className="h-full w-full object-cover"/>:<a href={v.video_url} target="_blank" rel="noreferrer" className="h-full flex flex-col items-center justify-center text-white"><Film size={34}/><span className="text-sm font-bold mt-2">Open {providerLabel(v.provider)}</span></a>}{v.is_featured&&<span className="absolute top-3 left-3 rounded-full bg-white px-2.5 py-1 text-[11px] font-black text-slate-950 inline-flex items-center gap-1 shadow"><Star size={12} fill="currentColor"/> Featured</span>}</div><div className="p-4 flex flex-col flex-1"><div><h3 className="font-black leading-tight">{v.title}</h3><div className="text-xs font-bold text-slate-500 mt-1">{providerLabel(v.provider)}</div></div>{v.description&&<p className="text-sm text-slate-600 mt-3">{v.description}</p>}<div className="mt-auto pt-4 flex flex-wrap gap-2"><a className="btn py-1.5 px-2.5 text-xs" href={v.video_url} target="_blank" rel="noreferrer"><ExternalLink size={13}/> Open</a><button className="btn py-1.5 px-2.5 text-xs" onClick={()=>copy(v)}>{copied===v.id?<Check size={13}/>:<Copy size={13}/>} {copied===v.id?'Copied':'Copy link'}</button>{!readOnly&&!v.is_featured&&<button className="btn py-1.5 px-2.5 text-xs" onClick={()=>makeFeatured(v)}><Star size={13}/> Feature</button>}{!readOnly&&<button className="btn py-1.5 px-2.5 text-xs text-red-700" onClick={()=>remove(v.id)}><Trash2 size={13}/> Remove</button>}</div></div></article>})}</div></section>)}</div>}
 {open&&<div className="fixed inset-0 z-[80] bg-slate-950/45 flex items-center justify-center p-4" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setOpen(false)}}><div className="bg-white rounded-2xl shadow-2xl w-full max-w-xl max-h-[92vh] overflow-y-auto"><div className="p-5 border-b flex items-start justify-between gap-4"><div><h2 className="text-xl font-black">Add recruiting video</h2><p className="muted text-sm mt-1">Paste the share link from YouTube, Hudl, Vimeo, SportsRecruits or another video host.</p></div><button className="p-2 rounded-lg hover:bg-slate-100" onClick={()=>setOpen(false)}><X size={18}/></button></div><form onSubmit={add} className="p-5 space-y-4"><label className="block"><span className="text-sm font-bold">Video title</span><input className="input mt-1" value={title} onChange={e=>setTitle(e.target.value)} placeholder="2026 Summer Highlights" required/></label><label className="block"><span className="text-sm font-bold">Category</span><select className="input mt-1" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label className="block"><span className="text-sm font-bold">Video link</span><input className="input mt-1" type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://youtu.be/..." required/><div className="muted text-xs mt-1">For YouTube, use Unlisted if you do not want the video publicly searchable. Anyone with the link can still watch it.</div></label><label className="block"><span className="text-sm font-bold">Description <span className="font-normal muted">optional</span></span><textarea className="input mt-1 min-h-24" value={description} onChange={e=>setDescription(e.target.value)} placeholder="What should a coach know about this video?"/></label><label className="flex items-start gap-3 rounded-xl border p-3"><input type="checkbox" className="mt-1" checked={featured} onChange={e=>setFeatured(e.target.checked)}/><span><b className="text-sm">Make this my featured video</b><span className="block muted text-xs mt-1">Use this for the video you most often want coaches to see first.</span></span></label>{msg&&<div className="text-sm text-red-600">{msg}</div>}<div className="flex justify-end gap-2"><button type="button" className="btn" onClick={()=>setOpen(false)} disabled={busy}>Cancel</button><button className="btn btn-red" disabled={busy}>{busy?'Saving...':'Add Video'}</button></div></form></div></div>}</div></AppShell>}
