'use client';
import {Suspense,useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {Compass,MapPin,Sparkles} from 'lucide-react';
import AppShell from '@/components/AppShell';
import {createClient} from '@/lib/supabase-browser';

const norm=(v:any)=>String(v||'').toLowerCase();
function divMatches(division:any,choices:string[]){if(!choices.length||choices.includes('No preference'))return true;const d=norm(division).replace(/[^a-z0-9]/g,'');return choices.some(c=>c==='NCAA DI'?(d.includes('d1')||d.includes('division1')):c==='NCAA DII'?(d.includes('d2')||d.includes('division2')):c==='NCAA DIII'?(d.includes('d3')||d.includes('division3')):c==='NAIA'?d.includes('naia'):c==='JUCO'?(d.includes('juco')||d.includes('njcaa')||d.includes('junior')):true)}
function typeMatches(type:any,choices:string[]){if(!choices.length||choices.includes('No preference'))return true;const t=norm(type);return choices.some(c=>t.includes(c.toLowerCase()))}
function divisionLabel(v:any){const d=norm(v).replace(/[^a-z0-9]/g,'');if(d.includes('d1')||d.includes('division1'))return'D1';if(d.includes('d2')||d.includes('division2'))return'D2';if(d.includes('d3')||d.includes('division3'))return'D3';if(d.includes('naia'))return'NAIA';if(d.includes('juco')||d.includes('njcaa'))return'JUCO';return String(v||'Other')}

function ParentDiscoverContent(){const sp=useSearchParams(),athleteId=sp.get('athlete')||'',c=createClient();const [allowed,setAllowed]=useState(false),[name,setName]=useState(''),[fit,setFit]=useState<any>(null),[schools,setSchools]=useState<any[]>([]),[connected,setConnected]=useState<Set<string>>(new Set()),[passed,setPassed]=useState<Set<string>>(new Set()),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{if(!athleteId){setLoading(false);return}const {data:access}=await c.from('parent_guardian_access').select('status,permissions').eq('athlete_user_id',athleteId).eq('status','active').maybeSingle();if(!access||access.permissions?.view_discovery===false){setLoading(false);return}setAllowed(true);const [{data:p},{data:f},{data:ac},{data:fb}]=await Promise.all([c.from('profiles').select('full_name').eq('id',athleteId).maybeSingle(),c.from('college_fit_profiles').select('*').eq('user_id',athleteId).maybeSingle(),c.from('athlete_colleges').select('college_id').eq('athlete_user_id',athleteId),c.from('college_discovery_feedback').select('college_id,decision').eq('athlete_user_id',athleteId)]);setName(p?.full_name||'Athlete');setFit(f||null);setConnected(new Set((ac||[]).map((x:any)=>x.college_id)));setPassed(new Set((fb||[]).filter((x:any)=>x.decision==='not_for_me').map((x:any)=>x.college_id)));const all:any[]=[];for(let from=0;from<5000;from+=1000){const {data}=await c.from('colleges').select('id,name,city,state,division,conference,school_type').order('name').range(from,from+999);all.push(...(data||[]));if(!data||data.length<1000)break}setSchools(all);setLoading(false)})()},[athleteId]);
 const ranked=useMemo(()=>schools.filter(s=>!connected.has(s.id)&&!passed.has(s.id)).map(s=>{let matches=0,total=0;const reasons:string[]=[];if((fit?.divisions||[]).length&&!fit.divisions.includes('No preference')){total++;if(divMatches(s.division,fit.divisions)){matches++;reasons.push(`${divisionLabel(s.division)} matches a selected competitive level`)}}if((fit?.school_types||[]).length&&!fit.school_types.includes('No preference')){total++;if(typeMatches(s.school_type,fit.school_types)){matches++;reasons.push(`${s.school_type} matches a school-type preference`)}}if(s.conference)reasons.push(`Competes in ${s.conference}`);return {...s,matches,total,reasons,score:total?matches/total:0}}).sort((a,b)=>b.score-a.score||b.matches-a.matches||a.name.localeCompare(b.name)).slice(0,16),[schools,connected,passed,fit]);
 if(loading)return <AppShell><div className="max-w-6xl mx-auto px-5 py-8"><div className="card p-10 text-center muted">Loading Discovery...</div></div></AppShell>;
 if(!allowed)return <AppShell><div className="max-w-3xl mx-auto px-5 py-8"><div className="card p-8"><h1 className="text-2xl font-black">Discovery access unavailable</h1><p className="muted mt-2">Your athlete has not approved Discovery access for this parent or guardian account.</p><Link href="/parent" className="btn mt-5">Back to Parent Overview</Link></div></div></AppShell>;
 return <AppShell><div className="max-w-6xl mx-auto px-5 md:px-8 py-7"><div className="flex items-start justify-between gap-4"><div><div className="text-xs uppercase tracking-[.16em] font-black text-red-600">Parent view · Read only</div><h1 className="text-3xl font-black mt-1">{name}'s Discovery</h1><p className="muted mt-2 max-w-2xl">See schools that may fit the preferences your athlete selected. Only the athlete can add or pass on schools.</p></div><Link href="/parent" className="btn">Back</Link></div>{!fit&&<div className="card p-5 mt-6"><Sparkles size={20}/><div className="font-black mt-3">College Fit Profile not completed yet</div><p className="muted text-sm mt-1">Discovery will become more useful after the athlete adds their preferences.</p></div>}<div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4 mt-7">{ranked.map(s=><article key={s.id} className="card p-5 flex flex-col"><div className="flex items-start gap-2"><Compass size={18} className="mt-0.5 shrink-0"/><div><h2 className="font-black leading-tight">{s.name}</h2><div className="text-xs text-slate-500 mt-1">{[s.city,s.state].filter(Boolean).join(', ')||'Location not listed'}</div></div></div><div className="flex flex-wrap gap-1.5 mt-3">{s.division&&<span className="rounded-full bg-slate-950 text-white px-2 py-1 text-[10px] font-black">{divisionLabel(s.division)}</span>}{s.school_type&&<span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold">{s.school_type}</span>}</div><div className="mt-4 border-t pt-3 space-y-2 flex-1">{s.reasons.slice(0,3).map((r:string)=><div key={r} className="text-xs text-slate-700 flex gap-2"><MapPin size={12} className="mt-0.5 shrink-0 text-red-600"/><span>{r}</span></div>)}</div></article>)}</div>{ranked.length===0&&<div className="card p-8 mt-6 text-center muted">No additional schools are available in Discovery right now.</div>}</div></AppShell>}

export default function ParentDiscover(){return <Suspense fallback={<AppShell><div className="max-w-6xl mx-auto px-5 py-8"><div className="card p-10 text-center muted">Loading Discovery...</div></div></AppShell>}><ParentDiscoverContent/></Suspense>}
