'use client';
import {Suspense,useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {Check,Compass,Grid2X2,MapPin,Search,Sparkles,ThumbsUp,X} from 'lucide-react';
import AppShell from '@/components/AppShell';
import PageHeader from '@/components/PageHeader';
import {EmptyState} from '@/components/ProductUI';
import {createClient} from '@/lib/supabase-browser';
const norm=(v:any)=>String(v||'').toLowerCase();
function divLabel(v:any){const d=norm(v).replace(/[^a-z0-9]/g,'');if(d.includes('d1')||d.includes('division1'))return'D1';if(d.includes('d2')||d.includes('division2'))return'D2';if(d.includes('d3')||d.includes('division3'))return'D3';if(d.includes('naia'))return'NAIA';if(d.includes('juco')||d.includes('njcaa'))return'JUCO';return String(v||'Other')}
function divMatches(v:any,choices:string[]){if(!choices?.length||choices.includes('No preference'))return true;const d=divLabel(v);return choices.some(c=>(c==='NCAA DI'&&d==='D1')||(c==='NCAA DII'&&d==='D2')||(c==='NCAA DIII'&&d==='D3')||c===d)}
function typeMatches(v:any,choices:string[]){if(!choices?.length||choices.includes('No preference'))return true;return choices.some(c=>norm(v).includes(norm(c)))}
function ParentDiscoverContent(){const sp=useSearchParams(),athleteId=sp.get('athlete')||'',previewRole=sp.get('previewRole'),previewAthlete=sp.get('previewAthlete'),c=createClient();const[allowed,setAllowed]=useState(false),[name,setName]=useState(''),[fit,setFit]=useState<any>(null),[schools,setSchools]=useState<any[]>([]),[connected,setConnected]=useState<Set<string>>(new Set()),[passed,setPassed]=useState<Set<string>>(new Set()),[advice,setAdvice]=useState<Record<string,string>>({}),[parentId,setParentId]=useState(''),[loading,setLoading]=useState(true),[browse,setBrowse]=useState(false),[search,setSearch]=useState(''),[division,setDivision]=useState('All'),[busy,setBusy]=useState('');
 const context=(path:string)=>{const p=new URLSearchParams();p.set('athlete',athleteId);if(previewRole)p.set('previewRole',previewRole);if(previewAthlete)p.set('previewAthlete',previewAthlete);return `${path}?${p.toString()}`};
 useEffect(()=>{(async()=>{if(!athleteId){setLoading(false);return}const{data:{user}}=await c.auth.getUser();if(!user){setLoading(false);return}setParentId(user.id);const{data:membership}=await c.from('organization_members').select('role').eq('user_id',user.id).eq('status','active').limit(1).maybeSingle();const ownerPreview=membership?.role==='owner'&&previewRole==='parent'&&previewAthlete===athleteId;const{data:access}=ownerPreview?{data:{status:'active',permissions:{view_discovery:true}}}:await c.from('parent_guardian_access').select('status,permissions').eq('parent_user_id',user.id).eq('athlete_user_id',athleteId).eq('status','active').maybeSingle();if(!access||access.permissions?.view_discovery===false){setLoading(false);return}setAllowed(true);const[{data:p},{data:f},{data:ac},{data:fb},{data:pa}]=await Promise.all([c.from('profiles').select('full_name').eq('id',athleteId).maybeSingle(),c.from('college_fit_profiles').select('*').eq('user_id',athleteId).maybeSingle(),c.from('athlete_colleges').select('college_id').eq('athlete_user_id',athleteId).is('archived_at',null),c.from('college_discovery_feedback').select('college_id,decision').eq('athlete_user_id',athleteId),c.from('parent_school_advice').select('college_id,advice').eq('parent_user_id',user.id).eq('athlete_user_id',athleteId)]);setName(p?.full_name||'Athlete');setFit(f||null);setConnected(new Set((ac||[]).map((x:any)=>x.college_id)));setPassed(new Set((fb||[]).filter((x:any)=>x.decision==='not_for_me').map((x:any)=>x.college_id)));setAdvice(Object.fromEntries((pa||[]).map((x:any)=>[x.college_id,x.advice])));const all:any[]=[];for(let from=0;from<5000;from+=1000){const{data}=await c.from('colleges').select('id,name,city,state,division,conference,school_type').order('name').range(from,from+999);all.push(...(data||[]));if(!data||data.length<1000)break}setSchools(all);setLoading(false)})()},[athleteId,previewRole,previewAthlete]);
 const ranked=useMemo(()=>schools.filter(s=>!connected.has(s.id)&&!passed.has(s.id)).map(s=>{let matches=0,total=0;const reasons:string[]=[];if((fit?.divisions||[]).length&&!fit.divisions.includes('No preference')){total++;if(divMatches(s.division,fit.divisions)){matches++;reasons.push(`${divLabel(s.division)} matches a competitive level ${name} selected`)}}if((fit?.school_types||[]).length&&!fit.school_types.includes('No preference')){total++;if(typeMatches(s.school_type,fit.school_types)){matches++;reasons.push(`${s.school_type} matches a school-type preference`)}}if(s.conference)reasons.push(`Competes in ${s.conference}`);return{...s,matches,total,reasons,score:total?matches/total:0}}).sort((a,b)=>b.score-a.score||b.matches-a.matches||a.name.localeCompare(b.name)),[schools,connected,passed,fit,name]);
 const groups=useMemo(()=>{const used=new Set<string>();const take=(arr:any[])=>arr.filter(s=>!used.has(s.id)).slice(0,4).map(s=>(used.add(s.id),s));return[{title:`Best Matches for ${name}`,sub:'Schools that line up best with the preferences we can check today.',items:take(ranked)},{title:'Schools You May Be Overlooking',sub:'Schools that match parts of the athlete profile and may deserve a closer look.',items:take(ranked.filter(s=>s.matches>0))},{title:'Athletic Fit',sub:'Schools that match the competitive levels selected in Fit Preferences.',items:take(ranked.filter(s=>divMatches(s.division,fit?.divisions||[])))},{title:'Explore Something Different',sub:'Options that broaden the conversation without changing the athlete’s own school list.',items:take([...ranked].reverse())}]},[ranked,name,fit]);
 const directory=useMemo(()=>ranked.filter(s=>(division==='All'||divLabel(s.division)===division)&&(!search||`${s.name} ${s.city} ${s.state} ${s.division} ${s.conference}`.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>a.name.localeCompare(b.name)),[ranked,division,search]);
 async function advise(collegeId:string,next:'consider'|'pass'){if(!parentId||busy)return;const previous=advice[collegeId];setAdvice(v=>({...v,[collegeId]:next}));setBusy(collegeId);const{error}=await c.from('parent_school_advice').upsert({parent_user_id:parentId,athlete_user_id:athleteId,college_id:collegeId,advice:next,updated_at:new Date().toISOString()},{onConflict:'parent_user_id,athlete_user_id,college_id'});if(error)setAdvice(v=>{const n={...v};if(previous)n[collegeId]=previous;else delete n[collegeId];return n});setBusy('')}
 const Card=({s}:any)=><article className="rounded-2xl border bg-white p-5 flex flex-col shadow-sm transition duration-200 hover:-translate-y-0.5 hover:shadow-md hover:border-slate-300"><Link href={context(`/colleges/${s.id}`)} className="block"><div className="flex items-start gap-2"><Compass size={18} className="mt-0.5 shrink-0"/><div><h3 className="font-black leading-tight hover:text-red-700">{s.name}</h3><div className="text-xs text-slate-500 mt-1">{[s.city,s.state].filter(Boolean).join(', ')||'Location not listed'}</div></div></div><div className="flex flex-wrap gap-1.5 mt-3">{s.division&&<span className="rounded-full bg-slate-950 text-white px-2 py-1 text-[10px] font-black">{divLabel(s.division)}</span>}{s.school_type&&<span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold">{s.school_type}</span>}</div><div className="mt-4 border-t pt-3 min-h-[92px]"><div className="text-[11px] font-black uppercase tracking-wide text-slate-500">Why it may fit</div>{s.reasons.slice(0,3).map((r:string)=><div key={r} className="text-xs text-slate-700 flex gap-2 mt-2"><Check size={12} className="mt-0.5 shrink-0 text-red-600"/><span>{r}</span></div>)}</div></Link><div className="grid grid-cols-2 gap-2 mt-4 pt-4 border-t"><button disabled={busy===s.id} onClick={()=>advise(s.id,'consider')} className={`h-9 rounded-lg text-xs font-black inline-flex items-center justify-center gap-1.5 border ${advice[s.id]==='consider'?'bg-red-600 border-red-600 text-white':'bg-white border-slate-300 hover:border-red-400 hover:bg-red-50'}`}><ThumbsUp size={13}/>Consider</button><button disabled={busy===s.id} onClick={()=>advise(s.id,'pass')} className={`h-9 rounded-lg text-xs font-black inline-flex items-center justify-center gap-1.5 border ${advice[s.id]==='pass'?'bg-slate-900 border-slate-900 text-white':'bg-white border-slate-300 hover:border-slate-500 hover:bg-slate-50'}`}><X size={13}/>Pass</button></div>{advice[s.id]&&<div className="text-[10px] font-bold text-slate-500 mt-2 text-center">Your advice: {advice[s.id]==='consider'?'Consider':'Pass'} · Athlete decides</div>}</article>;
 if(loading)return <AppShell><div className="max-w-6xl mx-auto px-5 py-8"><div className="card p-10 text-center muted">Finding schools...</div></div></AppShell>;
 if(!allowed)return <AppShell><div className="max-w-3xl mx-auto px-5 py-8"><EmptyState title="Find Schools access unavailable" description="Your athlete has not approved access to Find Schools for this parent or guardian account." href="/parent" actionLabel="Back to Parent Overview"/></div></AppShell>;
 return <AppShell><div className="max-w-6xl mx-auto px-5 md:px-8 py-7"><PageHeader eyebrow="PARENT SUPPORT" title="Find Schools" subtitle={`Explore schools that may fit what ${name} said matters. Your Consider/Pass advice is visible to the athlete but never changes the athlete’s own decision.`}/><div className="flex flex-wrap items-center gap-2 mt-5 mb-5"><button onClick={()=>setBrowse(v=>!v)} className="btn btn-red"><Search size={16}/>{browse?'Show Suggested Schools':'Browse All Schools'}</button><span className="text-xs text-slate-500">Research together. The athlete remains in control.</span></div><div className="rounded-xl border bg-slate-50 px-4 py-3 text-sm text-slate-700"><b>Keep in mind:</b> A school appearing here does not mean the school or coach is recruiting your athlete. It is a starting point for research.</div>{!fit&&<div className="card p-5 mt-6"><Sparkles size={20}/><div className="font-black mt-3">Fit Preferences are not finished yet</div><p className="muted text-sm mt-1">Suggestions become more useful after your athlete tells Rebels Recruit what matters in a school.</p></div>}{browse?<section className="mt-7"><div className="flex items-center gap-2 mb-4"><Grid2X2 size={18}/><h2 className="font-black text-xl">Browse All Schools</h2></div><div className="grid sm:grid-cols-[1fr_180px] gap-2 mb-5"><label className="relative"><Search size={16} className="absolute left-3 top-3.5 text-slate-400"/><input className="input pl-9" placeholder="Search school, city, state, conference…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select className="input" value={division} onChange={e=>setDivision(e.target.value)}><option>All</option><option>D1</option><option>D2</option><option>D3</option><option>NAIA</option><option>JUCO</option></select></div><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4">{directory.map(s=><Card key={s.id} s={s}/>)}</div></section>:<div className="space-y-9 mt-7">{groups.map(g=>g.items.length>0&&<section key={g.title}><h2 className="font-black text-xl">{g.title}</h2><p className="muted text-sm mt-1">{g.sub}</p><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4 mt-4">{g.items.map(s=><Card key={s.id} s={s}/>)}</div></section>)}</div>}{!browse&&ranked.length===0&&<div className="mt-6"><EmptyState title="No additional schools right now" description="There are no additional schools to show based on the current preferences and decisions."/></div>}</div></AppShell>}
export default function ParentDiscover(){return <Suspense fallback={<AppShell><div className="max-w-6xl mx-auto px-5 py-8"><div className="card p-10 text-center muted">Finding schools...</div></div></AppShell>}><ParentDiscoverContent/></Suspense>}
