'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {Activity,AlertTriangle,ArrowRight,Download,Search,ShieldCheck} from 'lucide-react';
import {createClient} from '@/lib/supabase-browser';
import {RECRUITING_JOURNEY,normalizeJourneyStage} from '@/lib/recruiting-journey';
import {cleanDisplayNote} from '@/lib/display-notes';

type Tab='overview'|'players'|'colleges'|'coaches'|'activity'|'advisors'|'accounts';
const one=(v:any)=>Array.isArray(v)?v[0]:v;
const exactDate=(a:any)=>a?.date_precision==='exact'&&a?.date?String(a.date):'';
const displayDate=(a:any)=>a?.date_precision==='exact'&&a?.date?String(a.date):a?.date_precision==='month'?'Month known':a?.date_precision==='year'?'Year known':'Date unknown';

export default function OrganizationCommandCenter(){
 const c=createClient();
 const [me,setMe]=useState<any>(null),[members,setMembers]=useState<any[]>([]),[profiles,setProfiles]=useState<any[]>([]),[colleges,setColleges]=useState<any[]>([]),[coaches,setCoaches]=useState<any[]>([]),[activity,setActivity]=useState<any[]>([]),[tasks,setTasks]=useState<any[]>([]),[reminders,setReminders]=useState<any[]>([]),[tab,setTab]=useState<Tab>('overview'),[q,setQ]=useState(''),[playerFilter,setPlayerFilter]=useState(''),[collegeFilter,setCollegeFilter]=useState(''),[coachFilter,setCoachFilter]=useState(''),[typeFilter,setTypeFilter]=useState(''),[dateFrom,setDateFrom]=useState(''),[dateTo,setDateTo]=useState(''),[msg,setMsg]=useState(''),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);const {data:{user}}=await c.auth.getUser();if(!user){setLoading(false);return}const {data:m}=await c.from('organization_members').select('*').eq('user_id',user.id).eq('status','active').maybeSingle();setMe(m);if(!m){setLoading(false);return}const {data:ms}=await c.from('organization_members').select('*').eq('organization_id',m.organization_id);setMembers(ms||[]);const ids=(ms||[]).map((x:any)=>x.user_id);const {data:ps}=ids.length?await c.from('profiles').select('id,full_name,email,app_role,advisor_type,created_at').in('id',ids):{data:[]};setProfiles(ps||[]);const athleteIds=(ms||[]).filter((x:any)=>x.role==='athlete'&&x.status==='active').map((x:any)=>x.user_id);if(!athleteIds.length){setColleges([]);setCoaches([]);setActivity([]);setTasks([]);setReminders([]);setLoading(false);return}const [ac,co,ints,ts,rs]=await Promise.all([c.from('athlete_colleges').select('id,athlete_user_id,status,fit_rating,college_id,colleges(id,name,division,state,conference)').in('athlete_user_id',athleteIds),c.from('athlete_coaches').select('id,athlete_user_id,coach_id,college_id,last_contact_date,next_step,colleges(id,name),college_coaches(id,first_name,last_name,title,email)').in('athlete_user_id',athleteIds),c.from('interactions').select('id,athlete_user_id,coach_id,college_id,type,date,date_precision,created_at,note,initiated_by,colleges(id,name),college_coaches(id,first_name,last_name,title)').in('athlete_user_id',athleteIds).order('date',{ascending:false}).order('created_at',{ascending:false}).limit(2000),c.from('advisor_tasks').select('id,athlete_user_id,created_by_user_id,status,due_date,title').in('athlete_user_id',athleteIds),c.from('reminders').select('id,athlete_user_id,status,due_date,title').in('athlete_user_id',athleteIds)]);setColleges(ac.data||[]);setCoaches(co.data||[]);setActivity(ints.data||[]);setTasks(ts.data||[]);setReminders(rs.data||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const pm=useMemo(()=>new Map(profiles.map(p=>[p.id,p])),[profiles]);
 const athletes=members.filter(m=>m.role==='athlete'&&m.status==='active');
 const advisors=members.filter(m=>['advisor','admin','owner'].includes(m.role));
 const activeOwners=members.filter(m=>m.role==='owner'&&m.status==='active');
 const today=new Date().toISOString().slice(0,10);
 const lastByPlayer=useMemo(()=>{const map=new Map<string,string>();for(const a of activity){const d=exactDate(a);if(!d)continue;const old=map.get(a.athlete_user_id);if(!old||d>old)map.set(a.athlete_user_id,d)}return map},[activity]);
 const stale=athletes.filter(a=>{const d=lastByPlayer.get(a.user_id);return !d||(Date.now()-new Date(`${d}T12:00:00`).getTime())/86400000>14});
 const overdue=reminders.filter(r=>['open','overdue'].includes(r.status)&&r.due_date&&r.due_date<today);
 const openTasks=tasks.filter(t=>t.status!=='completed');
 const noCoach=athletes.filter(a=>!coaches.some(c=>c.athlete_user_id===a.user_id));
 const filteredActivity=useMemo(()=>activity.filter(a=>{const player=(pm.get(a.athlete_user_id) as any)?.full_name||'';const college=one(a.colleges)?.name||'';const ch=one(a.college_coaches);const coach=[ch?.first_name,ch?.last_name].filter(Boolean).join(' ');const hay=`${player} ${college} ${coach} ${a.type||''} ${cleanDisplayNote(a.note)||''}`.toLowerCase();const d=exactDate(a);return(!q||hay.includes(q.toLowerCase()))&&(!playerFilter||a.athlete_user_id===playerFilter)&&(!collegeFilter||a.college_id===collegeFilter)&&(!coachFilter||a.coach_id===coachFilter)&&(!typeFilter||a.type===typeFilter)&&(!dateFrom||!!d&&d>=dateFrom)&&(!dateTo||!!d&&d<=dateTo)}),[activity,q,playerFilter,collegeFilter,coachFilter,typeFilter,dateFrom,dateTo,pm]);
 function csv(name:string,rows:any[]){if(!rows.length)return;const keys=Object.keys(rows[0]);const esc=(v:any)=>`"${String(v??'').replaceAll('"','""')}"`;const text=[keys.join(','),...rows.map(r=>keys.map(k=>esc(r[k])).join(','))].join('\n');const blob=new Blob([text],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
 async function orgAccess(userId:string,on:boolean){setMsg('');const {error}=await c.rpc('set_organization_view_access',{target_user:userId,enabled:on});setMsg(error?error.message:`Organization access ${on?'granted':'removed'}.`);if(!error)await load()}
 async function suspend(userId:string,on:boolean){setMsg('');const {error}=await c.rpc('set_organization_member_suspended',{target_user:userId,suspend:on});setMsg(error?error.message:on?'Account suspended.':'Account restored.');if(!error)await load()}
 async function remove(userId:string,name:string){if(!confirm(`Permanently delete ${name}'s account? This cannot be undone.`))return;const {error}=await c.rpc('delete_organization_account',{target_user:userId});setMsg(error?error.message:'Account permanently deleted.');if(!error)await load()}
 if(loading)return <div className="card p-10 text-center muted">Loading organization...</div>;
 if(!me||!(me.role==='owner'||me.role==='admin'||me.organization_view_access))return <div className="card p-8"><h2 className="font-black text-xl">Organization access required</h2><p className="muted mt-2">Your organization Owner or Admin must grant Organization View access.</p></div>;
 const superAdmin=['owner','admin'].includes(me.role);const tabs:Tab[]=superAdmin?['overview','players','colleges','coaches','activity','advisors','accounts']:['overview','players','colleges','coaches','activity','advisors'];
 const stageCount=(s:string)=>colleges.filter(x=>normalizeJourneyStage(x.status)===s).length;
 const metric=(label:string,value:any,dest:Tab,filter?:()=>void)=><button type="button" onClick={()=>{filter?.();setTab(dest)}} className="rr-metric-card p-3 sm:p-4 text-left group hover:border-slate-400 hover:bg-white transition"><div className="flex justify-between gap-2"><div className="rr-metric-label">{label}</div><ArrowRight size={14} className="opacity-40 group-hover:opacity-100"/></div><div className="rr-metric-value">{value}</div></button>;
 return <><div className="flex gap-2 overflow-x-auto pb-2 mb-5 -mx-1 px-1">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`min-h-11 sm:min-h-0 px-4 py-2 rounded-xl text-sm font-bold capitalize whitespace-nowrap ${tab===t?'bg-slate-900 text-white':'bg-white border hover:border-slate-400'}`}>{t}</button>)}</div>{msg&&<div className="mb-4 rounded-xl border bg-white p-3 text-sm font-semibold">{msg}</div>}
 {tab==='overview'&&<><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-3">{metric('Players',athletes.length,'players')}{metric('Colleges',new Set(colleges.map(x=>x.college_id)).size,'colleges')}{metric('Coaches',new Set(coaches.map(x=>x.coach_id)).size,'coaches')}{metric('Interactions',activity.length,'activity')}{metric('Open Tasks',openTasks.length,'players')}{metric('Overdue',overdue.length,'players')}{metric('Stale 14+ Days',stale.length,'players')}{metric('Advisors / Staff',advisors.length,'advisors')}{metric('Commitments',stageCount('Committed'),'colleges')}{metric('Follow-ups',reminders.filter(x=>['open','overdue','snoozed'].includes(x.status)).length,'players')}</div>
 <div className="grid lg:grid-cols-2 gap-5 sm:gap-6 mt-6"><section className="card p-4 sm:p-5"><div className="rr-eyebrow">PRIORITY</div><h2 className="rr-section-title flex items-center gap-2"><AlertTriangle size={20}/>Needs Attention</h2><p className="rr-section-subtitle">Every signal below opens the people or work behind the number.</p><div className="mt-4 space-y-2"><button className="w-full text-left border rounded-xl p-3 hover:bg-slate-50 flex justify-between gap-3" onClick={()=>setTab('players')}><span><b>{stale.length}</b> players with no exact-dated activity in 14+ days</span><ArrowRight size={16}/></button><Link href="/advisors/tasks?status=overdue" className="w-full border rounded-xl p-3 hover:bg-slate-50 flex justify-between gap-3"><span><b>{overdue.length}</b> overdue follow-ups</span><ArrowRight size={16}/></Link><button className="w-full text-left border rounded-xl p-3 hover:bg-slate-50 flex justify-between gap-3" onClick={()=>setTab('players')}><span><b>{noCoach.length}</b> players with no coach relationships</span><ArrowRight size={16}/></button></div></section>
 <section className="card p-4 sm:p-5"><div className="rr-eyebrow">RECRUITING JOURNEY</div><h2 className="rr-section-title">Recruiting Pipeline</h2><p className="rr-section-subtitle">Open any stage to see the relationships behind it.</p><div className="mt-4 space-y-2">{RECRUITING_JOURNEY.map(s=><Link href={`/advisors/colleges?stage=${encodeURIComponent(s)}`} className="flex justify-between items-center text-sm rounded-lg px-2 py-1.5 hover:bg-slate-50 group" key={s}><span>{s}</span><span className="flex items-center gap-2"><b>{stageCount(s)}</b><ArrowRight size={13} className="opacity-40 group-hover:opacity-100"/></span></Link>)}</div></section></div>
 <section className="card p-4 sm:p-5 mt-6"><div className="flex justify-between gap-3"><div><div className="rr-eyebrow">RECENT</div><h2 className="rr-section-title flex items-center gap-2"><Activity size={20}/>Organization Activity</h2><p className="rr-section-subtitle">Latest recruiting activity across the organization.</p></div><button className="font-bold text-sm" onClick={()=>setTab('activity')}>View All →</button></div><ActivityRows rows={activity.slice(0,12)} pm={pm}/></section></>}
 {tab==='players'&&<section className="card p-4 sm:p-5"><Header eyebrow="PLAYER SUPPORT" title="Players" onExport={()=>csv('organization-players.csv',athletes.map(a=>{const p:any=pm.get(a.user_id)||{};return{name:p.full_name,email:p.email,colleges:colleges.filter(x=>x.athlete_user_id===a.user_id).length,coaches:coaches.filter(x=>x.athlete_user_id===a.user_id).length,interactions:activity.filter(x=>x.athlete_user_id===a.user_id).length,last_exact_activity:lastByPlayer.get(a.user_id)||''}}))}/><div className="mt-4 divide-y">{athletes.map(a=>{const p:any=pm.get(a.user_id)||{};return <Link href={`/players/${a.user_id}`} key={a.user_id} className="block py-3 hover:bg-slate-50 px-2 -mx-2 rounded-lg"><div className="flex justify-between gap-3"><div><b>{p.full_name||'Player'}</b><div className="muted text-xs mt-1">{colleges.filter(x=>x.athlete_user_id===a.user_id).length} colleges · {coaches.filter(x=>x.athlete_user_id===a.user_id).length} coaches · {activity.filter(x=>x.athlete_user_id===a.user_id).length} interactions · Last exact activity {lastByPlayer.get(a.user_id)||'None'}</div></div><ArrowRight size={16}/></div></Link>})}</div></section>}
 {tab==='colleges'&&<RelationshipBreakdown kind="college" rows={colleges} activity={activity} pm={pm} csv={csv}/>} {tab==='coaches'&&<RelationshipBreakdown kind="coach" rows={coaches} activity={activity} pm={pm} csv={csv}/>} 
 {tab==='activity'&&<section className="card p-4 sm:p-5"><Header eyebrow="RECRUITING JOURNEY" title="Global Activity Feed" onExport={()=>csv('organization-activity.csv',filteredActivity.map(a=>({player:(pm.get(a.athlete_user_id) as any)?.full_name,type:a.type,college:one(a.colleges)?.name,coach:`${one(a.college_coaches)?.first_name||''} ${one(a.college_coaches)?.last_name||''}`.trim(),date:displayDate(a),note:cleanDisplayNote(a.note)||''})))}/><div className="grid md:grid-cols-3 gap-2 mt-4"><input className="input" placeholder="Search player, college, coach..." value={q} onChange={e=>setQ(e.target.value)}/><select className="input" value={playerFilter} onChange={e=>setPlayerFilter(e.target.value)}><option value="">All players</option>{athletes.map(a=><option value={a.user_id} key={a.user_id}>{(pm.get(a.user_id) as any)?.full_name}</option>)}</select><select className="input" value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="">All interaction types</option>{[...new Set(activity.map(a=>a.type).filter(Boolean))].map(x=><option key={x}>{x}</option>)}</select><select className="input" value={collegeFilter} onChange={e=>setCollegeFilter(e.target.value)}><option value="">All colleges</option>{[...new Map(colleges.map(x=>[x.college_id,one(x.colleges)?.name])).entries()].map(([id,n])=><option value={id} key={id}>{n}</option>)}</select><select className="input" value={coachFilter} onChange={e=>setCoachFilter(e.target.value)}><option value="">All coaches</option>{[...new Map(coaches.map(x=>{const z=one(x.college_coaches);return[x.coach_id,`${z?.first_name||''} ${z?.last_name||''}`.trim()]})).entries()].map(([id,n])=><option value={id} key={id}>{n}</option>)}</select><div className="flex flex-col sm:flex-row gap-2"><input className="input" type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/><input className="input" type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)}/></div></div><button className="text-sm font-bold mt-3 min-h-11" onClick={()=>{setQ('');setPlayerFilter('');setCollegeFilter('');setCoachFilter('');setTypeFilter('');setDateFrom('');setDateTo('')}}>Clear filters</button><ActivityRows rows={filteredActivity} pm={pm}/></section>}
 {tab==='advisors'&&<section className="card p-4 sm:p-5"><Header eyebrow="STAFF" title="Advisor Workload"/><div className="mt-4 divide-y">{advisors.map(a=>{const p:any=pm.get(a.user_id)||{};const assigned=new Set(tasks.filter(t=>t.created_by_user_id===a.user_id).map(t=>t.athlete_user_id));return <div className="py-4 flex flex-col md:flex-row md:items-center gap-3" key={a.user_id}><div className="flex-1 min-w-0"><b>{p.full_name||p.email||'Advisor'}</b><div className="muted text-xs capitalize">{a.role} · {assigned.size} players with tasks · {tasks.filter(t=>t.created_by_user_id===a.user_id&&t.status!=='completed').length} open tasks</div></div>{superAdmin&&a.role==='advisor'&&<label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={!!a.organization_view_access} onChange={e=>orgAccess(a.user_id,e.target.checked)}/> Organization View</label>}</div>})}</div></section>}
 {tab==='accounts'&&superAdmin&&<section className="card p-4 sm:p-5"><div className="rr-eyebrow">ADMINISTRATION</div><div className="flex items-start gap-2"><ShieldCheck size={21}/><div><h2 className="rr-section-title">Account Administration</h2><p className="rr-section-subtitle">Owners and Admins can manage organization accounts. The sole Owner is protected from suspension, deletion, reassignment, or ownership changes.</p></div></div><div className="mt-4 divide-y">{members.map(m=>{const p:any=pm.get(m.user_id)||{};const protectedOwner=m.role==='owner'&&activeOwners.length===1;return <div className="py-4 flex flex-col md:flex-row md:items-center gap-3" key={m.user_id}><div className="flex-1 min-w-0"><div className="flex flex-wrap items-center gap-2"><b>{p.full_name||p.email||'Account'}</b>{protectedOwner&&<span className="pill">Protected Owner</span>}</div><div className="muted text-xs break-words">{p.email} · <span className="capitalize">{m.role}</span> · {m.status}</div></div>{protectedOwner?<div className="text-xs font-bold text-slate-500">Cannot be suspended, deleted, or reassigned</div>:m.role!=='owner'&&<div className="flex flex-wrap gap-2"><button className="btn min-h-11 sm:min-h-9" onClick={()=>suspend(m.user_id,m.status==='active')}>{m.status==='active'?'Suspend':'Restore'}</button><button className="btn btn-red min-h-11 sm:min-h-9" onClick={()=>remove(m.user_id,p.full_name||p.email||'this user')}>Delete</button></div>}</div>})}</div></section>}</>}

function Header({title,eyebrow,onExport}:{title:string;eyebrow?:string;onExport?:()=>void}){return <div className="flex flex-col sm:flex-row sm:justify-between sm:items-start gap-3"><div>{eyebrow&&<div className="rr-eyebrow">{eyebrow}</div>}<h2 className="rr-section-title">{title}</h2></div>{onExport&&<button className="btn self-start sm:self-auto min-h-11 sm:min-h-9" onClick={onExport}><Download size={16}/>Export CSV</button>}</div>}
function ActivityRows({rows,pm}:{rows:any[];pm:Map<any,any>}){return <div className="mt-4 divide-y">{rows.map(a=>{const co=one(a.colleges),ch=one(a.college_coaches),note=cleanDisplayNote(a.note);return <div className="py-3" key={a.id}><div className="font-bold break-words"><Link className="hover:text-red-700 hover:underline" href={`/players/${a.athlete_user_id}`}>{pm.get(a.athlete_user_id)?.full_name||'Player'}</Link> → {co?.id?<Link className="hover:text-red-700 hover:underline" href={`/colleges/${co.id}?athlete=${a.athlete_user_id}`}>{co.name||'College'}</Link>:co?.name||'College'}{ch?.id?<><span> → </span><Link className="hover:text-red-700 hover:underline" href={`/coaches/${ch.id}?athlete=${a.athlete_user_id}`}>{`${ch.first_name||''} ${ch.last_name||''}`.trim()}</Link></>:''}<span> → </span><Link className="hover:text-red-700 hover:underline" href={`/activity/${a.id}`}>{a.type}</Link></div><div className="muted text-xs mt-1">{displayDate(a)}{note?` · ${note}`:''}</div></div>})}{!rows.length&&<div className="py-8 text-center muted">No activity matches these filters.</div>}</div>}
function RelationshipBreakdown({kind,rows,activity,pm,csv}:{kind:'college'|'coach';rows:any[];activity:any[];pm:Map<any,any>;csv:(n:string,r:any[])=>void}){const key=kind==='college'?'college_id':'coach_id';const groups=[...new Map(rows.map(r=>{const obj=kind==='college'?one(r.colleges):one(r.college_coaches);const name=kind==='college'?obj?.name:`${obj?.first_name||''} ${obj?.last_name||''}`.trim();return[r[key],{id:r[key],name,rows:rows.filter(x=>x[key]===r[key])}]})).values()];return <section className="card p-4 sm:p-5"><Header eyebrow="RELATIONSHIP COVERAGE" title={kind==='college'?'College Coverage':'Coach Coverage'} onExport={()=>csv(`organization-${kind}s.csv`,groups.map(g=>({name:g.name,players:new Set(g.rows.map((r:any)=>r.athlete_user_id)).size,interactions:activity.filter(a=>a[key]===g.id).length})))}/><div className="mt-4 divide-y">{groups.map(g=>{const athleteIds=[...new Set(g.rows.map((r:any)=>r.athlete_user_id))];const firstAthlete=athleteIds[0] as string|undefined;const href=kind==='college'?`/colleges/${g.id}${firstAthlete?`?athlete=${firstAthlete}`:''}`:`/coaches/${g.id}${firstAthlete?`?athlete=${firstAthlete}`:''}`;return <div className="py-4" key={g.id}><Link href={href} className="font-black hover:text-red-700 hover:underline inline-flex items-center gap-1">{g.name||'Unknown'} <ArrowRight size={14}/></Link><div className="muted text-xs">{athleteIds.length} players · {activity.filter(a=>a[key]===g.id).length} interactions</div><div className="text-sm mt-2 flex flex-wrap gap-x-2 gap-y-1">{athleteIds.map((id:any)=><Link key={id} href={`/players/${id}`} className="hover:text-red-700 hover:underline">{pm.get(id)?.full_name||'Player'}</Link>)}</div></div>})}</div></section>}
