'use client';
import {useEffect,useMemo,useState} from 'react';
import {CheckCircle2,CheckSquare,Clock3} from 'lucide-react';
import AppShell from '@/components/AppShell';
import PageHeader from '@/components/PageHeader';
import {createClient} from '@/lib/supabase-browser';

type Task={id:string;title:string;description:string|null;due_date:string|null;status:string;created_at:string;completed_at:string|null;created_by_user_id:string|null;creator?:any};
const fmt=(d:string|null)=>d?new Date(`${d.slice(0,10)}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'No due date';
export default function AthleteTasks(){
 const c=createClient();const [tasks,setTasks]=useState<Task[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
 async function load(){const {data:{user}}=await c.auth.getUser();if(!user){setLoading(false);return}const {data}=await c.from('advisor_tasks').select('id,title,description,due_date,status,created_at,completed_at,created_by_user_id').eq('athlete_user_id',user.id).order('created_at',{ascending:false});const base=(data||[]) as Task[];const ids=[...new Set(base.map(t=>t.created_by_user_id).filter(Boolean))] as string[];let profiles:any[]=[];if(ids.length){const {data:p}=await c.from('profiles').select('id,full_name,email').in('id',ids);profiles=p||[]}const pm=new Map(profiles.map(p=>[p.id,p]));setTasks(base.map(t=>({...t,creator:t.created_by_user_id?pm.get(t.created_by_user_id)||null:null})));setLoading(false)}
 useEffect(()=>{load()},[]);
 async function toggle(task:Task){setBusy(task.id);const complete=task.status!=='completed';await c.from('advisor_tasks').update({status:complete?'completed':'open',completed_at:complete?new Date().toISOString():null}).eq('id',task.id);await load();setBusy('')}
 const today=new Date().toISOString().slice(0,10);const open=useMemo(()=>tasks.filter(t=>t.status!=='completed').sort((a,b)=>(a.due_date||'9999').localeCompare(b.due_date||'9999')),[tasks]);const completed=tasks.filter(t=>t.status==='completed');
 return <AppShell><div className="max-w-5xl mx-auto px-5 md:px-8 py-6"><PageHeader title="Tasks" subtitle="Keep track of recruiting tasks assigned by your advisor and mark them complete as you go."/>{loading?<div className="card p-8 text-center muted">Loading tasks...</div>:<><section className="card p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-black text-lg flex items-center gap-2"><CheckSquare size={19}/>To Do</h2><p className="muted text-sm mt-1">{open.length} open task{open.length===1?'':'s'}</p></div></div><div className="mt-4 space-y-3">{open.map(t=>{const overdue=!!t.due_date&&t.due_date<today;return <div key={t.id} className="rounded-xl border p-4 flex flex-col sm:flex-row sm:items-start gap-4"><div className="flex-1 min-w-0"><div className="flex flex-wrap items-center gap-2"><div className="font-black">{t.title}</div>{overdue&&<span className="rounded-full bg-red-50 text-red-700 px-2 py-1 text-[10px] font-black">Overdue</span>}</div>{t.description&&<p className="text-sm text-slate-700 mt-2 whitespace-pre-wrap">{t.description}</p>}<div className="flex flex-wrap gap-x-4 gap-y-1 mt-3 text-xs text-slate-500"><span className="inline-flex items-center gap-1"><Clock3 size={13}/>{fmt(t.due_date)}</span><span>Assigned by {t.creator?.full_name||t.creator?.email||'your advisor'}</span></div></div><button disabled={busy===t.id} onClick={()=>toggle(t)} className="btn btn-red shrink-0"><CheckCircle2 size={16}/>{busy===t.id?'Saving...':'Mark Complete'}</button></div>})}{!open.length&&<div className="py-10 text-center muted text-sm">You’re all caught up. No open tasks.</div>}</div></section>{completed.length>0&&<section className="card p-5 mt-6"><h2 className="font-black text-lg">Completed</h2><div className="mt-3 divide-y">{completed.slice(0,20).map(t=><div key={t.id} className="py-3 flex items-center gap-3"><CheckCircle2 size={18} className="text-slate-400 shrink-0"/><div className="flex-1 min-w-0"><div className="font-semibold text-sm line-through text-slate-500">{t.title}</div><div className="muted text-xs mt-1">Assigned by {t.creator?.full_name||t.creator?.email||'your advisor'} · {fmt(t.due_date)}</div></div><button disabled={busy===t.id} onClick={()=>toggle(t)} className="text-xs font-bold text-slate-500">Reopen</button></div>)}</div></section>}</>}</div></AppShell>
}
