import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@/lib/supabase-server';

type Point={lat:number;lon:number};
type NcesFeature={attributes?:{CITY?:string;STATE?:string;LAT?:number;LON?:number}};
const STATE_ABBR:Record<string,string>={Alabama:'AL',Alaska:'AK',Arizona:'AZ',Arkansas:'AR',California:'CA',Colorado:'CO',Connecticut:'CT',Delaware:'DE',Florida:'FL',Georgia:'GA',Hawaii:'HI',Idaho:'ID',Illinois:'IL',Indiana:'IN',Iowa:'IA',Kansas:'KS',Kentucky:'KY',Louisiana:'LA',Maine:'ME',Maryland:'MD',Massachusetts:'MA',Michigan:'MI',Minnesota:'MN',Mississippi:'MS',Missouri:'MO',Montana:'MT',Nebraska:'NE',Nevada:'NV','New Hampshire':'NH','New Jersey':'NJ','New Mexico':'NM','New York':'NY','North Carolina':'NC','North Dakota':'ND',Ohio:'OH',Oklahoma:'OK',Oregon:'OR',Pennsylvania:'PA','Rhode Island':'RI','South Carolina':'SC','South Dakota':'SD',Tennessee:'TN',Texas:'TX',Utah:'UT',Vermont:'VT',Virginia:'VA',Washington:'WA','West Virginia':'WV',Wisconsin:'WI',Wyoming:'WY'};
function norm(v:string){return v.trim().toLowerCase().replace(/[^a-z0-9]/g,'')}
function state(v:string){const x=v.trim();return (STATE_ABBR[x]||x).toUpperCase()}
function miles(a:Point,b:Point){const r=3958.7613,d=Math.PI/180,dLat=(b.lat-a.lat)*d,dLon=(b.lon-a.lon)*d;const q=Math.sin(dLat/2)**2+Math.cos(a.lat*d)*Math.cos(b.lat*d)*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.sqrt(q))}
function estimate(a:Point,b:Point){const straight=miles(a,b);const road=straight*1.2;return{minutes:Math.max(10,Math.round(road/55*60)),distanceMiles:Math.round(road*10)/10,estimated:true}}
async function zipPoint(zip:string):Promise<Point|null>{try{const res=await fetch('https://api.zippopotam.us/us/'+encodeURIComponent(zip.slice(0,5)),{next:{revalidate:2592000}});if(!res.ok)return null;const j=await res.json(),p=j?.places?.[0];const lat=Number(p?.latitude),lon=Number(p?.longitude);return Number.isFinite(lat)&&Number.isFinite(lon)?{lat,lon}:null}catch{return null}}
async function schoolCityPoints(){const url='https://nces.ed.gov/opengis/rest/services/Postsecondary_School_Locations/EDGE_GEOCODE_POSTSECONDARYSCH_2324/MapServer/0/query?where=1%3D1&outFields=CITY%2CSTATE%2CLAT%2CLON&returnGeometry=false&resultRecordCount=10000&f=json';const res=await fetch(url,{next:{revalidate:2592000}});if(!res.ok)throw new Error('NCES school coordinates are temporarily unavailable.');const j=await res.json();const buckets=new Map<string,{lat:number;lon:number;n:number}>();for(const f of (j.features||[]) as NcesFeature[]){const a=f.attributes||{},lat=Number(a.LAT),lon=Number(a.LON);if(!a.CITY||!a.STATE||!Number.isFinite(lat)||!Number.isFinite(lon))continue;const k=norm(a.CITY)+'|'+state(a.STATE),v=buckets.get(k)||{lat:0,lon:0,n:0};v.lat+=lat;v.lon+=lon;v.n++;buckets.set(k,v)}const out=new Map<string,Point>();for(const[k,v]of buckets)out.set(k,{lat:v.lat/v.n,lon:v.lon/v.n});return out}
export async function POST(req:NextRequest){const c=await createClient();const{data:{user}}=await c.auth.getUser();if(!user)return NextResponse.json({error:'Please sign in again.'},{status:401});let body:any;try{body=await req.json()}catch{return NextResponse.json({error:'Invalid request.'},{status:400})}let profileUserId=user.id;const requested=String(body?.athleteId||'').trim();if(requested&&requested!==user.id){const{data:access}=await c.from('parent_guardian_access').select('permissions').eq('parent_user_id',user.id).eq('athlete_user_id',requested).eq('status','active').maybeSingle();const{data:m}=await c.from('organization_members').select('role').eq('user_id',user.id).eq('status','active').limit(1).maybeSingle();const preview=m?.role==='owner'&&body?.previewRole==='parent'&&body?.previewAthlete===requested;if(!preview&&(!access||access.permissions?.view_discovery===false))return NextResponse.json({error:'Find Schools access unavailable.'},{status:403});profileUserId=requested}let{data:athlete}=await c.from('athlete_profiles').select('home_zip').eq('user_id',profileUserId).maybeSingle();if(!String(athlete?.home_zip||'').trim()&&!requested){const{data:links}=await c.from('parent_guardian_access').select('athlete_user_id,permissions').eq('parent_user_id',user.id).eq('status','active').limit(2);const allowed=(links||[]).filter((x:any)=>x.permissions?.view_discovery!==false);if(allowed.length===1){profileUserId=allowed[0].athlete_user_id;const r=await c.from('athlete_profiles').select('home_zip').eq('user_id',profileUserId).maybeSingle();athlete=r.data}}const zip=String(athlete?.home_zip||'').trim();if(!zip)return NextResponse.json({configured:true,origin:null,times:{},error:'Add a home ZIP in the athlete profile to see estimated travel times.'});const origin=await zipPoint(zip);if(!origin)return NextResponse.json({configured:true,origin:zip,times:{},error:'We could not locate that home ZIP.'});const locations=[...new Set((Array.isArray(body?.locations)?body.locations:[]).map((v:any)=>String(v||'').trim()).filter(Boolean))].slice(0,2000) as string[];if(!locations.length)return NextResponse.json({configured:true,origin:zip,times:{}});try{const points=await schoolCityPoints(),times:Record<string,{minutes:number;distanceMiles:number;estimated:boolean}>={};for(const location of locations){const parts=location.split(',').map(x=>x.trim()),st=parts.pop()||'',city=parts.join(', '),p=points.get(norm(city)+'|'+state(st));if(p)times[location]=estimate(origin,p)}return NextResponse.json({configured:true,method:'local-estimate',origin:zip,times,requested:locations.length,notice:'Estimated travel time based on geographic distance. Actual driving time may vary.'})}catch(e){return NextResponse.json({configured:true,origin:zip,times:{},error:e instanceof Error?e.message:'Estimated travel times could not be loaded.'},{status:502})}}
