import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@/lib/supabase-server';

const MAX_DESTINATIONS_PER_REQUEST=49;
const MAX_LOCATIONS=2000;
const CACHE_READ_BATCH=100;
const CACHE_MAX_AGE_DAYS=180;
type Drive={minutes:number;distanceMiles:number};
type MatrixElement={destinationIndex?:number;distanceMeters?:number;duration?:string;condition?:string;status?:{code?:number;message?:string}};
function parseSeconds(duration?:string){if(!duration)return null;const m=duration.match(/^([0-9]+(?:\.[0-9]+)?)s$/);if(!m)return null;const n=Number(m[1]);return Number.isFinite(n)?n:null}
function originKey(zip:string){return `us-zip:${zip.trim().toLowerCase()}`;}
function freshEnough(value?:string|null){if(!value)return false;const age=Date.now()-new Date(value).getTime();return Number.isFinite(age)&&age<=CACHE_MAX_AGE_DAYS*24*60*60*1000}

export async function POST(req:NextRequest){
 const c=await createClient();const{data:{user}}=await c.auth.getUser();if(!user)return NextResponse.json({error:'Please sign in again.'},{status:401});let body:any;try{body=await req.json()}catch{return NextResponse.json({error:'Invalid request.'},{status:400})}
 let profileUserId=user.id;const requested=String(body?.athleteId||'').trim();if(requested&&requested!==user.id){const{data:access}=await c.from('parent_guardian_access').select('permissions').eq('parent_user_id',user.id).eq('athlete_user_id',requested).eq('status','active').maybeSingle();const{data:m}=await c.from('organization_members').select('role').eq('user_id',user.id).eq('status','active').limit(1).maybeSingle();const preview=m?.role==='owner'&&body?.previewRole==='parent'&&body?.previewAthlete===requested;if(!preview&&(!access||access.permissions?.view_discovery===false))return NextResponse.json({error:'Find Schools access unavailable.'},{status:403});profileUserId=requested}
 let{data:athlete}=await c.from('athlete_profiles').select('home_zip').eq('user_id',profileUserId).maybeSingle();
 if(!String(athlete?.home_zip||'').trim()&&!requested){const{data:links}=await c.from('parent_guardian_access').select('athlete_user_id,permissions').eq('parent_user_id',user.id).eq('status','active').limit(2);const allowed=(links||[]).filter((x:any)=>x.permissions?.view_discovery!==false);if(allowed.length===1){profileUserId=allowed[0].athlete_user_id;const r=await c.from('athlete_profiles').select('home_zip').eq('user_id',profileUserId).maybeSingle();athlete=r.data}}
 const zip=String(athlete?.home_zip||'').trim(),origin=zip?`${zip}, USA`:null;if(!origin)return NextResponse.json({configured:true,origin:null,times:{},error:'Add a home ZIP in the athlete profile to see driving times from home.'});
 const raw=Array.isArray(body?.locations)?body.locations:[];let locations:string[]=[...new Set(raw.map((v:any)=>String(v||'').trim()).filter(Boolean) as string[])];
 if(locations.length>=500&&body?.expandDirectory===true){const all:string[]=[];for(let from=0;from<5000;from+=1000){const{data,error}=await c.from('colleges').select('city,state').order('name').range(from,from+999);if(error)break;for(const school of data||[]){const loc=[school.city,school.state].filter(Boolean).join(', ').trim();if(loc)all.push(loc)}if(!data||data.length<1000)break}if(all.length)locations=[...new Set(all)]}
 locations=locations.slice(0,MAX_LOCATIONS);if(!locations.length)return NextResponse.json({configured:true,origin,times:{}});
 const key=originKey(zip);const times:Record<string,Drive>={};let cacheHits=0;
 for(let start=0;start<locations.length;start+=CACHE_READ_BATCH){const chunk=locations.slice(start,start+CACHE_READ_BATCH);const{data,error}=await c.from('driving_time_cache').select('destination,minutes,distance_miles,calculated_at').eq('origin_key',key).in('destination',chunk);if(error)console.error('Driving-time cache read failed',error.message);for(const row of data||[]){if(!freshEnough(row.calculated_at))continue;times[row.destination]={minutes:Number(row.minutes),distanceMiles:Number(row.distance_miles)};cacheHits++}}
 const missing=locations.filter(location=>!times[location]);if(!missing.length)return NextResponse.json({configured:true,origin,times,requested:locations.length,cacheHits,googleDestinations:0});
 const apiKey=process.env.GOOGLE_MAPS_API_KEY;if(!apiKey)return NextResponse.json({configured:false,origin,times,requested:locations.length,cacheHits,googleDestinations:0,error:'Driving-time estimates are not configured yet.'});
 try{const writes:any[]=[];for(let start=0;start<missing.length;start+=MAX_DESTINATIONS_PER_REQUEST){const chunk=missing.slice(start,start+MAX_DESTINATIONS_PER_REQUEST);const res=await fetch('https://routes.googleapis.com/distanceMatrix/v2:computeRouteMatrix',{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':apiKey,'X-Goog-FieldMask':'destinationIndex,status,condition,distanceMeters,duration'},body:JSON.stringify({origins:[{waypoint:{address:origin}}],destinations:chunk.map(location=>({waypoint:{address:location}})),travelMode:'DRIVE',routingPreference:'TRAFFIC_UNAWARE',regionCode:'us'}),cache:'no-store'});const data=await res.json() as MatrixElement[]|{error?:{message?:string}};if(!res.ok)throw new Error(!Array.isArray(data)&&data.error?.message?data.error.message:'Google Routes API request failed.');if(!Array.isArray(data))continue;for(const item of data){if(item.condition!=='ROUTE_EXISTS'||item.status?.code)continue;const i=item.destinationIndex,sec=parseSeconds(item.duration);if(i==null||sec==null)continue;const location=chunk[i];if(!location)continue;const drive={minutes:Math.round(sec/60),distanceMiles:Math.round(((item.distanceMeters||0)/1609.344)*10)/10};times[location]=drive;writes.push({origin_key:key,destination:location,minutes:drive.minutes,distance_miles:drive.distanceMiles,calculated_at:new Date().toISOString()})}}
 if(writes.length){const{error}=await c.from('driving_time_cache').upsert(writes,{onConflict:'origin_key,destination'});if(error)console.error('Could not persist driving-time cache',error.message)}
 return NextResponse.json({configured:true,origin,times,requested:locations.length,cacheHits,googleDestinations:missing.length});
 }catch(error){return NextResponse.json({configured:true,origin,times,requested:locations.length,cacheHits,googleDestinations:missing.length,error:error instanceof Error?error.message:'Driving times could not be loaded.'},{status:502})}
}
