import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@/lib/supabase-server';
const MAX_DESTINATIONS_PER_REQUEST=49;const MAX_LOCATIONS=2000;type MatrixElement={destinationIndex?:number;distanceMeters?:number;duration?:string;condition?:string;status?:{code?:number;message?:string}};
function parseSeconds(duration?:string){if(!duration)return null;const m=duration.match(/^([0-9]+(?:\.[0-9]+)?)s$/);if(!m)return null;const n=Number(m[1]);return Number.isFinite(n)?n:null}
export async function POST(req:NextRequest){const c=await createClient();const{data:{user}}=await c.auth.getUser();if(!user)return NextResponse.json({error:'Please sign in again.'},{status:401});let body:any;try{body=await req.json()}catch{return NextResponse.json({error:'Invalid request.'},{status:400})}
 let profileUserId=user.id;const requested=String(body?.athleteId||'').trim();if(requested&&requested!==user.id){const{data:access}=await c.from('parent_guardian_access').select('permissions').eq('parent_user_id',user.id).eq('athlete_user_id',requested).eq('status','active').maybeSingle();const{data:m}=await c.from('organization_members').select('role').eq('user_id',user.id).eq('status','active').limit(1).maybeSingle();const preview=m?.role==='owner'&&body?.previewRole==='parent'&&body?.previewAthlete===requested;if(!preview&&(!access||access.permissions?.view_discovery===false))return NextResponse.json({error:'Find Schools access unavailable.'},{status:403});profileUserId=requested}
 let{data:athlete}=await c.from('athlete_profiles').select('home_zip').eq('user_id',profileUserId).maybeSingle();
 if(!String(athlete?.home_zip||'').trim()&&!requested){const{data:links}=await c.from('parent_guardian_access').select('athlete_user_id,permissions').eq('parent_user_id',user.id).eq('status','active').limit(2);const allowed=(links||[]).filter((x:any)=>x.permissions?.view_discovery!==false);if(allowed.length===1){profileUserId=allowed[0].athlete_user_id;const r=await c.from('athlete_profiles').select('home_zip').eq('user_id',profileUserId).maybeSingle();athlete=r.data}}
 const zip=String(athlete?.home_zip||'').trim(),origin=zip?`${zip}, USA`:null;if(!origin)return NextResponse.json({configured:true,origin:null,times:{},error:'Add a home ZIP in the athlete profile to see driving times from home.'});const apiKey=process.env.GOOGLE_MAPS_API_KEY;if(!apiKey)return NextResponse.json({configured:false,origin,times:{},error:'Driving-time estimates are not configured yet.'});const raw=Array.isArray(body?.locations)?body.locations:[],locations:string[]=[...new Set(raw.map((v:any)=>String(v||'').trim()).filter(Boolean) as string[])].slice(0,MAX_LOCATIONS);if(!locations.length)return NextResponse.json({configured:true,origin,times:{}});const times:Record<string,{minutes:number;distanceMiles:number}>={};try{for(let start=0;start<locations.length;start+=MAX_DESTINATIONS_PER_REQUEST){const chunk=locations.slice(start,start+MAX_DESTINATIONS_PER_REQUEST);const res=await fetch('https://routes.googleapis.com/distanceMatrix/v2:computeRouteMatrix',{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':apiKey,'X-Goog-FieldMask':'destinationIndex,status,condition,distanceMeters,duration'},body:JSON.stringify({origins:[{waypoint:{address:origin}}],destinations:chunk.map(location=>({waypoint:{address:location}})),travelMode:'DRIVE',routingPreference:'TRAFFIC_UNAWARE',regionCode:'us'}),cache:'no-store'});const data=await res.json() as MatrixElement[]|{error?:{message?:string}};if(!res.ok)throw new Error(!Array.isArray(data)&&data.error?.message?data.error.message:'Google Routes API request failed.');if(!Array.isArray(data))continue;for(const item of data){if(item.condition!=='ROUTE_EXISTS'||item.status?.code)continue;const i=item.destinationIndex,sec=parseSeconds(item.duration);if(i==null||sec==null)continue;const location=chunk[i];if(location)times[location]={minutes:Math.round(sec/60),distanceMiles:Math.round(((item.distanceMeters||0)/1609.344)*10)/10}}}return NextResponse.json({configured:true,origin,times,requested:locations.length})}catch(error){return NextResponse.json({configured:true,origin,times:{},error:error instanceof Error?error.message:'Driving times could not be loaded.'},{status:502})}}
