'use client';

import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,CheckCircle2,Clock3,Search,ShieldCheck,UserPlus,Users,XCircle} from 'lucide-react';
import AppShell from '@/components/AppShell';
import PageHeader from '@/components/PageHeader';
import {createClient} from '@/lib/supabase-browser';

const text=(v:any)=>String(v||'').toLowerCase();

export default function AdvisorAccessPage(){
 const c=createClient();
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState('');
 const [orgId,setOrgId]=useState(''),[viewerId,setViewerId]=useState(''),[players,setPlayers]=useState<any[]>([]),[assignments,setAssignments]=useState<any[]>([]);
 useEffect(()=>{load()},[]);
 async function load(){setLoading(true);const {data:{user}}=await c.auth.getUser();if(!user){setLoading(false);return}setViewerId(user.id);const {data:me}=await c.from('organization_members').select('organization_id,role,status').eq('user_id',user.id).eq('status','active').maybeSingle();if(!me){setLoading(false);return}setOrgId(me.organization_id);const [{data:members},{data:as}]=await Promise.all([c.from('organization_members').select('user_id,role,status').eq('organization_id',me.organization_id).eq('status','active'),c.from('athlete_advisor_assignments').select('id,athlete_user_id,advisor_user_id,status,invited_at,responded_at').eq('organization_id',me.organization_id).eq('advisor_user_id',user.id)]);const athleteIds=(members||[]).filter((m:any)=>m.role==='athlete').map((m:any)=>String(m.user_id));const {data:profiles}=athleteIds.length?await c.from('profiles').select('id,full_name,email').in('id',athleteIds):{data:[] as any[]};setPlayers((profiles||[]).sort((a:any,b:any)=>text(a.full_name||a.email).localeCompare(text(b.full_name||b.email))));setAssignments(as||[]);setLoading(false)}
 const byAthlete=useMemo(()=>new Map(assignments.map(a=>[String(a.athlete_user_id),a])),[assignments]);
 const filtered=players.filter(p=>!search||[p.full_name,p.email].filter(Boolean).join(' ').toLowerCase().includes(search.toLowerCase()));
 async function requestAccess(athleteId:string){if(!viewerId||!orgId)return;setBusy(athleteId);setMessage('');const existing=byAthlete.get(athleteId);let error:any=null;if(existing){const r=await c.from('athlete_advisor_assignments').update({status:'pending',invited_at:new Date().toISOString(),responded_at:null,organization_id:orgId}).eq('id',existing.id);error=r.error}else{const r=await c.from('athlete_advisor_assignments').insert({athlete_user_id:athleteId,advisor_user_id:viewerId,organization_id:orgId,status:'pending',relationship_type:'Recruiting Advisor'});error=r.error}if(error){setMessage(error.message)}else{setMessage('Access request sent. The player must approve it before you can view and support their recruiting work.');await load()}setBusy('')}
 async function cancelRequest(athleteId:string){const existing=byAthlete.get(athleteId);if(!existing)return;setBusy(athleteId);setMessage('');const {error}=await c.from('athlete_advisor_assignments').update({status:'revoked',responded_at:new Date().toISOString()}).eq('id',existing.id);if(error)setMessage(error.message);else{setMessage('Request cancelled.');await load()}setBusy('')}
 const counts={active:assignments.filter(a=>a.status==='active').length,pending:assignments.filter(a=>a.status==='pending').length,available:players.filter(p=>!['active','pending'].includes(byAthlete.get(String(p.id))?.status)).length};
 return <AppShell><div className="max-w-6xl mx-auto px-4 sm:px-5 md:px-8 py-5 sm:py-6"><Link href="/advisors" className="text-sm font-bold inline-flex items-center gap-2 mb-4"><ArrowLeft size={15}/> Back to Advisor Home</Link><PageHeader eyebrow="WHO YOU CAN SUPPORT" title="Player Access" subtitle="Request access to players you advise. The player must approve the connection before you can view their recruiting work."/>
 <div className="mb-5 rounded-xl border bg-slate-50 px-4 py-3 text-sm text-slate-700"><b>Why approval matters:</b> Recruiting belongs to the player. Access lets you help with their schools, coach relationships, activity and Next Moves without taking control away from them.</div>
 {loading?<div className="card p-10 text-center muted">Loading players...</div>:<><div className="grid sm:grid-cols-3 gap-3 mb-5"><Metric icon={<CheckCircle2 size={18}/>} label="Players I Can Support" value={counts.active}/><Metric icon={<Clock3 size={18}/>} label="Waiting for Approval" value={counts.pending}/><Metric icon={<UserPlus size={18}/>} label="Available to Request" value={counts.available}/></div>
 <div className="card p-4 sm:p-5"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><h2 className="font-black text-lg flex items-center gap-2"><Users size={19}/>Players in Your Organization</h2><p className="muted text-sm mt-1">Once access is approved, open Player 360° to see the player’s recruiting picture and where your help may be useful.</p></div><div className="relative w-full md:w-80"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 muted"/><input className="input pl-9" placeholder="Search players" value={search} onChange={e=>setSearch(e.target.value)}/></div></div>{message&&<div className="mt-4 rounded-xl border bg-slate-50 px-4 py-3 text-sm font-semibold">{message}</div>}<div className="grid md:grid-cols-2 gap-3 mt-5">{filtered.map(p=>{const a=byAthlete.get(String(p.id));const status=a?.status||'none';return <div key={p.id} className="border rounded-xl p-4 flex flex-col sm:flex-row sm:items-center gap-4"><div className="min-w-0 flex-1">{status==='active'?<Link href={`/players/${p.id}`} className="font-black hover:underline">{p.full_name||'Player'}</Link>:<div className="font-black">{p.full_name||'Player'}</div>}<div className="muted text-sm truncate">{p.email}</div><div className="mt-2"><Status status={status}/></div></div><div className="shrink-0">{status==='active'?<Link href={`/players/${p.id}`} className="btn btn-red">Open Player 360°</Link>:status==='pending'?<button className="btn" onClick={()=>cancelRequest(String(p.id))} disabled={busy===p.id}><XCircle size={16}/>{busy===p.id?'Working...':'Cancel Request'}</button>:<button className="btn btn-red" onClick={()=>requestAccess(String(p.id))} disabled={busy===p.id}><UserPlus size={16}/>{busy===p.id?'Sending...':status==='declined'||status==='revoked'?'Request Again':'Request Access'}</button>}</div></div>})}{!filtered.length&&<div className="md:col-span-2 muted text-center py-10">No players match your search. Try a different name or clear the search.</div>}</div></div></>}</div></AppShell>;
}
function Status({status}:{status:string}){if(status==='active')return <span className="status-pill bg-green-50 text-green-700"><ShieldCheck size={13}/> Ready to support</span>;if(status==='pending')return <span className="status-pill bg-amber-50 text-amber-800"><Clock3 size={13}/> Waiting for player approval</span>;if(status==='declined')return <span className="status-pill bg-slate-100 text-slate-700">Previously declined</span>;if(status==='revoked')return <span className="status-pill bg-slate-100 text-slate-700">Access not active</span>;return <span className="status-pill bg-slate-100 text-slate-700">Not connected</span>}
function Metric({icon,label,value}:{icon:any,label:string,value:any}){return <div className="card p-4"><div className="flex items-center gap-2 muted text-sm">{icon}{label}</div><div className="text-2xl font-black mt-2">{value}</div></div>}
