import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@/lib/supabase-server';
import {createAdminClient} from '@/lib/supabase-admin';
import {REBELS_TEAMS} from '@/lib/rebels-teams';

async function membership(admin:any,userId:string){const {data,error}=await admin.from('organization_members').select('organization_id,role,status').eq('user_id',userId).eq('status','active').maybeSingle();if(error)throw new Error(error.message);return data||null}

export async function GET(){const c=await createClient();const {data:{user}}=await c.auth.getUser();if(!user)return NextResponse.json({error:'Please sign in again.'},{status:401});const admin=createAdminClient();try{const member=await membership(admin,user.id);if(!member)return NextResponse.json({teams:REBELS_TEAMS,currentTeam:''});const {data:existing}=await admin.from('team_members').select('team_id,teams(id,name,organization_id)').eq('athlete_user_id',user.id);const current=(existing||[]).map((r:any)=>Array.isArray(r.teams)?r.teams[0]:r.teams).find((t:any)=>t?.organization_id===member.organization_id);return NextResponse.json({teams:REBELS_TEAMS,currentTeam:current?.name||''})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Could not load team.'},{status:500})}}

export async function POST(req:NextRequest){const c=await createClient();const {data:{user}}=await c.auth.getUser();if(!user)return NextResponse.json({error:'Please sign in again.'},{status:401});let body:any;try{body=await req.json()}catch{return NextResponse.json({error:'Invalid request.'},{status:400})}const teamName=String(body?.teamName||'').trim();if(!REBELS_TEAMS.includes(teamName as any))return NextResponse.json({error:'Please choose a valid Rebels team.'},{status:400});const admin=createAdminClient();try{const member=await membership(admin,user.id);if(!member)return NextResponse.json({error:'You must belong to an organization before selecting a team.'},{status:403});let {data:team,error:teamError}=await admin.from('teams').select('id,name').eq('organization_id',member.organization_id).ilike('name',teamName).maybeSingle();if(teamError)throw new Error(teamError.message);if(!team){const created=await admin.from('teams').insert({organization_id:member.organization_id,name:teamName}).select('id,name').single();if(created.error)throw new Error(created.error.message);team=created.data}const {data:orgTeams,error:orgTeamsError}=await admin.from('teams').select('id').eq('organization_id',member.organization_id);if(orgTeamsError)throw new Error(orgTeamsError.message);const orgTeamIds=(orgTeams||[]).map((t:any)=>t.id);if(orgTeamIds.length){const removed=await admin.from('team_members').delete().eq('athlete_user_id',user.id).in('team_id',orgTeamIds);if(removed.error)throw new Error(removed.error.message)}const added=await admin.from('team_members').insert({team_id:team.id,athlete_user_id:user.id});if(added.error)throw new Error(added.error.message);return NextResponse.json({ok:true,team:team.name})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Could not save team.'},{status:500})}}
