import {NextResponse} from 'next/server';
import {inflateRawSync} from 'node:zlib';
import {createAdminClient} from '@/lib/supabase-admin';

export const maxDuration=300;
const TOKEN='rltnl-ipeds-load-20261001';
const norm=(s:string)=>String(s||'').toLowerCase().replace(/&/g,'and').replace(/\b(the|university|college|of|at|campus|main)\b/g,' ').replace(/[^a-z0-9]+/g,' ').trim();
function unzipFirst(buf:Buffer,prefix:string){let p=0;while(p+30<buf.length){if(buf.readUInt32LE(p)!==0x04034b50){p++;continue}const method=buf.readUInt16LE(p+8),cs=buf.readUInt32LE(p+18),ns=buf.readUInt16LE(p+26),es=buf.readUInt16LE(p+28),name=buf.subarray(p+30,p+30+ns).toString();const start=p+30+ns+es;if(name.toUpperCase().startsWith(prefix)&&name.toLowerCase().endsWith('.csv')){const data=buf.subarray(start,start+cs);return (method===8?inflateRawSync(data):data).toString('utf8')}p=start+cs}throw new Error('CSV not found '+prefix)}
function parse(text:string){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);const row=(line:string)=>{const a:string[]=[];let v='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){v+='"';i++}else q=!q}else if(ch===','&&!q){a.push(v);v=''}else v+=ch}a.push(v);return a};const h=row(lines[0]).map(x=>x.toUpperCase());return lines.slice(1).map(l=>{const v=row(l),o:any={};h.forEach((k,i)=>o[k]=v[i]||'');return o})}
async function get(url:string,prefix:string){const r=await fetch(url);if(!r.ok)throw new Error(url+' '+r.status);return parse(unzipFirst(Buffer.from(await r.arrayBuffer()),prefix))}
export async function GET(req:Request){if(new URL(req.url).searchParams.get('token')!==TOKEN)return NextResponse.json({error:'forbidden'},{status:403});try{const sb=createAdminClient();const [hd,comp]=await Promise.all([get('https://nces.ed.gov/ipeds/datacenter/data/HD2024.zip','HD2024'),get('https://nces.ed.gov/ipeds/datacenter/data/C2024_A.zip','C2024_A')]);const{data:schools,error}=await sb.from('colleges').select('id,name,state');if(error)throw error;const im=new Map(hd.map((r:any)=>[norm(r.INSTNM)+'|'+String(r.STABBR).toUpperCase(),Number(r.UNITID)]));const units=new Map<number,string>();for(const s of schools||[]){const u=im.get(norm(s.name)+'|'+String(s.state||'').toUpperCase());if(u){units.set(u,s.id);await sb.from('colleges').update({ipeds_unitid:u}).eq('id',s.id)}}const rec:any[]=[];for(const r of comp){const unit=Number(r.UNITID),college_id=units.get(unit),level=Number(r.AWLEVEL),total=Number(r.CTOTALT||0);if(!college_id||![5,6,7,8,17,18,19].includes(level)||total<=0)continue;const cip=String(r.CIPCODE||'').trim(),title=String(r.CIPTITLE||r.CIPDESC||'').trim();if(cip&&title)rec.push({college_id,ipeds_unitid:unit,cip_code:cip,cip_title:title,award_level:level,completions:total,reporting_year:2024,source:'IPEDS'})}await sb.from('college_programs').delete().eq('source','IPEDS');for(let i=0;i<rec.length;i+=500){const{error:e}=await sb.from('college_programs').upsert(rec.slice(i,i+500),{onConflict:'college_id,cip_code,award_level,reporting_year'});if(e)throw e}return NextResponse.json({ok:true,matched:units.size,programs:rec.length,year:2024})}catch(e){return NextResponse.json({ok:false,error:String(e)},{status:500})}}