'use client';
import {useEffect,useMemo,useState} from 'react';
import {useParams} from 'next/navigation';
import Link from 'next/link';
import {Activity,CalendarDays,ChevronLeft,Compass,Film,Flag,School,Target} from 'lucide-react';
import AppShell from '@/components/AppShell';
import {createClient} from '@/lib/supabase-browser';
import {RECRUITING_JOURNEY,normalizeJourneyStage} from '@/lib/recruiting-journey';

const one=(v:any)=>Array.isArray(v)?v[0]:v;
const fmt=(d?:string|null)=>d?new Date(`${String(d).slice(0,10)}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'Date unknown';

export default function ParentAthleteOverview(){const params=useParams<{id:string}>(),athleteId=String(params?.id||''),c=createClient();const [loading,setLoading]=useState(true),[allowed,setAllowed]=useState(false),[permissions,setPermissions]=useState<any>({}),[profile,setProfile]=useState<any>(null),[connections,setConnections]=useState<any[]>([]),[activity,setActivity]=useState<any[]>([]),[events,setEvents]=useState<any[]>([]),[fit,setFit]=useState<any>(null),[plan,setPlan]=useState<any>(null);
useEffect(()=>{(async()=>{if(!athleteId){setLoading(false);return}const {data:access}=await c.from('parent_guardian_access').select('status,permissions').eq('athlete_user_id',athleteId).eq('status','active').maybeSingle();if(!access){setLoading(false);return}setAllowed(true);const perms=access.permissions||{};setPermissions(perms);const jobs:any[]=[c.from('profiles').select('full_name').eq('id',athleteId).maybeSingle()];if(perms.view_connections!==false)jobs.push(c.from('athlete_colleges').select('id,status,college_id,colleges(id,name,division,state)').eq('athlete_user_id',athleteId).is('archived_at',null));else jobs.push(Promise.resolve({data:[]}));if(perms.view_activity!==false)jobs.push(c.from('interactions').select('id,type,date,date_precision,note,colleges(name),college_coaches(first_name,last_name)').eq('athlete_user_id',athleteId).order('date',{ascending:false}).order('created_at',{ascending:false}).limit(20));else jobs.push(Promise.resolve({data:[]}));if(perms.view_events!==false)jobs.push(c.from('athlete_events').select('id,status,events(id,name,date,type,location,colleges(name))').eq('athlete_user_id',athleteId));else jobs.push(Promise.resolve({data:[]}));if(perms.view_fit!==false)jobs.push(c.from('college_fit_profiles').select('*').eq('user_id',athleteId).maybeSingle());else jobs.push(Promise.resolve({data:null}));if(perms.view_game_plan!==false)jobs.push(c.from('recruiting_game_plans').select('*').eq('athlete_user_id',athleteId).order('period_start',{ascending:false}).limit(1).maybeSingle());else jobs.push(Promise.resolve({data:null}));const [p,co,int,ev,fp,gp]=await Promise.all(jobs);setProfile(p.data);setConnections(co.data||[]);setActivity(int.data||[]);setEvents((ev.data||[]).map((x:any)=>({...x,event:one(x.events)})).filter((x:any)=>x.event));setFit(fp.data);setPlan(gp.data);setLoading(false)})()},[athleteId]);
const stages=useMemo(()=>Object.fromEntries(RECRUITING_JOURNEY.map(s=>[s,connections.filter(r=>normalizeJourneyStage(r.status)===s).length])),[connections]);const upcoming=events.filter(x=>x.event?.date>=new Date().toISOString().slice(0,10)).sort((a,b)=>String(a.event.date).localeCompare(String(b.event.date))).slice(0,8);
if(loading)return <AppShell><div className="max-w-6xl mx-auto px-4 sm:px-5 md:px-8 py-6"><div className="card p-10 text-center muted">Loading athlete access...</div></div></AppShell>;
if(!allowed)return <AppShell><div className="max-w-3xl mx-auto px-4 sm:px-5 md:px-8 py-6"><div className="card p-8"><h1 className="text-2xl font-black">Access unavailable</h1><p className="muted mt-2">This athlete has not approved active Parent / Guardian access for your account.</p><Link href="/parent" className="btn mt-5">Back to Parent Home</Link></div></div></AppShell>;
return <AppShell><div className="max-w-6xl mx-auto px-4 sm:px-5 md:px-8 py-5 sm:py-7"><Link href="/parent" className="inline-flex items-center gap-1.5 text-sm font-bold mb-4"><ChevronLeft size={16}/>Parent Home</Link><div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4"><div><div className="text-xs uppercase tracking-[.16em] font-black text-red-600">Parent / Guardian · Read only</div><h1 className="text-2xl sm:text-3xl font-black mt-1">{profile?.full_name||'Athlete'}'s Recruiting Overview</h1><p className="muted mt-2">See only the recruiting information your athlete has chosen to share.</p></div>{permissions.view_discovery!==false&&<Link href={`/parent/discover?athlete=${athleteId}`} className="btn"><Compass size={16}/>Discovery</Link>}</div>
<div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 mt-6">{permissions.view_connections!==false&&<Metric icon={<School size={17}/>} label="Connections" value={connections.length}/>} {permissions.view_events!==false&&<Metric icon={<CalendarDays size={17}/>} label="Upcoming Events" value={upcoming.length}/>} {permissions.view_activity!==false&&<Metric icon={<Activity size={17}/>} label="Recent Activity" value={activity.length}/>} {permissions.view_progress!==false&&<Metric icon={<Flag size={17}/>} label="Offers / Committed" value={(stages['Offer']||0)+(stages['Committed']||0)}/>}</div>
{permissions.view_connections!==false&&<section className="card p-4 sm:p-5 mt-6"><h2 className="font-black text-lg flex items-center gap-2"><School size={18}/>Connections + Recruiting Journey</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-2 mt-4">{RECRUITING_JOURNEY.filter(s=>stages[s]>0).map(s=><div key={s} className="border rounded-xl p-3 flex items-center justify-between"><span className="text-sm font-semibold">{s}</span><b>{stages[s]}</b></div>)}</div><div className="mt-4 divide-y">{connections.slice(0,12).map(r=>{const school=one(r.colleges);return <div key={r.id} className="py-3 flex items-center justify-between gap-3"><div className="min-w-0"><div className="font-bold truncate">{school?.name||'College'}</div><div className="muted text-xs">{[school?.division,school?.state].filter(Boolean).join(' · ')}</div></div><span className="status-pill shrink-0">{normalizeJourneyStage(r.status)}</span></div>})}</div></section>}
<div className="grid lg:grid-cols-2 gap-5 sm:gap-6 mt-6">{permissions.view_events!==false&&<section className="card p-4 sm:p-5"><h2 className="font-black text-lg flex items-center gap-2"><CalendarDays size={18}/>Upcoming Events</h2><div className="mt-3 divide-y">{upcoming.map(x=><div key={x.id} className="py-3"><div className="font-bold text-sm">{x.event.name}</div><div className="muted text-xs mt-1">{fmt(x.event.date)} · {x.status==='going'?'Going':x.status==='not_going'?'Not Going':'Considering'}</div></div>)}{!upcoming.length&&<Empty text="No upcoming shared events."/>}</div></section>}{permissions.view_activity!==false&&<section className="card p-4 sm:p-5"><h2 className="font-black text-lg flex items-center gap-2"><Activity size={18}/>Recent Activity</h2><div className="mt-3 divide-y">{activity.slice(0,8).map(x=><div key={x.id} className="py-3"><div className="font-bold text-sm">{x.type}</div><div className="muted text-xs mt-1">{one(x.colleges)?.name||'College'} · {x.date_precision==='exact'?fmt(x.date):x.date_precision==='month'?'Month known':x.date_precision==='year'?'Year known':'Date unknown'}</div></div>)}{!activity.length&&<Empty text="No shared recruiting activity yet."/>}</div></section>}</div>
<div className="grid lg:grid-cols-2 gap-5 sm:gap-6 mt-6">{permissions.view_fit!==false&&<section className="card p-4 sm:p-5"><h2 className="font-black text-lg">College Fit</h2>{fit?<div className="mt-3 text-sm space-y-2"><div><b>Divisions:</b> {(fit.divisions||[]).join(', ')||'No preference recorded'}</div><div><b>School types:</b> {(fit.school_types||[]).join(', ')||'No preference recorded'}</div><div><b>Weather:</b> {(fit.weather_preferences||[]).join(', ')||'No preference recorded'}</div></div>:<Empty text="College Fit Profile has not been completed."/>}</section>}{permissions.view_game_plan!==false&&<section className="card p-4 sm:p-5"><h2 className="font-black text-lg flex items-center gap-2"><Target size={18}/>Game Plan</h2>{plan?<div className="mt-3 space-y-2">{(plan.goals||[]).map((g:any,i:number)=><div key={i} className="border rounded-xl p-3 text-sm flex gap-2"><span>{g.done?'✓':'○'}</span><span className={g.done?'line-through text-slate-400':'font-semibold'}>{g.title}</span></div>)}</div>:<Empty text="No shared Game Plan yet."/>}</section>}</div>
{permissions.view_videos!==false&&<Link href={`/videos?athlete=${athleteId}`} className="card p-4 sm:p-5 mt-6 flex items-center justify-between gap-3 hover:border-slate-400"><div><div className="font-black flex items-center gap-2"><Film size={18}/>Recruiting Videos</div><div className="muted text-sm mt-1">View the athlete's shared recruiting video library.</div></div><span className="font-bold text-sm">Open →</span></Link>}
</div></AppShell>}
function Metric({icon,label,value}:{icon:any;label:string;value:any}){return <div className="card p-4"><div className="flex items-center justify-between gap-2"><span className="muted text-xs">{label}</span>{icon}</div><div className="text-2xl font-black mt-2">{value}</div></div>}
function Empty({text}:{text:string}){return <div className="py-6 text-center muted text-sm">{text}</div>}
