import PublicLegalPage from '@/components/PublicLegalPage';

export const metadata={title:'Privacy Policy | Rebels Recruit',description:'Privacy Policy for Rebels Recruit.'};

export default function Privacy(){return <PublicLegalPage title="Privacy Policy" updated="September 8, 2026">
  <section><p>Rebels Recruit is a college softball recruiting relationship-management platform for athletes, recruiting advisors, coaches, and organization administrators. This Privacy Policy explains how Rebels Recruit collects, uses, stores, and protects information when you use the service, including information accessed through optional Google integrations.</p></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">Information we collect</h2><p>We may collect account and profile information you provide, recruiting information such as colleges, coaches, interactions, reminders, events and notes, organization membership and role information, and technical information needed to operate and secure the service.</p></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">How we use information</h2><p>We use information to provide and secure Rebels Recruit, organize recruiting relationships and activity, support collaboration within authorized organizations, provide reminders and event features, improve the service, respond to support requests, and comply with applicable legal obligations.</p></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">Google user data</h2><p>Connecting Google is optional. Rebels Recruit requests only the Google permissions needed for the features you choose to connect.</p><div className="mt-3 space-y-3"><p><strong>Gmail:</strong> If you connect Gmail, Rebels Recruit uses the Gmail send permission to send recruiting email that you initiate through Rebels Recruit on your behalf. Rebels Recruit does not request permission to read your Gmail inbox.</p><p><strong>Google Calendar:</strong> If you connect Google Calendar, Rebels Recruit may create, update, and delete Rebels Recruit-managed events on calendars you own; view events on calendars you are permitted to access; and view your subscribed calendar list so an authorized organization administrator can select a shared recruiting calendar. Events imported from an organization Google Calendar are displayed as read-only in Rebels Recruit and remain managed in Google Calendar.</p><p><strong>OAuth credentials:</strong> Google OAuth refresh tokens used to maintain a connection are stored server-side in encrypted form. Access tokens are obtained server-side as needed and are not intentionally exposed as ordinary user-readable application data.</p></div></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">Google API Services User Data Policy</h2><p>Rebels Recruit's use and transfer to any other app of information received from Google APIs will adhere to the Google API Services User Data Policy, including the Limited Use requirements. Google user data is used only to provide or improve the user-facing features described in this policy and is not used for advertising.</p></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">Sharing and service providers</h2><p>We do not sell Google user data. We may use service providers that process information on our behalf to host, secure, and operate Rebels Recruit. Information may also be visible to other authorized members of your Rebels Recruit organization according to your role and the collaboration features you use. We may disclose information when required by law or when reasonably necessary to protect users, the service, or others.</p></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">Data retention and deletion</h2><p>We retain information for as long as reasonably necessary to provide the service, maintain security and records, and meet legal obligations. You can disconnect Gmail and Google Calendar from Rebels Recruit. Disconnecting removes Rebels Recruit's stored connection for that service; it does not delete content that was already sent through Gmail or events already stored in Google unless the applicable product feature expressly does so. You may request deletion of your Rebels Recruit account or associated personal information by contacting us at the support email below, subject to legal and operational retention requirements.</p></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">Security</h2><p>We use administrative, technical, and organizational safeguards designed to protect information. No method of transmission or storage is completely secure, so we cannot guarantee absolute security.</p></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">Children and student athletes</h2><p>Rebels Recruit is designed for the college recruiting process and may be used by student athletes. Organizations and account holders are responsible for using the service in accordance with applicable laws and obtaining any consent required for minors. The service is not intended to be used to knowingly collect personal information from children under 13 without appropriate authorization.</p></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">Changes to this policy</h2><p>We may update this Privacy Policy as Rebels Recruit evolves. We will update the date above when material changes are published and provide additional notice when required.</p></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">Contact</h2><p>Questions about privacy, Google data, or deletion requests can be sent to <a className="font-bold text-red-700 hover:underline" href="mailto:bobwad01@gmail.com">bobwad01@gmail.com</a>.</p></section>
</PublicLegalPage>}
