'use client';
import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import {createClient} from '@/lib/supabase-browser';
import {AlertTriangle,RotateCcw} from 'lucide-react';

type Identity={name:string;email:string;organization:string;team:string};
const one=(v:any)=>Array.isArray(v)?v[0]:v;
export default function AccountLifecycleSettings(){
 const c=createClient();const [request,setRequest]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirmOpen,setConfirmOpen]=useState(false),[identity,setIdentity]=useState<Identity>({name:'Account holder',email:'Email unavailable',organization:'No organization assigned',team:'No team assigned'});
 async function load(){setLoading(true);setError('');const {data:{user},error:authError}=await c.auth.getUser();if(authError||!user){setError('We could not verify your account. Please refresh and try again.');setLoading(false);return}const [requestResult,profileResult,teamResponse]=await Promise.all([c.from('account_deletion_requests').select('id,status,requested_at').eq('user_id',user.id).in('status',['requested','processing']).order('requested_at',{ascending:false}).limit(1),c.from('profiles').select('full_name').eq('id',user.id).maybeSingle(),fetch('/api/profile/team')]);if(requestResult.error)setError('Account deletion status is temporarily unavailable. Your account has not been changed.');else setRequest(requestResult.data?.[0]||null);let organization='No organization assigned',team='No team assigned';if(teamResponse.ok){try{const data=await teamResponse.json();const org=(data.organizations||[]).find((m:any)=>m.organization_id===data.currentOrganizationId)||data.organizations?.[0];const orgData=one(org?.organizations);organization=[orgData?.name,orgData?.branch_name].filter(Boolean).join(' · ')||organization;const teamData=(data.teams||[]).find((t:any)=>t.id===data.currentTeamId);team=teamData?.name||team}catch{}}setIdentity({name:profileResult.data?.full_name||user.email||'Account holder',email:user.email||'Email unavailable',organization,team});setLoading(false)}
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!confirmOpen)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy)setConfirmOpen(false)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[confirmOpen,busy]);
 async function requestDeletion(){setBusy(true);setError('');const {error}=await c.rpc('request_account_deletion',{request_reason:'Requested from Settings'});if(error)setError('We could not submit your deletion request. Nothing was deleted. Please try again.');else setConfirmOpen(false);await load();setBusy(false)}
 async function cancel(){setBusy(true);setError('');const {error}=await c.rpc('cancel_account_deletion');if(error)setError('We could not cancel the request. Please try again.');await load();setBusy(false)}
 return <><div className="card p-6"><h2 className="font-black text-lg">Account & Data</h2><p className="muted text-sm mt-1">Your recruiting record belongs to your account. Leaving an organization removes that organization's access without deleting your recruiting history.</p>{loading?<div className="muted text-sm mt-4">Checking account status...</div>:error?<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-semibold text-amber-900">{error}</div>:request?<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="font-black flex items-center gap-2"><AlertTriangle size={17}/>Deletion request received</div><p className="text-sm mt-1">Your account is still active while the request is reviewed. Recruiting data is not deleted automatically when you submit this request.</p>{request.status==='requested'&&<button className="btn mt-3" disabled={busy} onClick={cancel}><RotateCcw size={15}/> Cancel deletion request</button>}</div>:<div className="mt-4"><button className="btn border-red-300 text-red-700" disabled={busy} onClick={()=>setConfirmOpen(true)}>Request Account Deletion</button><p className="muted text-xs mt-2">We record the request for review so organization access, parent access, imported history, and legal records can be handled correctly before deletion.</p></div>}</div>{confirmOpen&&typeof document!=='undefined'&&createPortal(<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/55 p-4" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setConfirmOpen(false)}}><div role="dialog" aria-modal="true" aria-labelledby="delete-account-title" className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="rr-eyebrow">CONFIRM ACCOUNT ACTION</div><h2 id="delete-account-title" className="mt-1 text-xl font-black">Request deletion for this account?</h2><p className="muted text-sm mt-2">Confirm the exact account and team context before continuing.</p><dl className="mt-5 grid gap-3 rounded-xl border bg-slate-50 p-4 text-sm">{[['Name',identity.name],['Email',identity.email],['Organization',identity.organization],['Team',identity.team]].map(([label,value])=><div key={label}><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-0.5 font-semibold break-all">{value}</dd></div>)}</dl><p className="mt-4 text-sm font-semibold text-red-700">Submitting this request does not immediately delete data. It starts the reviewed account-deletion process.</p><div className="mt-6 flex flex-col-reverse sm:flex-row sm:justify-end gap-2"><button className="btn" disabled={busy} onClick={()=>setConfirmOpen(false)}>Cancel</button><button className="btn btn-red" disabled={busy} onClick={requestDeletion}>{busy?'Submitting...':'Request Account Deletion'}</button></div></div></div>,document.body)}</>
}
