'use client';
import {useEffect,useState} from 'react';
import {createClient} from '@/lib/supabase-browser';
import {AlertTriangle,RotateCcw} from 'lucide-react';

export default function AccountLifecycleSettings(){
 const c=createClient();const [request,setRequest]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');const {data:{user},error:authError}=await c.auth.getUser();if(authError||!user){setError('We could not verify your account. Please refresh and try again.');setLoading(false);return}const {data,error}=await c.from('account_deletion_requests').select('id,status,requested_at').eq('user_id',user.id).in('status',['requested','processing']).order('requested_at',{ascending:false}).limit(1);if(error)setError('Account deletion status is temporarily unavailable. Your account has not been changed.');else setRequest(data?.[0]||null);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function requestDeletion(){if(!confirm('Request account deletion? Your account will remain active while the request is reviewed.'))return;setBusy(true);setError('');const {error}=await c.rpc('request_account_deletion',{request_reason:'Requested from Settings'});if(error)setError('We could not submit your deletion request. Nothing was deleted. Please try again.');await load();setBusy(false)}
 async function cancel(){setBusy(true);setError('');const {error}=await c.rpc('cancel_account_deletion');if(error)setError('We could not cancel the request. Please try again.');await load();setBusy(false)}
 return <div className="card p-6"><h2 className="font-black text-lg">Account & Data</h2><p className="muted text-sm mt-1">Your recruiting record belongs to your account. Leaving an organization removes that organization's access without deleting your recruiting history.</p>{loading?<div className="muted text-sm mt-4">Checking account status...</div>:error?<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-semibold text-amber-900">{error}</div>:request?<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="font-black flex items-center gap-2"><AlertTriangle size={17}/>Deletion request received</div><p className="text-sm mt-1">Your account is still active while the request is reviewed. Recruiting data is not deleted automatically when you submit this request.</p>{request.status==='requested'&&<button className="btn mt-3" disabled={busy} onClick={cancel}><RotateCcw size={15}/> Cancel deletion request</button>}</div>:<div className="mt-4"><button className="btn" disabled={busy} onClick={requestDeletion}>Request Account Deletion</button><p className="muted text-xs mt-2">We record the request for review so organization access, parent access, imported history, and legal records can be handled correctly before deletion.</p></div>}</div>
}
