'use client';
import {useEffect,useState} from 'react';
import {createClient} from '@/lib/supabase-browser';
const clarity=[['not_really','Not really'],['somewhat','Somewhat'],['very_clearly','Very clearly']];
const recommend=[['yes','Yes'],['maybe','Maybe'],['no','No']];
function Stars({value,onChange,label}:{value:number|null;onChange:(v:number)=>void;label:string}){return <div className="flex items-center gap-1" role="group" aria-label={label}>{[1,2,3,4,5].map(n=><button key={n} type="button" onClick={()=>onChange(n)} aria-label={`${n} of 5`} className={`text-3xl leading-none ${value&&n<=value?'text-amber-500':'text-slate-300'}`}>★</button>)}</div>}
export default function AthleteRecruitingExperience({collegeId,collegeName}:{collegeId:string;collegeName:string}){const c=createClient();const[loading,setLoading]=useState(true),[done,setDone]=useState(false),[dismissed,setDismissed]=useState(false),[overall,setOverall]=useState<number|null>(null),[communication,setCommunication]=useState<number|null>(null),[standing,setStanding]=useState(''),[rec,setRec]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
useEffect(()=>{c.from('athlete_recruiting_experiences').select('overall_experience,communication,standing_clarity,recommend_engaging,core_completed_at,dismissed_at').eq('college_id',collegeId).eq('subject_type','program').maybeSingle().then(({data})=>{if(data){setOverall(data.overall_experience);setCommunication(data.communication);setStanding(data.standing_clarity||'');setRec(data.recommend_engaging||'');setDone(!!data.core_completed_at);setDismissed(!!data.dismissed_at)}setLoading(false)})},[collegeId]);
async function save(){if(!overall&&!communication&&!standing&&!rec){setMessage('Answer at least one question to share your experience.');return}setSaving(true);setMessage('');const {data:{user}}=await c.auth.getUser();if(!user){setMessage('Please sign in again.');setSaving(false);return}const {error}=await c.from('athlete_recruiting_experiences').upsert({athlete_user_id:user.id,subject_type:'program',college_id:collegeId,overall_experience:overall,communication,standing_clarity:standing||null,recommend_engaging:rec||null,core_completed_at:new Date().toISOString(),dismissed_at:null,publication_status:'private',updated_at:new Date().toISOString()},{onConflict:'athlete_user_id,college_id'});setSaving(false);if(error){setMessage(error.message);return}setDone(true)}
async function dismiss(){const {data:{user}}=await c.auth.getUser();if(!user)return;await c.from('athlete_recruiting_experiences').upsert({athlete_user_id:user.id,subject_type:'program',college_id:collegeId,dismissed_at:new Date().toISOString(),publication_status:'private',updated_at:new Date().toISOString()},{onConflict:'athlete_user_id,college_id'});setDismissed(true)}
if(loading||dismissed)return null;if(done)return <section className="card p-4 sm:p-5"><div className="rr-eyebrow">ATHLETE EXPERIENCES</div><h2 className="font-black text-lg mt-1">Thanks. You've already helped.</h2><p className="muted text-sm mt-1">Your anonymous experience can help other athletes know what to expect from {collegeName}.</p></section>;
return <section className="card p-4 sm:p-5"><h2 className="font-black text-lg">Help other athletes understand this program better</h2><p className="muted text-sm mt-1">Share your recruiting experience with <b>{collegeName}</b>. Your feedback is anonymous and helps other athletes know what to expect.</p><div className="space-y-5 mt-5"><div><div className="font-bold text-sm">How was your overall recruiting experience with {collegeName}?</div><Stars value={overall} onChange={setOverall} label="Overall recruiting experience"/></div><div><div className="font-bold text-sm">How well did the staff communicate with you?</div><Stars value={communication} onChange={setCommunication} label="Staff communication"/></div><Choice label="Did you generally understand where you stood with them?" options={clarity} value={standing} onChange={setStanding}/><Choice label="Would you recommend other recruits engage with this program?" options={recommend} value={rec} onChange={setRec}/></div>{message&&<div className="text-sm font-bold text-red-700 mt-4">{message}</div>}<div className="flex flex-wrap items-center gap-3 mt-5"><button type="button" onClick={save} disabled={saving} className="btn btn-red">{saving?'Sharing…':'Share My Experience'}</button><button type="button" onClick={dismiss} className="text-sm font-semibold text-slate-500 hover:text-slate-900">Not now</button></div></section>}
function Choice({label,options,value,onChange}:{label:string;options:string[][];value:string;onChange:(v:string)=>void}){return <div><div className="font-bold text-sm">{label}</div><div className="flex flex-wrap gap-2 mt-2">{options.map(([v,l])=><button key={v} type="button" onClick={()=>onChange(v)} className={`rounded-lg border px-3 py-2 text-sm font-bold ${value===v?'border-slate-950 bg-slate-950 text-white':'bg-white hover:bg-slate-50'}`}>{l}</button>)}</div></div>}
