'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {CalendarDays,RefreshCw,Plus,Trash2,X,Link2,AlertCircle} from 'lucide-react';
type Sub={id:string;name:string;organization_id:string;team_id:string|null;enabled:boolean;last_synced_at:string|null;last_error:string|null};
type Org={id:string;name:string};type Team={id:string;name:string;organization_id:string};
export default function CalendarSubscriptions({onChange,readOnly=false}:{onChange:()=>void;readOnly?:boolean}){
 const [subs,setSubs]=useState<Sub[]>([]),[orgs,setOrgs]=useState<Org[]>([]),[teams,setTeams]=useState<Team[]>([]),[orgAdmins,setOrgAdmins]=useState<string[]>([]),[open,setOpen]=useState(false),[name,setName]=useState(''),[url,setUrl]=useState(''),[org,setOrg]=useState(''),[team,setTeam]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
 const load=useCallback(async()=>{try{const res=await fetch('/api/calendar-subscriptions?mode=manage',{cache:'no-store'});if(!res.ok)return;const d=await res.json();setSubs(d.subscriptions||[]);setOrgs(d.organizations||[]);setTeams(d.teams||[]);setOrgAdmins(d.organizationAdminIds||[]);setOrg((v:string)=>v||(d.organizations||[])[0]?.id||'')}catch{}},[]);
 useEffect(()=>{void load()},[load]);
 const scopedTeams=useMemo(()=>teams.filter(t=>t.organization_id===org),[teams,org]),canOrg=orgAdmins.includes(org);
 if(readOnly||(!orgs.length&&!subs.length))return null;
 async function call(method:string,body:any,task:string){setBusy(task);setError('');setMessage('');try{const res=await fetch('/api/calendar-subscriptions',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await res.json();if(!res.ok)throw new Error(d.error||'Calendar action failed.');await load();onChange();return d}catch(e){setError(e instanceof Error?e.message:'Calendar action failed.');return null}finally{setBusy('')}}
 async function add(e:React.FormEvent){e.preventDefault();const d=await call('POST',{organizationId:org,teamId:team||null,name,url},'add');if(d){setOpen(false);setName('');setUrl('');setMessage(d.sync?.ok?`Subscribed and imported ${d.sync.count} events.`:'Subscription saved, but its first sync failed. Use Sync Now to retry.');}}
 return <section className="card p-4 sm:p-5 mt-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black text-lg flex items-center gap-2"><CalendarDays size={20}/> Calendar Subscriptions</h2><p className="muted text-sm mt-1">Read-only public Google calendars. Organization feeds appear for every team; team feeds only for their team.</p></div><button type="button" className="btn btn-red min-h-11 sm:min-h-9" onClick={()=>{setError('');setOpen(true)}}><Plus size={16}/> Add Calendar</button></div>
 {error&&<div role="alert" className="mt-3 text-sm text-red-700 flex items-center gap-2"><AlertCircle size={16}/>{error}</div>}{message&&<div className="mt-3 text-sm text-green-700 font-semibold">{message}</div>}
 <div className="mt-4 space-y-2">{subs.map(s=><div key={s.id} className="border rounded-xl p-3 flex flex-col sm:flex-row sm:items-center gap-3"><div className="min-w-0 flex-1"><div className="font-bold text-sm break-words">{s.name}</div><div className="muted text-xs mt-1">{orgs.find(o=>o.id===s.organization_id)?.name||'Organization'} · {s.team_id?teams.find(t=>t.id===s.team_id)?.name||'Team':'All teams'} · {s.last_synced_at?'Synced '+new Date(s.last_synced_at).toLocaleString():'Not synced yet'}</div>{s.last_error&&<div className="text-red-700 text-xs mt-1">{s.last_error}</div>}</div><div className="flex flex-wrap items-center gap-2"><button type="button" disabled={!!busy} className="btn min-h-9 text-xs" onClick={()=>void call('PATCH',{id:s.id,enabled:!s.enabled},s.id)}>{s.enabled?'Pause':'Resume'}</button><button type="button" disabled={!!busy} className="btn min-h-9 text-xs" onClick={async()=>{const d=await call('POST',{action:'sync',id:s.id},s.id);if(d)setMessage(`Synced ${d.count} events.`)}}><RefreshCw size={14}/> Sync Now</button><button type="button" disabled={!!busy} className="btn min-h-9 text-xs" onClick={()=>{if(window.confirm('Remove this calendar subscription? Imported events will disappear, but player attendance history is retained.'))void call('DELETE',{id:s.id},s.id)}} aria-label={`Remove ${s.name}`}><Trash2 size={14}/></button></div></div>)}{!subs.length&&<div className="muted text-sm py-3">No calendars subscribed yet.</div>}</div>
 {open&&<div className="fixed inset-0 z-[110] bg-slate-950/50 p-4 flex items-center justify-center" onMouseDown={e=>{if(e.currentTarget===e.target)setOpen(false)}}><div role="dialog" aria-modal="true" aria-labelledby="calendar-sub-title" className="w-full max-w-lg max-h-[85vh] overflow-y-auto rounded-2xl bg-white p-5 sm:p-6 shadow-2xl"><div className="flex items-center justify-between gap-2"><h3 id="calendar-sub-title" className="font-black text-xl">Add Calendar Subscription</h3><button type="button" onClick={()=>setOpen(false)} className="min-w-11 min-h-11 flex items-center justify-center" aria-label="Close"><X size={20}/></button></div><p className="muted text-sm mt-2">In Google Calendar, open Settings → Integrate calendar → Public address in iCal format. The calendar must be publicly viewable. Do not use a secret iCal address.</p><form onSubmit={add} className="mt-4 space-y-3"><label className="block text-sm font-bold">Calendar name<input className="input mt-1" value={name} onChange={e=>setName(e.target.value)} placeholder="College Softball Camps" maxLength={120} required/></label><label className="block text-sm font-bold">Public ICS URL<input className="input mt-1" type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://calendar.google.com/calendar/ical/.../public/basic.ics" required/></label><label className="block text-sm font-bold">Organization<select className="input mt-1" value={org} onChange={e=>{setOrg(e.target.value);setTeam('')}}>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label className="block text-sm font-bold">Visibility<select className="input mt-1" value={team} onChange={e=>setTeam(e.target.value)} required={!canOrg}>{canOrg&&<option value="">All teams in organization</option>}{scopedTeams.map(t=><option key={t.id} value={t.id}>{t.name} only</option>)}</select></label>{error&&<div role="alert" className="text-sm text-red-700">{error}</div>}<div className="flex justify-end gap-2 pt-2"><button type="button" className="btn min-h-11" onClick={()=>setOpen(false)}>Cancel</button><button type="submit" disabled={!!busy||(!canOrg&&!team)} className="btn btn-red min-h-11"><Link2 size={15}/>{busy?'Connecting…':'Subscribe'}</button></div></form></div></div>}</section>;
}
