'use client';
import Link from 'next/link';
import {useMemo,useState} from 'react';
import {Plus,Search,School,Users,ArrowUpDown} from 'lucide-react';
import {createClient} from '@/lib/supabase-browser';

type RowValue=Record<string,any>|Record<string,any>[]|null|undefined;
type BoardProps={colleges:any[];coaches:any[];masterColleges:any[];masterCoaches:any[]};
type CollegeSort='name'|'division'|'conference'|'state'|'last_contact';
type CoachSort='name'|'school'|'division'|'conference'|'state'|'last_contact';
const aliases:Record<string,string>={sec:'southeastern conference',b1g:'big ten conference','big 10':'big ten conference','big ten':'big ten conference',acc:'atlantic coast conference',aac:'american athletic conference',mac:'mid-american conference',mvc:'missouri valley conference',wcc:'west coast conference',caa:'colonial athletic association',swac:'southwestern athletic conference',meac:'mid-eastern athletic conference',wac:'western athletic conference',rmacc:'rocky mountain athletic conference',kjccc:'kjccc'};
const unwrap=(v:RowValue):Record<string,any>|undefined=>Array.isArray(v)?v[0]:v||undefined;
const text=(v:any)=>String(v||'').toLowerCase();
const displayStatus=(s?:string)=>s?String(s).replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase()):'Researching';

export default function CollegesCoachesBoard({colleges,coaches,masterColleges,masterCoaches}:BoardProps){
 const c=createClient();
 const [search,setSearch]=useState('');
 const [collegeSort,setCollegeSort]=useState<CollegeSort>('name');
 const [coachSort,setCoachSort]=useState<CoachSort>('name');
 const [busy,setBusy]=useState('');
 const raw=search.trim().toLowerCase();
 const q=aliases[raw]||raw;
 const trackedCollegeIds=new Set(colleges.map((r:any)=>unwrap(r.colleges)?.id).filter(Boolean));
 const trackedCoachIds=new Set(coaches.map((r:any)=>unwrap(r.college_coaches)?.id).filter(Boolean));
 const collegeLastContact=useMemo(()=>{const m=new Map<string,string>();coaches.forEach((r:any)=>{const id=unwrap(r.colleges)?.id;if(id&&r.last_contact_date&&(!m.get(id)||r.last_contact_date>String(m.get(id))))m.set(id,r.last_contact_date)});return m},[coaches]);
 const filteredColleges=useMemo(()=>colleges.filter((row:any)=>{if(!q)return true;const x=unwrap(row.colleges);return [x?.name,x?.division,x?.state,x?.city,x?.conference,row.status].filter(Boolean).join(' ').toLowerCase().includes(q)}).sort((a:any,b:any)=>{const A=unwrap(a.colleges)||{},B=unwrap(b.colleges)||{};const av=collegeSort==='last_contact'?collegeLastContact.get(A.id)||'':text(A[collegeSort]);const bv=collegeSort==='last_contact'?collegeLastContact.get(B.id)||'':text(B[collegeSort]);return collegeSort==='last_contact'?String(bv).localeCompare(String(av)):String(av).localeCompare(String(bv))}),[colleges,q,collegeSort,collegeLastContact]);
 const filteredCoaches=useMemo(()=>coaches.filter((row:any)=>{if(!q)return true;const x=unwrap(row.colleges),coach=unwrap(row.college_coaches);return [coach?.first_name,coach?.last_name,coach?.title,coach?.email,coach?.phone,x?.name,x?.state,x?.city,x?.division,x?.conference].filter(Boolean).join(' ').toLowerCase().includes(q)}).sort((a:any,b:any)=>{const ac=unwrap(a.college_coaches)||{},bc=unwrap(b.college_coaches)||{},A=unwrap(a.colleges)||{},B=unwrap(b.colleges)||{};const av=coachSort==='name'?`${ac.last_name||''} ${ac.first_name||''}`:coachSort==='school'?A.name:coachSort==='last_contact'?a.last_contact_date||'':A[coachSort];const bv=coachSort==='name'?`${bc.last_name||''} ${bc.first_name||''}`:coachSort==='school'?B.name:coachSort==='last_contact'?b.last_contact_date||'':B[coachSort];return coachSort==='last_contact'?String(bv||'').localeCompare(String(av||'')):text(av).localeCompare(text(bv))}),[coaches,q,coachSort]);
 const directoryResults=useMemo(()=>{if(raw.length<2)return[];return masterColleges.filter((x:any)=>[x.name,x.division,x.state,x.city,x.conference,x.school_type].filter(Boolean).join(' ').toLowerCase().includes(q)).slice(0,10)},[masterColleges,q,raw]);
 const coachesByCollege=useMemo(()=>{const m=new Map<string,any[]>();masterCoaches.forEach((coach:any)=>{const rows=m.get(coach.college_id)||[];rows.push(coach);m.set(coach.college_id,rows)});return m},[masterCoaches]);
 async function addCollege(college:any){setBusy(`college-${college.id}`);const {data:{user}}=await c.auth.getUser();if(user){await c.from('athlete_colleges').upsert({athlete_user_id:user.id,college_id:college.id,status:'Researching'},{onConflict:'athlete_user_id,college_id'});location.reload()}setBusy('')}
 async function addCoach(coach:any,college:any){setBusy(`coach-${coach.id}`);const {data:{user}}=await c.auth.getUser();if(user){await c.from('athlete_colleges').upsert({athlete_user_id:user.id,college_id:college.id,status:'Researching'},{onConflict:'athlete_user_id,college_id'});await c.from('athlete_coaches').upsert({athlete_user_id:user.id,coach_id:coach.id,college_id:college.id},{onConflict:'athlete_user_id,coach_id'});location.reload()}setBusy('')}
 return <>
  <div className="flex items-start justify-between gap-4 mb-6"><div><h1 className="text-2xl md:text-3xl font-black tracking-tight">Colleges & Coaches</h1><p className="muted mt-1">Keep your schools and coach relationships together in one place.</p></div><div className="flex flex-col gap-2"><Link href="/colleges/new" className="btn btn-red"><Plus size={18}/> Add College</Link><Link href="/coaches/new" className="btn"><Plus size={18}/> Add Coach</Link></div></div>
  <div className="card p-3 mb-4 flex items-center gap-3"><Search size={18} className="muted"/><input className="w-full outline-none" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search any college, coach, state, division or conference (SEC, B1G...)"/></div>
  {raw.length>=2&&<section className="card p-4 mb-7"><div className="flex items-center justify-between gap-3"><div><div className="font-black">Search the college directory</div><div className="muted text-sm">Find schools you have not added yet and quickly add known coaches.</div></div><span className="text-xs muted">{directoryResults.length} results</span></div><div className="mt-4 grid md:grid-cols-2 gap-3">{directoryResults.map((x:any)=>{const known=(coachesByCollege.get(x.id)||[]).slice(0,3);return <div key={x.id} className="border rounded-xl p-4"><div className="flex justify-between gap-3"><div><div className="font-bold">{x.name}</div><div className="muted text-sm mt-1">{x.division||'Division not listed'} · {[x.city,x.state].filter(Boolean).join(', ')||'Location not listed'}</div><div className="muted text-xs mt-1">{x.conference||'Conference not listed'}</div></div>{trackedCollegeIds.has(x.id)?<span className="pill">Added</span>:<button className="btn btn-red shrink-0" disabled={busy===`college-${x.id}`} onClick={()=>addCollege(x)}><Plus size={15}/>{busy===`college-${x.id}`?'Adding...':'Add College'}</button>}</div>{known.length>0&&<div className="mt-3 pt-3 border-t space-y-2">{known.map((coach:any)=><div key={coach.id} className="flex items-center justify-between gap-2 text-sm"><div><b>{[coach.first_name,coach.last_name].filter(Boolean).join(' ')}</b><span className="muted"> · {coach.title||'Coach'}</span></div>{trackedCoachIds.has(coach.id)?<span className="text-xs font-bold text-slate-500">Added</span>:<button className="text-sm font-bold" disabled={busy===`coach-${coach.id}`} onClick={()=>addCoach(coach,x)}>+ Add Coach</button>}</div>)}</div>}</div>})}{!directoryResults.length&&<div className="muted py-5 md:col-span-2 text-center">No directory matches found.</div>}</div></section>}
  <section><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-4"><div className="flex items-center gap-2"><School size={20}/><h2 className="font-black text-xl">Colleges</h2><span className="muted text-sm">{filteredColleges.length}</span></div><label className="flex items-center gap-2 text-sm"><ArrowUpDown size={16}/><span className="muted">Sort</span><select className="input py-2" value={collegeSort} onChange={e=>setCollegeSort(e.target.value as CollegeSort)}><option value="name">Alphabetical</option><option value="division">Division</option><option value="conference">Conference</option><option value="state">State</option><option value="last_contact">Date of Last Contact</option></select></label></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{filteredColleges.map((row:any)=>{const x=unwrap(row.colleges);return <Link href={`/colleges/${x?.id}`} key={row.id} className="card p-5 hover:shadow-md transition min-h-[225px] flex flex-col"><div className="flex justify-between gap-4"><div className="font-black text-lg leading-tight">{x?.name||'College'}</div><span className="pill shrink-0 min-w-[108px] text-center whitespace-nowrap">{displayStatus(row.status)}</span></div><div className="mt-4 grid grid-cols-[90px_1fr] gap-y-2 text-sm"><span className="muted">Division</span><span className="font-semibold">{x?.division||'Not listed'}</span><span className="muted">Location</span><span className="font-semibold">{[x?.city,x?.state].filter(Boolean).join(', ')||'Not listed'}</span><span className="muted">Conference</span><span className="font-semibold">{x?.conference||'Not listed'}</span></div><div className="mt-auto pt-5 flex justify-between text-sm border-t"><span className="muted">Fit</span><span className="font-bold">{row.fit_rating?`${row.fit_rating}/5`:'Not rated'}</span></div></Link>})}{!filteredColleges.length&&<div className="card p-8 md:col-span-2 xl:col-span-3 text-center"><div className="font-black">No tracked colleges match your search.</div><p className="muted mt-2">Use the directory results above to add a new school.</p></div>}</div></section>
  <section className="mt-9"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-4"><div className="flex items-center gap-2"><Users size={20}/><h2 className="font-black text-xl">Coaches</h2><span className="muted text-sm">{filteredCoaches.length}</span></div><label className="flex items-center gap-2 text-sm"><ArrowUpDown size={16}/><span className="muted">Sort</span><select className="input py-2" value={coachSort} onChange={e=>setCoachSort(e.target.value as CoachSort)}><option value="name">Alphabetical</option><option value="school">School</option><option value="division">Division</option><option value="conference">Conference</option><option value="state">State</option><option value="last_contact">Date of Last Contact</option></select></label></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{filteredCoaches.map((row:any)=>{const x=unwrap(row.colleges),coach=unwrap(row.college_coaches);return <div key={row.id} className="card p-5 min-h-[205px] flex flex-col"><div className="font-black text-lg">{[coach?.first_name,coach?.last_name].filter(Boolean).join(' ')||'Coach'}</div><div className="muted text-sm mt-1">{coach?.title||'Coach'} · {x?.name||'School not listed'}</div><div className="mt-4 text-sm space-y-1"><div><span className="muted">Email: </span>{coach?.email||'Not listed'}</div><div><span className="muted">Phone: </span>{coach?.phone||'Not listed'}</div><div><span className="muted">Last contact: </span>{row.last_contact_date||'No contact logged'}</div></div><div className="mt-auto pt-4 flex items-center justify-end gap-3 border-t">{coach?.id&&<Link href={`/coaches/${coach.id}/edit`} className="text-sm font-bold">Edit Coach</Link>}{x?.id&&coach?.id?<Link href={`/activity/new?college=${x.id}&coach=${coach.id}`} className="text-sm font-bold">Log Interaction</Link>:null}</div></div>})}{!filteredCoaches.length&&<div className="card p-8 md:col-span-2 xl:col-span-3 text-center"><div className="font-black">No tracked coaches match your search.</div><p className="muted mt-2">Search the directory above or use Add Coach.</p></div>}</div></section>
 </>
}
