'use client';
import {useEffect,useMemo,useState} from 'react';
import {Search,X} from 'lucide-react';
type College={id:string;name:string;division?:string|null;city?:string|null;state?:string|null;conference?:string|null;school_type?:string|null};
type Props={colleges?:College[];value:string;onChange:(collegeId:string)=>void;placeholder?:string;allowNone?:boolean};
const aliases:Record<string,string>={sec:'southeastern conference',b1g:'big ten conference','big 10':'big ten conference','big ten':'big ten conference',acc:'atlantic coast conference',aac:'american athletic conference',mac:'mid-american conference',mvc:'missouri valley conference',wcc:'west coast conference',caa:'colonial athletic association',swac:'southwestern athletic conference',meac:'mid-eastern athletic conference',wac:'western athletic conference',rmacc:'rocky mountain athletic conference'};
export default function CollegeSearchSelect({colleges,value,onChange,placeholder='Search school, state, division or conference...',allowNone=true}:Props){
 const [remote,setRemote]=useState<College[]>([]),[query,setQuery]=useState(''),[open,setOpen]=useState(false),[loading,setLoading]=useState(false);const options=colleges??remote;const selected=options.find(c=>c.id===value)||null;
 useEffect(()=>{if(colleges!==undefined||!open)return;const raw=query.trim().toLowerCase(),q=aliases[raw]||raw;if(q.length<2){setRemote([]);return}const ctl=new AbortController();const timer=setTimeout(async()=>{setLoading(true);try{const r=await fetch(`/api/search/colleges?q=${encodeURIComponent(q)}`,{signal:ctl.signal});const j=await r.json();setRemote(j.items||[])}catch{}finally{setLoading(false)}},180);return()=>{clearTimeout(timer);ctl.abort()}},[colleges,open,query]);
 const matches=useMemo(()=>{if(colleges===undefined)return remote;const raw=query.trim().toLowerCase(),q=aliases[raw]||raw;if(!q)return options.slice(0,12);return options.filter(c=>[c.name,c.division,c.city,c.state,c.conference,c.school_type].filter(Boolean).join(' ').toLowerCase().includes(q)).slice(0,30)},[colleges,options,query,remote]);
 return <div className="relative"><div className="input flex items-center gap-2 px-3"><Search size={16} className="muted shrink-0"/><input className="min-w-0 flex-1 bg-transparent outline-none" value={open?query:(selected?.name||'')} placeholder={selected?'':placeholder} onFocus={()=>{setOpen(true);setQuery('')}} onChange={e=>{setQuery(e.target.value);setOpen(true)}} onBlur={()=>window.setTimeout(()=>setOpen(false),120)} aria-label="Search school" autoComplete="off"/>{value&&<button type="button" className="muted shrink-0" aria-label="Clear school" onMouseDown={e=>e.preventDefault()} onClick={()=>{onChange('');setQuery('');setOpen(false)}}><X size={15}/></button>}</div>{open&&<div className="absolute z-30 mt-1 max-h-72 w-full overflow-y-auto rounded-xl border bg-white shadow-lg">{allowNone&&<button type="button" className="block w-full px-3 py-2.5 text-left text-sm hover:bg-slate-50" onMouseDown={e=>e.preventDefault()} onClick={()=>{onChange('');setQuery('');setOpen(false)}}>No school</button>}{matches.map(col=><button key={col.id} type="button" className="block w-full border-t px-3 py-2.5 text-left hover:bg-slate-50" onMouseDown={e=>e.preventDefault()} onClick={()=>{onChange(col.id);setRemote(prev=>prev.some(x=>x.id===col.id)?prev:[col,...prev]);setQuery('');setOpen(false)}}><div className="text-sm font-semibold">{col.name}</div><div className="muted mt-0.5 text-xs">{[col.division,[col.city,col.state].filter(Boolean).join(', '),col.conference].filter(Boolean).join(' · ')}</div></button>)}{loading&&<div className="px-3 py-3 text-sm muted">Searching…</div>}{!loading&&!matches.length&&query.trim().length>=2&&<div className="px-3 py-3 text-sm muted">No matching schools</div>}{colleges===undefined&&query.trim().length<2&&<div className="px-3 py-3 text-sm muted">Type at least 2 characters to search.</div>}</div>}</div>
}
