'use client';
import Link from 'next/link';
import {useMemo,useState} from 'react';
import {Archive,CheckCircle2,Plus,RotateCcw,School,Search,Users} from 'lucide-react';
import {createClient} from '@/lib/supabase-browser';
import {RECRUITING_JOURNEY,normalizeJourneyStage} from '@/lib/recruiting-journey';
import {announceSuccess} from '@/lib/feedback';
import {emitDataChanged} from '@/lib/data-events';

const one=(v:any)=>Array.isArray(v)?v[0]:v;
const fmt=(d?:string|null)=>d?new Date(`${String(d).slice(0,10)}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'';
type Props={initialColleges:any[];initialCoaches:any[]};
type PendingArchive={kind:'college'|'coach';row:any;name:string}|null;

export default function ConnectionsBoard({initialColleges,initialCoaches}:Props){
 const c=createClient();
 const[colleges,setColleges]=useState(initialColleges),[coaches,setCoaches]=useState(initialCoaches),[mode,setMode]=useState<'current'|'all'>('current'),[search,setSearch]=useState(''),[busy,setBusy]=useState(''),[pending,setPending]=useState<PendingArchive>(null),[error,setError]=useState('');
 const q=search.trim().toLowerCase();
 const visibleColleges=useMemo(()=>colleges.filter(r=>(mode==='all'||!r.archived_at)&&(!q||[one(r.colleges)?.name,one(r.colleges)?.division,one(r.colleges)?.state,one(r.colleges)?.conference,normalizeJourneyStage(r.status)].filter(Boolean).join(' ').toLowerCase().includes(q))),[colleges,mode,q]);
 const visibleCoaches=useMemo(()=>coaches.filter(r=>(mode==='all'||!r.archived_at)&&(!q||[one(r.college_coaches)?.first_name,one(r.college_coaches)?.last_name,one(r.college_coaches)?.title,one(r.college_coaches)?.email,one(r.colleges)?.name].filter(Boolean).join(' ').toLowerCase().includes(q))),[coaches,mode,q]);
 async function changeStage(row:any,stage:string){const previous=row.status;if(normalizeJourneyStage(previous)===stage)return;setError('');setColleges(p=>p.map(x=>x.id===row.id?{...x,status:stage}:x));setBusy(`stage-${row.id}`);const r=await fetch('/api/recruiting-journey',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({relationshipId:row.id,stage,milestoneDate:new Date().toISOString().slice(0,10),note:'',offerType:''})});if(!r.ok){setColleges(p=>p.map(x=>x.id===row.id?{...x,status:previous}:x));setError('Could not update the Recruiting Journey. Your previous stage was restored.')}else{emitDataChanged('athlete_colleges','update',row.id);announceSuccess('Recruiting Journey updated.')}setBusy('')}
 async function confirmArchive(){if(!pending)return;const{kind,row}=pending,at=new Date().toISOString();setPending(null);setBusy(`${kind}-${row.id}`);setError('');if(kind==='college')setColleges(p=>p.map(x=>x.id===row.id?{...x,archived_at:at,archived_reason:'Stopped pursuing'}:x));else setCoaches(p=>p.map(x=>x.id===row.id?{...x,archived_at:at,archived_reason:'Stopped pursuing'}:x));let failed=false;if(kind==='college'){const school=one(row.colleges);const a=await c.from('athlete_colleges').update({archived_at:at,archived_reason:'Stopped pursuing'}).eq('id',row.id);if(a.error)failed=true;else if(school?.id){const b=await c.from('athlete_coaches').update({archived_at:at,archived_reason:'College stopped pursuing'}).eq('college_id',school.id).is('archived_at',null);if(b.error)failed=true;else setCoaches(p=>p.map(x=>x.college_id===school.id&&!x.archived_at?{...x,archived_at:at,archived_reason:'College stopped pursuing'}:x))}}else{const a=await c.from('athlete_coaches').update({archived_at:at,archived_reason:'Stopped pursuing'}).eq('id',row.id);if(a.error)failed=true}if(failed){if(kind==='college')setColleges(p=>p.map(x=>x.id===row.id?row:x));else setCoaches(p=>p.map(x=>x.id===row.id?row:x));setError('Could not archive this relationship. Nothing was changed.')}else{emitDataChanged(kind==='college'?'athlete_colleges':'athlete_coaches','archive',row.id);announceSuccess(kind==='college'?'School moved to All-Time.':'Coach moved to All-Time.')}setBusy('')}
 async function restore(kind:'college'|'coach',row:any){setBusy(`${kind}-${row.id}`);setError('');const setter=kind==='college'?setColleges:setCoaches;setter((p:any[])=>p.map(x=>x.id===row.id?{...x,archived_at:null,archived_reason:null}:x));const table=kind==='college'?'athlete_colleges':'athlete_coaches';const r=await c.from(table).update({archived_at:null,archived_reason:null}).eq('id',row.id);if(r.error){setter((p:any[])=>p.map(x=>x.id===row.id?row:x));setError('Could not restore this relationship.')}else{emitDataChanged(table,'restore',row.id);announceSuccess(kind==='college'?'School restored to Current Pipeline.':'Coach restored to Current Pipeline.')}setBusy('')}
 return <>
 <div className="card p-4 mb-5"><div className="flex flex-col lg:flex-row gap-3"><div className="inline-flex rounded-xl border bg-white p-1 self-start"><button className={`px-4 py-2 rounded-lg text-sm font-black ${mode==='current'?'bg-slate-900 text-white':''}`} onClick={()=>setMode('current')}>Current Pipeline <span className="opacity-70 ml-1">{colleges.filter(x=>!x.archived_at).length}</span></button><button className={`px-4 py-2 rounded-lg text-sm font-black ${mode==='all'?'bg-slate-900 text-white':''}`} onClick={()=>setMode('all')}>All-Time <span className="opacity-70 ml-1">{colleges.length}</span></button></div><div className="flex-1 flex items-center gap-3 border rounded-xl px-3 bg-white"><Search size={18}/><input className="w-full py-3 outline-none" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search school, coach, division, conference or journey stage"/></div><Link href="/colleges/new" className="btn btn-red"><Plus size={16}/>Add School</Link><Link href="/coaches/new" className="btn"><Plus size={16}/>Add Coach</Link></div></div>
 {error&&<div role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
 <section><div className="flex items-center gap-2 mb-3"><School size={20}/><h2 className="text-xl font-black">Schools ({visibleColleges.length})</h2></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{visibleColleges.map(row=>{const x=one(row.colleges),stage=normalizeJourneyStage(row.status);return <div key={row.id} className={`card p-5 flex flex-col min-h-[240px] ${row.archived_at?'opacity-75':''}`}><div className="flex justify-between gap-3"><Link href={`/colleges/${x?.id}`} className="font-black text-lg hover:text-red-700 hover:underline">{x?.name||'School'}</Link><span className="status-pill">{row.archived_at?'Archived':stage}</span></div><div className="muted text-sm mt-2">{[x?.division,[x?.city,x?.state].filter(Boolean).join(', '),x?.conference].filter(Boolean).join(' · ')||'School details not listed'}</div>{!row.archived_at?<label className="block mt-5 text-xs font-bold muted">Recruiting Journey<select className="input mt-1 py-2 text-sm" value={stage} disabled={busy===`stage-${row.id}`} onChange={e=>changeStage(row,e.target.value)}>{RECRUITING_JOURNEY.map(s=><option key={s}>{s}</option>)}</select></label>:<div className="text-sm mt-5"><b>Stopped pursuing:</b> {fmt(row.archived_at)}</div>}<div className="mt-auto pt-4"><button disabled={!!busy} onClick={()=>row.archived_at?restore('college',row):setPending({kind:'college',row,name:x?.name||'this school'})} className={`inline-flex items-center gap-1.5 text-xs font-bold ${row.archived_at?'text-green-700':'text-slate-600 hover:text-red-700'}`}>{row.archived_at?<><RotateCcw size={14}/>Restore to Pipeline</>:<><Archive size={14}/>Stop Pursuing</>}</button></div></div>})}</div></section>
 <section className="mt-9"><div className="flex items-center gap-2 mb-3"><Users size={20}/><h2 className="text-xl font-black">Coaches ({visibleCoaches.length})</h2></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{visibleCoaches.map(row=>{const x=one(row.colleges),coach=one(row.college_coaches),name=[coach?.first_name,coach?.last_name].filter(Boolean).join(' ')||'Coach';return <div key={row.id} className={`card p-5 flex flex-col min-h-[220px] ${row.archived_at?'opacity-75':''}`}><div className="flex justify-between gap-3"><Link href={`/coaches/${coach?.id}`} className="font-black text-lg hover:text-red-700 hover:underline">{name}</Link>{row.archived_at&&<span className="status-pill">Archived</span>}</div><div className="muted text-sm mt-1">{coach?.title||'Coach'} · {x?.name||'School not listed'}</div><div className="text-sm mt-4 space-y-1"><div><span className="muted">Email: </span>{coach?.email||'Not listed'}</div><div><span className="muted">Last contact: </span>{row.last_contact_date||'Never contacted'}</div></div><div className="mt-auto pt-4"><button disabled={!!busy} onClick={()=>row.archived_at?restore('coach',row):setPending({kind:'coach',row,name})} className={`inline-flex items-center gap-1.5 text-xs font-bold ${row.archived_at?'text-green-700':'text-slate-600 hover:text-red-700'}`}>{row.archived_at?<><RotateCcw size={14}/>Restore</>:<><Archive size={14}/>Stop Pursuing</>}</button></div></div>})}</div></section>
 {pending&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/45 px-4" onMouseDown={()=>!busy&&setPending(null)}><div role="dialog" aria-modal="true" className="w-full max-w-md rounded-2xl bg-white shadow-2xl border p-6" onMouseDown={e=>e.stopPropagation()}><Archive size={22} className="text-red-700"/><h2 className="text-xl font-black mt-4">Stop pursuing {pending.name}?</h2><p className="muted text-sm leading-6 mt-2">It will leave Current Pipeline, but its history will remain in All-Time. Nothing is deleted.</p><div className="flex justify-end gap-2 mt-6"><button className="btn" onClick={()=>setPending(null)}>Cancel</button><button className="btn btn-red" onClick={confirmArchive}>Stop Pursuing</button></div></div></div>}
 </>;
}
