'use client';
import {useEffect,useState} from 'react';
import {Film,Plus,X} from 'lucide-react';
import {createClient} from '@/lib/supabase-browser';

type Video={id:string;title:string;category:string;provider:string;video_url:string;is_featured:boolean};
export default function EmailVideoPicker({athleteUserId,onInsert}:{athleteUserId?:string;onInsert:(video:{title:string;url:string})=>void}){const c=createClient();const [open,setOpen]=useState(false),[videos,setVideos]=useState<Video[]>([]),[loading,setLoading]=useState(false);
 async function load(){setLoading(true);const {data:{user}}=await c.auth.getUser();const athlete=athleteUserId||user?.id;if(!athlete){setLoading(false);return}const {data}=await c.from('athlete_videos').select('id,title,category,provider,video_url,is_featured').eq('athlete_user_id',athlete).order('is_featured',{ascending:false}).order('created_at',{ascending:false});setVideos((data||[]) as Video[]);setLoading(false)}
 useEffect(()=>{if(open)load()},[open,athleteUserId]);
 return <div><button type="button" className="btn py-1.5 px-2.5 text-xs" onClick={()=>setOpen(v=>!v)}><Film size={14}/> Add Video</button>{open&&<div className="mt-2 rounded-xl border bg-slate-50 p-3"><div className="flex items-center justify-between gap-3"><div><div className="text-sm font-black">Recruiting videos</div><div className="muted text-xs mt-0.5">Insert a video link into this email.</div></div><button type="button" className="p-1.5 rounded-lg hover:bg-white" onClick={()=>setOpen(false)}><X size={15}/></button></div>{loading?<div className="muted text-sm py-4">Loading videos...</div>:videos.length?<div className="space-y-2 mt-3">{videos.map(v=><button type="button" key={v.id} className="w-full rounded-xl border bg-white p-3 text-left hover:border-slate-400 flex items-center justify-between gap-3" onClick={()=>{onInsert({title:v.title,url:v.video_url});setOpen(false)}}><div className="min-w-0"><div className="font-bold text-sm truncate">{v.title}</div><div className="muted text-xs mt-0.5">{v.category}{v.is_featured?' · Featured':''}</div></div><Plus size={15} className="shrink-0"/></button>)}</div>:<div className="mt-3 rounded-xl border bg-white p-3 text-sm text-slate-600">No videos in this athlete's library yet. Add them from <b>My Videos</b>.</div>}</div>}</div>}
