"use client";
import {useEffect,useState} from "react";
import {X} from "lucide-react";
export default function ManageOrganizationAccessModal({person,teams,busy,onClose,onSave}:{person:any;teams:any[];busy:boolean;onClose:()=>void;onSave:(role:string,enabled:boolean,teamIds:string[])=>void}){
 const[admin,setAdmin]=useState(false),[advisor,setAdvisor]=useState(false),[selected,setSelected]=useState<string[]>([]);
 useEffect(()=>{if(!person)return;setAdmin(person.roles?.includes("admin"));setAdvisor(person.roles?.includes("advisor"));setSelected((person.teamRoles||[]).filter((x:any)=>x.role==="advisor").map((x:any)=>x.team_id))},[person]);
 if(!person)return null;
 async function save(){await onSave("admin",admin,[]);await onSave("advisor",advisor,selected)}
 return <div className="fixed inset-0 z-[120] grid place-items-center bg-slate-950/55 p-4" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}>
  <div role="dialog" aria-modal="true" aria-labelledby="manage-access-title" className="w-full max-w-lg max-h-[85vh] overflow-y-auto rounded-2xl bg-white p-5 sm:p-6 shadow-2xl">
   <div className="flex items-start justify-between gap-4"><div><div className="rr-eyebrow">MANAGE STAFF ACCESS</div><h2 id="manage-access-title" className="mt-1 text-xl font-black">{person.profile?.full_name||person.profile?.email||"RLTNL user"}</h2><p className="muted text-xs mt-1">{person.profile?.email||""}</p></div><button className="btn p-2" disabled={busy} onClick={onClose} aria-label="Close"><X size={16}/></button></div>
   <div className="mt-5 space-y-3"><label className="flex items-start gap-3 rounded-xl border p-4"><input className="mt-1" type="checkbox" checked={advisor} onChange={e=>setAdvisor(e.target.checked)}/><span><span className="block font-black">Advisor</span><span className="block muted text-xs mt-1">Sees and supports only athletes assigned to them while in Advisor view.</span></span></label><label className="flex items-start gap-3 rounded-xl border p-4"><input className="mt-1" type="checkbox" checked={admin} onChange={e=>setAdmin(e.target.checked)}/><span><span className="block font-black">Admin</span><span className="block muted text-xs mt-1">Gets organization-wide administrative access.</span></span></label></div>
   {advisor&&<div className="mt-5"><div className="text-sm font-black">Advisor team assignments</div><p className="muted text-xs mt-1">Team assignments provide Advisor context. Athlete visibility still follows approved Advisor ↔ Athlete relationships.</p><div className="mt-3 max-h-52 overflow-y-auto rounded-xl border divide-y">{teams.filter(t=>!t.archived_at).map(t=><label key={t.id} className="flex items-center gap-3 p-3 text-sm"><input type="checkbox" checked={selected.includes(t.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,t.id]:v.filter(id=>id!==t.id))}/><span className="font-semibold">{t.name}</span></label>)}</div></div>}
   <div className="mt-4 rounded-xl bg-slate-50 border p-3 text-xs text-slate-600"><b>Advisor + Admin:</b> turn on both roles. The person keeps one RLTNL account and can switch views; Advisor view stays limited to their athletes, while Admin view shows the organization.</div>
   <div className="mt-6 flex justify-end gap-3"><button className="btn" disabled={busy} onClick={onClose}>Cancel</button><button className="btn btn-red" disabled={busy||(!admin&&!advisor)} onClick={save}>{busy?"Saving...":"Save Staff Access"}</button></div>
  </div>
 </div>
}