'use client';
import {useEffect,useState} from 'react';import {Check,X,Users,CalendarDays} from 'lucide-react';import {createClient} from '@/lib/supabase-browser';
export default function OrganizationEventAttendance({event}:{event?:any}){const c=createClient();const [role,setRole]=useState(''),[status,setStatus]=useState(''),[attendance,setAttendance]=useState<any>(null),[personalEvents,setPersonalEvents]=useState<any[]>([]),[busy,setBusy]=useState(false);
useEffect(()=>{(async()=>{const {data:{user}}=await c.auth.getUser();if(!user)return;const {data:p}=await c.from('profiles').select('app_role').eq('id',user.id).single();const r=p?.app_role||'athlete';setRole(r);if(event?.id){if(r==='athlete'){const res=await fetch('/api/events/rsvp',{cache:'no-store'});if(res.ok){const d=await res.json();setStatus(d.statuses?.[event.id]||'')}}else{const res=await fetch('/api/events/rsvp?scope=organization',{cache:'no-store'});if(res.ok){const d=await res.json();setAttendance(d.events?.[event.id]||{going:[],notGoing:[]})}}}else if(r==='athlete'){const today=new Date().toISOString().slice(0,10);const {data}=await c.from('athlete_events').select('id,event_id,status,events(id,name,date,location,type)').eq('athlete_user_id',user.id);setPersonalEvents((data||[]).map((x:any)=>({...x,event:Array.isArray(x.events)?x.events[0]:x.events})).filter((x:any)=>x.event?.date>=today).sort((a:any,b:any)=>String(a.event.date).localeCompare(String(b.event.date))))}})()},[event?.id]);
async function choose(next:'going'|'not_going'){if(!event?.id)return;setBusy(true);const res=await fetch('/api/events/rsvp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventId:event.id,status:next,eventName:event.name,eventDate:event.date})});if(res.ok)setStatus(next);setBusy(false)}
async function choosePersonal(row:any,next:'going'|'not_going'){setBusy(true);const {data:{user}}=await c.auth.getUser();if(user){const {error}=await c.from('athlete_events').upsert({athlete_user_id:user.id,event_id:row.event_id,status:next},{onConflict:'athlete_user_id,event_id'});if(!error)setPersonalEvents(list=>list.map(x=>x.event_id===row.event_id?{...x,status:next}:x))}setBusy(false)}
if(!role)return null;
if(!event?.id){if(role!=='athlete'||!personalEvents.length)return null;return <section className="card p-5"><div className="flex items-center gap-2"><CalendarDays size={18}/><div><h2 className="font-black text-lg">Your Added Events</h2><p className="muted text-sm">Set your attendance for events you added to Rebels Recruit.</p></div></div><div className="mt-4 divide-y">{personalEvents.map(row=><div key={row.event_id} className="py-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div className="min-w-0"><div className="font-bold">{row.event.name}</div><div className="muted text-sm mt-1">{new Date(`${row.event.date}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}{row.event.location?` · ${row.event.location}`:''}</div></div><div className="flex gap-2 shrink-0"><button disabled={busy} onClick={()=>choosePersonal(row,'going')} className={`btn min-h-11 sm:min-h-9 py-1.5 px-2.5 text-xs ${row.status==='going'?'bg-green-50 text-green-700 border-green-200':''}`}><Check size={14}/> Going</button><button disabled={busy} onClick={()=>choosePersonal(row,'not_going')} className={`btn min-h-11 sm:min-h-9 py-1.5 px-2.5 text-xs ${row.status==='not_going'?'bg-slate-100 border-slate-300':''}`}><X size={14}/> Not Going</button></div></div>)}</div></section>}
if(role==='athlete')return <div className="mt-4 pt-4 border-t"><div className="text-xs font-bold mb-2">Are you attending?</div><div className="flex gap-2"><button disabled={busy} onClick={()=>choose('going')} className={`btn min-h-11 sm:min-h-9 py-1.5 px-2.5 text-xs ${status==='going'?'bg-green-50 text-green-700 border-green-200':''}`}><Check size={14}/> Going</button><button disabled={busy} onClick={()=>choose('not_going')} className={`btn min-h-11 sm:min-h-9 py-1.5 px-2.5 text-xs ${status==='not_going'?'bg-slate-100':''}`}><X size={14}/> Not Going</button></div></div>;
const going=attendance?.going||[];return <div className="mt-4 pt-4 border-t"><div className="flex items-center gap-2 text-sm font-bold"><Users size={15}/>{going.length} player{going.length===1?'':'s'} going</div>{going.length>0&&<div className="flex flex-wrap gap-2 mt-2">{going.map((p:any)=><span key={p.athleteUserId} className="pill">{p.name}</span>)}</div>}</div>}
