'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Search,ShieldCheck,Users} from 'lucide-react';
import {createClient} from '@/lib/supabase-browser';
import PageHeader from '@/components/PageHeader';

export default function OwnerAdminPlayerAccess(){
 const c=createClient();const[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[players,setPlayers]=useState<any[]>([]),[advisors,setAdvisors]=useState<any[]>([]),[assignments,setAssignments]=useState<any[]>([]);
 useEffect(()=>{(async()=>{const{data:{user}}=await c.auth.getUser();if(!user){setLoading(false);return}const{data:ms}=await c.from('organization_members').select('organization_id,role').eq('user_id',user.id).eq('status','active').limit(20);const me=(ms||[]).find((m:any)=>['owner','admin'].includes(m.role));if(!me){setError('Owner or Admin access is required.');setLoading(false);return}const[members,as]=await Promise.all([c.from('organization_members').select('user_id,role,status').eq('organization_id',me.organization_id).eq('status','active'),c.from('athlete_advisor_assignments').select('id,athlete_user_id,advisor_user_id,status,invited_at,responded_at').eq('organization_id',me.organization_id)]);if(members.error||as.error){setError('Player access could not be loaded.');setLoading(false);return}const rows=members.data||[],pids=rows.filter((x:any)=>x.role==='athlete').map((x:any)=>x.user_id),aids=rows.filter((x:any)=>['advisor','admin','owner'].includes(x.role)).map((x:any)=>x.user_id),ids=[...new Set([...pids,...aids])];const{data:profiles,error:pe}=ids.length?await c.from('profiles').select('id,full_name,email').in('id',ids):{data:[],error:null};if(pe){setError('Player and staff names could not be loaded.');setLoading(false);return}const map=new Map((profiles||[]).map((p:any)=>[String(p.id),p]));setPlayers(pids.map((id:any)=>map.get(String(id))||{id,full_name:'Player'}).sort((a:any,b:any)=>String(a.full_name).localeCompare(String(b.full_name))));setAdvisors(aids.map((id:any)=>map.get(String(id))||{id,full_name:'Staff'}).sort((a:any,b:any)=>String(a.full_name).localeCompare(String(b.full_name))));setAssignments(as.data||[]);setLoading(false)})()},[]);
 const filtered=players.filter(p=>!q||[p.full_name,p.email].filter(Boolean).join(' ').toLowerCase().includes(q.toLowerCase()));
 const active=assignments.filter(a=>a.status==='active').length,pending=assignments.filter(a=>a.status==='pending').length;
 if(loading)return <div className="card p-10 text-center muted">Loading player access…</div>;
 if(error)return <div role="alert" className="card border-red-200 bg-red-50 p-5"><div className="font-black">Player access unavailable</div><p className="text-sm text-red-700 mt-1">{error}</p></div>;
 return <><PageHeader eyebrow="ORGANIZATION ACCESS" title="Player Access" subtitle="See which staff members are connected to each player and which access requests are still waiting for approval."/>
 <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 mb-5"><Metric label="Players" value={players.length}/><Metric label="Active Staff Connections" value={active}/><Metric label="Waiting for Approval" value={pending}/></div>
 <div className="card p-4 sm:p-5"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h2 className="font-black text-lg flex items-center gap-2"><Users size={19}/>Organization Players</h2><p className="muted text-sm mt-1">Player approval remains required for advisor access.</p></div><label className="input flex items-center gap-2 sm:w-72"><Search size={16}/><span className="sr-only">Search players</span><input className="bg-transparent outline-none min-w-0 flex-1" placeholder="Search players" value={q} onChange={e=>setQ(e.target.value)}/></label></div>
 <div className="divide-y mt-4">{filtered.map(p=>{const pa=assignments.filter(a=>String(a.athlete_user_id)===String(p.id));return <div key={p.id} className="py-4 flex flex-col lg:flex-row lg:items-center gap-3"><div className="lg:w-64 min-w-0"><Link href={'/players/'+p.id} className="font-black hover:text-red-700">{p.full_name||p.email||'Player'}</Link><div className="muted text-xs truncate mt-1">{p.email}</div></div><div className="flex-1 flex flex-wrap gap-2">{pa.length?pa.map(a=>{const person=advisors.find(x=>String(x.id)===String(a.advisor_user_id));const cls=a.status==='active'?'bg-green-50 text-green-700':a.status==='pending'?'bg-amber-50 text-amber-800':'bg-slate-100 text-slate-600';return <span key={a.id} className={'status-pill '+cls}>{a.status==='active'&&<ShieldCheck size={12}/>} {person?.full_name||person?.email||'Staff'} · {a.status==='active'?'Active':a.status==='pending'?'Waiting':'Not active'}</span>}):<span className="text-sm text-slate-500">No advisor connections</span>}</div><Link href={'/players/'+p.id} className="btn shrink-0">Review Player 360°</Link></div>})}{!filtered.length&&<div className="rr-empty-state my-4"><div className="font-black">No players match this search.</div></div>}</div></div></>
}
function Metric({label,value}:{label:string;value:number}){return <div className="card p-4"><div className="text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</div><div className="text-2xl font-black mt-1">{value}</div></div>}
