"use client";
import { useEffect, useRef, useState } from "react";
import { Camera, Upload, X } from "lucide-react";
import { createClient } from "@/lib/supabase-browser";

export default function PlayerPhotoUpload({athleteId,name,initialUrl,onSaved,compact=false,photoOnly=false}:{athleteId:string;name:string;initialUrl?:string|null;onSaved?:(url:string)=>void;compact?:boolean;photoOnly?:boolean}){
 const input=useRef<HTMLInputElement>(null),preview=useRef<HTMLCanvasElement>(null),[url,setUrl]=useState(initialUrl||""),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const[cropSrc,setCropSrc]=useState(""),[sourceFile,setSourceFile]=useState<File|null>(null),[zoom,setZoom]=useState(1),[panX,setPanX]=useState(0),[panY,setPanY]=useState(-25),drag=useRef<{x:number;y:number;px:number;py:number}|null>(null);
 const initials=(name||"Player").split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase();

 function cropRect(img:HTMLImageElement){const crop=Math.min(img.naturalWidth,img.naturalHeight)/zoom,maxX=Math.max(0,img.naturalWidth-crop),maxY=Math.max(0,img.naturalHeight-crop);return{crop,sx:maxX*((panX+100)/200),sy:maxY*((panY+100)/200)}}
 function moveDrag(e:React.PointerEvent){if(!drag.current)return;const dx=e.clientX-drag.current.x,dy=e.clientY-drag.current.y;setPanX(Math.max(-100,Math.min(100,drag.current.px-dx*.65)));setPanY(Math.max(-100,Math.min(100,drag.current.py-dy*.65)))}
 function draw(canvas:HTMLCanvasElement,img:HTMLImageElement,size:number){const{crop,sx,sy}=cropRect(img),ctx=canvas.getContext("2d");if(!ctx)return;canvas.width=size;canvas.height=size;ctx.clearRect(0,0,size,size);ctx.fillStyle="#f1f5f9";ctx.fillRect(0,0,size,size);ctx.drawImage(img,sx,sy,crop,crop,0,0,size,size)}
 useEffect(()=>{if(!cropSrc||!preview.current)return;const img=new Image();img.onload=()=>preview.current&&draw(preview.current,img,600);img.src=cropSrc},[cropSrc,zoom,panX,panY]);

 function choose(file?:File){if(!file)return;setMsg("");if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setMsg("Use a JPG, PNG or WebP photo.");return}if(file.size>5*1024*1024){setMsg("Photo must be 5 MB or smaller.");return}if(cropSrc)URL.revokeObjectURL(cropSrc);setSourceFile(file);setCropSrc(URL.createObjectURL(file));setZoom(1);setPanX(0);setPanY(-25)}
 async function makeCrop(){if(!sourceFile||!cropSrc)return;setBusy(true);try{const img=new Image();img.src=cropSrc;await img.decode();const canvas=document.createElement("canvas");draw(canvas,img,600);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/jpeg",.9));if(!blob)throw new Error("Photo could not be cropped.");await upload(new File([blob],"profile.jpg",{type:"image/jpeg"}));URL.revokeObjectURL(cropSrc);setCropSrc("");setSourceFile(null)}catch(e:any){setMsg(e?.message||"Photo could not be edited.");setBusy(false)}}
 async function upload(file:File){const c=createClient(),key=`${athleteId}/profile.jpg`;const up=await c.storage.from("player-photos").upload(key,file,{upsert:true,contentType:"image/jpeg",cacheControl:"3600"});if(up.error){setMsg(up.error.message);setBusy(false);return}const publicUrl=c.storage.from("player-photos").getPublicUrl(key).data.publicUrl+"?v="+Date.now();const{data:{user}}=await c.auth.getUser();if(!user){setMsg("Your account could not be verified.");setBusy(false);return}const save=user.id===athleteId?await c.from("profiles").update({avatar_url:publicUrl}).eq("id",athleteId):await c.rpc("set_player_avatar_url",{p_athlete_user_id:athleteId,p_avatar_url:publicUrl});setBusy(false);if(save.error){setMsg(save.error.message);return}setUrl(publicUrl);setMsg("Photo updated.");onSaved?.(publicUrl)}

 return <><div className={compact?"flex items-center gap-3":"flex flex-col sm:flex-row sm:items-center gap-4"}>
  <button type="button" onClick={()=>input.current?.click()} className={`group relative shrink-0 overflow-hidden rounded-2xl border bg-slate-100 grid place-items-center font-black text-slate-500 ${photoOnly?"h-20 w-20 sm:h-24 sm:w-24":compact?"h-16 w-16":"h-24 w-24"}`}} aria-label="Change player photo">{url?<img src={url} alt={name} className="h-full w-full object-cover"/>:<span className="text-xl">{initials}</span>}<span className="absolute bottom-1 right-1 h-7 w-7 rounded-full bg-slate-950 text-white grid place-items-center border-2 border-white"><Camera size={13}/></span></button>
  {!photoOnly&&<div><button type="button" className="btn" disabled={busy} onClick={()=>input.current?.click()}><Upload size={15}/>{url?"Change Photo":"Upload Photo"}</button><div className="muted text-xs mt-2">JPG, PNG or WebP · 5 MB max. Crop and position before saving.</div>{msg&&<div className={`text-xs font-bold mt-2 ${msg==="Photo updated."?"text-emerald-700":"text-red-600"}`}>{msg}</div>}</div>}
  <input ref={input} className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{choose(e.target.files?.[0]);e.currentTarget.value=""}}/>
 </div>
 {cropSrc&&<div className="fixed inset-0 z-[100] bg-slate-950/70 flex items-center justify-center p-4" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setCropSrc("")}}>
  <div className="w-full max-w-lg rounded-2xl border border-slate-200 bg-white shadow-2xl p-5 sm:p-6 text-slate-950">
   <div className="flex items-start justify-between gap-3"><div><div className="rr-eyebrow">PLAYER PHOTO</div><h2 className="text-xl font-black mt-1">Crop & position</h2><p className="text-slate-500 text-sm mt-1">Adjust the photo until the face is centered. The preview below is exactly what will be saved.</p></div><button type="button" className="h-9 w-9 rounded-lg border bg-white grid place-items-center shrink-0" onClick={()=>setCropSrc("")} disabled={busy}><X size={17}/></button></div>
   <div className="mt-5 mx-auto w-[320px] max-w-full aspect-square overflow-hidden rounded-[28px] border-2 border-slate-200 bg-slate-100 relative cursor-grab active:cursor-grabbing touch-none select-none" onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY,px:panX,py:panY};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={moveDrag} onPointerUp={e=>{drag.current=null;e.currentTarget.releasePointerCapture(e.pointerId)}} onPointerCancel={()=>{drag.current=null}}><canvas ref={preview} className="h-full w-full pointer-events-none"/><div className="pointer-events-none absolute inset-0 rounded-[26px] ring-1 ring-inset ring-white/70"/><div className="pointer-events-none absolute bottom-3 left-1/2 -translate-x-1/2 rounded-full bg-slate-950/70 px-3 py-1 text-[10px] font-bold text-white">Drag photo to reposition</div></div>
   <div className="grid gap-4 mt-5">
    <label className="text-xs font-black">Zoom <span className="float-right text-slate-400">{zoom.toFixed(1)}×</span><input className="w-full mt-2" type="range" min="1" max="3" step=".05" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label>
    <label className="text-xs font-black">Left / Right<input className="w-full mt-2" type="range" min="-100" max="100" value={panX} onChange={e=>setPanX(Number(e.target.value))}/><div className="flex justify-between text-[10px] text-slate-400 font-medium"><span>Left</span><span>Right</span></div></label>
    <label className="text-xs font-black">Up / Down<input className="w-full mt-2" type="range" min="-100" max="100" value={panY} onChange={e=>setPanY(Number(e.target.value))}/><div className="flex justify-between text-[10px] text-slate-400 font-medium"><span>Up</span><span>Down</span></div></label>
   </div>
   <div className="flex justify-end gap-2 mt-6"><button type="button" className="btn" onClick={()=>setCropSrc("")} disabled={busy}>Cancel</button><button type="button" className="btn btn-red" onClick={makeCrop} disabled={busy}>{busy?"Saving…":"Save Photo"}</button></div>
  </div>
 </div>}</>
}