"use client";
import { useRef, useState } from "react";
import { Camera, Upload, X } from "lucide-react";
import { createClient } from "@/lib/supabase-browser";

export default function PlayerPhotoUpload({athleteId,name,initialUrl,onSaved,compact=false}:{athleteId:string;name:string;initialUrl?:string|null;onSaved?:(url:string)=>void;compact?:boolean}){
 const input=useRef<HTMLInputElement>(null),[url,setUrl]=useState(initialUrl||""),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const[cropSrc,setCropSrc]=useState(""),[sourceFile,setSourceFile]=useState<File|null>(null),[zoom,setZoom]=useState(1),[panX,setPanX]=useState(0),[panY,setPanY]=useState(0);
 const initials=(name||"Player").split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase();
 function choose(file?:File){if(!file)return;setMsg("");if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setMsg("Use a JPG, PNG or WebP photo.");return}if(file.size>5*1024*1024){setMsg("Photo must be 5 MB or smaller.");return}setSourceFile(file);setCropSrc(URL.createObjectURL(file));setZoom(1);setPanX(0);setPanY(0)}
 async function makeCrop(){if(!sourceFile||!cropSrc)return;setBusy(true);try{const img=new Image();img.src=cropSrc;await img.decode();const crop=Math.min(img.naturalWidth,img.naturalHeight)/zoom;const maxX=Math.max(0,img.naturalWidth-crop),maxY=Math.max(0,img.naturalHeight-crop);const sx=Math.max(0,Math.min(maxX,maxX/2+(panX/100)*(maxX/2))),sy=Math.max(0,Math.min(maxY,maxY/2+(panY/100)*(maxY/2)));const canvas=document.createElement("canvas");canvas.width=600;canvas.height=600;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Photo editor could not start.");ctx.drawImage(img,sx,sy,crop,crop,0,0,600,600);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/jpeg",.9));if(!blob)throw new Error("Photo could not be cropped.");await upload(new File([blob],"profile.jpg",{type:"image/jpeg"}));URL.revokeObjectURL(cropSrc);setCropSrc("");setSourceFile(null)}catch(e:any){setMsg(e?.message||"Photo could not be edited.");setBusy(false)}}
 async function upload(file:File){const c=createClient();const key=`${athleteId}/profile.jpg`;const up=await c.storage.from("player-photos").upload(key,file,{upsert:true,contentType:"image/jpeg",cacheControl:"3600"});if(up.error){setMsg(up.error.message);setBusy(false);return}const publicUrl=c.storage.from("player-photos").getPublicUrl(key).data.publicUrl+"?v="+Date.now();const{data:{user}}=await c.auth.getUser();if(!user){setMsg("Your account could not be verified.");setBusy(false);return}const save=user.id===athleteId?await c.from("profiles").update({avatar_url:publicUrl}).eq("id",athleteId):await c.rpc("set_player_avatar_url",{p_athlete_user_id:athleteId,p_avatar_url:publicUrl});setBusy(false);if(save.error){setMsg(save.error.message);return}setUrl(publicUrl);setMsg("Photo updated.");onSaved?.(publicUrl)}
 return <><div className={compact?"flex items-center gap-3":"flex flex-col sm:flex-row sm:items-center gap-4"}>
  <button type="button" onClick={()=>input.current?.click()} className={`relative shrink-0 overflow-hidden rounded-2xl border bg-slate-100 grid place-items-center font-black text-slate-500 ${compact?"h-16 w-16":"h-24 w-24"}`} aria-label="Change player photo">{url?<img src={url} alt={name} className="h-full w-full object-cover"/>:<span className="text-xl">{initials}</span>}<span className="absolute bottom-1 right-1 h-7 w-7 rounded-full bg-slate-950 text-white grid place-items-center border-2 border-white"><Camera size={13}/></span></button>
  <div><button type="button" className="btn" disabled={busy} onClick={()=>input.current?.click()}><Upload size={15}/>{url?"Change Photo":"Upload Photo"}</button><div className="muted text-xs mt-2">JPG, PNG or WebP · 5 MB max. You can crop and reposition before saving.</div>{msg&&<div className={`text-xs font-bold mt-2 ${msg==="Photo updated."?"text-emerald-700":"text-red-600"}`}>{msg}</div>}</div>
  <input ref={input} className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{choose(e.target.files?.[0]);e.currentTarget.value=""}}/>
 </div>
 {cropSrc&&<div className="fixed inset-0 z-[80] bg-slate-950/60 grid place-items-center p-4" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setCropSrc("")}}><div className="card bg-white w-full max-w-md p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><div className="rr-eyebrow">PLAYER PHOTO</div><h2 className="text-xl font-black">Crop & position</h2><p className="muted text-sm mt-1">Center the player's face inside the square. This crop is used on Big Board and War Room.</p></div><button type="button" className="h-9 w-9 rounded-lg border grid place-items-center" onClick={()=>setCropSrc("")} disabled={busy}><X size={17}/></button></div>
 <div className="mt-5 mx-auto w-[300px] max-w-full aspect-square overflow-hidden rounded-2xl border-2 border-slate-200 bg-slate-100"><img src={cropSrc} alt="Crop preview" className="h-full w-full object-cover" style={{transform:`scale(${zoom}) translate(${panX/zoom/2}%,${panY/zoom/2}%)`,transformOrigin:"center"}}/></div>
 <div className="grid gap-3 mt-5"><label className="text-xs font-bold">Zoom<input className="w-full" type="range" min="1" max="3" step=".05" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><label className="text-xs font-bold">Horizontal position<input className="w-full" type="range" min="-100" max="100" value={panX} onChange={e=>setPanX(Number(e.target.value))}/></label><label className="text-xs font-bold">Vertical position<input className="w-full" type="range" min="-100" max="100" value={panY} onChange={e=>setPanY(Number(e.target.value))}/></label></div>
 <div className="flex justify-end gap-2 mt-5"><button type="button" className="btn" onClick={()=>setCropSrc("")} disabled={busy}>Cancel</button><button type="button" className="btn btn-red" onClick={makeCrop} disabled={busy}>{busy?"Saving…":"Crop & Save Photo"}</button></div></div></div>}</>
}