'use client';
import {useEffect,useMemo,useState} from 'react';
import {Plus,Activity,School,Users,Clock3,CalendarDays,X,ArrowLeft} from 'lucide-react';
import {createClient} from '@/lib/supabase-browser';
import CollegeSearchSelect from '@/components/CollegeSearchSelect';

const EVENT_TYPES=['Tournament','College Camp','Campus Visit','Showcase','Coach Call','Follow-up','Recruiting Deadline','Other'];
const INTERACTION_TYPES=['Email Sent','Email Received','Text','Phone Call','Video Call','Instagram DM','Coach Followed Me','Coach Liked Post','Coach Commented','Questionnaire','College Camp','Campus Visit','Tournament Interaction','Coach Watched Game','Coach Contacted Me','Thank You Message','Other'];
const PIPELINE_STATUSES=['Researching','High Interest','Recruiting Interest'];
const one=(v:any)=>Array.isArray(v)?v[0]:v;

type Mode='menu'|'interaction'|'college'|'coach'|'reminder'|'event';

export default function QuickAddMenu(){
 const c=createClient();
 const [open,setOpen]=useState(false),[mode,setMode]=useState<Mode>('menu'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [userId,setUserId]=useState('');const [colleges,setColleges]=useState<any[]>([]),[coaches,setCoaches]=useState<any[]>([]),[allColleges,setAllColleges]=useState<any[]>([]),[knownCoaches,setKnownCoaches]=useState<any[]>([]);
 const [interaction,setInteraction]=useState({college_id:'',coach_id:'',type:'Email Received',initiated_by:'Coach',date:new Date().toISOString().slice(0,10),note:'',follow_days:''});
 const [collegeSearch,setCollegeSearch]=useState(''),[collegeMatches,setCollegeMatches]=useState<any[]>([]),[selectedCollege,setSelectedCollege]=useState<any|null>(null);const [collegeForm,setCollegeForm]=useState({city:'',state:'',division:'',conference:'',status:'Researching'});
 const [coachSearch,setCoachSearch]=useState(''),[existingCoachId,setExistingCoachId]=useState('');const [coachForm,setCoachForm]=useState({college_id:'',first:'',last:'',title:'',email:'',phone:'',instagram:''});
 const [reminder,setReminder]=useState({title:'',due_date:'',college_id:'',coach_id:''});
 const [event,setEvent]=useState({name:'',type:'College Camp',date:'',location:'',college_id:'',registration_url:''});
 useEffect(()=>{if(!open)return;(async()=>{const {data:{user}}=await c.auth.getUser();if(!user)return;setUserId(user.id);const [{data:cs},{data:rs}]=await Promise.all([c.from('athlete_colleges').select('college_id,colleges(id,name)').eq('athlete_user_id',user.id).is('archived_at',null),c.from('athlete_coaches').select('coach_id,college_id,college_coaches(id,first_name,last_name,title)').eq('athlete_user_id',user.id).is('archived_at',null)]);setColleges((cs||[]).map((r:any)=>one(r.colleges)).filter(Boolean));setCoaches((rs||[]).map((r:any)=>({...(one(r.college_coaches)||{}),college_id:r.college_id})).filter((r:any)=>r.id))})()},[open]);
 useEffect(()=>{if(!open||mode!=='college'||selectedCollege||collegeSearch.trim().length<2){setCollegeMatches([]);return}const timer=setTimeout(async()=>{const safe=collegeSearch.trim().replace(/[%_,()]/g,' ');const {data}=await c.from('colleges').select('id,name,city,state,division,conference,school_type').or(`name.ilike.%${safe}%,city.ilike.%${safe}%,state.ilike.%${safe}%,division.ilike.%${safe}%,conference.ilike.%${safe}%`).order('name').limit(12);setCollegeMatches(data||[])},180);return()=>clearTimeout(timer)},[open,mode,collegeSearch,selectedCollege]);
 useEffect(()=>{if(!open||mode!=='coach'||allColleges.length)return;(async()=>{const all:any[]=[];for(let from=0;from<20000;from+=1000){const {data}=await c.from('colleges').select('id,name,city,state,division,conference,school_type').order('name').range(from,from+999);all.push(...(data||[]));if(!data||data.length<1000)break}setAllColleges(all);const {data}=await c.from('college_coaches').select('id,college_id,first_name,last_name,title,email,phone,instagram_url,colleges(id,name,state)').order('last_name').limit(5000);setKnownCoaches(data||[])})()},[open,mode]);
 const reminderCoaches=useMemo(()=>reminder.college_id?coaches.filter(x=>x.college_id===reminder.college_id):coaches,[coaches,reminder.college_id]);
 const interactionCoaches=useMemo(()=>interaction.college_id?coaches.filter(x=>x.college_id===interaction.college_id):[],[coaches,interaction.college_id]);
 const coachSuggestions=useMemo(()=>{const q=coachSearch.trim().toLowerCase();if(q.length<2)return [];return knownCoaches.filter(k=>{const col=one(k.colleges);return [k.first_name,k.last_name,k.title,k.email,k.phone,col?.name,col?.state].filter(Boolean).join(' ').toLowerCase().includes(q)}).slice(0,10)},[knownCoaches,coachSearch]);
 function close(){if(busy)return;setOpen(false);setMode('menu');setError('')}
 function chooseCollege(s:any){setSelectedCollege(s);setCollegeSearch(s.name);setCollegeForm(f=>({...f,city:s.city||'',state:s.state||'',division:s.division||'',conference:s.conference||''}));setCollegeMatches([])}
 function chooseCoach(k:any){const col=one(k.colleges);setExistingCoachId(k.id);setCoachForm({college_id:k.college_id||col?.id||'',first:k.first_name||'',last:k.last_name||'',title:k.title||'',email:k.email||'',phone:k.phone||'',instagram:k.instagram_url||''});setCoachSearch(`${k.first_name||''} ${k.last_name||''}`.trim())}
 function resetCoach(){setExistingCoachId('');setCoachForm({college_id:'',first:'',last:'',title:'',email:'',phone:'',instagram:''})}
 async function saveInteraction(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');if(!userId||!interaction.college_id){setError('Choose a college.');setBusy(false);return}const {data,error:insertError}=await c.from('interactions').insert({athlete_user_id:userId,actor_user_id:userId,college_id:interaction.college_id,coach_id:interaction.coach_id||null,type:interaction.type,initiated_by:interaction.initiated_by,date:interaction.date,note:interaction.note}).select('id').single();if(insertError||!data){setError(insertError?.message||'Could not save interaction.');setBusy(false);return}if(interaction.follow_days){const due=new Date(`${interaction.date}T12:00:00`);due.setDate(due.getDate()+Number(interaction.follow_days));await c.from('reminders').insert({owner_user_id:userId,athlete_user_id:userId,college_id:interaction.college_id,coach_id:interaction.coach_id||null,interaction_id:data.id,title:`Follow up after ${interaction.type.toLowerCase()}`,due_date:due.toISOString().slice(0,10),status:'open'})}setBusy(false);location.reload()}
 async function saveCollege(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');let school=selectedCollege;let err:any=null;if(!school){const found=await c.from('colleges').select('id,name,city,state,division,conference').ilike('name',collegeSearch.trim()).maybeSingle();school=found.data;err=found.error}if(!school&&!err){const r=await c.from('colleges').insert({name:collegeSearch.trim(),city:collegeForm.city||null,state:collegeForm.state||null,division:collegeForm.division||null,conference:collegeForm.conference||null}).select('id,name').single();school=r.data;err=r.error}if(err||!school){setError(err?.message||'Unable to save college.');setBusy(false);return}const {error:relError}=await c.from('athlete_colleges').upsert({athlete_user_id:userId,college_id:school.id,status:collegeForm.status,archived_at:null,archived_reason:null},{onConflict:'athlete_user_id,college_id'});if(relError){setError(relError.message);setBusy(false);return}setBusy(false);location.reload()}
 async function saveCoach(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');if(!userId||!coachForm.college_id){setError('Choose a college.');setBusy(false);return}let coachId=existingCoachId;if(coachId){const {error}=await c.from('college_coaches').update({college_id:coachForm.college_id,first_name:coachForm.first.trim(),last_name:coachForm.last.trim(),title:coachForm.title||null,email:coachForm.email||null,phone:coachForm.phone||null,instagram_url:coachForm.instagram||null,updated_by_user_id:userId,source_note:'Community-updated in Rebels Recruit'}).eq('id',coachId);if(error){setError(error.message);setBusy(false);return}}else{const {data,error}=await c.from('college_coaches').insert({college_id:coachForm.college_id,first_name:coachForm.first.trim(),last_name:coachForm.last.trim(),title:coachForm.title||null,email:coachForm.email||null,phone:coachForm.phone||null,instagram_url:coachForm.instagram||null,updated_by_user_id:userId,source_note:'Added by Rebels Recruit community'}).select('id').single();if(error||!data){setError(error?.message||'Could not add coach.');setBusy(false);return}coachId=data.id}await c.from('athlete_colleges').upsert({athlete_user_id:userId,college_id:coachForm.college_id,status:'Researching',archived_at:null,archived_reason:null},{onConflict:'athlete_user_id,college_id'});const {data:existing}=await c.from('athlete_coaches').select('id').eq('athlete_user_id',userId).eq('coach_id',coachId).maybeSingle();if(existing)await c.from('athlete_coaches').update({college_id:coachForm.college_id,archived_at:null,archived_reason:null}).eq('id',existing.id);else{const {error}=await c.from('athlete_coaches').insert({athlete_user_id:userId,college_id:coachForm.college_id,coach_id:coachId,archived_at:null,archived_reason:null});if(error){setError(error.message);setBusy(false);return}}setBusy(false);location.reload()}
 async function saveReminder(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const {data,error:insertError}=await c.from('reminders').insert({owner_user_id:userId,athlete_user_id:userId,title:reminder.title.trim(),due_date:reminder.due_date,college_id:reminder.college_id||null,coach_id:reminder.coach_id||null,status:'open'}).select('id').single();if(insertError||!data){setError(insertError?.message||'Could not add reminder.');setBusy(false);return}try{await fetch('/api/google/calendar/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({entityType:'reminder',entityId:data.id})})}catch{}setBusy(false);location.reload()}
 async function saveEvent(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const payload={name:event.name.trim(),type:event.type,date:event.date,location:event.location.trim()||null,college_id:event.college_id||null,registration_url:event.registration_url.trim()||null};const {data,error:insertError}=await c.from('events').insert(payload).select('id').single();if(insertError||!data){setError(insertError?.message||'Could not add event.');setBusy(false);return}try{await fetch('/api/google/calendar/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({entityType:'event',entityId:data.id})})}catch{}setBusy(false);location.reload()}
 const titles:Record<Mode,string>={menu:'Quick Add',interaction:'Log Interaction',college:'Add College',coach:'Add Coach',reminder:'Add Reminder',event:'Add Event'};
 return <><button type="button" className="btn btn-red" onClick={()=>{setOpen(true);setMode('menu')}}><Plus size={18}/> Quick Add</button>{open&&<div className="fixed inset-0 z-[100] bg-slate-950/45 px-4 flex items-center justify-center" onMouseDown={close}><div className="w-full max-w-lg max-h-[90vh] overflow-y-auto rounded-2xl bg-white shadow-2xl border" onMouseDown={e=>e.stopPropagation()}><div className="p-5 border-b flex items-start justify-between gap-4"><div className="flex items-start gap-2">{mode!=='menu'&&<button type="button" aria-label="Back to Quick Add" onClick={()=>{setMode('menu');setError('')}} className="h-9 w-9 -ml-2 rounded-lg hover:bg-slate-100 flex items-center justify-center"><ArrowLeft size={18}/></button>}<div><h2 className="text-xl font-black">{titles[mode]}</h2><p className="muted text-sm mt-1">{mode==='menu'?'What do you want to add?':'Save it without leaving Home.'}</p></div></div><button type="button" aria-label="Close Quick Add" onClick={close} className="h-9 w-9 rounded-lg hover:bg-slate-100 flex items-center justify-center"><X size={18}/></button></div>
 {mode==='menu'&&<div className="p-3"><Action onClick={()=>setMode('interaction')} icon={<Activity size={18}/>} label="Log Interaction" detail="Email, call, text, visit or other coach contact"/><Action onClick={()=>setMode('college')} icon={<School size={18}/>} label="Add College" detail="Add a new school to your Current Pipeline"/><Action onClick={()=>setMode('coach')} icon={<Users size={18}/>} label="Add Coach" detail="Add a coach relationship to a school"/><Action onClick={()=>setMode('reminder')} icon={<Clock3 size={18}/>} label="Add Reminder" detail="Create your next recruiting follow-up right here"/><Action onClick={()=>setMode('event')} icon={<CalendarDays size={18}/>} label="Add Event" detail="Add a camp, showcase, visit or recruiting event right here"/></div>}
 {mode==='interaction'&&<form onSubmit={saveInteraction} className="p-5 space-y-4"><Field label="College"><select className="input mt-1" required value={interaction.college_id} onChange={e=>setInteraction(r=>({...r,college_id:e.target.value,coach_id:''}))}><option value="">Choose a college</option>{colleges.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Coach (optional)"><select className="input mt-1" value={interaction.coach_id} onChange={e=>setInteraction(r=>({...r,coach_id:e.target.value}))}><option value="">No specific coach</option>{interactionCoaches.map(x=><option key={x.id} value={x.id}>{x.first_name} {x.last_name}{x.title?` · ${x.title}`:''}</option>)}</select></Field><Field label="What happened?"><select className="input mt-1" value={interaction.type} onChange={e=>setInteraction(r=>({...r,type:e.target.value}))}>{INTERACTION_TYPES.map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Who initiated it?"><select className="input mt-1" value={interaction.initiated_by} onChange={e=>setInteraction(r=>({...r,initiated_by:e.target.value}))}><option>Athlete</option><option>Coach</option><option>Other</option></select></Field><Field label="Date"><input className="input mt-1" type="date" required value={interaction.date} onChange={e=>setInteraction(r=>({...r,date:e.target.value}))}/></Field><Field label="Short note"><textarea className="input mt-1 min-h-20" placeholder="What matters about this interaction?" value={interaction.note} onChange={e=>setInteraction(r=>({...r,note:e.target.value}))}/></Field><Field label="Follow-up reminder"><select className="input mt-1" value={interaction.follow_days} onChange={e=>setInteraction(r=>({...r,follow_days:e.target.value}))}><option value="">No follow-up</option>{[1,3,5,7,10,14,30].map(d=><option key={d} value={d}>{d}-day follow-up</option>)}</select></Field><Error text={error}/><Save busy={busy} label="Save Interaction"/></form>}
 {mode==='college'&&<form onSubmit={saveCollege} className="p-5 space-y-4"><div className="relative"><Field label="Find a college"><input className="input mt-1" required placeholder="School, state, division or conference" value={collegeSearch} onChange={e=>{setCollegeSearch(e.target.value);setSelectedCollege(null)}}/></Field>{collegeMatches.length>0&&<div className="absolute z-20 left-0 right-0 mt-1 bg-white border rounded-xl shadow-xl max-h-64 overflow-y-auto">{collegeMatches.map(s=><button type="button" key={s.id} onClick={()=>chooseCollege(s)} className="w-full text-left p-3 border-b last:border-0 hover:bg-slate-50"><div className="font-bold">{s.name}</div><div className="muted text-xs">{[s.city,s.state,s.division,s.conference].filter(Boolean).join(' · ')}</div></button>)}</div>}</div>{selectedCollege?<div className="rounded-xl bg-slate-50 border p-3"><b>{selectedCollege.name}</b><div className="muted text-xs mt-1">{[selectedCollege.city,selectedCollege.state,selectedCollege.division,selectedCollege.conference].filter(Boolean).join(' · ')}</div></div>:<><div className="grid grid-cols-2 gap-3"><Field label="City"><input className="input mt-1" value={collegeForm.city} onChange={e=>setCollegeForm(r=>({...r,city:e.target.value}))}/></Field><Field label="State"><input className="input mt-1" value={collegeForm.state} onChange={e=>setCollegeForm(r=>({...r,state:e.target.value}))}/></Field></div><Field label="Division"><select className="input mt-1" value={collegeForm.division} onChange={e=>setCollegeForm(r=>({...r,division:e.target.value}))}><option value="">Not listed</option><option>NCAA D1</option><option>NCAA D2</option><option>NCAA D3</option><option>NAIA</option><option>JUCO</option></select></Field><Field label="Conference"><input className="input mt-1" value={collegeForm.conference} onChange={e=>setCollegeForm(r=>({...r,conference:e.target.value}))}/></Field></>}<Field label="Pipeline Status"><select className="input mt-1" value={collegeForm.status} onChange={e=>setCollegeForm(r=>({...r,status:e.target.value}))}>{PIPELINE_STATUSES.map(s=><option key={s}>{s}</option>)}</select></Field><Error text={error}/><Save busy={busy} label="Save College"/></form>}
 {mode==='coach'&&<form onSubmit={saveCoach} className="p-5 space-y-4"><div><Field label="Find a coach"><input className="input mt-1" placeholder="Coach name, school or email" value={coachSearch} onChange={e=>{setCoachSearch(e.target.value);if(existingCoachId)resetCoach()}}/></Field>{coachSuggestions.length>0&&<div className="border rounded-xl mt-2 divide-y max-h-56 overflow-y-auto">{coachSuggestions.map(k=>{const col=one(k.colleges);return <button type="button" key={k.id} onClick={()=>chooseCoach(k)} className="w-full text-left p-3 hover:bg-slate-50"><div className="font-bold">{k.first_name} {k.last_name}</div><div className="muted text-xs">{k.title||'Coach'}{col?.name?` · ${col.name}`:''}</div></button>})}</div>}</div>{existingCoachId&&<div className="rounded-xl bg-green-50 border border-green-200 p-3 text-sm"><b>Shared coach found.</b> Review the information and save.</div>}<Field label="College"><div className="mt-1"><CollegeSearchSelect colleges={allColleges} value={coachForm.college_id} onChange={v=>setCoachForm(r=>({...r,college_id:v}))} allowNone={false}/></div></Field><div className="grid grid-cols-2 gap-3"><Field label="First name"><input className="input mt-1" required value={coachForm.first} onChange={e=>setCoachForm(r=>({...r,first:e.target.value}))}/></Field><Field label="Last name"><input className="input mt-1" required value={coachForm.last} onChange={e=>setCoachForm(r=>({...r,last:e.target.value}))}/></Field></div><Field label="Title"><select className="input mt-1" value={coachForm.title} onChange={e=>setCoachForm(r=>({...r,title:e.target.value}))}><option value="">Select title</option><option>Head Coach</option><option>Assistant Coach</option><option>Recruiting Coordinator</option><option>Other</option></select></Field><Field label="Email"><input className="input mt-1" type="email" value={coachForm.email} onChange={e=>setCoachForm(r=>({...r,email:e.target.value}))}/></Field><Field label="Phone"><input className="input mt-1" value={coachForm.phone} onChange={e=>setCoachForm(r=>({...r,phone:e.target.value}))}/></Field><Field label="Instagram URL"><input className="input mt-1" type="url" value={coachForm.instagram} onChange={e=>setCoachForm(r=>({...r,instagram:e.target.value}))}/></Field><Error text={error}/><Save busy={busy} label={existingCoachId?'Use & Update Coach':'Add Coach'}/></form>}
 {mode==='reminder'&&<form onSubmit={saveReminder} className="p-5 space-y-4"><Field label="Reminder"><input className="input mt-1" required placeholder="Follow up with Coach Smith" value={reminder.title} onChange={e=>setReminder(r=>({...r,title:e.target.value}))}/></Field><Field label="Due date"><input className="input mt-1" type="date" required value={reminder.due_date} onChange={e=>setReminder(r=>({...r,due_date:e.target.value}))}/></Field><Field label="College (optional)"><select className="input mt-1" value={reminder.college_id} onChange={e=>setReminder(r=>({...r,college_id:e.target.value,coach_id:''}))}><option value="">General recruiting reminder</option>{colleges.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></Field><Field label="Coach (optional)"><select className="input mt-1" value={reminder.coach_id} onChange={e=>setReminder(r=>({...r,coach_id:e.target.value}))}><option value="">No specific coach</option>{reminderCoaches.map(x=><option value={x.id} key={x.id}>{x.first_name} {x.last_name}{x.title?` · ${x.title}`:''}</option>)}</select></Field><Error text={error}/><Save busy={busy} label="Save Reminder"/></form>}
 {mode==='event'&&<form onSubmit={saveEvent} className="p-5 space-y-4"><Field label="Event name"><input className="input mt-1" required placeholder="University Prospect Camp" value={event.name} onChange={e=>setEvent(r=>({...r,name:e.target.value}))}/></Field><Field label="Event type"><select className="input mt-1" value={event.type} onChange={e=>setEvent(r=>({...r,type:e.target.value}))}>{EVENT_TYPES.map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Date"><input className="input mt-1" type="date" required value={event.date} onChange={e=>setEvent(r=>({...r,date:e.target.value}))}/></Field><Field label="Location (optional)"><input className="input mt-1" placeholder="City, State or facility" value={event.location} onChange={e=>setEvent(r=>({...r,location:e.target.value}))}/></Field><Field label="College (optional)"><select className="input mt-1" value={event.college_id} onChange={e=>setEvent(r=>({...r,college_id:e.target.value}))}><option value="">No specific college</option>{colleges.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></Field><Field label="Registration / info URL (optional)"><input className="input mt-1" type="url" placeholder="https://..." value={event.registration_url} onChange={e=>setEvent(r=>({...r,registration_url:e.target.value}))}/></Field><Error text={error}/><Save busy={busy} label="Save Event"/></form>}
 </div></div>}</>}
function Action({onClick,icon,label,detail}:{onClick:()=>void;icon:React.ReactNode;label:string;detail:string}){return <button type="button" onClick={onClick} className="w-full text-left flex items-center gap-3 rounded-xl p-3 hover:bg-slate-50"><IconBox>{icon}</IconBox><Copy label={label} detail={detail}/></button>}
function IconBox({children}:{children:React.ReactNode}){return <div className="h-10 w-10 rounded-xl bg-slate-100 flex items-center justify-center shrink-0">{children}</div>}
function Copy({label,detail}:{label:string;detail:string}){return <div className="min-w-0"><div className="font-black text-sm">{label}</div><div className="muted text-xs mt-0.5">{detail}</div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="text-sm font-bold">{label}</span>{children}</label>}
function Error({text}:{text:string}){return text?<div className="rounded-lg bg-red-50 text-red-700 text-sm p-3">{text}</div>:null}
function Save({busy,label}:{busy:boolean;label:string}){return <button className="btn btn-red w-full" disabled={busy}>{busy?'Saving...':label}</button>}
