'use client';
import {useEffect,useRef,useState} from 'react';
import {createClient} from '@/lib/supabase-browser';

export default function RecruitingNotes({athleteId,collegeId,coachId,title='My Notes'}:{athleteId:string;collegeId?:string|null;coachId?:string|null;title?:string}){
 const c=createClient(),[note,setNote]=useState(''),[loaded,setLoaded]=useState(false),[status,setStatus]=useState('');const timer=useRef<any>(null),initial=useRef('');
 useEffect(()=>{let stop=false;(async()=>{let q=c.from('recruiting_private_notes').select('note').eq('athlete_user_id',athleteId);q=coachId?q.eq('coach_id',coachId):q.eq('college_id',collegeId!).is('coach_id',null);const{data}=await q.maybeSingle();if(!stop){const v=data?.note||'';setNote(v);initial.current=v;setLoaded(true)}})();return()=>{stop=true;if(timer.current)clearTimeout(timer.current)}},[athleteId,collegeId,coachId]);
 useEffect(()=>{if(!loaded||note===initial.current)return;if(timer.current)clearTimeout(timer.current);setStatus('Saving…');timer.current=setTimeout(async()=>{const{data:{user}}=await c.auth.getUser();if(!user)return;const row:any={user_id:user.id,athlete_user_id:athleteId,college_id:collegeId||null,coach_id:coachId||null,note,updated_at:new Date().toISOString()};const onConflict=coachId?'user_id,athlete_user_id,coach_id':'user_id,athlete_user_id,college_id';const{error}=await c.from('recruiting_private_notes').upsert(row,{onConflict});if(error){setStatus('Could not save');return}initial.current=note;setStatus('Saved');setTimeout(()=>setStatus(''),1500)},650);return()=>{if(timer.current)clearTimeout(timer.current)}},[note,loaded,athleteId,collegeId,coachId]);
 return <section className="card p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-black text-lg">{title}</h2><span className="text-xs text-slate-500">{status}</span></div><p className="muted text-xs mt-1">Private to you. Keep context, questions, impressions, or anything you want to remember.</p><textarea value={note} onChange={e=>setNote(e.target.value)} disabled={!loaded} placeholder="Add your notes…" className="mt-4 w-full min-h-[150px] rounded-xl border border-slate-200 p-3 text-sm resize-y focus:outline-none focus:ring-2 focus:ring-red-200 focus:border-red-400"/><div className="text-[11px] text-slate-400 mt-1">Saves automatically</div></section>
}