'use client';
import Link from 'next/link';import {useState} from 'react';import {ExternalLink,Mail,Clock3,CheckCircle2} from 'lucide-react';
type Intel={recruiting_intent:string;next_action:string|null;action_state?:string|null;action_decision?:string|null;action_due_date?:string|null;extracted_data?:{urls?:string[]}|null};
export default function RecruitingActionCard({interactionId,coachId,intel,onChanged}:{interactionId:string;coachId?:string|null;intel:Intel;onChanged?:()=>void}){
 const [busy,setBusy]=useState(''),[error,setError]=useState('');const state=intel.action_state||'review';const url=intel.extracted_data?.urls?.[0];
 async function choose(choice:string){setBusy(choice);setError('');try{const r=await fetch('/api/recruiting-actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({interactionId,choice})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not update next step.');window.dispatchEvent(new CustomEvent('rebels:data-changed',{detail:{entity:'interaction',action:'updated',id:interactionId}}));onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Could not update next step.')}finally{setBusy('')}}
 const configs:any={
 call_request:{review:[['accept','Confirm Call'],['need_time','Suggest Another Time'],['decline',"Can't Do It"]],prepare:[['completed','Call Completed']]},
 visit_invitation:{review:[['interested',"I'm Interested"],['cannot_attend',"Can't Attend"],['decide_later','Decide Later']],prepare:[['completed','Visit Completed']]},
 schedule_request:{review:[['send','Send Schedule'],['later','Do This Later']],waiting:[]},
 event_attendance:{review:[['confirm','Confirm Details'],['details_ok','Details Are Correct']],prepare:[['completed','Game Completed']]},
 information_request:{review:[['send','Send Information'],['later','Do This Later']],waiting:[]},
 questionnaire:{review:[['complete','Open Questionnaire'],['later','Do This Later']],external:[['submitted',"I've Submitted It"]],follow_up:[]},
 offer_related:{review:[['review','Review With Family/Advisor'],['discuss','Talk With Coach'],['later','Decide Later']],decision:[['discuss','Talk With Coach']]},
 follow_up:{review:[['send','Follow Up'],['later','Do This Later']]}
 };
 const cfg=configs[intel.recruiting_intent];if(cfg){const buttons=cfg[state]||[];const replyChoices=new Set(['accept','need_time','decline','interested','cannot_attend','send','confirm','discuss']);return <div className="mt-3 rounded-xl border bg-slate-50 p-3" onClick={e=>e.stopPropagation()}><div className="text-sm"><span className="font-black">Next step:</span> {intel.next_action||'Review this recruiting message'}</div><div className="flex flex-wrap gap-2 mt-3">{url&&['visit_invitation','questionnaire'].includes(intel.recruiting_intent)&&<a href={url} target="_blank" rel="noreferrer" className="btn py-2 px-3 text-sm"><ExternalLink size={14}/>Open Details</a>}{buttons.map(([choice,label]:string[])=>replyChoices.has(choice)&&coachId?<Link key={choice} href={`/coaches/${coachId}?action=recruiting-reply&interaction=${interactionId}&intent=${intel.recruiting_intent}&choice=${choice}`} onClick={()=>choose(choice)} className="btn btn-red py-2 px-3 text-sm"><Mail size={14}/>{label}</Link>:<button key={choice} className="btn py-2 px-3 text-sm" disabled={!!busy} onClick={()=>choose(choice)}>{label}</button>)}</div>{state==='deferred'&&<div className="mt-3 inline-flex items-center gap-2 text-xs font-semibold text-slate-600"><Clock3 size={14}/>Reminder set{intel.action_due_date?` for ${intel.action_due_date}`:''}</div>}{['waiting','follow_up','decision','external','prepare'].includes(state)&&!buttons.length&&<div className="mt-3 inline-flex items-center gap-2 text-xs font-semibold text-slate-600"><CheckCircle2 size={14}/>{intel.next_action}</div>}{error&&<div className="text-xs text-red-700 mt-2">{error}</div>}</div>}
 if(intel.recruiting_intent!=='camp_invitation')return intel.next_action?<div className="mt-3 rounded-xl border bg-slate-50 px-3 py-2 text-sm"><span className="font-black">Recommended next step:</span> {intel.next_action}</div>:null;
 return <div className="mt-3 rounded-xl border bg-slate-50 p-3" onClick={e=>e.stopPropagation()}><div className="text-sm"><span className="font-black">Next step:</span> {intel.next_action||'Review the camp invitation'}</div>
 {state==='review'&&<><div className="flex flex-wrap gap-2 mt-3">{url&&<a href={url} target="_blank" rel="noreferrer" className="btn py-2 px-3 text-sm"><ExternalLink size={14}/>View Camp Details</a>}<button className="btn py-2 px-3 text-sm" disabled={!!busy} onClick={()=>choose('interested')}>I'm Interested</button><button className="btn py-2 px-3 text-sm" disabled={!!busy} onClick={()=>choose('cannot_attend')}>Can't Attend</button><button className="btn py-2 px-3 text-sm" disabled={!!busy} onClick={()=>choose('decide_later')}>Decide Later</button></div></>}
 {state==='reply'&&coachId&&<div className="mt-3"><Link href={`/coaches/${coachId}?action=camp-reply&interaction=${interactionId}`} className="btn btn-red py-2 px-3 text-sm"><Mail size={14}/>Reply to Coach</Link></div>}
 {state==='registration'&&<div className="flex flex-wrap gap-2 mt-3">{url&&<a href={url} target="_blank" rel="noreferrer" className="btn py-2 px-3 text-sm"><ExternalLink size={14}/>View Camp Details</a>}<button className="btn py-2 px-3 text-sm" disabled={!!busy} onClick={()=>choose('registered')}>I've Registered</button><button className="btn py-2 px-3 text-sm" disabled={!!busy} onClick={()=>choose('not_registering')}>Not Registering</button></div>}
 {state==='prepare'&&<div className="mt-3 inline-flex items-center gap-2 text-xs font-semibold text-slate-600"><CheckCircle2 size={14}/>Registration recorded. Prepare for the camp and plan your follow-up afterward.</div>}
 {state==='closed'&&<div className="mt-3 inline-flex items-center gap-2 text-xs font-semibold text-slate-600"><CheckCircle2 size={14}/>Camp decision recorded. Keep building the relationship through your normal recruiting plan.</div>}
 {state==='deferred'&&<div className="mt-3 inline-flex items-center gap-2 text-xs font-semibold text-slate-600"><Clock3 size={14}/>Reminder set{intel.action_due_date?` for ${intel.action_due_date}`:''}</div>}
 {error&&<div className="text-xs text-red-700 mt-2">{error}</div>}</div>
}