'use client';
import {useEffect,useRef,useState} from 'react';
import {Bold,Italic,Underline,Link as LinkIcon,List,ListOrdered,Paperclip,X} from 'lucide-react';
export type EmailAttachment={name:string;type:string;data:string;size:number};
type Props={value:string;onChange:(plain:string,html:string)=>void;attachments:EmailAttachment[];onAttachmentsChange:(files:EmailAttachment[])=>void;disabled?:boolean};
function plainFrom(el:HTMLElement){return (el.innerText||'').replace(/\u00a0/g,' ').trim()}
export default function RichEmailEditor({value,onChange,attachments,onAttachmentsChange,disabled}:Props){const ref=useRef<HTMLDivElement>(null),fileRef=useRef<HTMLInputElement>(null),lastValue=useRef('');const [linkOpen,setLinkOpen]=useState(false),[linkUrl,setLinkUrl]=useState('');
 useEffect(()=>{if(ref.current&&value!==lastValue.current){ref.current.innerText=value;lastValue.current=value}},[value]);
 function emit(){if(!ref.current)return;const plain=plainFrom(ref.current);lastValue.current=plain;onChange(plain,ref.current.innerHTML)}
 function command(cmd:string,value?:string){ref.current?.focus();document.execCommand(cmd,false,value);emit()}
 function addLink(){let url=linkUrl.trim();if(!url)return;if(!/^https?:\/\//i.test(url)&&!/^mailto:/i.test(url))url='https://'+url;command('createLink',url);setLinkUrl('');setLinkOpen(false)}
 async function addFiles(list:FileList|null){if(!list)return;const next=[...attachments];let total=next.reduce((n,a)=>n+a.size,0);for(const file of Array.from(list)){if(next.length>=5){alert('You can attach up to 5 files.');break}if(file.size>2_500_000){alert(`${file.name} is too large. Keep each attachment under 2.5 MB.`);continue}if(total+file.size>3_000_000){alert('Keep the combined attachment size under 3 MB.');break}const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||'').split(',')[1]||'');r.onerror=()=>reject(r.error);r.readAsDataURL(file)});next.push({name:file.name,type:file.type||'application/octet-stream',data,size:file.size});total+=file.size}onAttachmentsChange(next);if(fileRef.current)fileRef.current.value=''}
 const tool='h-9 min-w-9 px-2 rounded-lg border bg-white hover:bg-slate-50 flex items-center justify-center disabled:opacity-40';
 return <div className="mt-1 rounded-xl border bg-white overflow-hidden focus-within:ring-2 focus-within:ring-red-100 focus-within:border-red-300"><div className="flex flex-wrap items-center gap-1 border-b bg-slate-50 p-2"><button type="button" className={tool} title="Bold" disabled={disabled} onMouseDown={e=>e.preventDefault()} onClick={()=>command('bold')}><Bold size={16}/></button><button type="button" className={tool} title="Italic" disabled={disabled} onMouseDown={e=>e.preventDefault()} onClick={()=>command('italic')}><Italic size={16}/></button><button type="button" className={tool} title="Underline" disabled={disabled} onMouseDown={e=>e.preventDefault()} onClick={()=>command('underline')}><Underline size={16}/></button><span className="mx-1 h-6 border-l"/><button type="button" className={tool} title="Insert link" disabled={disabled} onMouseDown={e=>e.preventDefault()} onClick={()=>setLinkOpen(v=>!v)}><LinkIcon size={16}/></button><button type="button" className={tool} title="Bulleted list" disabled={disabled} onMouseDown={e=>e.preventDefault()} onClick={()=>command('insertUnorderedList')}><List size={17}/></button><button type="button" className={tool} title="Numbered list" disabled={disabled} onMouseDown={e=>e.preventDefault()} onClick={()=>command('insertOrderedList')}><ListOrdered size={17}/></button><span className="mx-1 h-6 border-l"/><button type="button" className={tool+' gap-1.5 text-xs font-bold'} disabled={disabled} onClick={()=>fileRef.current?.click()}><Paperclip size={16}/> Attach</button><input ref={fileRef} type="file" multiple className="hidden" onChange={e=>addFiles(e.target.files)}/></div>{linkOpen&&<div className="flex gap-2 border-b bg-white p-2"><input className="input py-1.5 text-sm" autoFocus placeholder="Paste a URL" value={linkUrl} onChange={e=>setLinkUrl(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addLink()}}}/><button type="button" className="btn btn-red py-1.5 text-xs" onClick={addLink}>Add link</button><button type="button" className="btn py-1.5 text-xs" onClick={()=>setLinkOpen(false)}>Cancel</button></div>}<div ref={ref} contentEditable={!disabled} suppressContentEditableWarning onInput={emit} onBlur={emit} className="min-h-[420px] p-3 text-sm leading-6 outline-none whitespace-pre-wrap" data-placeholder="Write your email…"/>{attachments.length>0&&<div className="border-t bg-slate-50 p-3"><div className="text-xs font-black uppercase text-slate-500 mb-2">Attachments</div><div className="flex flex-wrap gap-2">{attachments.map((a,i)=><div key={`${a.name}-${i}`} className="flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-xs"><Paperclip size={13}/><span className="font-semibold max-w-[220px] truncate">{a.name}</span><span className="text-slate-500">{(a.size/1024/1024).toFixed(1)} MB</span><button type="button" title="Remove attachment" onClick={()=>onAttachmentsChange(attachments.filter((_,x)=>x!==i))}><X size={13}/></button></div>)}</div></div>}</div>}
