'use client';
import {useEffect,useState} from 'react';import {createClient} from '@/lib/supabase-browser';
const clarity=[['not_really','Not really'],['somewhat','Somewhat'],['very_clearly','Very clearly']],recommend=[['yes','Yes'],['maybe','Maybe'],['no','No']];
function Stars({value,onChange,label}:{value:number|null;onChange:(v:number)=>void;label:string}){return <div className="flex gap-1">{[1,2,3,4,5].map(n=><button key={n} type="button" onClick={()=>onChange(n)} aria-label={n+' of 5 '+label} className={'text-3xl '+(value&&n<=value?'text-amber-500':'text-slate-300')}>★</button>)}</div>}
export default function SchoolReviewForm({collegeId,collegeName,onSaved}:{collegeId:string;collegeName:string;onSaved?:()=>void}){const c=createClient();const[overall,setOverall]=useState<number|null>(null),[communication,setCommunication]=useState<number|null>(null),[standing,setStanding]=useState(''),[rec,setRec]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
useEffect(()=>{c.from('athlete_recruiting_experiences').select('*').eq('college_id',collegeId).eq('subject_type','program').is('coach_id',null).maybeSingle().then(({data})=>{if(data){setOverall(data.overall_experience);setCommunication(data.communication);setStanding(data.standing_clarity||'');setRec(data.recommend_engaging||'')}})},[collegeId]);
async function save(){if(!overall&&!communication&&!standing&&!rec){setMessage('Answer at least one question to share your experience.');return}setSaving(true);setMessage('');const{data:{user}}=await c.auth.getUser();if(!user){setSaving(false);return}const payload={overall_experience:overall,communication,standing_clarity:standing||null,recommend_engaging:rec||null,core_completed_at:new Date().toISOString(),dismissed_at:null,publication_status:'private',updated_at:new Date().toISOString()};const e=await c.from('athlete_recruiting_experiences').select('id').eq('athlete_user_id',user.id).eq('college_id',collegeId).eq('subject_type','program').is('coach_id',null).maybeSingle();const{error}=e.data?.id?await c.from('athlete_recruiting_experiences').update(payload).eq('id',e.data.id):await c.from('athlete_recruiting_experiences').insert({athlete_user_id:user.id,subject_type:'program',college_id:collegeId,...payload});setSaving(false);if(error){setMessage(error.message);return}onSaved?.()}
return <div><h3 className="font-black text-lg">Help other athletes understand this program better</h3><p className="muted text-sm mt-1">Share your recruiting experience with <b>{collegeName}</b>. Your feedback is anonymous and helps other athletes know what to expect.</p><div className="space-y-5 mt-5"><Q label={'How was your overall recruiting experience with '+collegeName+'?'} value={overall} set={setOverall}/><Q label="How well did the staff communicate with you?" value={communication} set={setCommunication}/><Choice label="Did you generally understand where you stood with them?" options={clarity} value={standing} set={setStanding}/><Choice label="Would you recommend other recruits engage with this program?" options={recommend} value={rec} set={setRec}/></div>{message&&<div className="text-sm font-bold text-red-700 mt-4">{message}</div>}<button onClick={save} disabled={saving} className="btn btn-red mt-5">{saving?'Sharing…':'Share My Experience'}</button></div>}
function Q({label,value,set}:{label:string;value:number|null;set:(v:number)=>void}){return <div><div className="font-bold text-sm">{label}</div><Stars value={value} onChange={set} label={label}/></div>}
function Choice({label,options,value,set}:{label:string;options:string[][];value:string;set:(v:string)=>void}){return <div><div className="font-bold text-sm">{label}</div><div className="flex flex-wrap gap-2 mt-2">{options.map(([v,l])=><button key={v} type="button" onClick={()=>set(v)} className={'rounded-lg border px-3 py-2 text-sm font-bold '+(value===v?'bg-slate-950 text-white':'bg-white')}>{l}</button>)}</div></div>}
