import Link from 'next/link';
import {AlertCircle,CalendarDays,CheckSquare,Clock3,UserPlus,Users,ArrowRight,School,UserRound} from 'lucide-react';

type Related={id:string;name:string};
type Move={id:string;kind:'reminder'|'task'|'stale'|'event'|'missing_coach'|'advisor_request';title:string;detail:string;why?:string;href:string;action:string;priority:number;date?:string|null;college?:Related|null;coach?:Related|null};
const icon=(kind:Move['kind'])=>kind==='task'?<CheckSquare size={18}/>:kind==='event'?<CalendarDays size={18}/>:kind==='missing_coach'?<Users size={18}/>:kind==='advisor_request'?<UserPlus size={18}/>:kind==='stale'?<Clock3 size={18}/>:<AlertCircle size={18}/>;
const tone=(p:number)=>p>=90?'bg-red-50 text-red-700 border-red-200':p>=70?'bg-slate-100 text-slate-900 border-slate-300':'bg-white text-slate-700 border-slate-200';
const source=(kind:Move['kind'])=>kind==='task'?'From your advisor':kind==='event'?'Event prep':kind==='missing_coach'?'Set up relationship':kind==='advisor_request'?'Access request':kind==='stale'?'Follow up':'Reminder';
const fmt=(d?:string|null)=>d?new Date(`${String(d).slice(0,10)}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'';
export function buildSmartNextMoves({reminders=[],tasks=[],coaches=[],colleges=[],events=[],advisorRequests=[]}:{reminders?:any[];tasks?:any[];coaches?:any[];colleges?:any[];events?:any[];advisorRequests?:any[]}){const now=new Date();now.setHours(0,0,0,0);const today=now.getTime();const moves:Move[]=[];const dateMs=(v:any)=>v?new Date(`${v}T00:00:00`).getTime():null;const college=(v:any)=>Array.isArray(v)?v[0]:v;const coach=(v:any)=>Array.isArray(v)?v[0]:v;
 reminders.filter(r=>['open','overdue','snoozed'].includes(String(r.status))).forEach(r=>{const due=dateMs(r.due_date),late=due!==null&&due<today,col=college(r.colleges),ch=coach(r.college_coaches),coachName=[ch?.first_name,ch?.last_name].filter(Boolean).join(' ');moves.push({id:`rem-${r.id}`,kind:'reminder',title:r.title||'Follow up',detail:`${col?.name||'Your reminder'} · ${late?'Overdue':'Due'} ${r.due_date?fmt(r.due_date):'soon'}`,href:'/game-plan#next-moves',action:'Complete Next Move',priority:late?112:due===today?110:106,date:r.due_date,college:col?.id?{id:col.id,name:col.name}:null,coach:ch?.id?{id:ch.id,name:coachName||'Coach'}:null})});
 tasks.filter(t=>String(t.status)!=='completed').forEach(t=>{const due=dateMs(t.due_date),late=due!==null&&due<today;moves.push({id:`task-${t.id}`,kind:'task',title:t.title||'Next Move from your advisor',detail:`Your advisor asked you to do this${t.due_date?` · ${late?'Overdue':'Due'} ${fmt(t.due_date)}`:''}`,why:t.description||undefined,href:'/game-plan#next-moves',action:'Review Advisor Next Move',priority:late?111:due===today?109:105,date:t.due_date})});
 coaches.forEach(r=>{const c=coach(r.college_coaches),col=college(r.colleges);const last=dateMs(r.last_contact_date),age=last===null?999:Math.floor((today-last)/86400000);if(age>30)moves.push({id:`stale-${r.id}`,kind:'stale',title:`Follow up with ${[c?.first_name,c?.last_name].filter(Boolean).join(' ')||'this coach'}`,detail:`${col?.name||'School'} · ${last===null?'No recent contact date recorded':`Last contact ${age} days ago`}`,why:'Staying in touch helps a coach get to know you and keeps the relationship moving.',href:c?.id?`/coaches/${c.id}`:'/connections',action:c?.id?'Review Coach Relationship':'Review Connections',priority:last===null?78:Math.min(92,70+Math.floor(age/10)),college:col?.id?{id:col.id,name:col.name}:null,coach:c?.id?{id:c.id,name:[c?.first_name,c?.last_name].filter(Boolean).join(' ')||'Coach'}:null})});
 const coachCollegeIds=new Set(coaches.map(r=>college(r.colleges)?.id||r.college_id).filter(Boolean));colleges.forEach(r=>{const col=college(r.colleges);if(col?.id&&!coachCollegeIds.has(col.id))moves.push({id:`missing-${r.id}`,kind:'missing_coach',title:`Find a coach at ${col.name}`,detail:`${String(r.status||'Researching').replace(/_/g,' ')} · You have not added a coach yet`,why:'Adding the right coach gives you someone to contact and lets Rebels Recruit track that relationship.',href:`/coaches/new?college=${col.id}`,action:'Find or Add Coach',priority:String(r.status||'').toLowerCase().includes('interest')?88:65,college:{id:col.id,name:col.name}})});
 events.forEach(e=>{const when=dateMs(e.date);if(when===null||when<today)return;const d=Math.floor((when-today)/86400000);if(d<=14)moves.push({id:`event-${e.id}`,kind:'event',title:d===0?`${e.name} is today`:`Get ready for ${e.name}`,detail:`${e.type||'Recruiting event'}${college(e.colleges)?.name?` · ${college(e.colleges).name}`:''} · ${d===0?'Today':`In ${d} day${d===1?'':'s'}`}`,why:d>0?'Preparing before an event helps you know who you want to connect with and what you want coaches to see.':undefined,href:e.id?`/events/${e.id}/prep`:'/events',action:'Prepare for Event',priority:d<=2?90:d<=7?76:60,date:e.date,college:college(e.colleges)?.id?{id:college(e.colleges).id,name:college(e.colleges).name}:null})});
 advisorRequests.forEach(r=>moves.push({id:`advisor-${r.id}`,kind:'advisor_request',title:'Review advisor access request',detail:`${r.advisorName||'An advisor'} wants access to help with your recruiting`,why:'Only approve people you want to see your recruiting information.',href:'/manage-access',action:'Review Access Request',priority:108,date:r.invited_at}));
 return moves.sort((a,b)=>b.priority-a.priority||String(a.date||'').localeCompare(String(b.date||''))).slice(0,10)}
export default function SmartNextMoves({moves,hrefTransform}:{moves:Move[];hrefTransform?:(href:string)=>string}){const go=(href:string)=>hrefTransform?hrefTransform(href):href;return <div className="space-y-3">{moves.length?moves.map(m=><div key={m.id} className="border rounded-xl p-4 flex items-start sm:items-center gap-3 hover:border-slate-400 transition"><div className={`h-9 w-9 shrink-0 rounded-xl border flex items-center justify-center ${tone(m.priority)}`}>{icon(m.kind)}</div><div className="flex-1 min-w-0"><div className="flex flex-wrap items-center gap-2"><Link href={go(m.href)} className="font-black hover:text-red-700">{m.title}</Link><span className="pill text-[11px]">{source(m.kind)}</span></div><div className="muted text-sm mt-1">{m.detail}</div>{m.why&&<div className="text-sm text-slate-700 mt-2"><span className="font-bold">Why this matters:</span> {m.why}</div>}{(m.college||m.coach)&&<div className="flex flex-wrap gap-2 mt-2">{m.college&&<Link href={go(`/colleges/${m.college.id}`)} className="inline-flex items-center gap-1.5 rounded-lg border bg-white px-2.5 py-1.5 text-xs font-bold hover:border-slate-400"><School size={13}/>{m.college.name}</Link>}{m.coach&&<Link href={go(`/coaches/${m.coach.id}`)} className="inline-flex items-center gap-1.5 rounded-lg border bg-white px-2.5 py-1.5 text-xs font-bold hover:border-slate-400"><UserRound size={13}/>{m.coach.name}</Link>}</div>}<Link href={go(m.href)} className="sm:hidden inline-flex items-center gap-1 text-xs font-black mt-3">{m.action}<ArrowRight size={13}/></Link></div><Link href={go(m.href)} className="hidden sm:inline-flex items-center gap-1 text-xs font-black whitespace-nowrap">{m.action}<ArrowRight size={14}/></Link></div>):<div className="py-10 text-center"><div className="font-black">You're caught up.</div><div className="muted text-sm mt-1">Nothing needs your attention right now. Keep an eye on upcoming events and coach replies.</div></div>}</div>}
