import Link from 'next/link';
import {AlertCircle,CalendarDays,CheckSquare,Clock3,UserPlus,Users,ArrowRight} from 'lucide-react';

type Move={id:string;kind:'reminder'|'task'|'stale'|'event'|'missing_coach'|'advisor_request';title:string;detail:string;href:string;action:string;priority:number;date?:string|null};
const icon=(kind:Move['kind'])=>kind==='task'?<CheckSquare size={18}/>:kind==='event'?<CalendarDays size={18}/>:kind==='missing_coach'?<Users size={18}/>:kind==='advisor_request'?<UserPlus size={18}/>:kind==='stale'?<Clock3 size={18}/>:<AlertCircle size={18}/>;
const tone=(p:number)=>p>=90?'bg-red-50 text-red-700 border-red-200':p>=70?'bg-amber-50 text-amber-800 border-amber-200':'bg-slate-50 text-slate-700 border-slate-200';
export function buildSmartNextMoves({reminders=[],tasks=[],coaches=[],colleges=[],events=[],advisorRequests=[]}:{reminders?:any[];tasks?:any[];coaches?:any[];colleges?:any[];events?:any[];advisorRequests?:any[]}){const now=new Date();now.setHours(0,0,0,0);const today=now.getTime();const moves:Move[]=[];const dateMs=(v:any)=>v?new Date(`${v}T00:00:00`).getTime():null;const college=(v:any)=>Array.isArray(v)?v[0]:v;const coach=(v:any)=>Array.isArray(v)?v[0]:v;
 reminders.filter(r=>['open','overdue','snoozed'].includes(String(r.status))).forEach(r=>{const due=dateMs(r.due_date),late=due!==null&&due<today;moves.push({id:`rem-${r.id}`,kind:'reminder',title:r.title||'Follow up',detail:`${college(r.colleges)?.name||'My reminder'} · ${late?'Overdue':'Due'} ${r.due_date||'soon'}`,href:'/game-plan#next-moves',action:'Open Game Plan',priority:late?112:due===today?110:106,date:r.due_date})});
 tasks.filter(t=>String(t.status)!=='completed').forEach(t=>{const due=dateMs(t.due_date),late=due!==null&&due<today;moves.push({id:`task-${t.id}`,kind:'task',title:t.title||'Advisor task',detail:`Assigned by your recruiting advisor${t.due_date?` · ${late?'Overdue':'Due'} ${t.due_date}`:''}`,href:'/game-plan#next-moves',action:'Open Game Plan',priority:late?111:due===today?109:105,date:t.due_date})});
 coaches.forEach(r=>{const c=coach(r.college_coaches),col=college(r.colleges);const last=dateMs(r.last_contact_date),age=last===null?999:Math.floor((today-last)/86400000);if(age>30)moves.push({id:`stale-${r.id}`,kind:'stale',title:`Reconnect with ${[c?.first_name,c?.last_name].filter(Boolean).join(' ')||'coach'}`,detail:`${col?.name||'College'} · ${last===null?'No contact logged':`Last contact ${age} days ago`}`,href:c?.id?`/coaches/${c.id}`:'/connections',action:c?.id?'Open relationship':'View connections',priority:last===null?78:Math.min(92,70+Math.floor(age/10))})});
 const coachCollegeIds=new Set(coaches.map(r=>college(r.colleges)?.id||r.college_id).filter(Boolean));colleges.forEach(r=>{const col=college(r.colleges);if(col?.id&&!coachCollegeIds.has(col.id))moves.push({id:`missing-${r.id}`,kind:'missing_coach',title:`Add a coach at ${col.name}`,detail:`${String(r.status||'Researching').replace(/_/g,' ')} · No coach relationship yet`,href:`/coaches/new?college=${col.id}`,action:'Find / add coach',priority:String(r.status||'').toLowerCase().includes('interest')?88:65})});
 events.forEach(e=>{const when=dateMs(e.date);if(when===null||when<today)return;const d=Math.floor((when-today)/86400000);if(d<=14)moves.push({id:`event-${e.id}`,kind:'event',title:d===0?`${e.name} is today`:`Prepare for ${e.name}`,detail:`${e.type||'Recruiting event'}${college(e.colleges)?.name?` · ${college(e.colleges).name}`:''} · ${d===0?'Today':`In ${d} day${d===1?'':'s'}`}`,href:'/events',action:'View event',priority:d<=2?90:d<=7?76:60,date:e.date})});
 advisorRequests.forEach(r=>moves.push({id:`advisor-${r.id}`,kind:'advisor_request',title:'Review advisor request',detail:`${r.advisorName||'An advisor'} wants access to your recruiting data`,href:'/manage-access',action:'Review request',priority:108,date:r.invited_at}));
 return moves.sort((a,b)=>b.priority-a.priority||String(a.date||'').localeCompare(String(b.date||''))).slice(0,10)}
export default function SmartNextMoves({moves}:{moves:Move[]}){return <div className="space-y-3">{moves.length?moves.map(m=><Link key={m.id} href={m.href} className="border rounded-xl p-4 flex items-center gap-3 hover:bg-slate-50 transition"><div className={`h-9 w-9 shrink-0 rounded-xl border flex items-center justify-center ${tone(m.priority)}`}>{icon(m.kind)}</div><div className="flex-1 min-w-0"><div className="font-bold">{m.title}</div><div className="muted text-sm mt-1">{m.detail}</div></div><div className="hidden sm:block text-xs font-bold whitespace-nowrap">{m.action}</div><ArrowRight size={17} className="shrink-0"/></Link>):<div className="py-10 text-center"><div className="font-bold">You're caught up.</div><div className="muted text-sm mt-1">No recruiting actions need your attention right now.</div></div>}</div>}
