'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {CheckSquare,Plus} from 'lucide-react';
import {createClient} from '@/lib/supabase-browser';

export default function StaffTaskCenter(){
 const c=createClient();const [me,setMe]=useState<any>(null),[players,setPlayers]=useState<any[]>([]),[tasks,setTasks]=useState<any[]>([]),[athlete,setAthlete]=useState(''),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[due,setDue]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function load(){const {data:{user}}=await c.auth.getUser();if(!user)return;setMe(user);const {data:om}=await c.from('organization_members').select('organization_id,role,organization_view_access').eq('user_id',user.id).eq('status','active').maybeSingle();if(!om)return;let ids:string[]=[];if(['owner','admin'].includes(String(om.role))||om.organization_view_access){const {data:m}=await c.from('organization_members').select('user_id').eq('organization_id',om.organization_id).eq('role','athlete').eq('status','active');ids=(m||[]).map((x:any)=>x.user_id)}else{const {data:a}=await c.from('athlete_advisor_assignments').select('athlete_user_id').eq('advisor_user_id',user.id).eq('status','active');ids=(a||[]).map((x:any)=>x.athlete_user_id)}const {data:p}=ids.length?await c.from('profiles').select('id,full_name,email').in('id',ids):{data:[]};const sorted=(p||[]).sort((a:any,b:any)=>String(a.full_name||a.email||'').localeCompare(String(b.full_name||b.email||'')));setPlayers(sorted);const qs=new URLSearchParams(window.location.search);const requested=qs.get('player');if(requested&&ids.includes(requested))setAthlete(requested);if(qs.get('title'))setTitle(qs.get('title')||'');if(qs.get('description'))setDescription(qs.get('description')||'');const {data:t}=await c.from('advisor_tasks').select('id,athlete_user_id,title,description,due_date,status,completed_at,created_at').in('athlete_user_id',ids.length?ids:['00000000-0000-0000-0000-000000000000']).order('created_at',{ascending:false}).limit(100);setTasks(t||[])}
 useEffect(()=>{load()},[]);const open=useMemo(()=>tasks.filter(t=>t.status!=='completed'),[tasks]);
 async function createTask(){setError('');setMessage('');if(!me||!athlete||!title.trim())return;const {error:e}=await c.from('advisor_tasks').insert({athlete_user_id:athlete,created_by_user_id:me.id,assigned_to_user_id:athlete,title:title.trim(),description:description.trim()||null,due_date:due||null});if(e){setError(e.message);return}setTitle('');setDescription('');setDue('');setMessage('Next Move assigned to the player.');await load()}
 async function complete(id:string){await c.from('advisor_tasks').update({status:'completed',completed_at:new Date().toISOString()}).eq('id',id);await load()}
 const name=(id:string)=>players.find(p=>p.id===id)?.full_name||players.find(p=>p.id===id)?.email||'Player';
 return <div className="grid lg:grid-cols-3 gap-6"><section className="card p-5"><div className="flex items-center gap-2"><Plus size={18}/><div><h2 className="font-black text-lg">Assign Next Move</h2><p className="muted text-sm">This appears in the player&apos;s Game Plan. Write one clear action they can understand and complete.</p></div></div><div className="rounded-xl border bg-slate-50 p-3 mt-4 text-sm text-slate-700"><b>Start with the action.</b> For example: Email Coach Smith before camp, update your video, or research the school&apos;s academic program.</div><div className="space-y-3 mt-4"><select className="input" value={athlete} onChange={e=>setAthlete(e.target.value)}><option value="">Choose player</option>{players.map(p=><option key={p.id} value={p.id}>{p.full_name||p.email}</option>)}</select><input className="input" placeholder="What should the player do?" value={title} onChange={e=>setTitle(e.target.value)}/><textarea className="input min-h-24" placeholder="Why it matters or what good completion looks like (optional)" value={description} onChange={e=>setDescription(e.target.value)}/><input className="input" type="date" value={due} onChange={e=>setDue(e.target.value)}/><button className="btn btn-red w-full" disabled={!athlete||!title.trim()} onClick={createTask}><Plus size={16}/>Assign Next Move</button>{message&&<div className="text-sm font-bold text-green-700">{message}</div>}{error&&<div className="text-sm text-red-600">{error}</div>}<Link href="/advisors/tasks" className="text-sm font-bold inline-block">Open Tasks</Link></div></section><section className="card p-5 lg:col-span-2"><div className="flex items-center gap-2"><CheckSquare size={18}/><div><h2 className="font-black text-lg">Player Next Moves</h2><p className="muted text-sm">Work you assigned that players have not completed yet.</p></div></div><div className="mt-4 divide-y">{open.map(t=><div key={t.id} className="py-4 flex flex-col sm:flex-row sm:items-center gap-3"><div className="flex-1 min-w-0"><Link href={`/players/${t.athlete_user_id}`} className="font-black text-sm hover:text-red-700">{name(t.athlete_user_id)}</Link><div className="font-semibold mt-1">{t.title}</div>{t.description&&<div className="muted text-sm mt-1">{t.description}</div>}<div className="muted text-xs mt-1">{t.due_date?`Due ${new Date(`${t.due_date}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}`:'No due date'}</div><Link href={`/game-plan?athlete=${t.athlete_user_id}#next-moves`} className="inline-flex text-xs font-black mt-2">Open Player Next Moves</Link></div><button className="btn text-xs" onClick={()=>complete(t.id)}>Mark Complete</button></div>)}{!open.length&&<div className="py-10 text-center"><div className="font-black text-sm">No assigned Next Moves are open.</div><div className="muted text-sm mt-1">New player work you assign will appear here until it is completed.</div></div>}</div></section></div>;
}
