'use client';
import {useEffect,useMemo,useState} from 'react';
import {GripVertical,ChevronUp,ChevronDown,Target,CheckCircle2} from 'lucide-react';

type TargetRow={relationshipId:string;athleteUserId:string;collegeId:string|null;name:string;division?:string|null;state?:string|null;conference?:string|null;status?:string;rank:number};
type Props={fallbackColleges?:any[];compact?:boolean};
const one=(v:any)=>Array.isArray(v)?v[0]:v;

export default function TargetRanking({fallbackColleges=[],compact=false}:Props){
 const [rows,setRows]=useState<TargetRow[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[dragged,setDragged]=useState<string|null>(null);
 useEffect(()=>{fetch('/api/targets',{cache:'no-store'}).then(async r=>r.ok?await r.json():{}).then(d=>{if(d.targets?.length)setRows(d.targets);else if(fallbackColleges.length)setRows(fallbackColleges.filter((r:any)=>!r.archived_at).map((r:any,i:number)=>{const c=one(r.colleges)||{};return{relationshipId:r.id,athleteUserId:r.athlete_user_id||'',collegeId:c.id||null,name:c.name||'College',division:c.division||null,state:c.state||null,conference:c.conference||null,status:r.status||'Researching',rank:i+1}}))}).catch(()=>{})},[fallbackColleges]);
 const ordered=useMemo(()=>[...rows].sort((a,b)=>a.rank-b.rank||a.name.localeCompare(b.name)),[rows]);
 async function save(next:TargetRow[]){setRows(next.map((r,i)=>({...r,rank:i+1})));setBusy(true);setMsg('');try{const res=await fetch('/api/targets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({order:next.map(r=>r.relationshipId)})});if(!res.ok){const d=await res.json().catch(()=>({}));setMsg(d.error||'Could not save target order.')}else{setMsg('Saved');setTimeout(()=>setMsg(''),1800)}}catch{setMsg('Could not save target order.')}finally{setBusy(false)}}
 function move(id:string,delta:number){const next=[...ordered],i=next.findIndex(r=>r.relationshipId===id),j=i+delta;if(i<0||j<0||j>=next.length)return;[next[i],next[j]]=[next[j],next[i]];save(next)}
 function drop(overId:string){if(!dragged||dragged===overId)return setDragged(null);const next=[...ordered],from=next.findIndex(r=>r.relationshipId===dragged),to=next.findIndex(r=>r.relationshipId===overId);if(from<0||to<0)return setDragged(null);const [item]=next.splice(from,1);next.splice(to,0,item);setDragged(null);save(next)}
 if(compact)return <div className="mt-4"><div className="flex items-center justify-between"><div className="font-black text-sm flex items-center gap-2"><Target size={16}/>Top Targets</div><span className="muted text-xs">Player ranked</span></div><div className="mt-2 space-y-2">{ordered.slice(0,5).map(r=><div key={r.relationshipId} className="flex items-center gap-2 text-sm"><span className="font-black w-6">#{r.rank}</span><span className="font-semibold truncate flex-1">{r.name}</span><span className="status-pill">{String(r.status||'Researching').replace(/_/g,' ')}</span></div>)}{!ordered.length&&<div className="muted text-xs">No targets ranked yet.</div>}</div></div>;
 return <section className="card p-5 mb-7"><div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><h2 className="font-black text-lg flex items-center gap-2"><Target size={19}/>Target Rankings</h2><p className="muted text-sm mt-1">Drag to rank the schools you want most. Your #1 target stays #1 even when you filter the page.</p></div><div className="text-xs font-semibold text-slate-600">{busy?'Saving...':msg||'Changes save automatically'}</div></div><div className="mt-4 space-y-2">{ordered.map((r,i)=><div key={r.relationshipId} draggable={!busy} onDragStart={()=>setDragged(r.relationshipId)} onDragOver={e=>e.preventDefault()} onDrop={()=>drop(r.relationshipId)} className={`border rounded-xl bg-white p-3 flex items-center gap-3 ${dragged===r.relationshipId?'opacity-50':''}`}><GripVertical size={18} className="muted cursor-grab hidden sm:block"/><div className={`h-9 w-9 rounded-full flex items-center justify-center font-black ${r.rank<=5?'bg-red-50 text-red-700':'bg-slate-100'}`}>#{r.rank}</div><div className="flex-1 min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-black">{r.name}</span>{r.rank<=5&&<span className="pill bg-red-50 text-red-700">Top Target</span>}<span className="status-pill">{String(r.status||'Researching').replace(/_/g,' ')}</span></div><div className="muted text-xs mt-1">{[r.division,r.state,r.conference].filter(Boolean).join(' · ')}</div></div><div className="flex gap-1"><button aria-label="Move up" disabled={busy||i===0} onClick={()=>move(r.relationshipId,-1)} className="h-9 w-9 rounded-lg border flex items-center justify-center disabled:opacity-30"><ChevronUp size={16}/></button><button aria-label="Move down" disabled={busy||i===ordered.length-1} onClick={()=>move(r.relationshipId,1)} className="h-9 w-9 rounded-lg border flex items-center justify-center disabled:opacity-30"><ChevronDown size={16}/></button></div></div>)}{!ordered.length&&<div className="rounded-xl border border-dashed p-6 text-center muted text-sm">Add a college to your Current Pipeline to start ranking targets.</div>}</div>{msg==='Saved'&&<div className="mt-3 text-xs font-bold text-green-700 inline-flex items-center gap-1"><CheckCircle2 size={14}/>Target order saved</div>}</section>
}
