'use client';
import {useEffect,useMemo,useState} from 'react';
import {Plus,Upload,Trash2,Search,Users} from 'lucide-react';
import AppShell from '@/components/AppShell';
import PageHeader from '@/components/PageHeader';
import {createClient} from '@/lib/supabase-browser';

const norm=(v:any)=>String(v||'').trim().toLowerCase();
const empty={athlete_name:'',graduation_year:'',position:'',team_name:'',college_id:'',college_coach_id:'',college_coach_name:'',organization_advisor_name:'',placement_type:'Committed',commitment_year:'',notes:''};
function parseCsv(text:string){const out:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))out.push(row);row=[];cell=''}else cell+=ch}row.push(cell);if(row.some(v=>v.trim()))out.push(row);return out}
export default function HistoricalRecruiting(){
 const c=createClient();const[orgId,setOrgId]=useState(''),[userId,setUserId]=useState(''),[admin,setAdmin]=useState(false),[readOnly,setReadOnly]=useState(false),[loading,setLoading]=useState(true),[history,setHistory]=useState<any[]>([]),[colleges,setColleges]=useState<any[]>([]),[coaches,setCoaches]=useState<any[]>([]),[form,setForm]=useState<any>(empty),[open,setOpen]=useState(false),[msg,setMsg]=useState(''),[q,setQ]=useState('');
 async function loadHistory(oid:string){const{data}=await c.from('organization_recruiting_history').select('*,colleges(id,name),college_coaches(id,first_name,last_name)').eq('organization_id',oid).order('graduation_year',{ascending:false});setHistory(data||[])}
 useEffect(()=>{(async()=>{const{data:{user}}=await c.auth.getUser();if(!user){setLoading(false);return}setUserId(user.id);const params=new URLSearchParams(window.location.search),previewRole=params.get('previewRole'),previewOrg=params.get('previewOrg');let m:any=null;if(previewRole==='admin'&&previewOrg){const{data:platform}=await c.from('platform_roles').select('role').eq('user_id',user.id).eq('role','super_owner').maybeSingle();if(platform){m={organization_id:previewOrg,role:'admin'};setReadOnly(true)}}if(!m){const{data:members}=await c.from('organization_members').select('organization_id,role').eq('user_id',user.id).eq('status','active').limit(20);const active=window.localStorage.getItem('rr-active-view');m=(members||[]).find((x:any)=>active==='admin'?x.role==='admin':active==='advisor'?x.role==='advisor':x.role==='admin')||(members||[])[0]}if(!m){setLoading(false);return}setOrgId(m.organization_id);setAdmin(m.role==='admin'&&!readOnly&&!(previewRole==='admin'&&previewOrg));const [{data:cs},{data:cc}]=await Promise.all([c.from('colleges').select('id,name').order('name').limit(5000),c.from('college_coaches').select('id,college_id,first_name,last_name').limit(10000)]);setColleges(cs||[]);setCoaches(cc||[]);await loadHistory(m.organization_id);setLoading(false)})()},[]);
 async function save(){if(!admin||!form.athlete_name.trim()||!form.college_id){setMsg('Player name and college are required.');return}const coach=coaches.find(x=>x.id===form.college_coach_id);const payload={...form,organization_id:orgId,created_by:userId,graduation_year:form.graduation_year?Number(form.graduation_year):null,commitment_year:form.commitment_year?Number(form.commitment_year):null,college_coach_id:form.college_coach_id||null,college_coach_name:coach?([coach.first_name,coach.last_name].filter(Boolean).join(' ')):form.college_coach_name||null,source:'admin_entry'};const{error}=await c.from('organization_recruiting_history').insert(payload);if(error){setMsg(error.message);return}setForm(empty);setOpen(false);setMsg('Historical placement added.');await loadHistory(orgId)}
 async function importCsv(file:File){if(!admin)return;setMsg('Reading CSV...');const rows=parseCsv(await file.text());if(rows.length<2){setMsg('No data rows found.');return}const headers=rows[0].map(norm),get=(r:string[],names:string[])=>{const i=headers.findIndex(h=>names.includes(h));return i>=0?String(r[i]||'').trim():''};const byCollege=new Map(colleges.map(x=>[norm(x.name),x]));let added=0,unmatched=0;for(const r of rows.slice(1)){const athlete=get(r,['athlete name','player name','athlete','player']),school=get(r,['college','school','program','college/program']);if(!athlete||!school)continue;let college=byCollege.get(norm(school));if(!college){const matches=colleges.filter(x=>norm(x.name).includes(norm(school))||norm(school).includes(norm(x.name)));if(matches.length===1)college=matches[0]}if(!college){unmatched++;continue}const coachName=get(r,['college coach','coach','coach name']);const coachMatches=coachName?coaches.filter(x=>x.college_id===college.id&&norm([x.first_name,x.last_name].filter(Boolean).join(' '))===norm(coachName)):[];const payload={organization_id:orgId,created_by:userId,athlete_name:athlete,graduation_year:Number(get(r,['graduation year','grad year','class year']))||null,position:get(r,['position'])||null,team_name:get(r,['team','team name'])||null,college_id:college.id,college_coach_id:coachMatches.length===1?coachMatches[0].id:null,college_coach_name:coachName||null,organization_advisor_name:get(r,['organization coach/advisor','advisor','club coach','organization advisor'])||null,placement_type:get(r,['placement type','status','outcome'])||'Committed',commitment_year:Number(get(r,['commitment year','commit year']))||null,notes:get(r,['notes','note'])||null,source:'csv_import',source_file_name:file.name};const{error}=await c.from('organization_recruiting_history').insert(payload);if(!error)added++}setMsg('Imported '+added+' historical placement'+(added===1?'':'s')+(unmatched?' · '+unmatched+' row'+(unmatched===1?'':'s')+' skipped because the college could not be matched.':'') );await loadHistory(orgId)}
 const filtered=useMemo(()=>history.filter(x=>!q||norm(x.athlete_name+' '+x.colleges?.name+' '+x.college_coach_name).includes(norm(q))),[history,q]);
 const programCount=new Set(history.map(x=>x.college_id)).size;
 if(loading)return <AppShell><div className="max-w-6xl mx-auto p-8"><div className="card p-10 text-center muted">Loading recruiting history...</div></div></AppShell>;
 return <AppShell><div className="max-w-7xl mx-auto px-5 md:px-8 py-7"><PageHeader eyebrow="ORGANIZATION" title="Historical Recruiting" subtitle="Bring the recruiting relationships your organization already earned into RLTNL." action={admin?<div className="flex gap-2"><label className="btn cursor-pointer"><Upload size={16}/>Import CSV<input className="hidden" type="file" accept=".csv,text/csv" onChange={e=>e.target.files?.[0]&&importCsv(e.target.files[0])}/></label><button className="btn btn-red" onClick={()=>setOpen(true)}><Plus size={16}/>Add Former Player</button></div>:undefined}/>
 {!admin&&<div className="card p-4 mb-4 text-sm">Historical recruiting is read-only in Advisor view. Organization Admins can add and import former players.</div>}
 {msg&&<div className="rounded-xl border bg-slate-50 px-4 py-3 text-sm font-bold mb-4">{msg}</div>}
 <div className="grid sm:grid-cols-3 gap-3 mb-4"><Metric label="Historical Placements" value={history.length}/><Metric label="Programs" value={programCount}/><Metric label="Years Represented" value={new Set(history.map(x=>x.graduation_year).filter(Boolean)).size}/></div>
 {open&&admin&&<section className="card p-5 mb-4"><h2 className="font-black text-lg">Add Former Player</h2><p className="muted text-sm mt-1 mb-4">Only player name and college are required. Add what you know.</p><div className="grid md:grid-cols-3 gap-3"><Field label="Player Name"><input className="input" value={form.athlete_name} onChange={e=>setForm({...form,athlete_name:e.target.value})}/></Field><Field label="Graduation Year"><input className="input" type="number" value={form.graduation_year} onChange={e=>setForm({...form,graduation_year:e.target.value})}/></Field><Field label="Position"><input className="input" value={form.position} onChange={e=>setForm({...form,position:e.target.value})}/></Field><Field label="Team"><input className="input" value={form.team_name} onChange={e=>setForm({...form,team_name:e.target.value})}/></Field><Field label="College / Program"><select className="input" value={form.college_id} onChange={e=>setForm({...form,college_id:e.target.value,college_coach_id:''})}><option value="">Choose college</option>{colleges.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="College Coach"><select className="input" value={form.college_coach_id} onChange={e=>setForm({...form,college_coach_id:e.target.value})}><option value="">Unknown / not listed</option>{coaches.filter(x=>x.college_id===form.college_id).map(x=><option key={x.id} value={x.id}>{[x.first_name,x.last_name].filter(Boolean).join(' ')}</option>)}</select></Field><Field label="Organization Coach / Advisor"><input className="input" value={form.organization_advisor_name} onChange={e=>setForm({...form,organization_advisor_name:e.target.value})}/></Field><Field label="Placement"><select className="input" value={form.placement_type} onChange={e=>setForm({...form,placement_type:e.target.value})}><option>Committed</option><option>Signed</option><option>Played</option><option>Other</option></select></Field><Field label="Commitment Year"><input className="input" type="number" value={form.commitment_year} onChange={e=>setForm({...form,commitment_year:e.target.value})}/></Field></div><Field label="Notes"><textarea className="input min-h-24 mt-3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><div className="flex justify-end gap-2 mt-4"><button className="btn" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-red" onClick={save}>Save Historical Placement</button></div></section>}
 <div className="card p-3 mb-3"><label className="flex items-center gap-2"><Search size={16}/><input className="w-full outline-none" placeholder="Search former players, colleges or coaches" value={q} onChange={e=>setQ(e.target.value)}/></label></div>
 <section className="card overflow-hidden">{filtered.length?<div className="divide-y">{filtered.map(x=><div key={x.id} className="p-4 flex items-center gap-4"><div className="h-10 w-10 rounded-xl bg-slate-100 flex items-center justify-center"><Users size={17}/></div><div className="min-w-0 flex-1"><div className="font-black">{x.athlete_name}{x.graduation_year?' · '+x.graduation_year:''}</div><div className="text-sm text-slate-600">{x.colleges?.name} · {x.placement_type}{x.college_coach_name?' · '+x.college_coach_name:''}</div>{x.notes&&<div className="text-xs text-slate-500 mt-1">{x.notes}</div>}</div>{admin&&<button title="Delete historical placement" className="btn" onClick={async()=>{if(!confirm('Delete this historical placement?'))return;await c.from('organization_recruiting_history').delete().eq('id',x.id);await loadHistory(orgId)}}><Trash2 size={15}/></button>}</div>)}</div>:<div className="p-10 text-center muted">No historical placements yet. Add a former player or import a CSV.</div>}</section>
 {admin&&<div className="mt-4 text-xs text-slate-500"><b>CSV columns:</b> Athlete Name, Graduation Year, Position, Team, College, College Coach, Organization Coach/Advisor, Placement Type, Commitment Year, Notes. Only Athlete Name and College are required.</div>}
 </div></AppShell>
}
function Field({label,children}:{label:string;children:any}){return <label className="block"><span className="text-xs font-black text-slate-600 block mb-1">{label}</span>{children}</label>}
function Metric({label,value}:{label:string;value:number}){return <div className="card p-4"><div className="text-2xl font-black">{value}</div><div className="text-xs font-bold text-slate-500 mt-1">{label}</div></div>}
