import PublicLegalPage from '@/components/PublicLegalPage';

export const metadata={title:'Terms of Service | Rebels Recruit',description:'Terms of Service for Rebels Recruit.'};

export default function Terms(){return <PublicLegalPage title="Terms of Service" updated="September 8, 2026">
  <section><p>These Terms of Service govern your access to and use of Rebels Recruit, a college softball recruiting relationship-management platform. By creating an account or using Rebels Recruit, you agree to these Terms.</p></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">Use of Rebels Recruit</h2><p>You may use Rebels Recruit for lawful recruiting, communication, organization, and related activities. You are responsible for information you enter, messages you choose to send, and actions taken through your account. You may not use the service to violate law, impersonate another person, interfere with the service, gain unauthorized access, distribute malicious content, or harass or abuse others.</p></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">Accounts and organizations</h2><p>You are responsible for maintaining the security of your account and for activity performed through it. Rebels Recruit may provide different permissions to athletes, recruiting advisors, administrators, and organization owners. Organization administrators are responsible for assigning access appropriately and for their organization's use of shared recruiting information.</p></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">Recruiting information</h2><p>Rebels Recruit helps users organize recruiting information and relationships, but it does not represent any college, university, athletic program, coach, recruiting service, or governing body unless expressly stated. We do not guarantee recruitment, roster placement, scholarships, admissions, eligibility, coach responses, or the accuracy or continued availability of third-party recruiting information.</p></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">Google and other third-party services</h2><p>Optional integrations may allow you to connect services such as Gmail or Google Calendar. Your use of those services remains subject to the applicable provider's terms and policies. You control whether to authorize these integrations and may disconnect supported integrations from Rebels Recruit. Rebels Recruit is not responsible for outages, changes, or actions of third-party services.</p></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">Your content</h2><p>You retain ownership of content you provide to Rebels Recruit. You grant us the limited rights necessary to host, process, transmit, display, and otherwise use that content to operate and provide the service to you and authorized members of your organization.</p></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">Privacy</h2><p>Our <a className="font-bold text-red-700 hover:underline" href="/privacy">Privacy Policy</a> explains how Rebels Recruit collects, uses, stores, and protects information, including information used through optional Google integrations.</p></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">Availability and changes</h2><p>We may update, add, remove, suspend, or discontinue features as the service evolves. We may also update these Terms. Continued use after updated Terms take effect constitutes acceptance of the updated Terms to the extent permitted by law.</p></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">Disclaimers and limitation of liability</h2><p>Rebels Recruit is provided on an “as is” and “as available” basis to the extent permitted by law. We do not warrant uninterrupted or error-free operation. To the maximum extent permitted by law, Rebels Recruit and its operators will not be liable for indirect, incidental, special, consequential, or punitive damages arising from use of the service.</p></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">Termination</h2><p>You may stop using Rebels Recruit at any time. We may suspend or terminate access when reasonably necessary to protect the service or its users, enforce these Terms, or comply with law.</p></section>
  <section><h2 className="text-xl font-black text-slate-900 mb-2">Contact</h2><p>Questions about these Terms can be sent to <a className="font-bold text-red-700 hover:underline" href="mailto:bobwad01@gmail.com">bobwad01@gmail.com</a>.</p></section>
</PublicLegalPage>}
