export type EmailStarterId='introduction'|'season_schedule'|'weekend_schedule'|'monthly_update'|'new_video'|'pre_camp'|'post_camp'|'coach_watched'|'weekend_highlights'|'recruiting_needs'|'coach_response'|'visit_followup'|'offer_followup'|'custom';
export type EmailStarter={id:EmailStarterId;label:string;purpose:string;guidance:string;ask:string};
export const EMAIL_STARTERS:EmailStarter[]=[
{id:'introduction',label:'Introduce Myself',purpose:'Player Profile',guidance:'Introduce who you are, then give one specific reason this school fits you.',ask:'Invite the staff to review your profile/video and follow you this season.'},
{id:'season_schedule',label:'Send Season Schedule',purpose:'Season Schedule',guidance:'Share your upcoming fall or summer schedule and remind them why you are interested.',ask:'Invite the staff to watch you play.'},
{id:'weekend_schedule',label:'Upcoming Weekend',purpose:'Weekend Schedule',guidance:'Send this as soon as the weekend schedule is known, ideally Tuesday–Thursday.',ask:'Share game times/locations and invite the staff to watch.'},
{id:'monthly_update',label:'Monthly Interest Update',purpose:'Recruiting Update',guidance:'Stay meaningfully in touch about once a month when there is no other natural reason to email.',ask:'Share a useful update, new progress or something you are working on.'},
{id:'new_video',label:'New Video / Training Update',purpose:'Video Update',guidance:'Show something specific you are working on rather than sending a generic check-in.',ask:'Invite the staff to watch the new clip.'},
{id:'pre_camp',label:'Upcoming Camp',purpose:'Camp',guidance:'Email the week before camp so the staff knows you will be there.',ask:'Tell them you are attending and are looking forward to being evaluated and learning from the staff.'},
{id:'post_camp',label:'Post-Camp Thank You',purpose:'Camp Thank You',guidance:'Follow up after camp with a short, personal thank-you.',ask:'Mention something specific you learned or enjoyed and reinforce your interest.'},
{id:'coach_watched',label:'Coach Watched Me',purpose:'Thank You',guidance:'Thank the coach for taking time to watch and include relevant highlights if you have them.',ask:'Reinforce your interest and share your next opportunity to be evaluated.'},
{id:'weekend_highlights',label:'Send Weekend Highlights',purpose:'Weekend Highlights',guidance:'If the staff did not watch, send a concise update with useful highlights.',ask:'Share video/highlights and your next schedule opportunity.'},
{id:'recruiting_needs',label:'Ask About Recruiting Needs',purpose:'Recruiting Needs',guidance:'Ask a focused question about your graduation class and position.',ask:'Ask whether they are still recruiting your position and about upcoming camps, clinics or evaluation opportunities.'},
{id:'coach_response',label:'Follow Up After Coach Response',purpose:'Follow Up',guidance:'Respond personally to what the coach actually said; do not use a generic reply.',ask:'Answer their question or continue the conversation with one useful next step.'},
{id:'visit_followup',label:'Visit Follow-Up',purpose:'Visit Follow Up',guidance:'Thank the staff after a visit and reference something specific from your time on campus.',ask:'Reinforce your interest and ask any genuine follow-up question.'},
{id:'offer_followup',label:'Offer Follow-Up',purpose:'Offer Follow Up',guidance:'Thank the staff for the offer and keep the message thoughtful and personal.',ask:'Confirm next steps or ask any questions you need answered before making a decision.'},
{id:'custom',label:'Write My Own',purpose:'Recruiting',guidance:'Write a personal recruiting email in your own words.',ask:'End with a clear reason for the email or next step.'}
];
export function starterById(id:string){return EMAIL_STARTERS.find(x=>x.id===id)||EMAIL_STARTERS[0]}
export function suggestedStarter(interactionType?:string|null,daysSince?:number|null){const t=(interactionType||'').toLowerCase();if(t.includes('camp'))return t.includes('attend')||t.includes('completed')?'post_camp':'pre_camp';if(t.includes('watched')||t.includes('in person'))return'coach_watched';if(t.includes('response')||t.includes('replied'))return'coach_response';if(t.includes('video'))return'new_video';if(t.includes('visit'))return'visit_followup';if((daysSince??0)>=28)return'monthly_update';return'introduction'}
