export type RecruitingStage='early'|'building'|'active'|'decision';
export type HealthCategory={id:string;label:string;score:number;max:number;status:'strong'|'building'|'attention';detail:string;href:string};
export type HealthProfile={classYear?:number|null;profileComplete?:boolean;fitComplete?:boolean};
export type IntelligenceInput={colleges?:any[];coaches?:any[];interactions?:any[];reminders?:any[];tasks?:any[];events?:any[];healthProfile?:HealthProfile};
export type RecruitingSignal={id:string;kind:'urgent'|'opportunity'|'momentum'|'foundation';title:string;detail:string;priority:number;href?:string};
export type RecruitingHealthFactor={id:string;label:string;impact:number;status:'strong'|'building'|'attention';detail:string;href:string};
export type HealthOpportunity={id:string;title:string;detail:string;points:number;href:string};
const one=(v:any)=>Array.isArray(v)?v[0]:v;
const day=(v?:string|null)=>v?new Date(`${String(v).slice(0,10)}T12:00:00`).getTime():null;
const age=(v?:string|null)=>{const d=day(v);return d===null?null:Math.max(0,Math.floor((Date.now()-d)/86400000))};
const exact=(x:any)=>!x.date_precision||x.date_precision==='exact';
const meaningful=(x:any)=>{const t=String(x.type||'').toLowerCase();return !t.includes('video added')&&!t.includes('note')};
const clamp=(n:number,min=0,max=1)=>Math.max(min,Math.min(max,n));
const points=(max:number,ratio:number)=>Math.round(max*clamp(ratio));
const status=(score:number,max:number):HealthCategory['status']=>score/max>=.8?'strong':score/max>=.5?'building':'attention';
export function recruitingStage(classYear?:number|null):RecruitingStage{
 if(!classYear)return 'building'; const now=new Date(),schoolGradYear=now.getMonth()>=6?now.getFullYear()+1:now.getFullYear(),years=classYear-schoolGradYear;
 return years>=3?'early':years===2?'building':years===1?'active':'decision';
}
const stageLabel=(s:RecruitingStage)=>s==='early'?'Foundation':s==='building'?'Building':s==='active'?'Active Recruiting':'Decision';
const weights:Record<RecruitingStage,Record<string,number>>={
 early:{foundation:30,schools:30,relationships:10,follow:10,activity:20},
 building:{foundation:20,schools:25,relationships:20,follow:15,activity:20},
 active:{foundation:10,schools:15,relationships:30,follow:20,activity:25},
 decision:{foundation:5,schools:10,relationships:30,follow:25,activity:30},
};
const thresholds:Record<RecruitingStage,{schools:number;coaches:number;fresh:number;grace:number}> = {
 early:{schools:5,coaches:1,fresh:45,grace:30},building:{schools:7,coaches:3,fresh:30,grace:21},active:{schools:8,coaches:6,fresh:21,grace:14},decision:{schools:6,coaches:6,fresh:14,grace:10},
};
export type RelationshipTrajectory={collegeId:string;coachId:string;interactionCount:number;athleteTouches:number;coachTouches:number;reciprocal:boolean;eventCount:number;postEventFollowUp:boolean;postEventCoachResponse:boolean;lastActivityAt:string|null;state:'awaiting-athlete'|'momentum'|'active'|'cooling'|'early'};
export type RelationshipIntelligence={total:number;athleteInitiated:number;coachInitiated:number;reciprocalRelationships:number;waitingOnAthlete:number;coolingRelationships:number;activeRelationships:number;momentumRelationships:number;responsePairs:number;medianResponseDays:number|null;followUpPairs:number;medianFollowUpDays:number|null;trajectories:RelationshipTrajectory[];signals:RecruitingSignal[]};
const actor=(x:any)=>String(x.initiated_by||'').toLowerCase();
const interactionTime=(x:any)=>new Date(x.date&&exact(x)?String(x.date).slice(0,10)+'T12:00:00':x.created_at||x.date||0).getTime();
const median=(xs:number[])=>{if(!xs.length)return null;const a=[...xs].sort((x,y)=>x-y),m=Math.floor(a.length/2);return Math.round((a.length%2?a[m]:(a[m-1]+a[m])/2)*10)/10};
export function buildRelationshipIntelligence(input:IntelligenceInput):RelationshipIntelligence{
 const coaches=(input.coaches||[]).filter((x:any)=>!x.archived_at),interactions=(input.interactions||[]).filter(meaningful),events=input.events||[],now=Date.now();let athleteInitiated=0,coachInitiated=0,reciprocalRelationships=0,waitingOnAthlete=0,coolingRelationships=0,activeRelationships=0,momentumRelationships=0;const responseDays:number[]=[],followDays:number[]=[],signals:RecruitingSignal[]=[],trajectories:RelationshipTrajectory[]=[];
 interactions.forEach((x:any)=>{const a=actor(x);if(a==='coach')coachInitiated++;else if(a==='athlete'||a==='player')athleteInitiated++});
 coaches.forEach((r:any)=>{const rows=interactions.filter((x:any)=>(r.coach_id&&x.coach_id===r.coach_id)||(!r.coach_id&&r.college_id&&x.college_id===r.college_id)).sort((a:any,b:any)=>interactionTime(a)-interactionTime(b));const sides=new Set(rows.map(actor).map(a=>a==='player'?'athlete':a).filter(a=>a==='athlete'||a==='coach'));if(sides.has('athlete')&&sides.has('coach'))reciprocalRelationships++;const latest=rows[rows.length-1],lastMs=latest?interactionTime(latest):(r.last_contact_date?day(r.last_contact_date):null),daysOld=lastMs?Math.max(0,Math.floor((now-lastMs)/86400000)):null;if(daysOld!==null&&daysOld<=14)activeRelationships++;if(daysOld!==null&&daysOld>=30)coolingRelationships++;if(latest&&actor(latest)==='coach'&&daysOld!==null&&daysOld<=14){waitingOnAthlete++;const c=one(r.college_coaches),school=one(r.colleges),name=[c?.first_name,c?.last_name].filter(Boolean).join(' ')||'a coach';signals.push({id:'relationship-reply-'+r.id,kind:'urgent',title:'Reply to '+name,detail:(school?.name?school.name+' · ':'')+'The most recent recorded contact came from the coach.',priority:111,href:c?.id?'/coaches/'+c.id:'/connections'})}for(let i=1;i<rows.length;i++){const prev=rows[i-1],cur=rows[i],p=actor(prev)==='player'?'athlete':actor(prev),q=actor(cur)==='player'?'athlete':actor(cur),gap=(interactionTime(cur)-interactionTime(prev))/86400000;if(gap<0||gap>60)continue;if(p==='athlete'&&q==='coach')responseDays.push(gap);if(p==='coach'&&q==='athlete')followDays.push(gap)}const recent=rows.filter((x:any)=>now-interactionTime(x)<=30*86400000),prior=rows.filter((x:any)=>{const d=now-interactionTime(x);return d>30*86400000&&d<=60*86400000});if(recent.length>=2&&recent.length>prior.length)momentumRelationships++;const relatedEvents=events.filter((e:any)=>e.college_id===r.college_id||one(e.colleges)?.id===r.college_id),eventTimes=relatedEvents.map((e:any)=>day(e.date)).filter((x:any):x is number=>x!==null),postEventRows=eventTimes.length?rows.filter((x:any)=>eventTimes.some((t:number)=>interactionTime(x)>=t&&interactionTime(x)<=t+14*86400000)):[],postEventFollowUp=postEventRows.some((x:any)=>['athlete','player'].includes(actor(x))),postEventCoachResponse=postEventRows.some((x:any)=>actor(x)==='coach'),state:RelationshipTrajectory['state']=latest&&actor(latest)==='coach'&&daysOld!==null&&daysOld<=14?'awaiting-athlete':recent.length>=2&&recent.length>prior.length?'momentum':daysOld!==null&&daysOld>=30?'cooling':daysOld!==null&&daysOld<=14?'active':'early';trajectories.push({collegeId:r.college_id||'',coachId:r.coach_id||'',interactionCount:rows.length,athleteTouches:rows.filter((x:any)=>['athlete','player'].includes(actor(x))).length,coachTouches:rows.filter((x:any)=>actor(x)==='coach').length,reciprocal:sides.has('athlete')&&sides.has('coach'),eventCount:relatedEvents.length,postEventFollowUp,postEventCoachResponse,lastActivityAt:latest?new Date(interactionTime(latest)).toISOString():r.last_contact_date||null,state})});
 return{total:coaches.length,athleteInitiated,coachInitiated,reciprocalRelationships,waitingOnAthlete,coolingRelationships,activeRelationships,momentumRelationships,responsePairs:responseDays.length,medianResponseDays:median(responseDays),followUpPairs:followDays.length,medianFollowUpDays:median(followDays),trajectories,signals:signals.sort((a,b)=>b.priority-a.priority)};
}
export function buildRecruitingIntelligence(input:IntelligenceInput){
 const colleges=input.colleges||[],coaches=input.coaches||[],interactions=input.interactions||[],reminders=input.reminders||[],tasks=input.tasks||[],events=input.events||[],hp=input.healthProfile||{};
 const stage=recruitingStage(hp.classYear),w=weights[stage],t=thresholds[stage];
 const active=colleges.filter(x=>!x.archived_at&&!String(x.status||'').toLowerCase().includes('stop'));
 const target=active.filter(x=>['Target School','Contacted','Engaged','Interested','Visit/Camp','Offer','Committed'].includes(String(x.status||'')));
 const exactActivity=interactions.filter(x=>exact(x)&&x.date&&meaningful(x));
 const lastExact=exactActivity.map(x=>age(x.date)).filter((x):x is number=>x!==null).sort((a,b)=>a-b)[0]??null;
 const recent30=exactActivity.filter(x=>{const a=age(x.date);return a!==null&&a<=30}).length;
 const openMoves=tasks.filter(x=>String(x.status)!=='completed'),completedMoves=tasks.filter(x=>String(x.status)==='completed');
 const todayValue=day(new Date().toISOString().slice(0,10))!,overdueMoves=openMoves.filter((x:any)=>x.due_date&&day(x.due_date)!<todayValue).length;
 const upcoming=events.filter(x=>(!x.rsvp||String(x.rsvp).toLowerCase()==='going')&&x.date&&day(x.date)!==null&&day(x.date)!>=todayValue).sort((a,b)=>String(a.date).localeCompare(String(b.date)));
 const signals:RecruitingSignal[]=[];const relationshipIntelligence=buildRelationshipIntelligence(input);signals.push(...relationshipIntelligence.signals);
 openMoves.forEach((x:any)=>{const due=day(x.due_date),overdue=due!==null&&due<todayValue,daysUntil=due===null?null:Math.max(0,Math.ceil((due-todayValue)/86400000));if(overdue){signals.push({id:`overdue-${x.id}`,kind:'urgent',title:x.title||'Overdue Next Step',detail:'This Next Step is late. Finish it or choose a new due date so it does not get lost.',priority:115,href:'/game-plan#next-moves'});return}const timing=daysUntil===0?'due today':daysUntil===1?'due tomorrow':daysUntil!==null?`due in ${daysUntil} days`:'ready when you are';signals.push({id:`next-${x.id}`,kind:'opportunity',title:x.title||'Complete your next recruiting step',detail:`This is one of your current Next Steps and is ${timing}.`,priority:daysUntil===0?112:daysUntil===1?110:daysUntil!==null&&daysUntil<=3?108:daysUntil!==null&&daysUntil<=7?104:96,href:'/game-plan#next-moves'})});
 coaches.forEach((r:any)=>{const c=one(r.college_coaches),school=one(r.colleges),coachRows=interactions.filter((x:any)=>x.coach_id&&x.coach_id===r.coach_id).sort((a:any,b:any)=>String(b.date||b.created_at||'').localeCompare(String(a.date||a.created_at||''))),latest=coachRows[0],days=age(r.last_contact_date||latest?.date||latest?.created_at),coachName=[c?.first_name,c?.last_name].filter(Boolean).join(' ')||'this coach';if(latest&&String(latest.initiated_by).toLowerCase()==='coach'&&days!==null&&days<=14)signals.push({id:`reply-${r.id}`,kind:'urgent',title:`Respond to ${coachName}`,detail:`${school?.name||'School'} · The latest logged interaction came from the coach.`,priority:109,href:c?.id?`/coaches/${c.id}`:'/connections'});if(days!==null&&days>=30)signals.push({id:`cool-${r.id}`,kind:'urgent',title:`Follow up with ${coachName}`,detail:`${school?.name||'School'} · ${days} days since your last recorded contact.`,priority:95,href:c?.id?`/coaches/${c.id}`:'/connections'});else if(days!==null&&days<=14)signals.push({id:`warm-${r.id}`,kind:'momentum',title:`Keep building with ${coachName}`,detail:`${school?.name||'School'} · You have had recent contact.`,priority:72,href:c?.id?`/coaches/${c.id}`:'/connections'})});
 upcoming.slice(0,3).forEach((e:any)=>{const days=Math.ceil((day(e.date)!-Date.now())/86400000);if(days<=14)signals.push({id:`event-${e.id}`,kind:'opportunity',title:`Get ready for ${e.name}`,detail:days<=0?'This event is today.':`This event is in ${days} day${days===1?'':'s'}.`,priority:days<=3?100:80,href:`/events/${e.id}/prep`})});
 if(active.length&&!coaches.length&&stage!=='early')signals.push({id:'coach-foundation',kind:'foundation',title:'Add coaches at your schools',detail:'Add the coaches you may want to contact so you can keep outreach and follow-up organized.',priority:88,href:'/connections'});
 if(!active.length)signals.push({id:'school-foundation',kind:'foundation',title:'Build your school list',detail:'Start with a focused group of schools that fit what matters to you.',priority:90,href:'/discover'});
 const foundationRatio=(hp.profileComplete?0.5:0)+(hp.fitComplete?0.5:0);
 const schoolRatio=clamp((active.length/t.schools)*.45+(target.length/Math.max(2,Math.ceil(t.schools*.6)))*.55);
 const freshCoaches=coaches.filter((x:any)=>{const a=age(x.last_contact_date);return a!==null&&a<=t.fresh}).length;
 const relationshipRatio=stage==='early'?clamp(coaches.length/t.coaches):clamp((coaches.length/t.coaches)*.45+(freshCoaches/Math.max(1,Math.ceil(t.coaches*.6)))*.55);
 const taskTotal=openMoves.length+completedMoves.length; const completionRatio=taskTotal?completedMoves.length/taskTotal:(stage==='early'?1:.5); const followRatio=clamp(completionRatio-(overdueMoves*.15));
 const activityRatio=lastExact===null?0:lastExact<=t.grace?1:lastExact<=t.grace*2?.65:lastExact<=t.grace*3?.3:0;
 const raw=[['foundation','Foundation',foundationRatio,'/profile'],['schools','School Discovery & Fit',schoolRatio,'/connections'],['relationships','Coach Relationships',relationshipRatio,'/connections'],['follow','Follow-Through',followRatio,'/game-plan#next-moves'],['activity','Recent Activity',activityRatio,'/journey']] as const;
 const categories:HealthCategory[]=raw.map(([id,label,ratio,href])=>{const max=w[id],score=points(max,ratio);return{id,label,score,max,status:status(score,max),href,detail:id==='foundation'?`${hp.profileComplete?'Profile complete':'Profile still needs work'} · ${hp.fitComplete?'College Fit Survey complete':'College Fit Survey not complete'}`:id==='schools'?`${active.length} active school${active.length===1?'':'s'} · ${target.length} beyond Researching`:id==='relationships'?`${coaches.length} coach relationship${coaches.length===1?'':'s'} · ${freshCoaches} active within this stage’s window`:id==='follow'?`${completedMoves.length} completed Next Step${completedMoves.length===1?'':'s'} · ${overdueMoves} overdue`:lastExact===null?'No meaningful recruiting activity with a known date yet.':`Last meaningful recruiting activity was ${lastExact} day${lastExact===1?'':'s'} ago.`}});
 const score=categories.reduce((sum,c)=>sum+c.score,0),health=score>=85?'Excellent':score>=70?'Strong':score>=50?'On Track':score>=25?'Building':'Getting Started';
 const ready=true;
 const factors:RecruitingHealthFactor[]=categories.map(c=>({id:c.id,label:c.label,impact:c.score,status:c.status,detail:c.detail,href:c.href}));
 const opportunities:HealthOpportunity[]=[];
 const foundationMax=w.foundation,foundationHalf=Math.round(foundationMax/2);
 if(!hp.profileComplete)opportunities.push({id:'complete-profile',title:'Complete your athlete profile',detail:'Finish the core information coaches and your recruiting team need.',points:foundationHalf,href:'/profile'});
 if(!hp.fitComplete)opportunities.push({id:'complete-fit',title:'Complete your College Fit Survey',detail:'Tell Rebels Recruit what matters to you so school discovery can better reflect your fit.',points:foundationMax-foundationHalf,href:'/fit-profile'});
 const schoolCat=categories.find(c=>c.id==='schools');if(schoolCat&&schoolCat.score<schoolCat.max)opportunities.push({id:'school-fit',title:active.length<t.schools?'Build your focused school list':'Move researched schools forward',detail:active.length<t.schools?'Research and add schools that genuinely fit what you want.':'Use what you learn to identify the schools you want to actively pursue.',points:schoolCat.max-schoolCat.score,href:'/connections'});
 const relationshipCat=categories.find(c=>c.id==='relationships');if(relationshipCat&&relationshipCat.score<relationshipCat.max)opportunities.push({id:'relationships',title:coaches.length<t.coaches?'Build coach relationships':'Reconnect with coaches who need follow-up',detail:coaches.length<t.coaches?'Add the right coaches at priority schools and begin appropriate outreach.':'Keep active relationships current with meaningful, timely follow-up.',points:relationshipCat.max-relationshipCat.score,href:'/connections'});
 const followCat=categories.find(c=>c.id==='follow');if(followCat&&followCat.score<followCat.max)opportunities.push({id:'follow-through',title:overdueMoves?'Close overdue Next Steps':'Complete your current Next Steps',detail:overdueMoves?'Finish or reschedule overdue recruiting work so important follow-through does not stall.':'Follow through on the recruiting actions already in your plan.',points:followCat.max-followCat.score,href:'/game-plan#next-moves'});
 const activityCat=categories.find(c=>c.id==='activity');if(activityCat&&activityCat.score<activityCat.max)opportunities.push({id:'recent-activity',title:'Get your recruiting moving again',detail:'Complete a meaningful recruiting action such as coach outreach, follow-up, event preparation or school research.',points:activityCat.max-activityCat.score,href:'/game-plan'});
 opportunities.sort((a,b)=>b.points-a.points);
 const top=signals.sort((a,b)=>b.priority-a.priority).slice(0,6);
 return {score,health,scoreReady:ready,stage,stageLabel:stageLabel(stage),categories,activeSchools:active.length,targetSchools:target.length,coachRelationships:coaches.length,lastMeaningfulActivityDays:lastExact,openNextMoves:openMoves.length,overdueNextMoves:overdueMoves,upcomingEvents:upcoming.length,signals:top,topPriority:top[0]||null,healthFactors:factors,opportunities:opportunities.slice(0,3),relationshipIntelligence,scoreFormula:`Your score is earned from Foundation, School Discovery & Fit, Coach Relationships, Follow-Through and Recent Activity. Expectations adjust for your ${stageLabel(stage).toLowerCase()} stage, and activity points can fade when recruiting activity slows.`};
}
