'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {Activity,AlertCircle,BarChart3,CalendarDays,CheckSquare,Flag,MessageSquare,Network,School,Search,Sparkles,TrendingUp,Users} from 'lucide-react';
import AppShell from '@/components/AppShell';
import PageHeader from '@/components/PageHeader';
import AdvisorEventAttendanceSummary from '@/components/AdvisorEventAttendanceSummary';
import AdvisorTargetRankings from '@/components/AdvisorTargetRankings';
import {createClient} from '@/lib/supabase-browser';
import {athleteEngagementScore,buildRelationshipInsights,daysSince,isMeaningfulContact} from '@/lib/communication-intelligence';
import {RECRUITING_JOURNEY,JOURNEY_ORDER,normalizeJourneyStage} from '@/lib/recruiting-journey';

const one=(v:any)=>Array.isArray(v)?v[0]:v;
const text=(v:any)=>String(v||'').toLowerCase();
const fmt=(d:any)=>d?new Date(`${String(d).slice(0,10)}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'';

export default function StaffHome(){
 const c=createClient();
 const [loading,setLoading]=useState(true),[role,setRole]=useState('advisor'),[orgAccess,setOrgAccess]=useState(false),[scope,setScope]=useState<'mine'|'org'>('mine'),[profiles,setProfiles]=useState<any[]>([]),[relationships,setRelationships]=useState<any[]>([]),[interactions,setInteractions]=useState<any[]>([]),[reminders,setReminders]=useState<any[]>([]),[colleges,setColleges]=useState<any[]>([]),[events,setEvents]=useState<any[]>([]),[assignments,setAssignments]=useState<any[]>([]),[milestones,setMilestones]=useState<any[]>([]),[search,setSearch]=useState('');
 useEffect(()=>{(async()=>{const {data:{user}}=await c.auth.getUser();if(!user){setLoading(false);return}const {data:me}=await c.from('organization_members').select('organization_id,role,organization_view_access').eq('user_id',user.id).eq('status','active').maybeSingle();if(!me){setLoading(false);return}setRole(me.role);const global=me.role==='owner'||me.role==='admin'||!!me.organization_view_access;setOrgAccess(global);if(me.role==='owner'||me.role==='admin')setScope('org');const [{data:ms},{data:as}]=await Promise.all([c.from('organization_members').select('user_id,role,status').eq('organization_id',me.organization_id).eq('status','active'),c.from('athlete_advisor_assignments').select('athlete_user_id,advisor_user_id,status').eq('organization_id',me.organization_id).eq('status','active')]);setAssignments(as||[]);const allAthletes=(ms||[]).filter((m:any)=>m.role==='athlete').map((m:any)=>m.user_id),myIds=(as||[]).filter((a:any)=>a.advisor_user_id===user.id).map((a:any)=>a.athlete_user_id),accessible=global?allAthletes:myIds;if(!accessible.length){setLoading(false);return}const [ps,rs,ints,rems,acs,evs]=await Promise.all([c.from('profiles').select('id,full_name,email').in('id',accessible),c.from('athlete_coaches').select('id,athlete_user_id,coach_id,college_id,last_contact_date,next_step,archived_at,colleges(id,name,division,state,conference),college_coaches(id,first_name,last_name,title)').in('athlete_user_id',accessible),c.from('interactions').select('id,athlete_user_id,coach_id,college_id,type,date,created_at,note,initiated_by,colleges(name),college_coaches(first_name,last_name)').in('athlete_user_id',accessible).order('date',{ascending:false}).order('created_at',{ascending:false}).limit(4000),c.from('reminders').select('id,athlete_user_id,coach_id,college_id,title,due_date,status').in('athlete_user_id',accessible),c.from('athlete_colleges').select('id,athlete_user_id,college_id,status,archived_at,colleges(id,name,division,state,conference)').in('athlete_user_id',accessible),c.from('athlete_events').select('athlete_user_id,status,events(id,name,type,date,location)').in('athlete_user_id',accessible)]);setProfiles(ps.data||[]);setRelationships((rs.data||[]).filter((r:any)=>!r.archived_at));setInteractions(ints.data||[]);setReminders(rems.data||[]);setColleges((acs.data||[]).filter((r:any)=>!r.archived_at));setEvents(evs.data||[]);try{const all=await Promise.all(accessible.map(id=>fetch(`/api/recruiting-journey?athlete=${encodeURIComponent(id)}`,{cache:'no-store'}).then(async r=>r.ok?(await r.json()).milestones||[]:[])));setMilestones(all.flat())}catch{setMilestones([])}setLoading(false)})()},[]);
 const mySet=useMemo(()=>new Set(assignments.map(a=>a.athlete_user_id)),[assignments]);
 const visibleIds=useMemo(()=>new Set(profiles.filter(p=>scope==='org'||mySet.has(p.id)).map(p=>p.id)),[profiles,scope,mySet]);
 const ps=profiles.filter(p=>visibleIds.has(p.id)),rs=relationships.filter(r=>visibleIds.has(r.athlete_user_id)),ints=interactions.filter(i=>visibleIds.has(i.athlete_user_id)),rems=reminders.filter(r=>visibleIds.has(r.athlete_user_id)),acs=colleges.filter(r=>visibleIds.has(r.athlete_user_id)),ms=milestones.filter(m=>visibleIds.has(m.athleteUserId));
 const insights=useMemo(()=>buildRelationshipInsights(rs,ints),[rs,ints]);
 const today=new Date().toISOString().slice(0,10);
 const rows=useMemo(()=>ps.map(p=>{const pi=ints.filter(i=>i.athlete_user_id===p.id),pr=rems.filter(r=>r.athlete_user_id===p.id),pc=acs.filter(r=>r.athlete_user_id===p.id),pco=rs.filter(r=>r.athlete_user_id===p.id),pins=insights.filter(r=>r.athleteUserId===p.id),overdue=pr.filter(r=>['open','overdue','snoozed'].includes(text(r.status))&&r.due_date&&r.due_date<today).length,last=pi[0]?.date||pi[0]?.created_at||null,stages=pc.map(x=>normalizeJourneyStage(x.status));const topJourney=stages.slice().sort((a,b)=>(JOURNEY_ORDER[b]??0)-(JOURNEY_ORDER[a]??0))[0]||'Researching';return{id:p.id,name:p.full_name||p.email||'Athlete',schools:pc.length,coaches:pco.length,overdue,last,stale:daysSince(last)>=14,score:athleteEngagementScore(p.id,insights,ints,rems),rising:pins.filter(x=>x.momentum==='Rising').length,cooling:pins.filter(x=>x.momentum==='Cooling').length,offers:stages.filter(s=>s==='Offer').length,committed:stages.includes('Committed'),topJourney}}).sort((a,b)=>a.score-b.score),[ps,ints,rems,acs,rs,insights,today]);
 const filteredRows=rows.filter(r=>!search||r.name.toLowerCase().includes(search.toLowerCase()));
 const alerts=rows.filter(r=>r.stale||r.overdue||r.score<35).slice(0,6),pm=new Map(profiles.map(p=>[p.id,p]));
 const recent=ints.slice(0,8),upcoming=events.map(x=>({...x,event:one(x.events)})).filter(x=>visibleIds.has(x.athlete_user_id)&&x.event?.date>=today).sort((a,b)=>String(a.event.date).localeCompare(String(b.event.date))).slice(0,6);
 const meaningful30=ints.filter(i=>daysSince(i.date||i.created_at)<=30&&isMeaningfulContact(i)).length,uniqueSchools=new Set(acs.map(r=>r.college_id)).size,uniqueCoaches=new Set(rs.map(r=>r.coach_id).filter(Boolean)).size,avg=Math.round(rows.reduce((n,p)=>n+p.score,0)/Math.max(1,rows.length));
 const isOwner=role==='owner'||role==='admin',journeyCounts=Object.fromEntries(RECRUITING_JOURNEY.map(s=>[s,acs.filter(r=>normalizeJourneyStage(r.status)===s).length])),activeOffers=journeyCounts['Offer']||0,committedPlayers=rows.filter(r=>r.committed).length,recentMilestones=ms.slice().sort((a,b)=>String(b.milestoneDate).localeCompare(String(a.milestoneDate))).slice(0,6),collegeByRel=new Map(acs.map(r=>[r.id,one(r.colleges)?.name||'College']));
 if(loading)return <AppShell><div className="max-w-7xl mx-auto p-5 sm:p-8"><div className="card p-8 sm:p-10 text-center muted">Building your recruiting dashboard...</div></div></AppShell>;
 return <AppShell><div className="max-w-7xl mx-auto px-4 sm:px-5 md:px-8 py-5 sm:py-6 min-w-0"><PageHeader title={isOwner?'Organization Recruiting Command Center':'Advisor Recruiting Command Center'} subtitle={isOwner?'See recruiting reach, player progress and where your organization needs attention.':'See which players need you and what recruiting activity matters next.'} action={<div className="grid grid-cols-2 sm:flex gap-2 w-full sm:w-auto"><Link href="/advisors/tasks" className="btn w-full sm:w-auto px-3 text-sm whitespace-nowrap"><CheckSquare size={17}/> Assign Task</Link><Link href="/messages" className="btn btn-red w-full sm:w-auto px-3 text-sm whitespace-nowrap"><MessageSquare size={17}/> Messages</Link></div>}/>{orgAccess&&<div className="grid grid-cols-2 rounded-xl border bg-white p-1 mb-5 w-full sm:w-fit"><button onClick={()=>setScope('mine')} className={`px-3 sm:px-4 py-2 rounded-lg text-sm font-bold ${scope==='mine'?'bg-slate-900 text-white':''}`}>My Players</button><button onClick={()=>setScope('org')} className={`px-3 sm:px-4 py-2 rounded-lg text-sm font-bold ${scope==='org'?'bg-slate-900 text-white':''}`}>All Organization Players</button></div>}<div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Metric icon={<Users size={18}/>} label={scope==='org'?'Active Players':'My Players'} value={rows.length} detail={`${alerts.length} currently need attention`}/><Metric icon={<School size={18}/>} label="Current Colleges" value={acs.length} detail={`${uniqueSchools} unique programs`}/><Metric icon={<Flag size={18}/>} label="Offers / Commits" value={`${activeOffers} / ${committedPlayers}`} detail="current Recruiting Journey"/><Metric icon={<Sparkles size={18}/>} label="Meaningful Contacts" value={meaningful30} detail="last 30 days"/></div>
 <section className="card p-4 sm:p-5 mt-6"><div className="flex flex-col md:flex-row md:justify-between gap-3"><div><h2 className="font-black text-lg flex items-center gap-2"><Flag size={19}/>Recruiting Journey Overview</h2><p className="muted text-sm">Read-only view of where players are and when milestones were reached.</p></div><Link href="/intelligence" className="text-sm font-bold">Open Insights →</Link></div><div className="grid grid-cols-2 sm:grid-cols-4 xl:grid-cols-8 gap-2 mt-4">{RECRUITING_JOURNEY.map(s=><div key={s} className="rounded-xl border p-3"><div className="text-xl font-black">{journeyCounts[s]||0}</div><div className="text-xs font-bold mt-1 break-words">{s}</div></div>)}</div>{recentMilestones.length>0&&<div className="grid md:grid-cols-3 gap-3 mt-4">{recentMilestones.map(m=><div key={m.id} className="rounded-xl bg-slate-50 border p-3"><div className="flex justify-between gap-2"><b className="text-sm">{m.stage}</b><span className="muted text-xs">{fmt(m.milestoneDate)}</span></div><div className="text-sm mt-1">{(pm.get(m.athleteUserId) as any)?.full_name||'Player'} · {collegeByRel.get(m.relationshipId)||'College'}</div>{m.offerType&&<div className="muted text-xs mt-1">{m.offerType}</div>}</div>)}</div>}</section>
 <div className="grid lg:grid-cols-3 gap-6 mt-6"><section className="card p-4 sm:p-5 lg:col-span-2"><div className="flex flex-col sm:flex-row sm:justify-between gap-2"><div><h2 className="font-black text-lg flex items-center gap-2"><AlertCircle size={19}/>Needs Your Attention</h2><p className="muted text-sm">Players surfaced from inactivity, overdue follow-ups and engagement signals.</p></div><Link href="/intelligence" className="text-sm font-bold">Insights →</Link></div><div className="mt-4 grid md:grid-cols-2 gap-3">{alerts.map(p=><Link href={`/advisors/player/${p.id}`} key={p.id} className="border rounded-xl p-4 hover:bg-slate-50"><div className="flex justify-between gap-2"><b>{p.name}</b><span className="status-pill">{p.score}/100</span></div><div className="muted text-sm mt-2">{p.committed?'Committed':p.offers?`${p.offers} active offer${p.offers===1?'':'s'}`:p.overdue?`${p.overdue} overdue follow-up${p.overdue===1?'':'s'}`:p.stale?'No recruiting activity in 14+ days':'Recruiting engagement needs attention'}</div></Link>)}{!alerts.length&&<Empty text="No players currently meet the attention thresholds."/>}</div></section><section className="card p-4 sm:p-5"><h2 className="font-black text-lg">Recruiting Insights</h2><p className="muted text-sm">Health across the players in this view.</p><div className="mt-4 space-y-3"><Summary label="Average Recruiting Pulse" value={`${avg}/100`}/><Summary label="Active offers" value={activeOffers}/><Summary label="Committed players" value={committedPlayers}/><Summary label="Overdue follow-ups" value={rows.reduce((n,p)=>n+p.overdue,0)}/><Summary label="Relationships rising" value={insights.filter(r=>r.momentum==='Rising').length}/><Summary label="Relationships cooling" value={insights.filter(r=>r.momentum==='Cooling').length}/></div></section></div>
 <section className="card p-4 sm:p-5 mt-6"><div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><h2 className="font-black text-lg">Player Recruiting Health</h2><p className="muted text-sm">A quick way to see who is active and who may need support.</p></div><div className="relative w-full md:w-auto"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 muted"/><input className="input pl-9 w-full md:w-64" placeholder="Search players" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="overflow-x-auto mt-4"><table className="w-full min-w-[680px] text-sm"><thead><tr className="text-left muted border-b"><th className="py-3">Player</th><th>Schools</th><th>Coaches</th><th>Follow-Up</th><th>Last Activity</th><th>Momentum</th><th>Engagement</th></tr></thead><tbody>{filteredRows.map(p=><tr key={p.id} className="border-b"><td className="py-3"><Link href={`/advisors/player/${p.id}`} className="font-bold">{p.name}</Link><div className="muted text-xs">{p.topJourney}{p.offers?` · ${p.offers} offer${p.offers===1?'':'s'}`:''}{p.committed?' · committed':''}</div></td><td>{p.schools}</td><td>{p.coaches}</td><td>{p.overdue?`${p.overdue} overdue`:'Current'}</td><td>{p.last?`${daysSince(p.last)}d ago`:'None'}</td><td>{p.rising?`${p.rising} rising`:p.cooling?`${p.cooling} cooling`:'Steady'}</td><td><b>{p.score}</b>/100</td></tr>)}</tbody></table></div></section>
 <div className="mt-6"><AdvisorTargetRankings/></div><div className="grid lg:grid-cols-2 gap-6 mt-6"><section className="card p-4 sm:p-5"><div className="flex justify-between gap-3"><h2 className="font-black text-lg flex items-center gap-2"><Activity size={19}/>Recent Player Activity</h2><Link href="/advisors/activity" className="text-sm font-bold">View all</Link></div><div className="mt-4 divide-y">{recent.map(r=><div key={r.id} className="py-3"><b>{(pm.get(r.athlete_user_id) as any)?.full_name||'Player'}</b><div className="text-sm">{r.type} · {one(r.colleges)?.name||'College'}</div><div className="muted text-xs">{r.date||r.created_at?.slice(0,10)}</div></div>)}{!recent.length&&<Empty text="No recruiting activity yet."/>}</div></section><section className="card p-4 sm:p-5"><h2 className="font-black text-lg flex items-center gap-2"><CalendarDays size={19}/>Upcoming Player Events</h2><div className="mt-4 space-y-3">{upcoming.map(x=><Link href="/events" key={`${x.athlete_user_id}-${x.event.id}`} className="block border rounded-xl p-3"><b>{(pm.get(x.athlete_user_id) as any)?.full_name||'Player'}</b><div className="text-sm">{x.event.name}</div><div className="muted text-xs break-words">{x.event.date} · {x.event.location||x.event.type||''}</div></Link>)}{!upcoming.length&&<Empty text="No upcoming player events."/>}</div></section></div><div className="mt-6"><AdvisorEventAttendanceSummary/></div>
 {isOwner&&<><div className="grid lg:grid-cols-2 gap-6 mt-6"><section className="card p-4 sm:p-5"><h2 className="font-black text-lg flex items-center gap-2"><Network size={19}/>Organization Recruiting Reach</h2><div className="mt-4 space-y-3"><Summary label="Unique college programs" value={uniqueSchools}/><Summary label="Unique college coaches" value={uniqueCoaches}/><Summary label="Active offers" value={activeOffers}/><Summary label="Committed players" value={committedPlayers}/></div></section><section className="card p-4 sm:p-5"><h2 className="font-black text-lg flex items-center gap-2"><BarChart3 size={19}/>Player Recruiting Pulse</h2><div className="mt-4 space-y-3"><Summary label="Highly engaged" value={rows.filter(p=>p.score>=75).length}/><Summary label="Building" value={rows.filter(p=>p.score>=50&&p.score<75).length}/><Summary label="Early" value={rows.filter(p=>p.score>=25&&p.score<50).length}/><Summary label="Needs attention" value={rows.filter(p=>p.score<25).length}/></div></section></div><section className="card p-4 sm:p-5 mt-6"><h2 className="font-black text-lg flex items-center gap-2"><TrendingUp size={19}/>Organization Insights</h2><div className="grid md:grid-cols-3 gap-3 mt-4"><Insight text={`${uniqueSchools} unique college programs are represented across active player relationships.`}/><Insight text={`${activeOffers} active offers and ${committedPlayers} committed players are represented in the current Recruiting Journey.`}/><Insight text={`${insights.filter(r=>r.momentum==='Rising').length} coach relationships are currently gaining momentum.`}/></div></section></>}
 </div></AppShell>}

function Metric({icon,label,value,detail}:{icon:any;label:string;value:any;detail:string}){return <div className="card p-3.5 sm:p-4 min-w-0"><div className="flex justify-between gap-2"><span className="muted text-xs leading-tight">{label}</span>{icon}</div><div className="font-black text-2xl mt-2">{value}</div><div className="muted text-xs mt-1 break-words">{detail}</div></div>}
function Summary({label,value}:{label:string;value:any}){return <div className="border rounded-xl p-3 flex justify-between gap-3 text-sm"><span>{label}</span><b>{value}</b></div>}
function Insight({text}:{text:string}){return <div className="rounded-xl bg-slate-50 border p-4 text-sm break-words">{text}</div>}
function Empty({text}:{text:string}){return <div className="py-6 text-center muted text-sm">{text}</div>}
