'use client';
import {useEffect,useState} from 'react';
import AppShell from '@/components/AppShell';
import {createClient} from '@/lib/supabase-browser';
import {Check,Shield,UserRound,X} from 'lucide-react';

type Row={id:string;parent_user_id:string;status:string;permissions:any;profile?:any};
const defaults={view_discovery:true,view_connections:true,view_activity:true,view_events:true,view_fit:true,view_progress:true,view_videos:true,view_game_plan:true,manage_calendar:false};
const labels:[keyof typeof defaults,string][]=[['view_discovery','Discovery'],['view_connections','Connections'],['view_activity','Activity'],['view_events','Events'],['view_fit','College Fit'],['view_progress','Recruiting Progress'],['view_videos','Videos'],['view_game_plan','Game Plan'],['manage_calendar','Manage Calendar']];
export default function FamilyAccess(){const c=createClient();const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
 async function load(){const {data:{user}}=await c.auth.getUser();if(!user){setLoading(false);return}const {data}=await c.from('parent_guardian_access').select('id,parent_user_id,status,permissions').eq('athlete_user_id',user.id).order('created_at',{ascending:false});const base=(data||[]) as Row[];const ids=base.map(x=>x.parent_user_id);let profiles:any[]=[];if(ids.length){const {data:p}=await c.from('profiles').select('id,full_name,email').in('id',ids);profiles=p||[]}const pm=new Map(profiles.map(p=>[p.id,p]));setRows(base.map(x=>({...x,profile:pm.get(x.parent_user_id)||null})));setLoading(false)}
 useEffect(()=>{load()},[]);
 async function setStatus(id:string,status:string){setBusy(id);await c.from('parent_guardian_access').update({status,updated_at:new Date().toISOString()}).eq('id',id);await load();setBusy('')}
 async function toggle(row:Row,key:keyof typeof defaults){const next={...defaults,...(row.permissions||{}),[key]:!({...defaults,...(row.permissions||{})} as any)[key]};setBusy(row.id);await c.from('parent_guardian_access').update({permissions:next,updated_at:new Date().toISOString()}).eq('id',row.id);await load();setBusy('')}
 return <AppShell><div className="max-w-4xl mx-auto px-5 md:px-8 py-7"><div><div className="text-xs uppercase tracking-[.16em] font-black text-red-600">Privacy + access</div><h1 className="text-3xl font-black mt-1">Family Access</h1><p className="muted mt-2 max-w-2xl">You stay in control. Approve a parent or guardian, then choose exactly what they can see in Rebels Recruit.</p></div>{loading?<div className="card p-8 mt-6 text-center muted">Loading...</div>:rows.length===0?<div className="card p-8 mt-6 text-center"><UserRound size={34} className="mx-auto text-slate-400"/><h2 className="font-black text-xl mt-4">No family access requests yet</h2><p className="muted mt-2">A parent or guardian can create a Parent account and request access using the email address on your athlete account.</p></div>:<div className="space-y-4 mt-6">{rows.map(row=>{const p=row.profile;const perms={...defaults,...(row.permissions||{})};return <div key={row.id} className="card p-5"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><div className="font-black text-lg">{p?.full_name||'Parent / Guardian'}</div><div className="text-sm text-slate-500 mt-1">{p?.email||'Email unavailable'} · {row.status}</div></div>{row.status==='pending'?<div className="flex gap-2"><button className="btn btn-red" disabled={busy===row.id} onClick={()=>setStatus(row.id,'active')}><Check size={15}/> Approve</button><button className="btn" disabled={busy===row.id} onClick={()=>setStatus(row.id,'declined')}><X size={15}/> Decline</button></div>:row.status==='active'?<button className="btn" disabled={busy===row.id} onClick={()=>setStatus(row.id,'revoked')}>Revoke access</button>:<button className="btn" disabled={busy===row.id} onClick={()=>setStatus(row.id,'active')}>Restore access</button>}</div>{row.status==='active'&&<div className="mt-5 border-t pt-4"><div className="flex items-center gap-2 font-black text-sm"><Shield size={16}/> What they can access</div><div className="grid sm:grid-cols-2 gap-2 mt-3">{labels.map(([key,label])=><label key={key} className="flex items-center justify-between gap-4 rounded-xl border px-3 py-2.5"><span className="text-sm font-semibold">{label}</span><input type="checkbox" checked={!!perms[key]} disabled={busy===row.id} onChange={()=>toggle(row,key)}/></label>)}</div><p className="muted text-xs mt-3">Parent access is view-only unless you explicitly enable a management permission such as calendar access.</p></div>}</div>})}</div>}</div></AppShell>}
