'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {CheckCircle2,Circle,Target} from 'lucide-react';
import AppShell from '@/components/AppShell';
import {createClient} from '@/lib/supabase-browser';
const DEFAULT_GOALS=['Add 5 new schools that fit my profile','Research 3 new programs','Contact 4 new coaches','Follow up with 3 existing relationships','Attend or plan 1 recruiting event','Review my College Fit Profile'];
export default function GamePlan(){const c=createClient();const [uid,setUid]=useState(''),[profile,setProfile]=useState<any>(null),[fit,setFit]=useState<any>(null),[connections,setConnections]=useState(0),[interactions,setInteractions]=useState(0),[events,setEvents]=useState(0),[goals,setGoals]=useState<any[]>([]),[saved,setSaved]=useState('');
useEffect(()=>{(async()=>{const {data:{user}}=await c.auth.getUser();if(!user)return;setUid(user.id);const [p,f,co,i,e,g]=await Promise.all([c.from('athlete_profiles').select('*').eq('user_id',user.id).maybeSingle(),c.from('college_fit_profiles').select('*').eq('user_id',user.id).maybeSingle(),c.from('athlete_colleges').select('id',{count:'exact',head:true}).eq('athlete_user_id',user.id).is('archived_at',null),c.from('interactions').select('id',{count:'exact',head:true}).eq('athlete_user_id',user.id),c.from('athlete_events').select('id',{count:'exact',head:true}).eq('athlete_user_id',user.id).eq('status','going'),c.from('recruiting_game_plans').select('*').eq('athlete_user_id',user.id).order('period_start',{ascending:false}).limit(1).maybeSingle()]);setProfile(p.data);setFit(f.data);setConnections(co.count||0);setInteractions(i.count||0);setEvents(e.count||0);setGoals(g.data?.goals?.length?g.data.goals:DEFAULT_GOALS.map(title=>({title,done:false})))})()},[]);
const checks=useMemo(()=>[{label:'Athlete profile complete',ok:!!profile?.school_name&&!!profile?.class_year&&!!profile?.positions?.length},{label:'Home ZIP added',ok:!!profile?.home_zip},{label:'Academic interests added',ok:!!profile?.interested_majors?.length},{label:'College Fit Profile complete',ok:!!fit?.completed_at},{label:'At least 5 active Connections',ok:connections>=5},{label:'Recruiting activity started',ok:interactions>0},{label:'Recruiting event planned',ok:events>0}], [profile,fit,connections,interactions,events]);const score=Math.round(checks.filter(x=>x.ok).length/checks.length*100);
async function save(){if(!uid)return;const now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),1),end=new Date(now.getFullYear(),now.getMonth()+1,0);const {error}=await c.from('recruiting_game_plans').upsert({athlete_user_id:uid,period_start:start.toISOString().slice(0,10),period_end:end.toISOString().slice(0,10),goals,updated_at:new Date().toISOString()},{onConflict:'athlete_user_id,period_start'});setSaved(error?error.message:'Saved')}
return <AppShell><div className="max-w-6xl mx-auto px-4 sm:px-5 md:px-8 py-6 sm:py-8"><div className="flex flex-col sm:flex-row sm:justify-between gap-4 sm:items-start"><div><h1 className="text-2xl sm:text-3xl font-black">My Recruiting Game Plan</h1><p className="muted mt-1">Know whether you are ready, then focus on the work that moves recruiting forward.</p></div><Link href="/discover" className="btn self-start">Discover Schools</Link></div><div className="grid lg:grid-cols-[.8fr_1.2fr] gap-5 sm:gap-6 mt-6 sm:mt-7"><section className="card p-4 sm:p-6"><div className="flex items-center justify-between"><div><div className="text-sm font-black uppercase tracking-wider text-slate-500">Recruiting Readiness</div><div className="text-4xl sm:text-5xl font-black mt-2">{score}%</div></div><Target size={34}/></div><div className="space-y-3 mt-6">{checks.map(x=><div key={x.label} className="flex gap-3 items-center">{x.ok?<CheckCircle2 size={19} className="text-red-600 shrink-0"/>:<Circle size={19} className="text-slate-300 shrink-0"/>}<span className={x.ok?'font-semibold':'text-slate-600'}>{x.label}</span></div>)}</div><div className="mt-6 flex gap-2 flex-wrap"><Link href="/profile" className="btn">Update Profile</Link><Link href="/fit-profile" className="btn">College Fit</Link></div></section><section className="card p-4 sm:p-6"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><div className="text-sm font-black uppercase tracking-wider text-red-600">This Month</div><h2 className="text-xl sm:text-2xl font-black mt-1">Recruiting priorities</h2></div><button className="btn btn-red self-start sm:self-auto" onClick={save}>Save Plan</button></div>{saved&&<div className={`text-sm font-bold mt-2 ${saved==='Saved'?'text-green-700':'text-red-600'}`}>{saved}</div>}<div className="space-y-3 mt-5">{goals.map((g,i)=><label key={i} className="flex items-start gap-3 rounded-xl border p-3 sm:p-4 cursor-pointer"><input type="checkbox" className="mt-1 shrink-0" checked={!!g.done} onChange={()=>setGoals(v=>v.map((x,j)=>j===i?{...x,done:!x.done}:x))}/><input className={`w-full min-w-0 bg-transparent outline-none font-semibold ${g.done?'line-through text-slate-400':''}`} value={g.title} onChange={e=>setGoals(v=>v.map((x,j)=>j===i?{...x,title:e.target.value}:x))}/></label>)}</div><button className="text-sm font-bold mt-4 min-h-11" onClick={()=>setGoals(v=>[...v,{title:'New recruiting goal',done:false}])}>+ Add goal</button></section></div></div></AppShell>}
