'use client';
import {useEffect,useState} from 'react';
import {useParams} from 'next/navigation';
import Link from 'next/link';
import AppShell from '@/components/AppShell';
import CollegeSearchSelect from '@/components/CollegeSearchSelect';
import {createClient} from '@/lib/supabase-browser';

export default function SuggestCoachUpdate(){
 const {id}=useParams<{id:string}>(); const c=createClient();
 const [firstName,setFirstName]=useState(''),[lastName,setLastName]=useState(''); const [coach,setCoach]=useState<any>(null),[type,setType]=useState('incorrect_info'),[details,setDetails]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[title,setTitle]=useState(''),[x,setX]=useState(''),[collegeId,setCollegeId]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 useEffect(()=>{(async()=>{const {data}=await c.from('college_coaches').select('id,first_name,last_name,title,email,phone,x_url,college_id,colleges(name)').eq('id',id).maybeSingle();setCoach(data)})()},[id]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg('');const {data:{user}}=await c.auth.getUser();if(!user){setMsg('Please sign in and try again.');setBusy(false);return}const {error}=await c.from('college_coach_update_suggestions').insert({coach_id:id,submitted_by_user_id:user.id,suggestion_type:type,details:details.trim()||null,proposed_first_name:firstName.trim()||null,proposed_last_name:lastName.trim()||null,proposed_email:email.trim()||null,proposed_phone:phone.trim()||null,proposed_title:title.trim()||null,proposed_x_url:x.trim()||null,proposed_college_id:type==='moved_school'&&collegeId?collegeId:null});if(error)setMsg(error.message);else setMsg('Thanks. RLTNL will verify this update before changing the shared coach record.');setBusy(false)}
 const name=coach?[coach.first_name,coach.last_name].filter(Boolean).join(' '):'Coach';
 return <AppShell><div className="max-w-xl mx-auto px-5 md:px-8 py-8"><Link href={`/coaches/${id}`} className="text-sm font-bold">← Back to Coach</Link><div className="card p-6 mt-5"><h1 className="text-2xl font-black">Suggest an Update</h1><p className="muted mt-1">Help RLTNL keep {name}'s shared coach record accurate. We verify suggestions before changing information for everyone.</p><form onSubmit={submit} className="space-y-4 mt-7"><div><label className="text-sm font-bold">What changed?</label><select className="input mt-1" value={type} onChange={e=>setType(e.target.value)}><option value="incorrect_info">Information is incorrect</option><option value="contact_update">Email, phone or X changed</option><option value="title_update">Title changed</option><option value="left_program">Coach left this program</option><option value="moved_school">Coach moved to another school</option><option value="retired">Coach retired</option><option value="other">Other</option></select></div>{type==='moved_school'&&<div><label className="text-sm font-bold">New school</label><CollegeSearchSelect value={collegeId} onChange={setCollegeId} allowNone placeholder="Search for the new school..."/></div>}{type==='incorrect_info'&&<><input className="input" placeholder="Correct first name (if known)" value={firstName} onChange={e=>setFirstName(e.target.value)}/><input className="input" placeholder="Correct last name (if known)" value={lastName} onChange={e=>setLastName(e.target.value)}/></>}{['contact_update','incorrect_info'].includes(type)&&<><input className="input" type="email" placeholder="Correct email (if known)" value={email} onChange={e=>setEmail(e.target.value)}/><input className="input" placeholder="Correct phone (if known)" value={phone} onChange={e=>setPhone(e.target.value)}/><input className="input" placeholder="Official-page X/Twitter URL (if listed)" value={x} onChange={e=>setX(e.target.value)}/></>}{['title_update','incorrect_info'].includes(type)&&<input className="input" placeholder="Correct title (if known)" value={title} onChange={e=>setTitle(e.target.value)}/>}<textarea className="input min-h-28" placeholder="What should RLTNL know? Add any context that can help us verify the change." value={details} onChange={e=>setDetails(e.target.value)} required={['left_program','retired','other'].includes(type)}/>{msg&&<p className={`text-sm ${msg.startsWith('Thanks')?'text-green-700':'text-red-600'}`}>{msg}</p>}<button className="btn btn-red w-full" disabled={busy}>{busy?'Submitting...':'Submit Update for Verification'}</button></form></div></div></AppShell>
}