'use client';
import {useEffect,useState} from 'react';
import {createClient} from '@/lib/supabase-browser';
import {Check,Shield,UserRound,X,AlertTriangle} from 'lucide-react';

type Row={id:string;parent_user_id:string;status:string;permissions:any;profile?:any};
const defaults={view_discovery:true,view_connections:true,view_activity:true,view_events:true,view_fit:true,view_progress:true,view_videos:true,view_game_plan:true,manage_calendar:false,manage_history_import:false};
const labels:[keyof typeof defaults,string][]=[['view_discovery','Discovery'],['view_connections','Connections'],['view_activity','Journey / Activity'],['view_events','Events'],['view_fit','School Fit'],['view_progress','Recruiting Progress'],['view_videos','Videos'],['view_game_plan','Game Plan'],['manage_calendar','Manage Calendar'],['manage_history_import','Import Recruiting History']];

export default function FamilyAccessSection(){const c=createClient();const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[partial,setPartial]=useState('');
 async function load(){setLoading(true);setError('');setPartial('');const {data:{user},error:authError}=await c.auth.getUser();if(authError||!user){setError('We could not verify your account, so family access cannot be shown right now.');setLoading(false);return}const {data,error:dataError}=await c.from('parent_guardian_access').select('id,parent_user_id,status,permissions').eq('athlete_user_id',user.id).order('created_at',{ascending:false});if(dataError){setError('We could not load family access. No permissions were changed. Please try again.');setLoading(false);return}const base=(data||[]) as Row[];const ids=base.map(x=>x.parent_user_id);let profiles:any[]=[];if(ids.length){const {data:p,error:profileError}=await c.from('profiles').select('id,full_name,email').in('id',ids);profiles=p||[];if(profileError)setPartial('Family permissions loaded, but some names or email addresses are temporarily unavailable.')}const pm=new Map(profiles.map(p=>[p.id,p]));setRows(base.map(x=>({...x,profile:pm.get(x.parent_user_id)||null})));setLoading(false)}
 useEffect(()=>{load()},[]);
 async function setStatus(id:string,status:string){setBusy(id);setError('');const {error}=await c.from('parent_guardian_access').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error){setError('We could not change this person’s access. Their current permissions are unchanged.');setBusy('');return}await load();setBusy('')}
 async function toggle(row:Row,key:keyof typeof defaults){const next={...defaults,...(row.permissions||{}),[key]:!({...defaults,...(row.permissions||{})} as any)[key]};setBusy(row.id);setError('');const {error}=await c.from('parent_guardian_access').update({permissions:next,updated_at:new Date().toISOString()}).eq('id',row.id);if(error){setError('We could not save that permission change. The previous permission is still in effect.');setBusy('');return}await load();setBusy('')}
 if(loading)return <div className="card p-8 text-center muted">Loading family access...</div>;
 if(error&&rows.length===0)return <div className="card p-6 border-amber-200 bg-amber-50"><div className="font-black flex items-center gap-2"><AlertTriangle size={18}/>Family access is unavailable</div><p className="text-sm mt-2">{error}</p><button className="btn mt-4" onClick={load}>Try Again</button></div>;
 if(rows.length===0)return <div className="card p-8 text-center"><UserRound size={34} className="mx-auto text-slate-400"/><h3 className="font-black text-lg mt-4">No family access requests</h3><p className="muted text-sm mt-2">A parent or guardian can create a Parent account and request access using the email address on your athlete account.</p></div>;
 return <div className="space-y-4">{partial&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-semibold">{partial}</div>}{error&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-semibold">{error}</div>}{rows.map(row=>{const p=row.profile;const perms={...defaults,...(row.permissions||{})};return <div key={row.id} className="card p-5"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><div className="font-black text-lg">{p?.full_name||'Parent / Guardian'}</div><div className="text-sm text-slate-500 mt-1">{p?.email||'Email temporarily unavailable'} · {row.status}</div></div>{row.status==='pending'?<div className="flex gap-2"><button className="btn btn-red" disabled={busy===row.id} onClick={()=>setStatus(row.id,'active')}><Check size={15}/> Approve Access</button><button className="btn" disabled={busy===row.id} onClick={()=>setStatus(row.id,'declined')}><X size={15}/> Decline Access</button></div>:row.status==='active'?<button className="btn" disabled={busy===row.id} onClick={()=>setStatus(row.id,'revoked')}>Revoke Access</button>:<button className="btn" disabled={busy===row.id} onClick={()=>setStatus(row.id,'active')}>Restore Access</button>}</div>{row.status==='active'&&<div className="mt-5 border-t pt-4"><div className="flex items-center gap-2 font-black text-sm"><Shield size={16}/> What they can access</div><div className="grid sm:grid-cols-2 gap-2 mt-3">{labels.map(([key,label])=><label key={key} className="flex items-center justify-between gap-4 rounded-xl border px-3 py-2.5"><span className="text-sm font-semibold">{label}</span><input type="checkbox" checked={!!perms[key]} disabled={busy===row.id} onChange={()=>toggle(row,key)}/></label>)}</div><p className="muted text-xs mt-3">Parent access is view-only unless you explicitly enable a management permission such as calendar access or recruiting-history import.</p></div>}</div>})}</div>}
