'use client';
import {useEffect,useState} from 'react';
import {useParams} from 'next/navigation';
import AppShell from '@/components/AppShell';
import {createClient} from '@/lib/supabase-browser';

const types=['Email Sent','Email Received','Text','Phone Call','Video Call','X/Twitter DM','Instagram DM','Coach Followed Me','Coach Liked Post','Coach Commented','Questionnaire','College Camp','Campus Visit','Tournament Interaction','Coach Watched Game','Coach Contacted Me','Thank You Message','Other'];

export default function EditInteraction(){
 const {id}=useParams<{id:string}>();const c=createClient();const [colleges,setColleges]=useState<any[]>([]);const [coaches,setCoaches]=useState<any[]>([]);const [college,setCollege]=useState('');const [coach,setCoach]=useState('');const [type,setType]=useState('');const [initiated,setInitiated]=useState('');const [note,setNote]=useState('');const [date,setDate]=useState('');const [followUp,setFollowUp]=useState('');const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');
 useEffect(()=>{(async()=>{const {data:{user}}=await c.auth.getUser();if(!user){setLoading(false);return}const [{data:interaction},{data:collegeRows},{data:reminder}]=await Promise.all([c.from('interactions').select('id,college_id,coach_id,type,initiated_by,date,note').eq('id',id).eq('athlete_user_id',user.id).single(),c.from('athlete_colleges').select('college_id,colleges(id,name)').eq('athlete_user_id',user.id),c.from('reminders').select('id,due_date,status').eq('interaction_id',id).eq('athlete_user_id',user.id).neq('status','completed').maybeSingle()]);setColleges((collegeRows||[]).map((x:any)=>x.colleges));if(interaction){setCollege(interaction.college_id||'');setCoach(interaction.coach_id||'');setType(interaction.type||'');setInitiated(interaction.initiated_by||'');setDate(interaction.date||'');setNote(interaction.note||'');}if(reminder?.due_date)setFollowUp(reminder.due_date);setLoading(false)})()},[id]);
 useEffect(()=>{if(!college){setCoaches([]);return}c.from('college_coaches').select('id,first_name,last_name,title').eq('college_id',college).order('last_name').then(({data})=>setCoaches(data||[]))},[college]);
 async function save(e:React.FormEvent){e.preventDefault();setMessage('');const {data:{user}}=await c.auth.getUser();if(!user){setMessage('Your session has expired.');return}const {error}=await c.from('interactions').update({college_id:college,coach_id:coach||null,type,initiated_by:initiated,date,note:note.trim()||null}).eq('id',id).eq('athlete_user_id',user.id);if(error){setMessage(error.message);return}const {data:existing}=await c.from('reminders').select('id,status').eq('interaction_id',id).eq('athlete_user_id',user.id).neq('status','completed').maybeSingle();if(followUp){if(existing){await c.from('reminders').update({college_id:college,coach_id:coach||null,title:`Follow up after ${type.toLowerCase()}`,due_date:followUp}).eq('id',existing.id)}else{await c.from('reminders').insert({owner_user_id:user.id,athlete_user_id:user.id,college_id:college,coach_id:coach||null,interaction_id:id,title:`Follow up after ${type.toLowerCase()}`,due_date:followUp})}}else if(existing){await c.from('reminders').delete().eq('id',existing.id)}location.href=`/activity/${id}`}
 if(loading)return <AppShell><div className="max-w-2xl mx-auto px-5 py-8"><div className="card p-8 muted">Loading interaction...</div></div></AppShell>;
 return <AppShell><div className="max-w-2xl mx-auto px-5 md:px-8 py-8"><div className="card p-6"><h1 className="text-2xl font-black">Edit Interaction</h1><p className="muted mt-1">Changes are reflected everywhere this interaction appears.</p><form onSubmit={save} className="space-y-5 mt-7"><label className="block"><span className="text-sm font-bold">College</span><select className="input mt-1" value={college} onChange={e=>{setCollege(e.target.value);setCoach('')}} required><option value="">Choose a college</option>{colleges.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="block"><span className="text-sm font-bold">Coach</span><select className="input mt-1" value={coach} onChange={e=>setCoach(e.target.value)} disabled={!college}><option value="">Select a coach</option>{coaches.map(c=><option key={c.id} value={c.id}>{c.first_name} {c.last_name}{c.title?` · ${c.title}`:''}</option>)}</select></label><label className="block"><span className="text-sm font-bold">What happened?</span><select className="input mt-1" value={type} onChange={e=>setType(e.target.value)}>{types.map(t=><option key={t}>{t}</option>)}</select></label><label className="block"><span className="text-sm font-bold">Who initiated it?</span><select className="input mt-1" value={initiated} onChange={e=>setInitiated(e.target.value)}><option>Athlete</option><option>Coach</option><option>Advisor</option><option>Other</option></select></label><label className="block"><span className="text-sm font-bold">Date</span><input className="input mt-1" type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label className="block"><span className="text-sm font-bold">Short note</span><textarea className="input mt-1 min-h-24" value={note} onChange={e=>setNote(e.target.value)}/></label><label className="block"><span className="text-sm font-bold">Follow-up due date</span><input className="input mt-1" type="date" value={followUp} onChange={e=>setFollowUp(e.target.value)}/><div className="muted text-xs mt-1">Leave blank to remove the open follow-up tied to this interaction.</div></label>{message&&<div className="text-sm text-red-600">{message}</div>}<div className="flex gap-2"><button type="button" className="btn flex-1" onClick={()=>location.href=`/activity/${id}`}>Cancel</button><button className="btn btn-red flex-1">Save changes</button></div></form></div></div></AppShell>
}
