'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useParams} from 'next/navigation';
import {ArrowLeft,CheckCircle2,Mail,MessageSquare,School} from 'lucide-react';
import AppShell from '@/components/AppShell';
import PageHeader from '@/components/PageHeader';
import CoachActionBar from '@/components/CoachActionBar';
import EventWorkflowPanel from '@/components/EventWorkflowPanel';
import {createClient} from '@/lib/supabase-browser';

const one=(v:any)=>Array.isArray(v)?v[0]:v;
const fmt=(d:any)=>d?new Date(`${String(d).slice(0,10)}T12:00:00`).toLocaleDateString('en-US',{month:'2-digit',day:'2-digit',year:'numeric'}):'Date not set';

export default function EventPrep(){
 const{id}=useParams<{id:string}>(),c=createClient();
 const[event,setEvent]=useState<any>(null),[history,setHistory]=useState<any[]>([]),[coaches,setCoaches]=useState<any[]>([]),[debrief,setDebrief]=useState<any>(null),[eventReminders,setEventReminders]=useState<any[]>([]),[form,setForm]=useState({coaches_spoken_to:'',what_happened:'',interest_signal:'unclear',follow_up_needed:true,follow_up_notes:''}),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false),[saveMessage,setSaveMessage]=useState('');
 useEffect(()=>{(async()=>{const{data:{user}}=await c.auth.getUser();if(!user)return;const{data:e}=await c.from('events').select('*,colleges(id,name)').eq('id',id).single();setEvent(e);if(e?.college_id){const[{data:i},{data:cr}]=await Promise.all([c.from('interactions').select('id,type,date,note,initiated_by,college_coaches(first_name,last_name)').eq('athlete_user_id',user.id).eq('college_id',e.college_id).order('date',{ascending:false}).limit(8),c.from('athlete_coaches').select('coach_id,college_coaches(id,first_name,last_name,title,email,phone)').eq('athlete_user_id',user.id).eq('college_id',e.college_id)]);setHistory(i||[]);setCoaches((cr||[]).sort((a:any,b:any)=>{const ta=String(one(a.college_coaches)?.title||'').toLowerCase(),tb=String(one(b.college_coaches)?.title||'').toLowerCase(),rank=(t:string)=>/^head\s+coach\b/.test(t)?0:/associate\s+head/.test(t)?1:/assistant/.test(t)?3:2;return rank(ta)-rank(tb)}))}const[{data:d},{data:r}]=await Promise.all([c.from('event_debriefs').select('*').eq('athlete_user_id',user.id).eq('event_id',id).maybeSingle(),c.from('reminders').select('id,title,due_date,status,reminder_kind,event_id').eq('athlete_user_id',user.id).eq('event_id',id)]);setEventReminders(r||[]);if(d){setDebrief(d);setForm({coaches_spoken_to:d.coaches_spoken_to||'',what_happened:d.what_happened||'',interest_signal:d.interest_signal||'unclear',follow_up_needed:d.follow_up_needed,follow_up_notes:d.follow_up_notes||''})}})()},[id]);
 async function save(){const{data:{user}}=await c.auth.getUser();if(!user)return;setSaving(true);setSaved(false);setSaveMessage('');const now=new Date(),today=now.toISOString().slice(0,10);const {data:d,error}=await c.from('event_debriefs').upsert({athlete_user_id:user.id,event_id:id,...form,updated_at:new Date().toISOString()},{onConflict:'athlete_user_id,event_id'}).select('*').single();if(error){setSaveMessage(error.message);setSaving(false);return}if(event?.college_id&&form.what_happened.trim()&&!debrief){await c.from('interactions').insert({athlete_user_id:user.id,actor_user_id:user.id,college_id:event.college_id,type:'Event Debrief',initiated_by:'Athlete',date:today,date_precision:'exact',date_year:now.getFullYear(),date_month:now.getMonth()+1,note:`${event.name}: ${form.what_happened}${form.coaches_spoken_to?` Coaches spoken with: ${form.coaches_spoken_to}.`:''}${form.follow_up_notes?` Follow-up: ${form.follow_up_notes}`:''}`})}if(form.follow_up_needed){const existing=eventReminders.find((r:any)=>r.reminder_kind==='event_followup'&&r.status!=='completed');if(!existing){const due=new Date();due.setDate(due.getDate()+1);const{data:r}=await c.from('reminders').insert({owner_user_id:user.id,athlete_user_id:user.id,event_id:id,college_id:event?.college_id||null,title:`Follow up after ${event?.name||'recruiting event'}`,due_date:due.toISOString().slice(0,10),status:'open',reminder_kind:'event_followup'}).select('id,title,due_date,status,reminder_kind,event_id').single();if(r)setEventReminders(v=>[...v,r])}}const pre=eventReminders.filter((r:any)=>r.reminder_kind==='event_prearrival_email'&&r.status!=='completed');if(pre.length&&event?.date<=today)await c.from('reminders').update({status:'completed',completed_at:new Date().toISOString()}).in('id',pre.map((r:any)=>r.id));setDebrief(d);setSaved(true);setSaveMessage(form.follow_up_needed?'Debrief saved. A follow-up Next Step is ready for you.':'Debrief saved to your Journey.');setSaving(false)}
 if(!event)return <AppShell><div className="p-8 text-center muted">Loading Camp & Visit Prep...</div></AppShell>;
 const school=one(event.colleges),past=event.date<new Date().toISOString().slice(0,10),emailReminder=eventReminders.find((r:any)=>r.reminder_kind==='event_prearrival_email'||/email coaches before/i.test(r.title||''));
 return <AppShell><div className="max-w-5xl mx-auto px-4 sm:px-5 md:px-8 py-6"><Link href="/game-plan#camp-visit-prep" className="text-sm font-bold inline-flex items-center gap-2"><ArrowLeft size={16}/>Game Plan</Link><div className="mt-5"><PageHeader eyebrow="RECRUITING EVENT WORKFLOW" title={past?'Camp & Visit Debrief':'Camp & Visit Prep'} subtitle={`${event.name} · ${fmt(event.date)}${school?.name?` · ${school.name}`:''}`}/></div><EventWorkflowPanel event={event} emailReminder={emailReminder} debrief={debrief}/>
 {!past&&<section className="card p-5 mt-5 border-2 border-red-200 bg-red-50"><div className="flex items-start gap-3"><div className="h-10 w-10 rounded-xl bg-white border border-red-200 flex items-center justify-center shrink-0"><Mail size={19}/></div><div><div className="rr-eyebrow">HIGH-PRIORITY PREP STEP</div><h2 className="text-xl font-black">Email the coaches before you go</h2><p className="text-sm text-slate-700 mt-1 max-w-3xl">Let the staff know you will be at the camp or on campus. For most events, 2–5 days beforehand is a strong window. Marking an event <b>Going</b> automatically creates this Next Step.</p></div></div>{coaches.length>0?<div className="mt-4 space-y-3">{coaches.map((r:any,i)=>{const x=one(r.college_coaches),name=[x?.first_name,x?.last_name].filter(Boolean).join(' ')||'Coach';return <div key={x?.id||i} className="rounded-xl border bg-white p-4"><div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-2"><div><Link href={x?.id?`/coaches/${x.id}`:'#'} className="font-black hover:text-red-700">{name}</Link><div className="muted text-xs">{x?.title||'Coach'}{x?.email?` · ${x.email}`:''}</div></div><div className="text-xs font-bold text-red-700">Send before the event</div></div>{x?.id&&<div className="mt-3"><CoachActionBar coachId={x.id} collegeId={event.college_id} coachName={name} collegeName={school?.name} email={x.email} phone={x.phone} compact primaryAction="email" hideReminder initialEmailStarter="pre_camp"/></div>}</div>})}</div>:<div className="rounded-xl border bg-white p-4 mt-4"><div className="font-bold">No coach relationship is linked yet.</div><p className="muted text-sm mt-1">Add the coaching staff you expect to meet so you can contact them before the event.</p>{school?.id&&<Link href={`/colleges/${school.id}`} className="btn mt-3">Review School Playbook</Link>}</div>}</section>}
 <div className="grid lg:grid-cols-3 gap-5 mt-5"><section className="card p-5 lg:col-span-2"><div className="rr-eyebrow">EVENT CONTEXT</div><h2 className="font-black text-lg">Know the relationship before you arrive</h2><div className="grid sm:grid-cols-2 gap-3 mt-4">{['Review your last conversation','Know who you want to speak with','Prepare 3 questions','Have an updated video ready'].map(x=><div key={x} className="border rounded-xl p-3 flex gap-2 text-sm font-semibold"><CheckCircle2 size={17}/>{x}</div>)}</div>{coaches.length>0&&<><h3 className="font-black mt-6">Coaches you already track</h3><div className="mt-3 space-y-2">{coaches.map((r:any,i)=>{const x=one(r.college_coaches);return <Link href={x?.id?`/coaches/${x.id}`:'#'} key={i} className="block border rounded-xl p-3 hover:bg-slate-50"><b>{x?.first_name} {x?.last_name}</b><div className="muted text-xs">{x?.title||'Coach'}{x?.email?` · ${x.email}`:''}</div></Link>})}</div></>}</section><section className="card p-5"><div className="rr-eyebrow">RELATIONSHIP CONTEXT</div><div className="text-3xl font-black">{history.length}</div><div className="muted text-sm">recent recorded interactions</div>{school?.id&&<Link href={`/colleges/${school.id}`} className="btn w-full mt-5"><School size={16}/>Open Playbook</Link>}</section></div>
 <section className="card p-5 mt-5"><div className="rr-eyebrow">AFTER THE EVENT</div><h2 className="font-black text-xl">Capture what happened, then close the loop</h2><p className="muted text-sm mt-1">Your first saved debrief adds an dated Journey entry. If follow-up is needed, Rebels Recruit creates a Next Step for the next day instead of leaving the event as a dead-end calendar item.</p><div className="grid sm:grid-cols-2 gap-4 mt-5"><label className="text-sm font-bold">Coaches you spoke with<input className="input w-full mt-1" value={form.coaches_spoken_to} onChange={e=>setForm({...form,coaches_spoken_to:e.target.value})}/></label><label className="text-sm font-bold">Interest signal<select className="input w-full mt-1" value={form.interest_signal} onChange={e=>setForm({...form,interest_signal:e.target.value})}><option value="strong">Strong</option><option value="positive">Positive</option><option value="neutral">Neutral</option><option value="unclear">Unclear</option><option value="negative">Negative</option></select></label></div><label className="text-sm font-bold block mt-4">What happened?<textarea className="input w-full mt-1 min-h-28" value={form.what_happened} onChange={e=>setForm({...form,what_happened:e.target.value})}/></label><label className="flex items-center gap-2 text-sm font-bold mt-4"><input type="checkbox" checked={form.follow_up_needed} onChange={e=>setForm({...form,follow_up_needed:e.target.checked})}/>Follow-up needed</label>{form.follow_up_needed&&<label className="text-sm font-bold block mt-3">Follow-up plan<input className="input w-full mt-1" value={form.follow_up_notes} onChange={e=>setForm({...form,follow_up_notes:e.target.value})} placeholder="Thank coach, send video, answer a question..."/></label>}<div className="flex flex-col sm:flex-row sm:items-center gap-3 mt-5"><button onClick={save} disabled={saving} className="btn btn-red"><MessageSquare size={17}/>{saving?'Saving...':'Save Debrief & Next Step'}</button>{saveMessage&&<span className={`text-sm font-bold ${saved?'text-slate-700':'text-red-700'}`}>{saveMessage}</span>}</div></section></div></AppShell>
}
