'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowRight,BarChart3,Clock3,MessageCircleMore,RefreshCw,Sparkles,TrendingDown,TrendingUp,Users} from 'lucide-react';
import AppShell from '@/components/AppShell';
import PageHeader from '@/components/PageHeader';
import {createClient} from '@/lib/supabase-browser';
import {athleteEngagementScore,buildRelationshipInsights,cadenceLabel,daysSince,isMeaningfulContact,scoreLabel} from '@/lib/communication-intelligence';

type Profile={id:string;full_name?:string|null;email?:string|null};
export default function CommunicationIntelligence(){const c=createClient();const [loading,setLoading]=useState(true),[role,setRole]=useState('athlete'),[viewerId,setViewerId]=useState(''),[profiles,setProfiles]=useState<Profile[]>([]),[relationships,setRelationships]=useState<any[]>([]),[interactions,setInteractions]=useState<any[]>([]),[reminders,setReminders]=useState<any[]>([]),[colleges,setColleges]=useState<any[]>([]),[selectedAthlete,setSelectedAthlete]=useState('');
 async function load(){setLoading(true);const {data:{user}}=await c.auth.getUser();if(!user){setLoading(false);return}setViewerId(user.id);const {data:p}=await c.from('profiles').select('app_role').eq('id',user.id).single();const appRole=p?.app_role||'athlete';setRole(appRole);let athleteIds:string[]=[user.id];if(appRole!=='athlete'){const {data:m}=await c.from('organization_members').select('organization_id,role,organization_view_access').eq('user_id',user.id).eq('status','active').maybeSingle();if(m){if(m.role==='owner'||m.role==='admin'||m.organization_view_access){const {data:ms}=await c.from('organization_members').select('user_id,role').eq('organization_id',m.organization_id).eq('status','active');athleteIds=(ms||[]).filter((x:any)=>x.role==='athlete').map((x:any)=>x.user_id)}else{const {data:a}=await c.from('athlete_advisor_assignments').select('athlete_user_id').eq('advisor_user_id',user.id).eq('status','active');athleteIds=(a||[]).map((x:any)=>x.athlete_user_id)}}}
 athleteIds=[...new Set(athleteIds)];if(!athleteIds.length){setProfiles([]);setLoading(false);return}const [ps,rs,ints,rems,acs]=await Promise.all([c.from('profiles').select('id,full_name,email').in('id',athleteIds),c.from('athlete_coaches').select('id,athlete_user_id,coach_id,college_id,last_contact_date,next_step,colleges(name),college_coaches(first_name,last_name,title)').in('athlete_user_id',athleteIds),c.from('interactions').select('id,athlete_user_id,coach_id,college_id,type,date,created_at,note,initiated_by,colleges(name),college_coaches(first_name,last_name,title)').in('athlete_user_id',athleteIds).order('date',{ascending:false}).order('created_at',{ascending:false}).limit(4000),c.from('reminders').select('id,athlete_user_id,coach_id,college_id,title,due_date,status').in('athlete_user_id',athleteIds),c.from('athlete_colleges').select('id,athlete_user_id,college_id,status,colleges(name)').in('athlete_user_id',athleteIds)]);setProfiles(ps.data||[]);setRelationships(rs.data||[]);setInteractions(ints.data||[]);setReminders(rems.data||[]);setColleges(acs.data||[]);if(appRole!=='athlete'&&!selectedAthlete)setSelectedAthlete('all');setLoading(false)}
 useEffect(()=>{load()},[]);
 const insights=useMemo(()=>buildRelationshipInsights(relationships,interactions),[relationships,interactions]);const pm=useMemo(()=>new Map(profiles.map(p=>[p.id,p])),[profiles]);const visibleInsights=selectedAthlete&&selectedAthlete!=='all'?insights.filter(x=>x.athleteUserId===selectedAthlete):insights;const visibleInts=selectedAthlete&&selectedAthlete!=='all'?interactions.filter(x=>x.athlete_user_id===selectedAthlete):interactions;
 const athleteRows=useMemo(()=>profiles.map(p=>{const rs=insights.filter(r=>r.athleteUserId===p.id);const ints=interactions.filter(i=>i.athlete_user_id===p.id);const rem=reminders.filter(r=>r.athlete_user_id===p.id);const score=athleteEngagementScore(p.id,insights,interactions,reminders);const last=ints[0]?.date||ints[0]?.created_at||null;const overdue=rem.filter(r=>['open','overdue','snoozed'].includes(String(r.status||'').toLowerCase())&&r.due_date&&r.due_date<new Date().toISOString().slice(0,10)).length;return{id:p.id,name:p.full_name||p.email||'Athlete',score,lastActivity:last,stale:daysSince(last)>=14,overdue,relationships:rs.length,meaningful30:ints.filter(i=>daysSince(i.date||i.created_at)<=30&&isMeaningfulContact(i)).length,rising:rs.filter(r=>r.momentum==='Rising').length,cooling:rs.filter(r=>r.momentum==='Cooling').length}}).sort((a,b)=>a.score-b.score),[profiles,insights,interactions,reminders]);
 const currentId=role==='athlete'?viewerId:(selectedAthlete&&selectedAthlete!=='all'?selectedAthlete:'');const currentScore=currentId?athleteEngagementScore(currentId,insights,interactions,reminders):Math.round(athleteRows.reduce((n,p)=>n+p.score,0)/Math.max(1,athleteRows.length));const meaningful30=visibleInts.filter(i=>daysSince(i.date||i.created_at)<=30&&isMeaningfulContact(i)).length;const stale14=visibleInsights.filter(r=>r.daysSinceContact>=14).length;const rising=visibleInsights.filter(r=>r.momentum==='Rising').length;const cooling=visibleInsights.filter(r=>r.momentum==='Cooling').length;
 const alerts=athleteRows.filter(p=>p.stale||p.overdue||p.score<35).slice(0,8);const recommendations=visibleInsights.slice().sort((a,b)=>{const aw=a.daysSinceContact>=14?100:100-a.score;const bw=b.daysSinceContact>=14?100:100-b.score;return bw-aw}).slice(0,8);
 if(loading)return <AppShell><div className="max-w-7xl mx-auto p-8"><div className="card p-10 text-center muted">Analyzing recruiting communication...</div></div></AppShell>;
 return <AppShell><div className="max-w-7xl mx-auto px-5 md:px-8 py-6"><PageHeader title="Communication Intelligence" subtitle="Turn logged recruiting activity into relationship signals, cadence guidance and next actions." action={<button className="btn" onClick={load}><RefreshCw size={17}/> Refresh</button>}/>
 {role!=='athlete'&&<div className="card p-4 mb-5 flex flex-col md:flex-row gap-3 md:items-center"><div className="flex-1"><div className="font-bold">View</div><div className="muted text-sm">Organization-wide or drill into one athlete.</div></div><select className="input md:w-72" value={selectedAthlete||'all'} onChange={e=>setSelectedAthlete(e.target.value)}><option value="all">All accessible athletes</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.full_name||p.email||'Athlete'}</option>)}</select></div>}
 <div className="grid grid-cols-2 lg:grid-cols-5 gap-3"><Metric label={role==='athlete'?'Recruiting engagement':'Avg. engagement'} value={currentScore} detail={`${scoreLabel(currentScore)} / 100`}/><Metric label="Meaningful contacts" value={meaningful30} detail="last 30 days"/><Metric label="14+ day gaps" value={stale14} detail="coach relationships"/><Metric label="Rising" value={rising} detail="relationship momentum"/><Metric label="Cooling" value={cooling} detail="needs attention"/></div>
 <div className="grid lg:grid-cols-3 gap-6 mt-6"><section className="card p-5 lg:col-span-2"><div className="flex items-center gap-2"><Sparkles size={19}/><div><h2 className="font-black text-lg">Suggested Next Actions</h2><p className="muted text-sm">Recommendations derived from cadence, recency and logged response signals.</p></div></div><div className="mt-4 space-y-3">{recommendations.length?recommendations.map(r=><Link key={r.id} href={r.coachId?`/coaches/${r.coachId}`:'/colleges'} className="border rounded-xl p-4 flex gap-3 items-center hover:bg-slate-50"><div className={`h-10 w-10 rounded-xl flex items-center justify-center ${r.daysSinceContact>=14?'bg-amber-50':'bg-slate-50'}`}>{r.momentum==='Rising'?<TrendingUp size={18}/>:r.momentum==='Cooling'?<TrendingDown size={18}/>:<Clock3 size={18}/>}</div><div className="flex-1 min-w-0"><div className="font-bold">{r.nextAction}</div><div className="muted text-sm mt-1">{r.coach} · {r.college} · {r.daysSinceContact===999?'No contact logged':`${r.daysSinceContact} days since contact`}</div></div><ArrowRight size={17}/></Link>):<Empty text="Add coach relationships and log interactions to generate recommendations."/>}</div></section>
 <section className="card p-5"><div className="flex items-center gap-2"><MessageCircleMore size={19}/><h2 className="font-black text-lg">Response Intelligence</h2></div><p className="muted text-sm mt-1">Signals from manually logged interactions.</p><div className="mt-4 space-y-3">{visibleInsights.slice().sort((a,b)=>b.score-a.score).slice(0,6).map(r=><div key={r.id} className="border rounded-xl p-3"><div className="flex justify-between gap-2"><b>{r.coach}</b><span className="text-xs font-bold">{r.score}/100</span></div><div className="muted text-xs mt-1">{r.college}</div><div className="text-sm mt-2">{r.responseSignal}</div></div>)}</div></section></div>
 <section className="card p-5 mt-6"><div className="flex items-center justify-between gap-3"><div><h2 className="font-black text-lg flex items-center gap-2"><BarChart3 size={19}/>Relationship Intelligence</h2><p className="muted text-sm">Meaningful-contact score, cadence, momentum and suggested follow-up for every coach relationship.</p></div><span className="pill">{visibleInsights.length} relationships</span></div><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left muted border-b"><th className="py-3 pr-4">Coach / College</th><th className="py-3 pr-4">Score</th><th className="py-3 pr-4">Momentum</th><th className="py-3 pr-4">Cadence</th><th className="py-3 pr-4">Meaningful</th><th className="py-3 pr-4">Last Contact</th><th className="py-3">Next Move</th></tr></thead><tbody>{visibleInsights.slice().sort((a,b)=>b.score-a.score).map(r=><tr key={r.id} className="border-b align-top"><td className="py-3 pr-4"><b>{r.coach}</b><div className="muted text-xs">{r.college}</div></td><td className="py-3 pr-4"><b>{r.score}</b><div className="muted text-xs">{scoreLabel(r.score)}</div></td><td className="py-3 pr-4"><Momentum value={r.momentum}/></td><td className="py-3 pr-4">{cadenceLabel(r.cadenceDays)}</td><td className="py-3 pr-4">{r.meaningfulContacts} / {r.totalContacts}</td><td className="py-3 pr-4">{r.daysSinceContact===999?'Never':`${r.daysSinceContact}d ago`}</td><td className="py-3 min-w-[240px]">{r.nextAction}</td></tr>)}</tbody></table>{!visibleInsights.length&&<Empty text="No coach relationships are available yet."/>}</div></section>
 {role!=='athlete'&&<><div className="grid lg:grid-cols-2 gap-6 mt-6"><section className="card p-5"><div className="flex items-center gap-2"><AlertTriangle size={19}/><div><h2 className="font-black text-lg">Advisor Alerts</h2><p className="muted text-sm">Players who may need proactive support.</p></div></div><div className="mt-4 space-y-3">{alerts.length?alerts.map(p=><Link href={`/advisors/player/${p.id}`} key={p.id} className="border rounded-xl p-4 block hover:bg-slate-50"><div className="flex justify-between gap-3"><b>{p.name}</b><span className="font-black">{p.score}/100</span></div><div className="muted text-sm mt-1">{p.stale?'No recruiting activity in 14+ days':p.overdue?`${p.overdue} overdue follow-up${p.overdue===1?'':'s'}`:'Low recruiting engagement'}</div></Link>):<Empty text="No athletes currently meet the attention thresholds."/>}</div></section><section className="card p-5"><div className="flex items-center gap-2"><Users size={19}/><div><h2 className="font-black text-lg">Organization Intelligence</h2><p className="muted text-sm">Communication health across accessible athletes.</p></div></div><div className="mt-4 space-y-3"><Summary label="Athletes analyzed" value={athleteRows.length}/><Summary label="Average engagement" value={`${Math.round(athleteRows.reduce((n,p)=>n+p.score,0)/Math.max(1,athleteRows.length))}/100`}/><Summary label="Athletes inactive 14+ days" value={athleteRows.filter(p=>p.stale).length}/><Summary label="Overdue follow-ups" value={athleteRows.reduce((n,p)=>n+p.overdue,0)}/><Summary label="Relationships gaining momentum" value={insights.filter(r=>r.momentum==='Rising').length}/></div></section></div><section className="card p-5 mt-6"><h2 className="font-black text-lg">Athlete Engagement Ranking</h2><p className="muted text-sm mt-1">A directional score based on recent activity, meaningful contacts, active coach relationships, response signals and overdue follow-ups.</p><div className="mt-4 divide-y">{athleteRows.map(p=><Link href={`/advisors/player/${p.id}`} key={p.id} className="py-3 flex items-center gap-4 hover:bg-slate-50 -mx-2 px-2 rounded-xl"><div className="h-10 w-10 rounded-xl bg-slate-100 flex items-center justify-center font-black">{p.score}</div><div className="flex-1"><b>{p.name}</b><div className="muted text-xs">{p.relationships} coach relationships · {p.meaningful30} meaningful contacts in 30 days · {p.rising} rising · {p.cooling} cooling</div></div><ArrowRight size={16}/></Link>)}</div></section></>}
 <div className="mt-6 rounded-xl border bg-slate-50 p-4 text-xs text-slate-600"><b>How these signals work:</b> Communication Intelligence uses only recruiting data already logged in Rebels Recruit. Scores are directional coaching aids—not predictions of a college coach's intent. Response signals are inferred only from interaction types, notes and who initiated an interaction when that information has been logged.</div>
 </div></AppShell>}
function Metric({label,value,detail}:{label:string;value:any;detail:string}){return <div className="card p-4"><div className="muted text-xs">{label}</div><div className="font-black text-2xl mt-1">{value}</div><div className="muted text-xs mt-1">{detail}</div></div>}
function Momentum({value}:{value:string}){return <span className={`pill ${value==='Rising'?'bg-emerald-50 text-emerald-700':value==='Cooling'?'bg-amber-50 text-amber-800':''}`}>{value}</span>}
function Summary({label,value}:{label:string;value:any}){return <div className="flex items-center justify-between border rounded-xl p-3"><span className="text-sm">{label}</span><b>{value}</b></div>}
function Empty({text}:{text:string}){return <div className="py-8 text-center muted text-sm">{text}</div>}
