'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowRight,BarChart3,CheckSquare,Clock3,Flag,Mail,MessageCircleMore,MessageSquare,RefreshCw,Sparkles,TrendingDown,TrendingUp,Users} from 'lucide-react';
import AppShell from '@/components/AppShell';
import PageHeader from '@/components/PageHeader';
import {createClient} from '@/lib/supabase-browser';
import {athleteEngagementScore,buildRelationshipInsights,cadenceLabel,daysSince,isMeaningfulContact,scoreLabel} from '@/lib/communication-intelligence';
import {exactInteractionDate} from '@/lib/interaction-dates';
import {RECRUITING_JOURNEY,journeySuggestion,journeyUrgencyDays,normalizeJourneyStage} from '@/lib/recruiting-journey';
import {contextualNextMove} from '@/lib/contextual-next-move';
import {resolveStaffOrganizationContext} from '@/lib/owner-preview';

type Profile={id:string;full_name?:string|null;email?:string|null};
const one=(v:any)=>Array.isArray(v)?v[0]:v;
const fmt=(d?:string|null)=>d?new Date(`${String(d).slice(0,10)}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'';
const enc=(v:any)=>encodeURIComponent(String(v||''));
const taskHref=(athleteId:string,title:string,description:string)=>`/advisors/tasks?player=${enc(athleteId)}&title=${enc(title)}&description=${enc(description)}`;
const coachLastName=(name:string)=>String(name||'').trim().split(/\s+/).pop()||'';

export default function RecruitingInsights(){
 const c=createClient();
 const [loading,setLoading]=useState(true),[role,setRole]=useState('athlete'),[view,setView]=useState<'overview'|'schools'|'coaches'>('overview'),[coverageSearch,setCoverageSearch]=useState(''),[coverageDetail,setCoverageDetail]=useState<any>(null),[historical,setHistorical]=useState<any[]>([]),[viewerId,setViewerId]=useState(''),[profiles,setProfiles]=useState<Profile[]>([]),[relationships,setRelationships]=useState<any[]>([]),[interactions,setInteractions]=useState<any[]>([]),[reminders,setReminders]=useState<any[]>([]),[colleges,setColleges]=useState<any[]>([]),[milestones,setMilestones]=useState<any[]>([]),[events,setEvents]=useState<any[]>([]),[selectedAthlete,setSelectedAthlete]=useState(''),[momentumFilter,setMomentumFilter]=useState(''),[previewReadOnly,setPreviewReadOnly]=useState(false),[orgTeams,setOrgTeams]=useState<any[]>([]),[teamMembers,setTeamMembers]=useState<any[]>([]);
 async function load(){setLoading(true);const {data:{user}}=await c.auth.getUser();if(!user){setLoading(false);return}setViewerId(user.id);const q=typeof window!=='undefined'?new URLSearchParams(window.location.search):new URLSearchParams();const m:any=await resolveStaffOrganizationContext(c,user.id,q);setPreviewReadOnly(Boolean(q.get('previewRole')));const {data:roles}=await c.from('user_roles').select('role').eq('user_id',user.id);const heldRoles=(roles||[]).map((r:any)=>String(r.role));const activeView=typeof window!=='undefined'?window.localStorage.getItem('rr-active-view'):null;const effectiveRole=m?.role||(activeView&&heldRoles.includes(activeView)?activeView:(heldRoles.includes('athlete')?'athlete':heldRoles[0]||'athlete'));setRole(effectiveRole);let athleteIds:string[]=[user.id];if(effectiveRole!=='athlete'){if(m){if(m.preview&&m.role==='advisor'&&m.previewAthleteId){athleteIds=[String(m.previewAthleteId)]}else if(m.role==='owner'||m.role==='admin'||m.organization_view_access){const {data:ms}=await c.from('organization_members').select('user_id,role').eq('organization_id',m.organization_id).eq('status','active');athleteIds=(ms||[]).filter((x:any)=>x.role==='athlete').map((x:any)=>x.user_id)}else{const {data:a}=await c.from('athlete_advisor_assignments').select('athlete_user_id').eq('advisor_user_id',user.id).eq('status','active');athleteIds=(a||[]).map((x:any)=>x.athlete_user_id)}}}athleteIds=[...new Set(athleteIds)];if(!athleteIds.length){setProfiles([]);setLoading(false);return}
 const [ps,rs,ints,rems,acs,evs]=await Promise.all([
  c.from('profiles').select('id,full_name,email').in('id',athleteIds),
  c.from('athlete_coaches').select('id,athlete_user_id,coach_id,college_id,last_contact_date,next_step,colleges(name),college_coaches(first_name,last_name,title,email)').in('athlete_user_id',athleteIds),
  c.from('interactions').select('id,athlete_user_id,coach_id,college_id,type,date,date_precision,date_year,date_month,created_at,note,initiated_by,colleges(name),college_coaches(first_name,last_name,title)').in('athlete_user_id',athleteIds).order('date',{ascending:false,nullsFirst:false}).order('created_at',{ascending:false}).limit(4000),
  c.from('reminders').select('id,athlete_user_id,coach_id,college_id,title,due_date,status').in('athlete_user_id',athleteIds),
  c.from('athlete_colleges').select('id,athlete_user_id,college_id,status,created_at,archived_at,colleges(name,logo_url,division)').in('athlete_user_id',athleteIds),
  c.from('athlete_events').select('athlete_user_id,status,events(id,name,type,date,college_id,colleges(name))').in('athlete_user_id',athleteIds)
 ]);
 if(m?.organization_id&&(effectiveRole==='admin'||effectiveRole==='owner')){const [{data:ts},{data:tm}]=await Promise.all([c.from('teams').select('id,name,age_group,sort_order').eq('organization_id',m.organization_id).is('archived_at',null).order('sort_order'),c.from('team_members').select('team_id,user_id').in('user_id',athleteIds)]);setOrgTeams(ts||[]);setTeamMembers(tm||[]);const{data:h}=await c.from('organization_recruiting_history').select('id,athlete_name,graduation_year,college_id,college_coach_id,college_coach_name,colleges(id,name)').eq('organization_id',m.organization_id);setHistorical(h||[])}else{setHistorical([]);setOrgTeams([]);setTeamMembers([])};setProfiles(ps.data||[]);setRelationships(rs.data||[]);setInteractions(ints.data||[]);setReminders(rems.data||[]);setColleges(acs.data||[]);setEvents(evs.data||[]);try{const all=await Promise.all(athleteIds.map(id=>fetch(`/api/recruiting-journey?athlete=${encodeURIComponent(id)}`,{cache:'no-store'}).then(async r=>r.ok?(await r.json()).milestones||[]:[])));setMilestones(all.flat())}catch{setMilestones([])}
 if(typeof window!=='undefined'){const q=new URLSearchParams(window.location.search);const requested=q.get('athlete');const momentum=q.get('momentum')||'';const requestedView=q.get('view');if((requestedView==='overview'||requestedView==='schools'||requestedView==='coaches')&&(effectiveRole==='admin'||effectiveRole==='owner'))setView(requestedView);if(effectiveRole!=='athlete')setSelectedAthlete(requested&&athleteIds.includes(requested)?requested:'all');if(momentum)setMomentumFilter(momentum)}else if(effectiveRole!=='athlete'&&!selectedAthlete)setSelectedAthlete('all');setLoading(false)}
 useEffect(()=>{load()},[]);
 const insights=useMemo(()=>buildRelationshipInsights(relationships,interactions),[relationships,interactions]);const pm=useMemo(()=>new Map(profiles.map(p=>[p.id,p])),[profiles]);
 const baseVisibleInsights=selectedAthlete&&selectedAthlete!=='all'?insights.filter(x=>x.athleteUserId===selectedAthlete):insights;const visibleInsights=momentumFilter==='stale14'?baseVisibleInsights.filter(x=>x.daysSinceContact!==999&&x.daysSinceContact>=14):momentumFilter?baseVisibleInsights.filter(x=>x.momentum===momentumFilter):baseVisibleInsights;const visibleInts=selectedAthlete&&selectedAthlete!=='all'?interactions.filter(x=>x.athlete_user_id===selectedAthlete):interactions;const visibleColleges=selectedAthlete&&selectedAthlete!=='all'?colleges.filter(x=>x.athlete_user_id===selectedAthlete):colleges;const visibleMilestones=selectedAthlete&&selectedAthlete!=='all'?milestones.filter(x=>x.athleteUserId===selectedAthlete):milestones;
 const collegeLast=useMemo(()=>{const m=new Map<string,string>();for(const i of interactions){const k=`${i.athlete_user_id}:${i.college_id||''}`;const d=exactInteractionDate(i);if(d&&(!m.get(k)||d>String(m.get(k))))m.set(k,d)}return m},[interactions]);
 const athleteRows=useMemo(()=>profiles.map(p=>{const rs=insights.filter(r=>r.athleteUserId===p.id),ints=interactions.filter(i=>i.athlete_user_id===p.id),rem=reminders.filter(r=>r.athlete_user_id===p.id),score=athleteEngagementScore(p.id,insights,interactions,reminders),exactDates=ints.map(exactInteractionDate).filter(Boolean).sort().reverse() as string[],last=exactDates[0]||null,overdue=rem.filter(r=>['open','overdue','snoozed'].includes(String(r.status||'').toLowerCase())&&r.due_date&&r.due_date<new Date().toISOString().slice(0,10)).length,offerCount=colleges.filter(x=>x.athlete_user_id===p.id&&normalizeJourneyStage(x.status)==='Offer'&&!x.archived_at).length,committed=colleges.some(x=>x.athlete_user_id===p.id&&normalizeJourneyStage(x.status)==='Committed'&&!x.archived_at),hasActivity=ints.length>0;return{id:p.id,name:p.full_name||p.email||'Athlete',score,lastActivity:last,stale:Boolean(last)&&daysSince(last)>=14,overdue,relationships:rs.length,meaningful30:ints.filter(i=>{const d=exactInteractionDate(i);return Boolean(d)&&daysSince(d)<=30&&isMeaningfulContact(i)}).length,rising:rs.filter(r=>r.momentum==='Rising').length,cooling:rs.filter(r=>r.momentum==='Cooling').length,offerCount,committed,hasActivity}}).sort((a,b)=>a.score-b.score),[profiles,insights,interactions,reminders,colleges]);
 const currentId=role==='athlete'?viewerId:(selectedAthlete&&selectedAthlete!=='all'?selectedAthlete:'');const currentScore=currentId?athleteEngagementScore(currentId,insights,interactions,reminders):Math.round(athleteRows.reduce((n,p)=>n+p.score,0)/Math.max(1,athleteRows.length));const meaningful30=visibleInts.filter(i=>{const d=exactInteractionDate(i);return Boolean(d)&&daysSince(d)<=30&&isMeaningfulContact(i)}).length;const stale14=baseVisibleInsights.filter(r=>r.daysSinceContact!==999&&r.daysSinceContact>=14).length;const rising=baseVisibleInsights.filter(r=>r.momentum==='Rising').length;const cooling=baseVisibleInsights.filter(r=>r.momentum==='Cooling').length;const needsAttention=baseVisibleInsights.filter(r=>r.momentum==='Cooling'||r.daysSinceContact>=14&&r.daysSinceContact!==999).length;const athletesNeedingAttention=new Set(baseVisibleInsights.filter(r=>r.momentum==='Cooling'||(r.daysSinceContact!==999&&r.daysSinceContact>=14)).map(r=>r.athleteUserId)).size;const activeRelationships=baseVisibleInsights.length;const upcomingEvents=events.filter((x:any)=>{const e=one(x.events),d=e?.date?new Date(`${String(e.date).slice(0,10)}T12:00:00`):null;return d&&d>=new Date(new Date().toDateString())}).length;
 const alerts=athleteRows.filter(p=>p.stale||p.overdue||(p.hasActivity&&p.score<35)).slice(0,8);
 const enriched=useMemo(()=>baseVisibleInsights.map(r=>{const college=colleges.find(x=>x.athlete_user_id===r.athleteUserId&&x.college_id===r.collegeId),relInts=interactions.filter(i=>i.athlete_user_id===r.athleteUserId&&((r.coachId&&i.coach_id===r.coachId)||(r.collegeId&&i.college_id===r.collegeId))),relEvents=events.filter(e=>e.athlete_user_id===r.athleteUserId).map(e=>one(e.events)).filter((e:any)=>e&&(!r.collegeId||!e.college_id||e.college_id===r.collegeId)),lastInteraction=relInts.slice().sort((a:any,b:any)=>String(exactInteractionDate(b)||b.created_at||'').localeCompare(String(exactInteractionDate(a)||a.created_at||'')))[0]||null,move=contextualNextMove({stage:college?.status,interactions:relInts,events:relEvents,lastContact:r.lastContact});return{...r,stage:normalizeJourneyStage(college?.status),move,lastInteraction}}),[baseVisibleInsights,colleges,interactions,events]);
 const contextualRecommendations=enriched.filter(x=>x.move.priority>0).sort((a,b)=>b.move.priority-a.move.priority||b.daysSinceContact-a.daysSinceContact).slice(0,10);
 const relationshipWorkbench=enriched.filter(r=>!momentumFilter||(momentumFilter==='stale14'?(r.daysSinceContact!==999&&r.daysSinceContact>=14):r.momentum===momentumFilter)).sort((a,b)=>{const am=a.momentum==='Cooling'?3:a.move.priority>0?2:a.momentum==='Rising'?1:0,bm=b.momentum==='Cooling'?3:b.move.priority>0?2:b.momentum==='Rising'?1:0;return bm-am||b.daysSinceContact-a.daysSinceContact||b.score-a.score}).slice(0,18);
 const journeyCounts=useMemo(()=>Object.fromEntries(RECRUITING_JOURNEY.map(s=>[s,visibleColleges.filter(r=>!r.archived_at&&normalizeJourneyStage(r.status)===s).length])),[visibleColleges]);
 const journeyNeeds=useMemo(()=>visibleColleges.filter(r=>!r.archived_at).map(r=>{const stage=normalizeJourneyStage(r.status),last=collegeLast.get(`${r.athlete_user_id}:${r.college_id}`)||null,d=last?daysSince(last):999,limit=journeyUrgencyDays(stage);return{...r,stage,days:d,limit,last,name:one(r.colleges)?.name||'School'}}).filter(r=>r.stage!=='Committed'&&r.days!==999&&r.days>=r.limit).sort((a,b)=>b.days-a.days).slice(0,8),[visibleColleges,collegeLast]);
 const recentMilestones=useMemo(()=>visibleMilestones.slice().sort((a,b)=>String(b.milestoneDate).localeCompare(String(a.milestoneDate))).slice(0,10),[visibleMilestones]);
 const athleteTeams=useMemo(()=>{const m=new Map<string,Set<string>>();for(const x of teamMembers){const set=m.get(x.user_id)||new Set<string>();set.add(String(x.team_id));m.set(x.user_id,set)}return m},[teamMembers]);const collegeMeta=useMemo(()=>{const m=new Map<string,any>();for(const x of colleges){const id=String(x.college_id||'');if(id&&!m.has(id))m.set(id,one(x.colleges)||{})}return m},[colleges]);
 const schoolCoverage=useMemo(()=>{const map=new Map<string,any>();for(const x of colleges.filter((x:any)=>!x.archived_at)){const id=String(x.college_id||''),name=one(x.colleges)?.name||'School',logoUrl=one(x.colleges)?.logo_url||'';if(!id)continue;const v=map.get(id)||{id,name,logoUrl,division:one(x.colleges)?.division||'',athletes:new Map(),coaches:new Set(),historical:[],attention:0,rising:0};v.athletes.set(x.athlete_user_id,{id:x.athlete_user_id,name:pm.get(x.athlete_user_id)?.full_name||'Athlete',stage:normalizeJourneyStage(x.status),teamIds:[...(athleteTeams.get(x.athlete_user_id)||new Set<string>())]});const rels=insights.filter((r:any)=>r.athleteUserId===x.athlete_user_id&&String(r.collegeId||'')===id);for(const r of rels){if(r.coachId)v.coaches.add(r.coachId);if(r.momentum==='Cooling'||(r.daysSinceContact!==999&&r.daysSinceContact>=14))v.attention++;if(r.momentum==='Rising')v.rising++}map.set(id,v)}for(const h of historical){const id=String(h.college_id||'');const v=map.get(id)||{id,name:one(h.colleges)?.name||'School',logoUrl:one(h.colleges)?.logo_url||'',division:one(h.colleges)?.division||'',athletes:new Map(),coaches:new Set(),historical:[],attention:0,rising:0};v.historical.push(h);map.set(id,v)}return [...map.values()].sort((a,b)=>b.athletes.size-a.athletes.size||a.name.localeCompare(b.name))},[colleges,historical,insights,pm,athleteTeams]);
 const coachCoverage=useMemo(()=>{const map=new Map<string,any>();for(const r of insights){if(!r.coachId)continue;const v=map.get(r.coachId)||{id:r.coachId,name:r.coach,school:r.college,division:collegeMeta.get(String(r.collegeId||''))?.division||'',athletes:new Map(),reciprocal:0,rising:0,cooling:0,attention:0,last:''};v.athletes.set(r.athleteUserId,{id:r.athleteUserId,name:pm.get(r.athleteUserId)?.full_name||'Athlete',momentum:r.momentum,days:r.daysSinceContact,teamIds:[...(athleteTeams.get(r.athleteUserId)||new Set<string>())]});if(r.meaningfulContacts>1)v.reciprocal++;if(r.momentum==='Rising')v.rising++;if(r.momentum==='Cooling')v.cooling++;if(r.momentum==='Cooling'||(r.daysSinceContact!==999&&r.daysSinceContact>=14))v.attention++;map.set(r.coachId,v)}return [...map.values()].sort((a,b)=>b.athletes.size-a.athletes.size||coachLastName(a.name).localeCompare(coachLastName(b.name))||a.name.localeCompare(b.name))},[insights,pm,collegeMeta,athleteTeams]);
 const programPatterns=useMemo(()=>{const map=new Map<string,any>();for(const r of insights){if(!r.collegeId)continue;const v=map.get(r.collegeId)||{id:r.collegeId,name:r.college||'College program',athletes:new Set<string>(),reciprocal:0,rising:0,cooling:0,meaningful:0,historical:0};v.athletes.add(r.athleteUserId);if(r.meaningfulContacts>1)v.reciprocal++;if(r.momentum==='Rising')v.rising++;if(r.momentum==='Cooling')v.cooling++;v.meaningful+=r.meaningfulContacts||0;map.set(r.collegeId,v)}for(const h of historical){const id=String(h.college_id||'');if(!id)continue;const v=map.get(id)||{id,name:one(h.colleges)?.name||'College program',athletes:new Set<string>(),reciprocal:0,rising:0,cooling:0,meaningful:0,historical:0};v.historical++;map.set(id,v)}return [...map.values()].map(x=>({...x,athleteCount:x.athletes.size})).filter(x=>x.athleteCount>=2||x.reciprocal>=2||x.historical>0).sort((a,b)=>b.athleteCount-a.athleteCount||b.reciprocal-a.reciprocal||b.historical-a.historical).slice(0,8)},[insights,historical]);
 const filteredSchoolCoverage=useMemo(()=>{const q=coverageSearch.trim().toLowerCase();return !q?schoolCoverage:schoolCoverage.filter((g:any)=>g.name.toLowerCase().includes(q)||[...g.athletes.values()].some((a:any)=>a.name.toLowerCase().includes(q)))},[schoolCoverage,coverageSearch]);
 const filteredCoachCoverage=useMemo(()=>{const q=coverageSearch.trim().toLowerCase();return !q?coachCoverage:coachCoverage.filter((g:any)=>g.name.toLowerCase().includes(q)||String(g.school||'').toLowerCase().includes(q)||[...g.athletes.values()].some((a:any)=>a.name.toLowerCase().includes(q)))},[coachCoverage,coverageSearch]);
 const openCoverageDetail=(kind:'school'|'coach',group:any,athlete:any)=>{const related=insights.filter((r:any)=>r.athleteUserId===athlete.id&&(kind==='school'?String(r.collegeId||'')===String(group.id):String(r.coachId||'')===String(group.id)));setCoverageDetail({kind,group,athlete,related})};
 const staff=role!=='athlete';
 if(loading)return <AppShell><div className="max-w-7xl mx-auto p-8"><div className="card p-10 text-center muted">Building Recruiting Insights...</div></div></AppShell>;
 return <AppShell><div className="max-w-7xl mx-auto px-5 md:px-8 py-6"><PageHeader eyebrow={role==='owner'||role==='admin'?'ORGANIZATION INTELLIGENCE':undefined} title="Recruiting Insights" subtitle={role==='owner'||role==='admin'?'Understand recruiting relationship health across the organization and see where athletes or advisors may need support.':staff?'Relationship-level intelligence that tells you what needs attention and gives you the next action.':"See what's moving, what needs attention and what your Next Step could be."} action={<div className="flex items-center gap-2 rounded-xl border bg-white p-2">{(role==='owner'||role==='admin')&&(['overview','schools','coaches'] as const).map(v=><button key={v} className={`btn ${view===v?'bg-slate-900 text-white':''}`} onClick={()=>{setView(v);setCoverageSearch('')}}>{v.charAt(0).toUpperCase()+v.slice(1)}</button>)}<button className="btn px-3" onClick={load} aria-label="Refresh Recruiting Insights" title="Refresh"><RefreshCw size={17}/></button></div>}/>
 {(role==='owner'||role==='admin')&&view==='schools'&&<CoverageView kind="school" groups={filteredSchoolCoverage} teams={orgTeams} search={coverageSearch} setSearch={setCoverageSearch} openDetail={openCoverageDetail}/>}
{(role==='owner'||role==='admin')&&view==='coaches'&&<CoverageView kind="coach" groups={filteredCoachCoverage} teams={orgTeams} search={coverageSearch} setSearch={setCoverageSearch} openDetail={openCoverageDetail}/>}
{(!((role==='owner'||role==='admin'))||view==='overview')&&<>
 {(role==='owner'||role==='admin')?<AdminOverview profiles={profiles} insights={enriched} events={events} activeRelationships={activeRelationships} needsAttention={needsAttention} athletesNeedingAttention={athletesNeedingAttention} cooling={cooling} rising={rising} stale14={stale14} upcomingEvents={upcomingEvents}/>:<>
 <section className="card p-5 mt-6"><div className="flex items-center justify-between gap-3 flex-wrap"><div><h2 className="font-black text-lg flex items-center gap-2"><Flag size={19}/>Recruiting Journey</h2><p className="muted text-sm">Current stage counts and milestone history. Athletes control journey changes.</p></div><span className="pill">{visibleColleges.filter(r=>!r.archived_at).length} active schools</span></div><div className="grid grid-cols-2 sm:grid-cols-4 xl:grid-cols-8 gap-2 mt-4">{RECRUITING_JOURNEY.map(s=>staff?<Link href={`/advisors/colleges?${selectedAthlete&&selectedAthlete!=='all'?`player=${enc(selectedAthlete)}&`:''}stage=${enc(s)}`} key={s} className="rounded-xl border p-3 min-w-0 hover:bg-slate-50 group"><div className="flex justify-between"><div className="text-xl font-black">{journeyCounts[s]||0}</div><ArrowRight size={13} className="opacity-0 group-hover:opacity-100"/></div><div className="text-xs font-bold mt-1 break-words">{s}</div></Link>:<div key={s} className="rounded-xl border p-3 min-w-0"><div className="text-xl font-black">{journeyCounts[s]||0}</div><div className="text-xs font-bold mt-1 break-words">{s}</div></div>)}</div></section>

 <div className="grid lg:grid-cols-2 gap-6 mt-6"><section className="card p-5"><div className="flex items-center gap-2"><AlertTriangle size={19}/><div><h2 className="font-black text-lg">Journey Needs Attention</h2><p className="muted text-sm">Stage-aware reminders based only on dated communication gaps.</p></div></div><div className="mt-4 space-y-3">{journeyNeeds.length?journeyNeeds.map(r=>{const playerName=pm.get(r.athlete_user_id)?.full_name||'Athlete';return <div key={r.id} className="border rounded-xl p-4"><div className="flex items-start justify-between gap-3"><div><b>{r.name}</b><div className="muted text-xs mt-1">{role==='athlete'?r.stage:`${playerName} · ${r.stage}`}</div></div><span className="pill">{`${r.days}d`}</span></div><div className="text-sm mt-2">{journeySuggestion(r.stage,r.days)}</div>{staff&&<div className="flex flex-wrap gap-2 mt-3"><Link href={`/advisors/colleges?player=${r.athlete_user_id}&stage=${enc(r.stage)}`} className="btn py-1.5 px-3 text-xs">Review school</Link>{!previewReadOnly&&<Link href={taskHref(r.athlete_user_id,`Follow up with ${r.name}`,`${r.name} is at the ${r.stage} stage and has a ${r.days}-day dated communication gap. ${journeySuggestion(r.stage,r.days)}`)} className="btn btn-red py-1.5 px-3 text-xs">Assign task</Link>}</div>}</div>}):<Empty text="Nothing with an dated communication gap needs attention right now."/>}</div></section><section className="card p-5"><div className="flex items-center gap-2"><Flag size={19}/><div><h2 className="font-black text-lg">Recent Milestones</h2><p className="muted text-sm">Dated movement through the Recruiting Journey.</p></div></div><div className="mt-4 space-y-3">{recentMilestones.length?recentMilestones.map(m=>{const row=colleges.find(x=>x.id===m.relationshipId);const playerName=pm.get(m.athleteUserId)?.full_name||'Athlete';const card=<><div className="flex justify-between gap-3"><b>{m.stage}</b><span className="muted text-xs">{fmt(m.milestoneDate)}</span></div><div className="text-sm mt-1">{one(row?.colleges)?.name||'School'}{role!=='athlete'?` · ${playerName}`:''}</div>{m.note&&<div className="muted text-xs mt-1">{m.note}</div>}{m.offerType&&<div className="muted text-xs mt-1">Offer type: {m.offerType}</div>}</>;return staff?<Link href={`/advisors/player/${m.athleteUserId}?relationship=${m.relationshipId}`} key={m.id} className="border rounded-xl p-3 block hover:bg-slate-50">{card}</Link>:<div key={m.id} className="border rounded-xl p-3">{card}</div>}):<Empty text="Journey milestones will appear here as stages change."/>}</div></section></div>

 <section className="card p-5 mt-6"><div className="flex items-center gap-2"><Sparkles size={19}/><div><h2 className="font-black text-lg">Suggested Next Steps</h2><p className="muted text-sm">Recommendations use Recruiting Journey stage, response signals, events and dated communication gaps.</p></div></div><div className="mt-4 space-y-3">{contextualRecommendations.length?contextualRecommendations.map(r=>{const playerName=pm.get(r.athleteUserId)?.full_name||'Athlete';const athleteParam=role==='athlete'?'':`athlete=${encodeURIComponent(r.athleteUserId)}&`;const emailHref=r.coachId&&r.move.starter?`/coaches/${r.coachId}?${athleteParam}emailStarter=${encodeURIComponent(r.move.starter)}`:r.coachId?`/coaches/${r.coachId}${role==='athlete'?'':`?athlete=${encodeURIComponent(r.athleteUserId)}`}`:'/colleges';return <div key={r.id} className="border rounded-xl p-4"><div className="flex gap-3 items-start"><div className="h-10 w-10 rounded-xl bg-slate-50 flex items-center justify-center shrink-0">{r.move.starter?<Mail size={18}/>:r.momentum==='Rising'?<TrendingUp size={18}/>:r.momentum==='Cooling'?<TrendingDown size={18}/>:<Clock3 size={18}/>}</div><div className="flex-1 min-w-0"><div className="font-black">{r.move.title}</div><div className="muted text-sm mt-1">{r.coach} · {r.college} · {r.stage}{role!=='athlete'?` · ${playerName}`:''}</div><div className="text-sm mt-2">{r.move.reason}</div><div className="flex flex-wrap gap-2 mt-3"><Link href={emailHref} className={r.move.starter?'btn btn-red py-1.5 px-3 text-xs':'btn py-1.5 px-3 text-xs'}>{r.move.starter?<><Mail size={14}/> Start recommended email</>:<>View relationship <ArrowRight size={14}/></>}</Link>{r.coachId&&<Link href={`/activity/new?college=${r.collegeId||''}&coach=${r.coachId}${role==='athlete'?'':`&athlete=${r.athleteUserId}`}`} className="btn py-1.5 px-3 text-xs">Log activity</Link>}{staff&&!previewReadOnly&&<Link href={taskHref(r.athleteUserId,r.move.title,`${r.coach} · ${r.college}. ${r.move.reason}`)} className="btn py-1.5 px-3 text-xs"><CheckSquare size={13}/> Task {String(playerName).split(' ')[0]}</Link>}</div></div></div></div>}):<Empty text="Add coach relationships, events and interactions to generate contextual suggestions."/>}</div></section>

 </>}

 </>}
 {coverageDetail&&<CoverageModal detail={coverageDetail} close={()=>setCoverageDetail(null)}/>} 
 </div></AppShell>}
function AdminOverview(props:any){
 const {profiles,insights,events,activeRelationships,needsAttention,athletesNeedingAttention,cooling,rising,stale14,upcomingEvents}=props;
 const [athlete,setAthlete]=useState('all'),[status,setStatus]=useState('attention'),[expanded,setExpanded]=useState(false),[detail,setDetail]=useState<string|null>(null);
 const pm=useMemo(()=>new Map(profiles.map((p:any)=>[p.id,p])),[profiles]);
 const attention=(r:any)=>r.momentum==='Cooling'||(r.daysSinceContact!==999&&r.daysSinceContact>=14);
 const sorted=useMemo(()=>insights.slice().sort((a:any,b:any)=>{const priority=(r:any)=>r.momentum==='Cooling'?3:(r.daysSinceContact!==999&&r.daysSinceContact>=14)?2:r.momentum==='Rising'?1:0;return priority(b)-priority(a)||b.daysSinceContact-a.daysSinceContact}),[insights]);
 const filtered=sorted.filter((r:any)=>{const am=athlete==='all'||r.athleteUserId===athlete;const sm=status==='all'?true:status==='attention'?attention(r):status==='stale14'?(r.daysSinceContact!==999&&r.daysSinceContact>=14):r.momentum===status;return am&&sm});
 const shown=expanded?filtered:filtered.slice(0,16);
 const athleteAttention=useMemo(()=>{const m=new Map<string,any>();insights.filter(attention).forEach((r:any)=>{const x=m.get(r.athleteUserId)||{id:r.athleteUserId,count:0,cooling:0,gaps:0};x.count++;if(r.momentum==='Cooling')x.cooling++;if(r.daysSinceContact!==999&&r.daysSinceContact>=14)x.gaps++;m.set(r.athleteUserId,x)});return [...m.values()].sort((a,b)=>b.count-a.count)},[insights]);
 const eventRows=(events||[]).filter((x:any)=>{const e=one(x.events),d=e?.date?new Date(`${String(e.date).slice(0,10)}T12:00:00`):null;return d&&d>=new Date(new Date().toDateString())}).sort((a:any,b:any)=>String(one(a.events)?.date||'').localeCompare(String(one(b.events)?.date||'')));
 const signalAthletes=athleteAttention.slice(0,4);
 const detailRows=detail==='tracked'?sorted:detail==='cooling'?sorted.filter((r:any)=>r.momentum==='Cooling'):detail==='attention'?athleteAttention:detail==='events'?eventRows:[];
 const closeDetail=()=>setDetail(null);
 return <>
  <section className="card overflow-hidden">
   <div className="px-5 py-4 flex items-center justify-between gap-4"><div><div className="rr-eyebrow">ORGANIZATION SNAPSHOT</div><h2 className="font-black text-xl">Recruiting relationship health</h2></div><span className="text-xs text-slate-500 hidden md:block">Click any metric to see the records behind it.</span></div>
   <div className="border-t grid grid-cols-2 lg:grid-cols-4 divide-x divide-y lg:divide-y-0">
    <HealthStat label="Tracked relationships" value={activeRelationships} detail="coach relationships being tracked" onClick={()=>setDetail('tracked')}/>
    <HealthStat label="Athletes needing attention" value={athletesNeedingAttention} detail={`${needsAttention} relationships need review`} onClick={()=>setDetail('attention')}/>
    <HealthStat label="Cooling" value={cooling} detail={`${stale14} have 14+ day contact gaps`} onClick={()=>setDetail('cooling')}/>
    <HealthStat label="Upcoming events" value={upcomingEvents} detail="future recruiting events" onClick={()=>setDetail('events')}/>
   </div>
  </section>
  <div className="grid xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)] gap-6 mt-6 items-start">
   <section id="admin-relationship-health" className="card overflow-hidden scroll-mt-4">
    <div className="p-5"><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div><h2 className="font-black text-xl">Relationship Health</h2><p className="muted text-sm mt-1">See where recruiting relationships may need support.</p></div><div className="flex flex-col sm:flex-row gap-2"><select className="input sm:w-52" value={athlete} onChange={e=>{setAthlete(e.target.value);setExpanded(false)}}><option value="all">All athletes</option>{profiles.map((p:any)=><option key={p.id} value={p.id}>{p.full_name||p.email||'Athlete'}</option>)}</select><select className="input sm:w-44" value={status} onChange={e=>{setStatus(e.target.value);setExpanded(false)}}><option value="attention">Needs attention</option><option value="all">All relationships</option><option value="stale14">14+ day gaps</option><option value="Cooling">Cooling</option><option value="Rising">Rising</option><option value="Steady">Steady</option></select></div></div><div className="text-xs text-slate-500 mt-3">Showing {shown.length} of {filtered.length} {status==='attention'?'relationships needing attention':'relationships'}</div></div>
    <div className="border-t"><div className="hidden md:grid grid-cols-[1fr_1.35fr_105px_95px] gap-3 px-5 py-2.5 bg-slate-50 text-[11px] font-black text-slate-500"><span>Athlete</span><span>School / Coach</span><span>Health</span><span>Last contact</span></div><div className="divide-y">{shown.map((r:any)=>{const p:any=pm.get(r.athleteUserId),name=p?.full_name||p?.email||'Athlete',href=r.coachId?`/coaches/${r.coachId}?athlete=${r.athleteUserId}`:`/advisors/colleges?player=${r.athleteUserId}`;return <Link key={r.id} href={href} className="grid md:grid-cols-[1fr_1.35fr_105px_95px] gap-2 md:gap-3 px-5 py-3 items-center hover:bg-slate-50 group"><b className="text-sm">{name}</b><div className="min-w-0"><div className="text-sm font-bold truncate">{r.college}</div><div className="text-xs text-slate-500 truncate">{r.coach}</div></div><span><span className={`rounded-full px-2 py-1 text-[11px] font-bold ${r.momentum==='Cooling'?'bg-red-100 text-red-700':r.momentum==='Rising'?'bg-slate-900 text-white':'bg-slate-100 text-slate-700'}`}>{r.momentum}</span></span><span className="text-xs text-slate-500 flex items-center justify-between">{r.daysSinceContact===999?'—':`${r.daysSinceContact}d`}<ArrowRight size={13} className="opacity-0 group-hover:opacity-100"/></span></Link>})}{!shown.length&&<Empty text="No relationships match this view."/>}</div></div>
    {filtered.length>16&&<div className="border-t"><button type="button" className="w-full px-5 py-3.5 text-sm font-black hover:bg-slate-50" onClick={()=>{if(expanded){setExpanded(false);setTimeout(()=>document.getElementById('admin-relationship-health')?.scrollIntoView({behavior:'smooth',block:'start'}),0)}else setExpanded(true)}}>{expanded?'Show fewer / Back to top ↑':`Show ${filtered.length-16} more relationships ↓`}</button></div>}
   </section>
   <aside className="card overflow-hidden">
    <div className="p-5"><div className="rr-eyebrow">ORGANIZATION SIGNALS</div><h2 className="font-black text-xl">What stands out</h2><p className="muted text-sm mt-1">Patterns worth understanding across the recruiting program.</p></div>
    <div className="border-t p-5"><div className="text-xs font-black text-slate-500 mb-3">ATTENTION IS CONCENTRATED</div><div className="space-y-3">{signalAthletes.map((a:any)=>{const p:any=pm.get(a.id);return <button key={a.id} className="w-full text-left group" onClick={()=>{setAthlete(a.id);setStatus('attention');setExpanded(false);document.getElementById('admin-relationship-health')?.scrollIntoView({behavior:'smooth',block:'start'})}}><div className="flex justify-between gap-3"><b className="text-sm group-hover:text-red-700">{p?.full_name||p?.email||'Athlete'}</b><span className="text-sm font-black">{a.count}</span></div><div className="text-xs text-slate-500 mt-0.5">{a.cooling} cooling · {a.gaps} with 14+ day gaps</div></button>})}{!signalAthletes.length&&<div className="text-sm text-slate-500">No athletes currently need attention.</div>}</div></div>
    <div className="border-t p-5"><div className="text-xs font-black text-slate-500 mb-3">RELATIONSHIP MOVEMENT</div><div className="grid grid-cols-3 gap-2 text-center"><SignalStat value={rising} label="Rising"/><SignalStat value={cooling} label="Cooling"/><SignalStat value={Math.max(0,activeRelationships-rising-cooling)} label="Steady"/></div></div>
    <div className="border-t p-5"><div className="text-xs font-black text-slate-500 mb-2">RECRUITING ACTIVITY</div><button className="w-full flex items-center justify-between text-sm hover:text-red-700" onClick={()=>setDetail('events')}><span>Upcoming events</span><b>{upcomingEvents}</b></button></div>
   </aside>
  </div>
  {detail&&<div className="fixed inset-0 z-50 bg-slate-950/45 flex items-center justify-center p-4" onMouseDown={closeDetail}><div className="bg-white rounded-2xl shadow-2xl border w-full max-w-4xl max-h-[82vh] overflow-hidden flex flex-col" onMouseDown={e=>e.stopPropagation()}><div className="p-5 border-b flex justify-between gap-4"><div><div className="rr-eyebrow">UNDERLYING DETAILS</div><h2 className="font-black text-xl">{detail==='tracked'?`${activeRelationships} Tracked Relationships`:detail==='attention'?`${athletesNeedingAttention} Athletes Needing Attention`:detail==='cooling'?`${cooling} Cooling Relationships`:`${upcomingEvents} Upcoming Recruiting Event${upcomingEvents===1?'':'s'}`}</h2></div><button className="btn self-start" onClick={closeDetail}>Close</button></div><div className="overflow-auto divide-y">{detail==='attention'?detailRows.map((a:any)=>{const p:any=pm.get(a.id);return <button key={a.id} className="w-full p-4 text-left hover:bg-slate-50" onClick={()=>{closeDetail();setAthlete(a.id);setStatus('attention');setExpanded(true);setTimeout(()=>document.getElementById('admin-relationship-health')?.scrollIntoView({behavior:'smooth',block:'start'}),0)}}><div className="flex justify-between gap-4"><div><b>{p?.full_name||p?.email||'Athlete'}</b><div className="text-xs text-slate-500 mt-1">{a.cooling} cooling · {a.gaps} with 14+ day gaps</div></div><span className="font-black">{a.count} relationship{a.count===1?'':'s'}</span></div></button>}):detail==='events'?detailRows.map((x:any,i:number)=>{const e=one(x.events),p:any=pm.get(x.athlete_user_id);return <div key={e?.id||i} className="p-4"><div className="flex justify-between gap-4"><div><b>{e?.name||'Recruiting event'}</b><div className="text-sm text-slate-600 mt-1">{p?.full_name||p?.email||'Athlete'}{one(e?.colleges)?.name?` · ${one(e.colleges).name}`:''}</div></div><span className="text-sm font-bold">{fmt(e?.date)}</span></div></div>}):detailRows.map((r:any)=>{const p:any=pm.get(r.athleteUserId),href=r.coachId?`/coaches/${r.coachId}?athlete=${r.athleteUserId}`:`/advisors/colleges?player=${r.athleteUserId}`;return <Link key={r.id} href={href} className="grid md:grid-cols-[1fr_1.2fr_1fr_110px] gap-3 p-4 hover:bg-slate-50" onClick={closeDetail}><b className="text-sm">{p?.full_name||p?.email||'Athlete'}</b><div><div className="text-sm font-bold">{r.college}</div><div className="text-xs text-slate-500">{r.coach}</div></div><span className="text-xs text-slate-600">{r.daysSinceContact===999?'No recorded contact':`Last contact ${r.daysSinceContact}d ago`}</span><span className={`text-xs font-black ${r.momentum==='Cooling'?'text-red-700':''}`}>{r.momentum}</span></Link>})}{!detailRows.length&&<Empty text="No records are included in this metric right now."/>}</div></div></div>}
 </>;
}
function HealthStat({label,value,detail,onClick}:{label:string;value:any;detail:string;onClick:()=>void}){return <button type="button" onClick={onClick} className="p-4 md:p-5 bg-white text-left hover:bg-slate-50 transition group"><div className="text-xs font-bold text-slate-500">{label}</div><div className="font-black text-2xl mt-1 flex items-center gap-2">{value}<ArrowRight size={15} className="text-slate-300 group-hover:text-red-700"/></div><div className="text-xs text-slate-500 mt-1">{detail}</div></button>}
function SignalStat({value,label}:{value:number;label:string}){return <div className="rounded-xl bg-slate-50 border p-2"><div className="font-black text-lg">{value}</div><div className="text-[11px] text-slate-500">{label}</div></div>}
function CoverageView({kind,groups,teams,search,setSearch,openDetail}:{kind:'school'|'coach';groups:any[];teams:any[];search:string;setSearch:(v:string)=>void;openDetail:(k:'school'|'coach',g:any,a:any)=>void}){
 const school=kind==='school';const [expanded,setExpanded]=useState(false),[team,setTeam]=useState('all'),[division,setDivision]=useState('all'),[stage,setStage]=useState('all'),[sort,setSort]=useState('athletes');
 const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
 const divisions=useMemo(()=>[...new Set(groups.map((g:any)=>String(g.division||'').trim()).filter(Boolean))].sort(),[groups]);
 const stages=useMemo(()=>school?[...new Set(groups.flatMap((g:any)=>[...g.athletes.values()].map((a:any)=>a.stage)).filter(Boolean))].sort():[],[groups,school]);
 const filtered=useMemo(()=>groups.map((g:any)=>{const athletes=new Map([...g.athletes.entries()].filter(([,a]:any)=>team==='all'||a.teamIds?.includes(team)).filter(([,a]:any)=>!school||stage==='all'||a.stage===stage));return {...g,athletes}}).filter((g:any)=>g.athletes.size>0&&(division==='all'||g.division===division)).sort((a:any,b:any)=>sort==='name'?a.name.localeCompare(b.name):sort==='coaches'&&school?b.coaches.size-a.coaches.size||b.athletes.size-a.athletes.size||a.name.localeCompare(b.name):sort==='school'&&!school?String(a.school||'').localeCompare(String(b.school||''))||coachLastName(a.name).localeCompare(coachLastName(b.name)):sort==='coach'&&!school?coachLastName(a.name).localeCompare(coachLastName(b.name))||a.name.localeCompare(b.name):b.athletes.size-a.athletes.size||a.name.localeCompare(b.name)),[groups,team,division,stage,sort,school]);
 const searching=Boolean(search.trim()),shown=searching||expanded?filtered:filtered.slice(0,5),sectionId=school?'school-relationships':'coach-relationships';
 const collapse=()=>{setExpanded(false);setTimeout(()=>document.getElementById(sectionId)?.scrollIntoView({behavior:'smooth',block:'start'}),0)};
 return <section id={sectionId} className="card overflow-hidden scroll-mt-4">
  <div className="px-5 py-5 bg-white"><div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><h2 className="font-black text-xl">{school?'School Insights':'Coach Insights'}</h2><p className="muted text-sm mt-1">{school?'See where athletes across the organization are building school relationships.':'See which college coaches have relationships with athletes across the organization.'}</p></div><input className="input md:w-72" placeholder={school?'Search schools or athletes':'Search coaches, schools or athletes'} value={search} onChange={e=>setSearch(e.target.value)}/></div>
   <div className="flex flex-wrap gap-2 mt-4">
    <select className="input py-2 text-sm" value={team} onChange={e=>{setTeam(e.target.value);setExpanded(false)}}><option value="all">All teams</option>{teams.map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select>
    <select className="input py-2 text-sm" value={division} onChange={e=>{setDivision(e.target.value);setExpanded(false)}}><option value="all">All divisions</option>{divisions.map(d=><option key={d} value={d}>{d}</option>)}</select>
    {school&&<select className="input py-2 text-sm" value={stage} onChange={e=>{setStage(e.target.value);setExpanded(false)}}><option value="all">All stages</option>{stages.map(x=><option key={x} value={x}>{x}</option>)}</select>}
    <select className="input py-2 text-sm" value={sort} onChange={e=>{setSort(e.target.value);setExpanded(false)}}><option value="athletes">Sort: Most athletes</option>{school&&<option value="coaches">Sort: Most coach relationships</option>}<option value="name">{school?'Sort: School A–Z':'Sort: Coach A–Z'}</option>{!school&&<option value="school">Sort: School A–Z</option>}</select>
   </div>
  </div>
  <div className="border-t divide-y divide-slate-200">{shown.map((g:any)=><div key={g.id} className="grid md:grid-cols-[300px_1fr] bg-white"><div className="p-5 bg-slate-100/70 border-b md:border-b-0 md:border-r flex items-start gap-3">{school?(g.logoUrl?<img src={g.logoUrl} alt="" className="h-14 w-14 rounded-xl object-contain bg-white border p-1.5 shrink-0"/>:<div className="h-14 w-14 rounded-xl border bg-white flex items-center justify-center text-xs font-black text-slate-500 shrink-0">{initials(g.name)}</div>):<div className="h-12 w-12 rounded-full bg-slate-900 text-white flex items-center justify-center text-xs font-black shrink-0">{initials(g.name)}</div>}<div className="min-w-0 pt-1"><Link href={school?`/colleges/${g.id}?staff=1`:`/coaches/${g.id}?staff=1`} className="font-black text-base leading-tight hover:text-red-700">{g.name} <ArrowRight size={14} className="inline"/></Link>{!school&&<div className="muted text-xs mt-1">{g.school}</div>}{g.division&&<div className="text-[11px] text-slate-400 mt-1">{g.division}</div>}<div className="text-[11px] font-bold text-slate-500 mt-2">{g.athletes.size} athlete{g.athletes.size===1?'':'s'}</div></div></div><div className="px-4 py-3 flex flex-col justify-center">{[...g.athletes.values()].map((a:any,i:number)=><button key={a.id} type="button" onClick={()=>openDetail(kind,g,a)} className={`group w-full flex items-center justify-between gap-3 py-2.5 text-left hover:text-red-700 ${i?'border-t border-slate-100':''}`}><div className="flex items-center gap-3 min-w-0"><b className="text-sm">{a.name}</b><span className={`rounded-full px-2 py-0.5 text-[11px] font-bold ${!school&&a.momentum==='Cooling'?'bg-red-100 text-red-700':!school&&a.momentum==='Rising'?'bg-slate-900 text-white':'bg-slate-100 text-slate-600'}`}>{school?a.stage:a.momentum}{!school&&a.days!==999?` · ${a.days}d`:''}</span></div><ArrowRight size={14} className="text-slate-300 group-hover:text-red-700 shrink-0"/></button>)}{school&&g.historical.length>0&&<div className="pt-2 mt-1 border-t text-xs text-slate-400">Historical: {g.historical.slice(0,5).map((h:any)=>`${h.athlete_name}${h.graduation_year?' · '+h.graduation_year:''}`).join(' · ')}</div>}</div></div>)}{!filtered.length&&<Empty text={school?'No schools match these filters.':'No coaches match these filters.'}/>}</div>
  {!searching&&filtered.length>5&&<div className="border-t bg-white"><button type="button" className="w-full px-5 py-4 text-sm font-black hover:bg-slate-50 transition" onClick={expanded?collapse:()=>setExpanded(true)}>{expanded?`Show fewer ${school?'schools':'coaches'} ↑`:`Show ${filtered.length-5} more ${school?'schools':'coaches'} ↓`}</button></div>}
 </section>
}
function CoverageModal({detail,close}:{detail:any;close:()=>void}){return <div className="fixed inset-0 z-50 bg-slate-950/45 flex items-center justify-center p-4" onMouseDown={close}><div className="bg-white rounded-2xl shadow-2xl border w-full max-w-2xl max-h-[80vh] overflow-auto p-5" onMouseDown={e=>e.stopPropagation()}><div className="flex justify-between gap-4"><div><div className="rr-eyebrow">{detail.kind==='school'?'ATHLETE + SCHOOL':'ATHLETE + COACH'}</div><h2 className="font-black text-xl">{detail.athlete.name}</h2><div className="muted text-sm">{detail.kind==='school'?detail.group.name:`${detail.group.name} · ${detail.group.school}`}</div></div><button className="btn" onClick={close}>Close</button></div><div className="mt-4 space-y-3">{detail.related.length?detail.related.map((r:any)=><div key={r.id} className="rounded-xl border p-4"><div className="flex gap-2 items-center flex-wrap"><b>{r.coach}</b><span className="pill">{r.momentum}</span><span className="text-xs font-black">{r.score}/100</span></div><div className="muted text-sm mt-1">{r.college}</div><div className="grid grid-cols-2 gap-2 mt-3 text-xs"><div className="rounded-lg border bg-slate-50 p-2"><div className="muted">Last recorded contact</div><b>{r.daysSinceContact===999?'Not available':`${r.daysSinceContact} days ago`}</b></div><div className="rounded-lg border bg-slate-50 p-2"><div className="muted">Meaningful contacts</div><b>{r.meaningfulContacts} of {r.totalContacts}</b></div></div><div className="text-sm mt-3"><b>Signal:</b> {r.responseSignal||'No signal yet'}</div></div>):<div className="rounded-xl border bg-slate-50 p-4 text-sm">No coach-level activity has been recorded for this relationship yet.</div>}</div><div className="flex flex-wrap gap-2 mt-5"><Link className="btn" href={`/advisors/player/${detail.athlete.id}`}>Player 360°</Link>{detail.kind==='school'?<Link className="btn" href={`/colleges/${detail.group.id}?staff=1`}>School Details</Link>:<Link className="btn" href={`/coaches/${detail.group.id}?athlete=${detail.athlete.id}`}>Coach Relationship</Link>}</div></div></div>}

function SnapshotCard({label,value,detail}:{label:string;value:any;detail:string}){return <div className="card p-4"><div className="muted text-xs">{label}</div><div className="font-black text-2xl mt-1">{value}</div><div className="muted text-xs mt-1">{detail}</div></div>}
function MetricLink({href,label,value,detail,onClick}:{href:string;label:string;value:any;detail:string;onClick?:()=>void}){return <Link href={href} onClick={onClick} className="card p-4 hover:border-slate-400 hover:shadow-sm transition group"><div className="muted text-xs">{label}</div><div className="font-black text-2xl mt-1">{value}</div><div className="flex items-center justify-between gap-2"><div className="muted text-xs mt-1">{detail}</div><ArrowRight size={13} className="opacity-0 group-hover:opacity-100"/></div></Link>}
function Momentum({value}:{value:string}){return <span className="pill">{value}</span>}
function SummaryLink({href,label,value,onClick}:{href:string;label:string;value:any;onClick?:()=>void}){return <Link href={href} onClick={onClick} className="flex items-center justify-between border rounded-xl p-3 hover:bg-slate-50"><span className="text-sm">{label}</span><span className="flex items-center gap-2"><b>{value}</b><ArrowRight size={13}/></span></Link>}
function Empty({text}:{text:string}){return <div className="py-8 text-center muted text-sm">{text}</div>}
