'use client';
import {useEffect,useMemo,useState} from 'react';
import AppShell from '@/components/AppShell';
import PageHeader from '@/components/PageHeader';
import {createClient} from '@/lib/supabase-browser';
import {Download,FileSpreadsheet} from 'lucide-react';

const arr=(v:any)=>Array.isArray(v)?v:[];
const csv=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;
const duration=(m:any)=>{if(m==null)return'';if(Number(m)>=99999)return'Anywhere';const h=Math.floor(Number(m)/60),r=Number(m)%60;return h?`${h} hr${h===1?'':'s'}${r?` ${r} min`:''}`:`${r} min`};
export default function CollegeFitExport(){
 const c=createClient();const [rows,setRows]=useState<any[]>([]),[teams,setTeams]=useState<any[]>([]),[teamMembers,setTeamMembers]=useState<any[]>([]),[loading,setLoading]=useState(true),[team,setTeam]=useState('all'),[player,setPlayer]=useState('all');
 useEffect(()=>{(async()=>{const {data:{user}}=await c.auth.getUser();if(!user){setLoading(false);return}const {data:m}=await c.from('organization_members').select('organization_id,role,organization_view_access').eq('user_id',user.id).eq('status','active').maybeSingle();if(!m){setLoading(false);return}let ids:string[]=[];if(m.role==='owner'||m.role==='admin'||m.organization_view_access){const {data}=await c.from('organization_members').select('user_id').eq('organization_id',m.organization_id).eq('role','athlete').eq('status','active');ids=(data||[]).map((x:any)=>x.user_id)}else{const {data}=await c.from('athlete_advisor_assignments').select('athlete_user_id').eq('organization_id',m.organization_id).eq('advisor_user_id',user.id).eq('status','active');ids=(data||[]).map((x:any)=>x.athlete_user_id)}const [{data:p},{data:a},{data:f},{data:t},{data:tm}]=await Promise.all([c.from('profiles').select('id,full_name,email').in('id',ids),c.from('athlete_profiles').select('user_id,class_year,positions,school_name,home_zip').in('user_id',ids),c.from('college_fit_profiles').select('*').in('user_id',ids),c.from('teams').select('id,name,age_group').eq('organization_id',m.organization_id),c.from('team_members').select('team_id,user_id')]);const pm=new Map((p||[]).map((x:any)=>[x.id,x])),am=new Map((a||[]).map((x:any)=>[x.user_id,x])),fm=new Map((f||[]).map((x:any)=>[x.user_id,x]));setTeams(t||[]);setTeamMembers(tm||[]);setRows(ids.map(id=>({id,profile:pm.get(id)||{},athlete:am.get(id)||{},fit:fm.get(id)||null})).sort((x,y)=>String(x.profile.full_name||'').localeCompare(String(y.profile.full_name||''))));setLoading(false)})()},[]);
 const filtered=useMemo(()=>rows.filter(r=>(team==='all'||teamMembers.some(tm=>tm.user_id===r.id&&tm.team_id===team))&&(player==='all'||r.id===player)),[rows,teamMembers,team,player]);
 function download(){const headers=['Player','Class Year','Team','Age Group','Home ZIP','Top Priorities','Max Drive Time','Distance Importance','Max Annual Cost','Cost Importance','Would Attend Without Athletic Scholarship','Divisions','Academic Interests','School Sizes','Campus Settings','Weather','Campus Experience','City Access','Competition Preferences','Religious Affiliation','School Types','Notes','Last Updated'];const teamMap=new Map(teams.map(t=>[t.id,t]));const body=filtered.map(r=>{const memberships=teamMembers.filter(tm=>tm.user_id===r.id).map(tm=>teamMap.get(tm.team_id)).filter(Boolean);const f=r.fit||{};return [r.profile.full_name||r.profile.email||'Player',r.athlete.class_year||'',memberships.map((x:any)=>x.name).join('; '),memberships.map((x:any)=>x.age_group).filter(Boolean).join('; '),r.athlete.home_zip||'',arr(f.top_priorities).join('; '),duration(f.max_drive_minutes),f.distance_importance||'',f.max_annual_cost||'',f.cost_importance||'',f.athletic_aid_required||'',arr(f.divisions).join('; '),arr(f.academic_interests).join('; '),arr(f.school_sizes).join('; '),arr(f.settings).join('; '),arr(f.weather_preferences).join('; '),arr(f.campus_experience).join('; '),arr(f.city_access_preferences).join('; '),arr(f.competition_preferences).join('; '),arr(f.religious_affiliation_preferences).join('; '),arr(f.school_types).join('; '),f.notes||'',f.updated_at?String(f.updated_at).slice(0,10):''].map(csv).join(',')});const blob=new Blob([[headers.map(csv).join(','),...body].join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`school-fit-report-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
 if(loading)return <AppShell><div className="max-w-6xl mx-auto p-8"><div className="card p-10 text-center muted">Loading School Fit Report...</div></div></AppShell>;
 return <AppShell><div className="max-w-6xl mx-auto px-5 md:px-8 py-7"><PageHeader title="School Fit Report" subtitle="Export the School Fit preferences your athletes have submitted, using the same advisor and organization access rules as the rest of Rebels Recruit." action={<button onClick={download} className="btn btn-red"><Download size={17}/> Export CSV</button>}/><div className="card p-4 grid md:grid-cols-2 gap-3 mb-5"><select className="input" value={team} onChange={e=>{setTeam(e.target.value);setPlayer('all')}}><option value="all">All teams</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}{t.age_group?` · ${t.age_group}`:''}</option>)}</select><select className="input" value={player} onChange={e=>setPlayer(e.target.value)}><option value="all">All players in view</option>{filtered.map(r=><option key={r.id} value={r.id}>{r.profile.full_name||r.profile.email||'Player'}</option>)}</select></div><section className="card p-5"><div className="flex items-center gap-2"><FileSpreadsheet size={19}/><h2 className="font-black text-lg">Report Preview</h2></div><div className="muted text-sm mt-1">{filtered.length} player{filtered.length===1?'':'s'} in this report · {filtered.filter(r=>r.fit).length} completed Fit Profile{filtered.filter(r=>r.fit).length===1?'':'s'}</div><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th className="py-2 pr-4">Player</th><th className="py-2 pr-4">Top priorities</th><th className="py-2 pr-4">Distance</th><th className="py-2 pr-4">Cost</th><th className="py-2 pr-4">Divisions</th><th className="py-2">Updated</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-b last:border-0"><td className="py-3 pr-4 font-bold">{r.profile.full_name||r.profile.email||'Player'}</td><td className="py-3 pr-4">{r.fit?arr(r.fit.top_priorities).join(', ')||'—':'Not completed'}</td><td className="py-3 pr-4">{r.fit?duration(r.fit.max_drive_minutes)||'—':'—'}</td><td className="py-3 pr-4">{r.fit?.max_annual_cost?`$${Number(r.fit.max_annual_cost).toLocaleString()}`:'—'}</td><td className="py-3 pr-4">{r.fit?arr(r.fit.divisions).join(', ')||'—':'—'}</td><td className="py-3">{r.fit?.updated_at?new Date(r.fit.updated_at).toLocaleDateString():'—'}</td></tr>)}</tbody></table></div></section></div></AppShell>;
}
