create table if not exists public.college_staff_dry_runs (
 id bigint generated by default as identity primary key,
 college_id uuid not null references public.colleges(id) on delete cascade,
 college_name text not null,
 status text not null,
 staff_url text,
 result jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);
create index if not exists college_staff_dry_runs_college_created_idx on public.college_staff_dry_runs(college_id,created_at desc);
alter table public.college_staff_dry_runs enable row level security;
comment on table public.college_staff_dry_runs is 'Internal QA results from controlled College Staff Intelligence dry runs; written only by the service-role ingestion route.';