alter table public.colleges add column if not exists ipeds_unitid bigint unique;

create table if not exists public.college_programs (
  id bigint generated by default as identity primary key,
  college_id uuid not null references public.colleges(id) on delete cascade,
  ipeds_unitid bigint not null,
  cip_code text not null,
  cip_title text not null,
  award_level integer,
  completions integer not null default 0,
  reporting_year integer not null,
  source text not null default 'IPEDS',
  updated_at timestamptz not null default now(),
  unique (college_id, cip_code, award_level, reporting_year)
);
create index if not exists college_programs_college_id_idx on public.college_programs(college_id);
create index if not exists college_programs_cip_title_idx on public.college_programs using gin (to_tsvector('english', cip_title));
create index if not exists college_programs_unitid_idx on public.college_programs(ipeds_unitid);
alter table public.college_programs enable row level security;
drop policy if exists "Authenticated users can read college programs" on public.college_programs;
create policy "Authenticated users can read college programs" on public.college_programs for select to authenticated using (true);
