'use client';
import {useEffect,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import Link from 'next/link';
import {PrimaryBrand} from '@/components/BrandLogo';
export default function JoinPage(){
 const p=useParams(),router=useRouter(),token=String(p?.token||'');const[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState('');
 useEffect(()=>{fetch('/api/join?token='+encodeURIComponent(token)).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)}).catch(e=>setError(e.message))},[token]);
 async function join(){setBusy(true);setError('');const r=await fetch('/api/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});const d=await r.json();if(r.status===401){router.push('/signup?join_token='+encodeURIComponent(token));return}if(!r.ok){setError(d.error||'Could not join.');setBusy(false);return}if(d.next){router.push(d.next);return}setDone(d.pending?'Your Admin access request has been sent for approval.':'Access added to your RLTNL account.');setBusy(false)}
 return <div className="min-h-screen grid place-items-center p-6 bg-slate-50"><div className="card p-8 w-full max-w-md bg-white"><PrimaryBrand className="text-xl justify-center"/>{error?<p className="mt-8 text-red-600">{error}</p>:!data?<p className="mt-8 muted">Loading access link…</p>:<><h1 className="text-2xl font-black mt-8">Join {data.organization?.name||'RLTNL Recruiting'}</h1><p className="muted mt-2">Add <strong>{data.role}</strong> access{data.team?.name?<> for <strong>{data.team.name}</strong></>:null} to your RLTNL account.{data.requires_approval?' Admin access requires approval.':''}</p>{done?<><div className="mt-6 rounded-xl bg-green-50 border border-green-200 p-4 text-sm font-semibold">{done}</div><Link href="/login" className="btn btn-red w-full mt-4 text-center">Continue to RLTNL</Link></>:<button onClick={join} disabled={busy} className="btn btn-red w-full mt-6">{busy?'Adding access…':'Continue'}</button>}</>}</div></div>
}