'use client';
import {useEffect,useState} from 'react';
import ExcelJS from 'exceljs';
import AppShell from '@/components/AppShell';
import PageHeader from '@/components/PageHeader';
import {createClient} from '@/lib/supabase-browser';
import {AlertTriangle,CheckCircle2,FileSpreadsheet,Upload} from 'lucide-react';

type Row=Record<string,any>;
type Mapping={player:string;email:string;school:string;coach:string;coachEmail:string;coachPhone:string;date:string;type:string;notes:string;stage:string;gradYear:string;team:string;jersey:string};
type Review={index:number;row:Row;schoolId:string;schoolName:string;coachId:string;coachName:string;ready:boolean;issues:string[]};
const EMPTY:Mapping={player:'',email:'',school:'',coach:'',coachEmail:'',coachPhone:'',date:'',type:'',notes:'',stage:'',gradYear:'',team:'',jersey:''};
const norm=(v:any)=>String(v||'').trim().toLowerCase();
const hints:Record<keyof Mapping,string[]>={player:['player','athlete','player name','athlete name'],email:['player email','athlete email','email'],school:['school','college','university','program'],coach:['coach','coach name','contact'],coachEmail:['coach email'],coachPhone:['coach phone','coach mobile'],date:['date','contact date','interaction date','last contact'],type:['type','interaction','activity','method'],notes:['notes','note','details','context'],stage:['stage','status','recruiting stage'],gradYear:['grad year','graduation year','class year'],team:['team','team name'],jersey:['jersey','jersey number','number']};
const autoMap=(headers:string[])=>{const m={...EMPTY};(Object.keys(m) as (keyof Mapping)[]).forEach(k=>{const exact=headers.find(h=>hints[k].includes(norm(h)));const fuzzy=exact||headers.find(h=>hints[k].some(x=>norm(h).includes(x)));if(fuzzy)m[k]=fuzzy});return m};
const excelSerialDate=(serial:number)=>{if(!Number.isFinite(serial))return null;const d=new Date(Math.round((serial-25569)*86400000));if(Number.isNaN(d.getTime()))return null;return{y:d.getUTCFullYear(),m:d.getUTCMonth()+1,d:d.getUTCDate()}};
const dateInfo=(v:any)=>{if(v===null||v===undefined||v==='')return{date:null,precision:'unknown',year:null,month:null};if(v instanceof Date&&!Number.isNaN(v.getTime())){const y=v.getFullYear(),m=v.getMonth()+1,d=v.getDate();return{date:`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`,precision:'exact',year:y,month:m}}if(typeof v==='number'){const d=excelSerialDate(v);if(d)return{date:`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`,precision:'exact',year:d.y,month:d.m}}const s=String(v).trim();let x=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(x)return{date:`${x[1]}-${x[2].padStart(2,'0')}-${x[3].padStart(2,'0')}`,precision:'exact',year:+x[1],month:+x[2]};x=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{2,4})$/);if(x){const y=+x[3]<100?2000+(+x[3]):+x[3];return{date:`${y}-${x[1].padStart(2,'0')}-${x[2].padStart(2,'0')}`,precision:'exact',year:y,month:+x[1]}}x=s.match(/^(\d{1,2})\/(\d{4})$/);if(x)return{date:null,precision:'month',year:+x[2],month:+x[1]};x=s.match(/^(\d{4})$/);if(x)return{date:null,precision:'year',year:+x[1],month:null};return{date:null,precision:'unknown',year:null,month:null}};
const importedType=(v:any)=>{const s=String(v||'').trim();if(!s)return'Imported Recruiting Activity';return /^imported /i.test(s)?s:`Imported ${s}`};
const paginate=async(c:any,table:string,select:string)=>{const all:any[]=[];for(let from=0;from<10000;from+=1000){const{data,error}=await c.from(table).select(select).range(from,from+999);if(error)break;all.push(...(data||[]));if(!data||data.length<1000)break}return all};

export default function TeamImportPage(){
 const c=createClient();
 const [me,setMe]=useState<any>(null),[org,setOrg]=useState<any>(null),[rows,setRows]=useState<Row[]>([]),[headers,setHeaders]=useState<string[]>([]),[mapping,setMapping]=useState<Mapping>(EMPTY),[fileName,setFileName]=useState(''),[review,setReview]=useState<Review[]>([]),[colleges,setColleges]=useState<any[]>([]),[coaches,setCoaches]=useState<any[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[result,setResult]=useState<any>(null);
 useEffect(()=>{(async()=>{const {data:{user}}=await c.auth.getUser();if(!user)return;setMe(user);const {data:m}=await c.from('organization_members').select('organization_id,role,status').eq('user_id',user.id).eq('status','active').in('role',['owner','admin']).limit(1).maybeSingle();if(!m)return;const {data:o}=await c.from('organizations').select('id,name').eq('id',m.organization_id).maybeSingle();setOrg({id:m.organization_id,name:o?.name||'Your organization',role:m.role})})()},[]);
 function parseCsv(text:string){const out:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v!==''))out.push(row);row=[];cell=''}else cell+=ch}row.push(cell);if(row.some(v=>v!==''))out.push(row);return out}
function excelValue(v:any):any{if(v===null||v===undefined)return'';if(v instanceof Date)return v;if(typeof v!=='object')return v;if('result' in v)return excelValue(v.result);if(Array.isArray(v.richText))return v.richText.map((x:any)=>x.text||'').join('');if('text' in v)return v.text||'';if('hyperlink' in v)return v.text||v.hyperlink||'';return String(v)}
 async function readFile(file:File){setResult(null);setReview([]);setMsg('');setFileName(file.name);try{let json:Row[]=[];if(file.name.toLowerCase().endsWith('.csv')){const matrix=parseCsv(await file.text());const hs=(matrix[0]||[]).map(x=>String(x).trim());json=matrix.slice(1).filter(r=>r.some(v=>String(v).trim()!=='' )).map(r=>Object.fromEntries(hs.map((h,i)=>[h,r[i]??''])))}else if(file.name.toLowerCase().endsWith('.xlsx')){const wb=new ExcelJS.Workbook();await wb.xlsx.load(await file.arrayBuffer() as any);const ws=wb.worksheets[0];if(!ws)throw new Error('No worksheet');const hs=(ws.getRow(1).values as any[]).slice(1).map(v=>String(excelValue(v)).trim());ws.eachRow((row,rowNumber)=>{if(rowNumber===1)return;const vals=(row.values as any[]).slice(1).map(excelValue);if(vals.some(v=>String(v??'').trim()!==''))json.push(Object.fromEntries(hs.map((h,i)=>[h,vals[i]??''])))});}else throw new Error('Unsupported file type');const hs=json.length?Object.keys(json[0]):[];setRows(json);setHeaders(hs);setMapping(autoMap(hs));if(!json.length)setMsg('The spreadsheet opened successfully, but no data rows were found.')}catch{setRows([]);setHeaders([]);setMsg('This spreadsheet could not be read. Use an .xlsx or .csv file and try again.')}}
 async function analyze(){if(!mapping.player||!mapping.email||!mapping.school){setMsg('Map Player Name, Player Email, and School before continuing.');return}setBusy(true);setMsg('');const [cols,chs]=await Promise.all([paginate(c,'colleges','id,name,city,state,division'),paginate(c,'college_coaches','id,college_id,first_name,last_name,title,email,phone')]);setColleges(cols);setCoaches(chs);const colByName=new Map(cols.map((x:any)=>[norm(x.name),x]));const next=rows.map((row,index)=>{const issues:string[]=[];const player=String(row[mapping.player]||'').trim(),email=String(row[mapping.email]||'').trim(),schoolRaw=String(row[mapping.school]||'').trim();if(!player)issues.push('Player name missing');if(!email||!email.includes('@'))issues.push('Valid player email required');let school=colByName.get(norm(schoolRaw));if(!school&&schoolRaw){const candidates=cols.filter((x:any)=>norm(x.name).includes(norm(schoolRaw))||norm(schoolRaw).includes(norm(x.name)));if(candidates.length===1)school=candidates[0]}if(!school)issues.push('School needs review');let coachId='',coachName='';const rawCoach=mapping.coach?String(row[mapping.coach]||'').replace(/^coach\s+/i,'').trim():'';const rawCoachEmail=mapping.coachEmail?norm(row[mapping.coachEmail]):'';if(school&&(rawCoach||rawCoachEmail)){const pool=chs.filter((x:any)=>x.college_id===school.id);let matches=rawCoachEmail?pool.filter((x:any)=>norm(x.email)===rawCoachEmail):[];if(!matches.length&&rawCoach){matches=pool.filter((x:any)=>norm(`${x.first_name} ${x.last_name}`)===norm(rawCoach));if(!matches.length){const last=norm(rawCoach.split(/\s+/).pop());matches=pool.filter((x:any)=>norm(x.last_name)===last)}}if(matches.length===1){coachId=matches[0].id;coachName=[matches[0].first_name,matches[0].last_name].filter(Boolean).join(' ')}else issues.push('Coach not confirmed')}return{index,row,schoolId:school?.id||'',schoolName:school?.name||schoolRaw,coachId,coachName,ready:issues.filter(x=>x!=='Coach not confirmed').length===0,issues}});setReview(next);setBusy(false)}
 function setReviewItem(index:number,patch:Partial<Review>){setReview(v=>v.map(x=>x.index===index?{...x,...patch}:x))}
 async function runImport(){if(!org||!me)return;const blocking=review.filter(x=>x.issues.some(y=>y!=='Coach not confirmed'));if(blocking.length){setMsg(`${blocking.length} row${blocking.length===1?'':'s'} still need a valid player email or school.`);return}setBusy(true);setMsg('');const {data:batch,error:batchError}=await c.from('organization_import_batches').insert({organization_id:org.id,uploaded_by_user_id:me.id,file_name:fileName,status:'reviewed'}).select('id').single();if(batchError||!batch){setBusy(false);setMsg(batchError?.message||'Could not start import.');return}let imported=0,claimed=0,unclaimed=0,coachMatched=0;const recordCache=new Map<string,any>();for(const item of review){const row=item.row;const email=String(row[mapping.email]||'').trim().toLowerCase(),player=String(row[mapping.player]||'').trim();let record=recordCache.get(email);if(!record){const {data:existing}=await c.from('organization_player_records').select('id,claimed_user_id,status').eq('organization_id',org.id).ilike('email',email).maybeSingle();record=existing;if(!record){const {data:created,error}=await c.from('organization_player_records').insert({organization_id:org.id,full_name:player,email,grad_year:mapping.gradYear?Number(row[mapping.gradYear])||null:null,team_label:mapping.team?String(row[mapping.team]||'').trim()||null:null,jersey_number:mapping.jersey?String(row[mapping.jersey]||'').trim()||null:null,created_by_user_id:me.id}).select('id,claimed_user_id,status').single();if(error||!created)continue;record=created}recordCache.set(email,record)}const d=dateInfo(mapping.date?row[mapping.date]:'');const rowKey=[item.index,email,item.schoolId,item.coachId||'',d.date||`${d.year||''}-${d.month||''}`,mapping.type?String(row[mapping.type]||''):'',mapping.notes?String(row[mapping.notes]||''):''].join('|');const {error}=await c.from('organization_player_import_items').insert({batch_id:batch.id,player_record_id:record.id,college_id:item.schoolId,coach_id:item.coachId||null,school_name:item.schoolName,coach_name:mapping.coach?String(row[mapping.coach]||'').trim()||item.coachName||null:item.coachName||null,coach_email:mapping.coachEmail?String(row[mapping.coachEmail]||'').trim()||null:null,coach_phone:mapping.coachPhone?String(row[mapping.coachPhone]||'').trim()||null:null,stage:mapping.stage?String(row[mapping.stage]||'').trim()||null:null,activity_type:importedType(mapping.type?row[mapping.type]:''),activity_date:d.date,date_precision:d.precision,date_year:d.year,date_month:d.month,note:mapping.notes?String(row[mapping.notes]||'').trim()||null:null,row_key:rowKey,raw_row:row});if(error)continue;imported++;if(item.coachId)coachMatched++;const {data:fresh}=await c.from('organization_player_records').select('claimed_user_id').eq('id',record.id).single();if(fresh?.claimed_user_id)claimed++;else unclaimed++}
 await c.from('organization_import_batches').update({status:'imported'}).eq('id',batch.id);setResult({rows:imported,claimed,unclaimed,coachMatched,players:recordCache.size});setBusy(false)}
 const mapFields:[keyof Mapping,string,boolean][]=[['player','Player Name',true],['email','Player Email',true],['school','School',true],['coach','Coach',false],['coachEmail','Coach Email',false],['coachPhone','Coach Phone',false],['date','Activity Date',false],['type','Activity Type',false],['notes','Notes / Context',false],['stage','Journey Stage',false],['gradYear','Grad Year',false],['team','Team',false],['jersey','Jersey Number',false]];
 if(!org)return <AppShell><div className="max-w-4xl mx-auto px-5 md:px-8 py-8"><div className="card p-6"><h1 className="font-black text-xl">Owner or Admin access required</h1><p className="muted mt-2">Team imports create player records for your organization, including players who have not joined Rebels Recruit yet.</p></div></div></AppShell>;
 return <AppShell><div className="max-w-6xl mx-auto px-4 sm:px-5 md:px-8 py-6"><PageHeader eyebrow="TEAM ONBOARDING" title="Import Team Recruiting History" subtitle={`Upload recruiting history for ${org.name||'your organization'}. Existing accounts are connected when possible, and other players can claim their history later.`}/>
 <div className="card p-5 sm:p-6 mb-5"><div className="flex gap-3"><FileSpreadsheet className="text-red-600 shrink-0"/><div><h2 className="font-black text-lg">Upload Excel (.xlsx) or CSV</h2><p className="muted text-sm mt-1">Player email is the identity key. Rebels Recruit will never auto-match a player by name alone.</p></div></div><label className="btn btn-red inline-flex mt-4 cursor-pointer"><Upload size={18}/>Choose Spreadsheet<input type="file" accept=".xlsx,.csv" className="hidden" onChange={e=>e.target.files?.[0]&&readFile(e.target.files[0])}/></label>{fileName&&<div className="text-sm font-semibold mt-3">{fileName} · {rows.length} rows</div>}</div>
 {rows.length>0&&<><div className="card p-5 sm:p-6 mb-5"><h2 className="font-black text-lg">1. Confirm Columns</h2><p className="muted text-sm mt-1">Player Name, Player Email, and School are required. Coach information is optional but strongly recommended.</p><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-4">{mapFields.map(([key,label,req])=><label className="text-sm font-semibold" key={key}>{label}{req&&<span className="text-red-600"> *</span>}<select className="input w-full mt-1" value={mapping[key]} onChange={e=>{setMapping(v=>({...v,[key]:e.target.value}));setReview([])}}><option value="">Not mapped</option>{headers.map(h=><option key={h} value={h}>{h}</option>)}</select></label>)}</div><button className="btn btn-red mt-5" disabled={busy} onClick={analyze}>{busy?'Analyzing...':'Analyze & Review'}</button></div>
 {review.length>0&&!result&&<div className="card p-5 sm:p-6"><div className="flex flex-col sm:flex-row sm:justify-between gap-3"><div><h2 className="font-black text-lg">2. Review Matches</h2><p className="muted text-sm mt-1">School matches must be resolved. Coach matches can be left open and the player can confirm a coach later.</p></div><div className="text-sm font-bold">{review.filter(x=>x.ready).length} ready · {review.filter(x=>!x.ready).length} need attention</div></div><div className="space-y-3 mt-5">{review.map(item=>{const row=item.row;const player=String(row[mapping.player]||'').trim(),email=String(row[mapping.email]||'').trim(),schoolChoices=colleges.filter((x:any)=>norm(x.name).includes(norm(item.schoolName))||norm(item.schoolName).includes(norm(x.name))).slice(0,8),coachChoices=coaches.filter((x:any)=>x.college_id===item.schoolId);return <div className="border rounded-xl p-4" key={item.index}><div className="font-black">{player||'Player'} <span className="font-normal muted">· {email||'No email'}</span></div><div className="grid md:grid-cols-2 gap-3 mt-3"><label className="text-sm font-semibold">School<select className="input w-full mt-1" value={item.schoolId} onChange={e=>{const s=colleges.find((x:any)=>x.id===e.target.value);setReviewItem(item.index,{schoolId:e.target.value,schoolName:s?.name||item.schoolName,coachId:'',coachName:'',ready:Boolean(e.target.value&&email.includes('@')),issues:e.target.value&&email.includes('@')?[]:['School needs review']})}}><option value="">Choose school</option>{schoolChoices.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="text-sm font-semibold">Coach<select className="input w-full mt-1" value={item.coachId} onChange={e=>{const co=coaches.find((x:any)=>x.id===e.target.value);setReviewItem(item.index,{coachId:e.target.value,coachName:co?[co.first_name,co.last_name].filter(Boolean).join(' '):'',issues:item.issues.filter(x=>x!=='Coach not confirmed')})}}><option value="">No coach confirmed yet</option>{coachChoices.map((co:any)=><option key={co.id} value={co.id}>{[co.first_name,co.last_name].filter(Boolean).join(' ')}{co.title?` · ${co.title}`:''}</option>)}</select></label></div>{item.issues.length>0&&<div className="mt-3 text-xs text-amber-700 flex gap-2"><AlertTriangle size={15}/>{item.issues.join(' · ')}</div>}</div>})}</div><button className="btn btn-red mt-5" disabled={busy||review.some(x=>x.issues.some(y=>y!=='Coach not confirmed'))} onClick={runImport}>{busy?'Importing...':'Import Reviewed Rows'}</button></div>}
 {result&&<div className="card p-6 border-green-200 bg-green-50"><div className="flex gap-3"><CheckCircle2 className="text-green-700 shrink-0"/><div><h2 className="font-black text-xl">Team history imported</h2><p className="mt-1 text-sm">{result.rows} recruiting rows across {result.players} players were saved.</p></div></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-5">{[['Rows saved',result.rows],['Matched to accounts',result.claimed],['Awaiting player claim',result.unclaimed],['Coach matches',result.coachMatched]].map(([a,b])=><div className="rounded-xl border bg-white p-3" key={String(a)}><div className="muted text-xs">{a}</div><div className="font-black text-2xl mt-1">{b}</div></div>)}</div><p className="text-sm mt-5"><b>What happens next:</b> Players with an existing matching email receive the history in their account. Players without an account keep a secure unclaimed player record. When they later sign up with that verified email, Rebels Recruit connects the history automatically and asks them to approve organization access.</p></div>}
 </>}</div></AppShell>}
