'use client';
import {useEffect,useState} from 'react';
import AppShell from '@/components/AppShell';
import PageHeader from '@/components/PageHeader';
import {createClient} from '@/lib/supabase-browser';
import {DEFAULT_TIMEZONE,US_TIMEZONES} from '@/lib/us-timezones';

export default function AdvisorProfile(){
 const [name,setName]=useState('');const [email,setEmail]=useState('');const [phone,setPhone]=useState('');const [type,setType]=useState('Advisor');const [timezone,setTimezone]=useState(DEFAULT_TIMEZONE);const [isOnboarding,setIsOnboarding]=useState(false);const [msg,setMsg]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{(async()=>{const c=createClient();const {data:{user}}=await c.auth.getUser();if(!user)return;const {data:p}=await c.from('profiles').select('full_name,email,phone,advisor_type,timezone,profile_completed_at').eq('id',user.id).single();setName(p?.full_name||'');setEmail(p?.email||user.email||'');setPhone(p?.phone||'');setType(p?.advisor_type||'Advisor');setTimezone(p?.timezone||DEFAULT_TIMEZONE);setIsOnboarding(!p?.profile_completed_at)})()},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg('');setError('');const c=createClient();const {data:{user}}=await c.auth.getUser();if(!user){setError('Please sign in again.');setBusy(false);return}const cleanEmail=email.trim();if(!name.trim()||!cleanEmail||!phone.trim()||!type||!timezone){setError('Please complete all required fields before continuing.');setBusy(false);return}if(cleanEmail!==user.email){const {error:authError}=await c.auth.updateUser({email:cleanEmail});if(authError){setError(authError.message);setBusy(false);return}}const {error:profileError}=await c.from('profiles').update({full_name:name.trim(),email:cleanEmail,phone:phone.trim(),advisor_type:type,timezone,profile_completed_at:new Date().toISOString()}).eq('id',user.id);if(profileError)setError(profileError.message);else{setMsg(cleanEmail!==user.email?'Profile saved. Check your new email address to confirm the email change.':'Profile saved.');if(isOnboarding){location.href='/advisors';return}}setBusy(false)}
 return <AppShell><div className="max-w-3xl mx-auto px-5 md:px-8 py-6"><PageHeader title={isOnboarding?'Complete Your Profile':'My Profile'} subtitle={isOnboarding?'Complete your profile before using Rebels Recruit.':'Keep your advisor information up to date.'}/><div className="card p-6"><form onSubmit={save} className="grid md:grid-cols-2 gap-4"><label className="block"><span className="text-sm font-bold">Name *</span><input className="input mt-1" value={name} onChange={e=>setName(e.target.value)} required/></label><label className="block"><span className="text-sm font-bold">Email address *</span><input className="input mt-1" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label className="block"><span className="text-sm font-bold">Phone number *</span><input className="input mt-1" type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone number" required/></label><label className="block"><span className="text-sm font-bold">I am a *</span><select className="input mt-1" value={type} onChange={e=>setType(e.target.value)} required><option>Parent</option><option>Coach</option><option>Advisor</option><option>Other</option></select></label><label className="block md:col-span-2"><span className="text-sm font-bold">Time zone *</span><select className="input mt-1" value={timezone} onChange={e=>setTimezone(e.target.value)} required>{US_TIMEZONES.map(z=><option key={z.value} value={z.value}>{z.label}</option>)}</select></label>{msg&&<div className="md:col-span-2 rounded-lg border border-green-200 bg-green-50 p-3 text-sm font-semibold text-green-800">{msg}</div>}{error&&<p className="md:col-span-2 text-sm text-red-600">{error}</p>}<button disabled={busy} className="btn btn-red md:col-span-2">{busy?'Saving...':isOnboarding?'Save Profile & Continue':'Save Profile'}</button></form></div></div></AppShell>}
